### ISSUE TITLE
Proj.4 version 10 - potential issue

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#102]
st_proj_info(type = "ellps") still works, but may have to disappear when Proj.4 version 10 appears.

**Comment by Nowosad** [comment]
+ rename Proj.4 -> PROJ (https://github.com/OSGeo/proj.4/blob/master/NEWS)

**Comment by Robinlovelace** [comment]
Well spotted. Have the changes to PROJ filtered down into the R ecosystem yet, to the point where we can make the necessary changes?

**Comment by Nowosad** [comment]
I don't think so. I will keep track of these changes.

**Comment by Nowosad** [comment]
https://github.com/r-spatial/sf/issues/545
