### ISSUE TITLE
Left join example improve...

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#106]
"A third example is towards the end of section 3.2.3. You distinguish data.frame objects from sf objects in the situation of reversing the order of parameters in the left_join function. What are the implications of having the sf output versus the data.frame output? Why would I want to ensure I choose one over the other." 
@jannes-m @Robinlovelace please take a look at the `left_join4` example in section 3.2.3. Do you have any idea how to improve it? This is just a standard `dplyr` behavior.

**Comment by Robinlovelace** [comment]
OK I think that fixes the issue: I think it's simply a question of warning that geometry list columns are essentially useless unless they are in an `sf` object. I don't think we need to change the code: the example is useful in that it shows **dplyr** behaviour that may not be expected by the reader.

**Comment by Robinlovelace** [comment]
Btw I've fixed the typos in that commit in the next commit.
