### ISSUE TITLE
Topical and functional indices before publishing

### ISSUE THREAD

**Issue by jannes-m** [Robinlovelace/geocompr#108]
Reviewer 1 (round 1) recommends topical and functional indices as in ASDAR. I create this issue here, to remind ourselves to say so to the CRC editors before publishing.

**Comment by Nowosad** [comment]
Reviewer 2 (round2): One idea that comes to mind in terms of additions is to try adding a chart, “cheatsheet” or inforaphic of the various spatial analysis methods covered in this book, perhaps with thumbnails illustrating the types of operations and tasks, referring to the corresponding book sections. In other words – making a visual index. The book, as it seems, will become the most comprehensive textbook on spatial analysis in R. Supplementing it with some kind of visual index summarizing the ecosystem of currently available tools can bring additional value, especially to those using the book as an introduction to the field. I understand this requires some thought and may or may not be eventually feasible, so this is just a thought.

**Comment by Robinlovelace** [comment]
I've set-up something for this: https://github.com/Robinlovelace/geocompr-cheatsheat - thoughts? I can give it a bash later today.

**Comment by Robinlovelace** [comment]
The issue of indices is outside the scope of this repo - it's done on the publisher's side (although we will be able to input) so closing for now - the cheatsheet is a good idea but a separate issue IMO. Would be great to have a graphical overview of the contents of the book + contents but suggest we finish a cohesive draft first.
