### ISSUE TITLE
Missing 'spDataLarge' package

### ISSUE THREAD

**Issue by cyenglish3** [Robinlovelace/geocompr#111]
Apologies for the abruptness, and the diatribe. 'spDataLarge' package is missing. To compile the book, 'packages.bib' attempts to install 'spDataLarge', however, as it does not exist, compilation errors out at '02_spatial-data.Rmd'.  Even without compiling the book, moving beyond loading libraries cannot be completed without the package in question.  Suggest posting a viable workaround to fetch the Landsat raster and associated datasets if the package is no longer available.

**Comment by Nowosad** [comment]
Hi @cyenglish3, what's the code you used for packages installation?
You could install all of them using:

```R
devtools::install_packages("robinlovelace/geocompr")
```

Or if you just want to install `spDataLarge`:

```R
library(spData)
install.packages("spDataLarge")
```

**Comment by Robinlovelace** [comment]
It works fine on my university desktop running windows:

![image](https://user-images.githubusercontent.com/1825120/32372232-e948d20c-c08b-11e7-83b9-6ac4e9052191.png)

**Comment by cyenglish3** [comment]
I did attempt to install via install.packages(). I kept getting the error that spDataLarge was not a package. I see, though, that you are using R version 3.4.2.  I am using version 3.3.2.  I will update to the latest version of R and try again.

**Comment by cyenglish3** [comment]
Uhm.. I'm appalled, mortified even. It worked. *Expletive* magic strikes again... or just plain operator headspace.  Thank you, kindly, for responding.

**Comment by Robinlovelace** [comment]
No problem. If you have any other issues, find any typos or just suggestions we're happy to hear about them!

**Comment by Monduiz** [comment]
It seems to be an issue that keep creeping up. On a new MacBook Pro, I am getting this too:

"Warning in install.packages :
  package ‘spDataLarge’ is not available (for R version 3.4.2)"

**Comment by Nowosad** [comment]
Hi @Monduiz ,
have you tried installing `spDataLarge` after loading the `spData` package:

```R
library(spData)
install.packages("spDataLarge")
```

**Comment by Monduiz** [comment]
You did mention that earlier in the thread. I should have read more carefully, sorry about this! Would it help to add a note in the book?

Thanks!

**Comment by Robinlovelace** [comment]
Yes it may be worth mentioning at the beginning Chapter 2. Feel free to put in a PR on this + thanks for the feedback.
