### ISSUE TITLE
Redo broken figures in c4 with tmap

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#116]
Specifically these are not right:

![image](https://user-images.githubusercontent.com/1825120/33166759-46fecfda-d033-11e7-95e8-9900db57ea23.png)

![image](https://user-images.githubusercontent.com/1825120/33166983-ff407008-d033-11e7-9f05-f93843957ff3.png)

![image](https://user-images.githubusercontent.com/1825120/33166956-e73b4d20-d033-11e7-9ab6-4cbfded41228.png)

This fits into wider plans to have a consistent tmap theme for the book - will be great to have a unique style.

**Comment by Robinlovelace** [comment]
They are no longer broken so closing. However I think there is still an argument for shifting to **tmap** - the us states plot below being a case in point (although I think `scale = 0.7` would improve it):

![image](https://user-images.githubusercontent.com/1825120/33177346-3bf3d5aa-d05a-11e7-963a-1a6c2d861d6d.png)

**Comment by Robinlovelace** [comment]
Thoughts @Nowosad and @jannes-m ? One to discuss soon!

**Comment by jannes-m** [comment]
What don't you like about the plot specifically? The strip text (could be easily changed)?

I have used `spplot()`,  **lattice** and **latticeExtra** for a couple of plots. I don't know if it is easily possible to convert the corresponding code into **tmap** code, and if **tmap** supports all the functions and arguments I have used (but maybe I just don't know). Then there are at least two other things which come to mind:

1. a consistent figure style is nice but I am not sure if this would require to use always the same package (though certainly this would support a consistent style).
2. What about simple plots created with `plot()`. Do you want to recreate all these plots also with **tmap?

**Comment by Robinlovelace** [comment]
Agreed - if it ain't broke don't fix it is a good strategy. Happy with `plot()` and you *can* have styles with base plot options too.
