### ISSUE TITLE
ch5 geometric operations

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#117]
Prerequisites
5.1 Introduction
5.2 Geometric operations on vector data
5.2.1 Reprojections
5.2.2 Geometry transformations
5.2.3 Type transformations
5.2.4 Simplifications
5.2.5 Rasterization
5.3 Geometric operations on raster data
5.3.1 Reprojections
5.3.2 Raster alignment
5.3.3 Aggregation
5.3.4 Polygonize
5.4 Exercises

**Comment by Robinlovelace** [comment]
Affine transformations should go somewhere.
