### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#122]
These flag-up after

```r
bookdown::render_book("index.Rmd")
```

```
1: The label(s) fig:spatial-aggregation not found 
2: The label(s) gis not found 
3: The label(s) aligning-rasters not found 
4: The label(s) ttwa-bristol not found 
```

At least one of them's mine - thought it worth logging as I've noticed it a few times.

**Comment by jannes-m** [comment]
The gis flag is not found because the chapter is still commented in our yaml file, so I'd say we just ignore it. Will have a look at the aligning-rasters label

**Comment by Robinlovelace** [comment]
Great. More importantly for now please take a look at the latest discussion here - your views very welcome: https://github.com/Robinlovelace/geocompr/commit/63d06440ad0c4fcdcca4c96f4b745b58c1f7e496
