### ISSUE TITLE
spDataLarge is not on CRAN

### ISSUE THREAD

**Issue by Zedseayou** [Robinlovelace/geocompr#126]
Chapter 2's prerequisites section suggests `install.packages("spDataLarge")` to get this package, but it no longer seems to be on CRAN? I used `devtools::install_github()` to get it, and there is an annotation to similar effect, but it might be worth swapping the text and the annotation unless `spDataLarge` is intended to be back on CRAN by the time of the book's release.

**Comment by Nowosad** [comment]
Hi @Zedseayou !
The size **spDataLarge** is to big to be on CRAN. You can get information how to install this package from https://geocompr.robinlovelace.net/spatial-class.html#prerequisites. 
Long story short, you've got three options:

1. Install all of the required packages using `devtools::install_github("robinlovelace/geocompr")`
2. Install **spDataLarge** after loading **spData** - `library(spData)` and afterwards `install.packages("spDataLarge")` 
3. Install **spDataLarge** using its address - `install.packages("spDataLarge", repos = "https://nowosad.github.io/drat/", type = "source")`

**Comment by Robinlovelace** [comment]
At the beginning of Chapter 2 it clearly states that **spDataLarge** must installed after **spData** is loaded: 

> The chapter also relies on two data packages: spData and spDataLarge, the latter of which must be installed after spData is loaded

Please take a look here: https://geocompr.robinlovelace.net/spatial-class.html

Happy to hear suggestions about how to clarify the prerequisites though. Which of the options mentioned by Jakub, for example, would you find easiest?

I think this should resolve your issue in any case.

**Comment by Zedseayou** [comment]
I guess I must have done something wrong because when I posted this attempting to use `install.packages("spDataLarge")` with `spData` loaded it didn't successfully install, but I removed R and all my packages and tried again and it worked this time as described. Thanks for the quick response!
