### ISSUE TITLE
Render_book error

### ISSUE THREAD

**Issue by jdiez** [Robinlovelace/geocompr#127]
Hi,
I've got the following error (see below) while I was trying to render the book.
It couldn't fine the dataset 'seine', neither do I manually.
Any idea of how to solve it?
Thanks,
Javier

"""Quitting from lines 464-465 (05-transform.Rmd) 
Error in st_simplify(seine, dTolerance = 2000) : object 'seine' not found
Calls: local ... withCallingHandlers -> withVisible -> eval -> eval -> st_simplify

Execution halted
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile 05-transform.Rmd """

**Comment by jdiez** [comment]
Sorry, this is solved installing directly from github, although I though the installer was doing it already.
Apologies once again.

**Comment by Nowosad** [comment]
Hi @jdiez,
thanks for the question. The book changes everyday - I've added this new dataset `seine` to the `spData` package just yesterday. I plan to submit the new version to CRAN in about a week.

**Comment by jdiez** [comment]
Hi @Nowosad ,
Thanks to you all for sharing the book, it's awesome.
I've got another error later on on the same chapter which was solved reinstalling (updating) 'sf' package manually.
I did rendered a previous version of the book, like a month ago, installation worked smoothly for me.
These are not major issues, if it helps you or anyone else it's fine.
Thanks again for the book,
Javi
