### ISSUE TITLE
Additional resources to link-to

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#128]
We should compile a list of additional resources we've not already mentioned to include if time constraints allow. This could go in a final chapter on taking things further. Please add to this list by editing this issue and adding more tick-boxes or just add a comment below.

- [x] Geostatistics & Open-source statistical computing by D G Rossiter: http://www.css.cornell.edu/faculty/dgr2/teach/degeostats.html
- [ ] Teaching from Marbug University and [AGIS2015](http://moc.online.uni-marburg.de/doku.php?id=courses:lala:meg-advanced-gis-2015:description) corresponding [perfectPeak](https://github.com/gisma/perfectPeak) package. Thanks to @gisma.

**Comment by gisma** [comment]
Maybe it is worthwhile to have look at our stuff here in Marburg It is dealing with a lot of applied crossover R-GIS topics
[Marburg Open Courseware](http://moc.online.uni-marburg.de/doku.php)
imho especially the advanced GIS courses are pretty near to your concepts of bridging R to GIS.
[](url)
[AGIS2015](http://moc.online.uni-marburg.de/doku.php?id=courses:lala:meg-advanced-gis-2015:description)
[AGIS 2016](http://moc.online.uni-marburg.de/doku.php?id=courses:msc:msc-phygeo-gis:description)

**Comment by Robinlovelace** [comment]
Many thanks for those suggestions. Just to confirm: are they free and likely to be future-proof (the url will persist)? Definitely worth linking to and learning from based on a quick peek.

**Comment by gisma** [comment]
All stuff is [by-nc-sa](https://creativecommons.org/licenses/by-nc-sa/4.0/)
The contents and the portal web address  will persist -  nevertheless we are in a migration process to GitHub  jekyll hosting. This may result in some linking cascades. If you are interested I will organize a persistent link to this kind of teaching stuff. 
Probably the combination of the [AGIS2015](http://moc.online.uni-marburg.de/doku.php?id=courses:lala:meg-advanced-gis-2015:description) course and the corresponding [perfectPeak](https://github.com/gisma/perfectPeak)   package will be a pretty good resource for applied conceptual and training goals according to the book

**Comment by Robinlovelace** [comment]
Fantastic, many thanks - I'll add these great resources to the check-list.
