### ISSUE TITLE
Add vector examples to ch4

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#130]
@Robinlovelace all previous vector examples were moved from ch4 to ch5.

**Comment by Robinlovelace** [comment]
Ok will take a look now.

**Comment by Nowosad** [comment]
@Robinlovelace - the second thing - the vector exercises in ch5 ask to use buffers in degrees. Probably they should be changed.

**Comment by Robinlovelace** [comment]
Agreed.
