### ISSUE TITLE
Cannot see bike shops in interactive map in c7

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#132]
I still cannot see the recommended locations in this figure - any ideas @jannes-m ?

http://geocompr.robinlovelace.net/location.html#fig:bikeshop-berlin

**Comment by jannes-m** [comment]
this is strange, locally it works... let me rebuild again, will report back

**Comment by jannes-m** [comment]
Strange, running the code chunks in the R console yields the expected result. However, using `bookdown::render_book()` ignores `berlin_raster`

**Comment by Robinlovelace** [comment]
Interesting... You could always take a screenshot of the result and use that for now.

I'm thinking of adding an online version of the maps in the transport chapter outside the book and linking to them, e.g. using tinyurl to create mini urls - that's a good option I think.

**Comment by jannes-m** [comment]
Is it possible that somewhere a weird cache exists?

If I use berlin_raster > 6, we get an output, as soon as we use > 7, there is nothing to be found. However, as I said, when I run all chunks locally, everything is in order, i.e., that berlin_raster > 9 gives the expected result.

**Comment by Robinlovelace** [comment]
It is possible but I cannot see a mechanism for that to be enabled from Travis, other than the pkgs being cached, I think.

**Comment by Robinlovelace** [comment]
Could try commenting this but don't see how it would help: https://github.com/Robinlovelace/geocompr/blob/master/.travis.yml#L2

**Comment by Robinlovelace** [comment]
BUT there may be artefacts stored in the GH pages branch: https://github.com/Robinlovelace/geocompr/tree/gh-pages

Feel free to delete anything suspicious there.

**Comment by jannes-m** [comment]
I think I have found out where the bug is, however, it was really strange. Is it possible that code chunks within  are also evaluated? And apparently, between knitting sessions code chunks are cached, i.e. if you don't change anything in them, they are returned as before. I think this is really strange. Any thoughts on this, and how we can avoid such conflicts in the future (@Nowosad)?

**Comment by jannes-m** [comment]
I tested it, and yes, R code chunks hidden within  are in fact evaluated when knitted. So be careful!

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/34129183-1c8e4d40-e43b-11e7-9ab6-39b1f8f420e7.png)

That's where to set-up a bike shop in Berlin :+1: (based on various stated assumption in the chapter :)
