### ISSUE TITLE
Code block required to describe visualization 

### ISSUE THREAD

**Issue by pembletonc** [Robinlovelace/geocompr#136]
Some description required on how results of vector analysis are visualised, e.g. using tmap / leaflet. 
e.g. section 4.2 spatial operations "Canterbury Heights":

```
canterbury = nz %>% filter(REGC2017_NAME == "Canterbury Region")
canterbury_height = nz_height[canterbury, ]
```

**Comment by Robinlovelace** [comment]
The answer can be found here: https://raw.githubusercontent.com/Robinlovelace/geocompr/master/04-spatial-operations.Rmd

Does that answer your question? We could of course say "See https://raw.githubusercontent.com/Robinlovelace/geocompr/master/04-spatial-operations.Rmd for the code that generated this plot" or something similar next to the figure, but then that would suggest adding such words next to every figure which would become cumbersome. The fact that the book is open source should encourage people to look at the source code, but perhaps we could say more about this in the [intro](https://geocompr.robinlovelace.net/) and preface: https://geocompr.robinlovelace.net/preface.html

Please take a look - if you see any opportunity for improvement there in terms of pointing people towards the source code, or any other way, happy to hear suggestions.

**Comment by pembletonc** [comment]
Yes, it answers it well, and got me looking at the source code (and those
of other projects).

You're right it would be too cumbersome to add references to the source
code everytime; perhaps a small explanation in the intro (e.g. connection
between this book & the source code) would get people looking at it,
although this may be obvious to a majority of the users and thus be
unnecessary.

Thanks for the guidance, will continue working through it and keeping out
for any points from a R beginner perspective.

Corey


On Jan 2, 2018 18:25, "Robin" <notifications@github.com> wrote:

The answer can be found here: https://raw.githubusercontent.
com/Robinlovelace/geocompr/master/04-spatial-operations.Rmd

Does that answer your question? We could of course say "See
https://raw.githubusercontent.com/Robinlovelace/geocompr/
master/04-spatial-operations.Rmd for the code that generated this plot" or
something similar next to the figure, but then that would suggest adding
such words next to every figure which would become cumbersome. The fact
that the book is open source should encourage people to look at the source
code, but perhaps we could say more about this in the intro
<https://geocompr.robinlovelace.net/> and preface: https://geocompr.
robinlovelace.net/preface.html

Please take a look - if you see any opportunity for improvement there in
terms of pointing people towards the source code, or any other way, happy
to hear suggestions.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Robinlovelace/geocompr/issues/136#issuecomment-354902589>,
or mute the thread
