### ISSUE TITLE
Content before the second round of reviews 

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#137]
- [x] Buffers @Robinlovelace 
- [x] Rasterization @nowosad
- [x] intro to 5.4 @jannes-m 
- [x] Separate of raster aggregation from 5.4.2 to 5.4.1 and therefore slight rewrite of 5.4.2 @jannes-m 
- [x] ch5 Exercises @nowosad @jannes-m @Robinlovelace 
- [x] draft of ch8 @Robinlovelace 
- [x] internal review of ch8 @jannes-m 
- [x] ask reviewers about amount of code output in c2 @Nowosad and @robinlovelace

Optional:
- [x] move datasets in `extdata/` into **spDataLarge** @robinlovelace
- [x] organise code chunks so that any large ones (e.g. 5+ lines) go into `code` - up for that @jannes-m?
- [x] change order ch7<->ch8
- [x] exercises reorder @Robinlovelace 
- [x] coffee example @Robinlovelace

**Comment by jannes-m** [comment]
Perfect, this list matches my personal to-do list

**Comment by Nowosad** [comment]
@Robinlovelace should be have exercises like (geographical CRS):
```
Write code that uses functions aggregate() and st_buffer() to answers the following question: What proportion of the world’s population lives in countries that intersect a circle with a 10 degree radius of the intersection between the equator and the 9th meridian?

Assuming that people are evenly distributed across countries, estimate the population living within the circle created to answer the previous question.
Warning messages should have been produced during the working to find the answer to the previous questions. What do these warnings mean and how could they be stopped?

Bonus: rewrite code that generated the answer to the previous question using a projected CRS (suggestion: UTM). 
```

**Comment by Robinlovelace** [comment]
@Nowosad I was just looking at the exercises and thought that those looked out-of-place. I suggest we comment those out for now.

**Comment by Nowosad** [comment]
Awesome work @Robinlovelace. 
Regarding to the exercises order - I just put them in the thematic order (crs -> vector -> raster). Feel free to change it.

**Comment by Robinlovelace** [comment]
OK will do. My guess: difficulty and topical / context order is more important for the exercises so yes I'll plan to re-order them.

**Comment by Nowosad** [comment]
Great progress.
@Robinlovelace - I've read the second chapter and I agree that there are a lot of code outputs. However, (in my highly biased opinion) most of them are very important, as they show internal structure of spatial objects and how to create them. I reduced code in one place though (https://github.com/Robinlovelace/geocompr/commit/c3cf3540798a8db342a5582a2fcbacbb8c503c91).

**Comment by Robinlovelace** [comment]
Sounds good. I'm happy to make this a question for reviewers.

**Comment by Robinlovelace** [comment]
See incoming PR in spDataLarge fixing my only outstanding point 👍 : https://github.com/Nowosad/spDataLarge/pull/4

**Comment by Robinlovelace** [comment]
Can leave it open for a while... Anything else to add? @jannes-m ?

**Comment by jannes-m** [comment]
For the moment I have nothing to add 😄

**Comment by Nowosad** [comment]
@jannes-m - I've added the data from ch8 - https://github.com/Nowosad/spDataLarge/commit/8b24a4fe3f35850b3118bc8c640092189bc0b626.
