### ISSUE TITLE
`extract()` is overridden by tidyr

### ISSUE THREAD

**Issue by yutannihilation** [Robinlovelace/geocompr#144]
In [Chapter4](https://geocompr.robinlovelace.net/spatial-operations.html#spatial-ras), libraries are loaded in this order:

``` r
library(sf)
library(raster)
library(tidyverse)
library(spData)
```

Since tidyr package also has `extract()` and is loaded after raster package, this `extract()` in 4.3.1 Spatial subsetting is probably not the intended one:

```r
extract(elev, data.frame(x = -1.5, y = 1.5))
#> Error in UseMethod("extract_") : 
#>   no applicable method for 'extract_' applied to an object of class "c('RasterLayer', 'Raster', 'BasicRaster')"
```

Maybe `raster::` is needed as wall as some gentle warning about the name conflict as you did on `select()` in the chapter 3.

**Comment by Robinlovelace** [comment]
This is similar to #28 in which `dplyr::select()` conflicts with `raster::select()`. To resolve that issue we always use the long-form `dplyr::select()` with a note. Would that resolve this issue from your perspective?

**Comment by yutannihilation** [comment]
Thanks. Yes, I think so.

**Comment by Robinlovelace** [comment]
Closed here: https://github.com/Robinlovelace/geocompr/commit/4a48b7856996b6d4ea5227d2895964fe800a5c99

**Comment by yutannihilation** [comment]
Thanks!
