### ISSUE TITLE
Sourcing method of spDataLarge

### ISSUE THREAD

**Issue by dmi3kno** [Robinlovelace/geocompr#164]
I have issues with spData quietly adding repos to my environment, so that calling install.packages("spDataLarge") without explicitly specifying `repo` argument does not fail with error, but rather proceeds with the download from `https://nowosad.github.io/drat`. I have nothing against installing packages from different repositories, I just want it to be explicit.

Current code in `spData::.onAttach`
```
repos = getOption("repos")
repos["nowosaddrat"] = "https://nowosad.github.io/drat/ "
options(repos = repos)
invisible(repos)
```

**Comment by Nowosad** [comment]
Hi @dmi3kno, thank you for your concerns.
We discussed that with @Robinlovelace more than a few times and for simplicity sake we decided on adding an invisible repo. Alternatively, the installation code could look like this `install.packages("spDataLarge", repos = "https://nowosad.github.io/drat/", type = "source")`. 
@Robinlovelace, what do you think?

**Comment by dmi3kno** [comment]
Hi @Nowosad, that is what the [article](https://journal.r-project.org/archive/2017/RJ-2017-026/index.html) you cited on twitter suggests. Make it explicit for users that the package is about to be installed from `drat` not from CRAN mirror

**Comment by Robinlovelace** [comment]
I think Dmytro has a point: explicit is good. That's a persuasive reason to shift it.

**Comment by Nowosad** [comment]
Perfect. I'm going to work on this during the weekend. Thanks again @dmi3kno - let us know if you have some other ideas or comments.

**Comment by Nowosad** [comment]
I think I've fixed it here -https://github.com/Nowosad/spData/commit/8b290959790a3c62d55ec8763c4b01e081298a22. Please test and let me know if it's good now.

**Comment by Robinlovelace** [comment]
Works like a charm as illustrated below so closing. Thanks for the input @dmi3kno - any further comments / suggestions welcome.

``` r
devtools::install_github("Nowosad/spData")
#> Skipping install of 'spData' from a github remote, the SHA1 (b7feb414) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(spData)
#> To access larger datasets in this package, install the spDataLarge
#> package with: `install.packages('spDataLarge',
#> repos='https://nowosad.github.io/drat/', type='source'))`
install.packages("spDataLarge", repos = "https://nowosad.github.io/drat/", type = "source")
#> Installing package into '/home/robin/R/x86_64-pc-linux-gnu-library/3.4'
#> (as 'lib' is unspecified)
```
