### ISSUE TITLE
Not able to compile the pdf version

### ISSUE THREAD

**Issue by MYaseen208** [Robinlovelace/geocompr#166]
Not able to compile the pdf version. Tried

`bookdown::render_book("index.Rmd", output_format = "bookdown::pdf_book")
`

This throws the following error:

> pandoc: preamble.tex: openBinaryFile: does not exist (No such file or directory)
> Error: pandoc document conversion failed with error 1
> Please delete _main.md after you finish debugging the error.
>

**Comment by Robinlovelace** [comment]
It works on the pdf branch.

**Comment by mo0zi** [comment]
Sorry but with `git branch -avv` I cannot find a pdf branch :(
