### ISSUE TITLE
Cite tmap paper

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#170]
When it comes out. I read a preprint a year ago and it was already awesome.

Citation: 

Tennekes, M. (2018) tmap: Thematic Maps in R. Forthcoming in the Journal of Statistical Software (JSS)

See https://github.com/Robinlovelace/geocompr/commit/37db6c0770c83aab9cf49c87c1296fbeebed7ce9

**Comment by Nowosad** [comment]
:man_firefighter:
