### ISSUE TITLE
Suggestion: Make the difference between the aggregate functions more clear

### ISSUE THREAD

**Issue by beingalink** [Robinlovelace/geocompr#174]
Possibly it's a lack of my english litteracy but anyway ...

In section 3.2.2 you introduce the aggregate function from base R which doesn't return an sf object and loses the geometry information (if I understood it correctly). Alternatively the tidy way is contrasted to this approach which returns an sf object and thus keeps the geometry information:
> The result is a spatial data frame of class sf (only the non-spatial results are shown): the aggregation procedure dissolves boundaries within continental land masses (explained in detail in section 5.3.6).

Then in section 5.3.6:
> Further to what was covered in section 3.2.2, aggregation of polygons often silently dissolves the geometries of touching polygons in the same group. This is demonstrated in the code chunk below, in which the REGION variable in us_states is used to aggregate the states into four regions, illustrated in Figure 5.14: ...

In the following code example there's again an aggregate function being used but it's not the one from base R. Perhaps this should be stated a bit more clearly that this is `sf::aggregate()` which obviously doesn't have the disadvantages of the base R version. In this case it's equivalent to the tidy way.

To me this was a bit confusing and I had to look it up myself what was going on. :)
 
Thanks for your efforts with this book! I'm learning a lot from it and will definitely buy a paper copy of it once it's released.

**Comment by Robinlovelace** [comment]
Thanks for the comment, really useful. It's made me go back to explore what's going on, which I think is clarified in the code and output below. As you say: the first time it uses base `aggregate()` and the second it uses sf's version (`sf:::aggregate()` not `sf::aggregate()` though - it seems to be generic method not a function that's imported into the namespace. The reason for the unexpected behaviour is that `sf:::aggregate()` is only activated when its second argument `by` is of class `sf`. This can be seen by reading the source code of the function which is printed below.

I think there are 2 improvements that can result from this astute observation:

1. Improve the book to show how `sf:::aggregate()` can be used when by is a list.

2. Add an example to documentation in **sf** (this may be of interest to @edzer - I can put in a PR doing that documentation if that would be welcome).

Reproducible example:

``` r
library(tidyverse)
#> ── Attaching packages ───────────────────────────────── tidyverse 1.2.1 ──
#> ✔ ggplot2 2.2.1     ✔ purrr   0.2.4
#> ✔ tibble  1.4.2     ✔ dplyr   0.7.4
#> ✔ tidyr   0.8.0     ✔ stringr 1.3.0
#> ✔ readr   1.1.1     ✔ forcats 0.2.0
#> ── Conflicts ──────────────────────────────────── tidyverse_conflicts() ──
#> ✖ dplyr::filter() masks stats::filter()
#> ✖ dplyr::lag()    masks stats::lag()
library(spData)
library(sf)
#> Linking to GEOS 3.5.1, GDAL 2.2.2, proj.4 4.9.2
world_agg1 = aggregate(pop ~ continent, FUN = sum, data = world, na.rm = TRUE)
class(world_agg1)
#> [1] "data.frame"
world_agg2 = group_by(world, continent) %>% summarize(sum(pop, na.rm = TRUE))
class(world_agg2)
#> [1] "sf"         "tbl_df"     "tbl"        "data.frame"
world_agg3 = sf:::aggregate.sf(x = world["pop"], by = list(world$continent), 
  FUN = sum, na.rm = TRUE)
class(world_agg3)
#> [1] "sf"         "data.frame"
plot(world_agg2)
#> Warning in classInt::classIntervals(na.omit(values), min(nbreaks, n.unq), :
#> n same as number of different finite values\neach different finite value is
#> a separate class
```

![](https://i.imgur.com/fWpjc1T.png)

``` r
plot(world_agg3)
#> Warning in classInt::classIntervals(na.omit(values), min(nbreaks, n.unq), :
#> n same as number of different finite values\neach different finite value is
#> a separate class
```

![](https://i.imgur.com/iAURvBi.png)

``` r
# ?aggregate.sf
sf:::aggregate.sf
#> function (x, by, FUN, ..., do_union = TRUE, simplify = TRUE, 
#>     join = st_intersects) 
#> {
#>     if (inherits(by, "sf") || inherits(by, "sfc")) {
#>         if (inherits(by, "sfc")) 
#>             by = st_sf(by)
#>         i = join(st_geometry(by), st_geometry(x))
#>         st_geometry(x) = NULL
#>         a = aggregate(x[unlist(i), , drop = FALSE], list(rep(seq_len(nrow(by)), 
#>             lengths(i))), FUN, ...)
#>         nrow_diff = nrow(by) - nrow(a)
#>         if (nrow_diff > 0) {
#>             a_na = a[rep(NA, nrow(by)), ]
#>             a_na[a$Group.1, ] = a
#>             a = a_na
#>         }
#>         a$Group.1 = NULL
#>         row.names(a) = row.names(by)
#>         st_set_geometry(a, st_geometry(by))
#>     }
#>     else {
#>         crs = st_crs(x)
#>         lst = lapply(split(st_geometry(x), by), function(y) do.call(c, 
#>             y))
#>         geom = do.call(st_sfc, lst[!sapply(lst, is.null)])
#>         if (do_union) 
#>             geom = st_union(geom, by_feature = TRUE)
#>         st_geometry(x) = NULL
#>         x = aggregate(x, by, FUN, ..., simplify = simplify)
#>         st_geometry(x) = geom
#>         st_crs(x) = crs
#>         geoms = which(vapply(x, function(vr) inherits(vr, "sfc"), 
#>             TRUE))
#>         agr_names = names(x)[-geoms]
#>         agr = rep("aggregate", length(agr_names))
#>         names(agr) = agr_names
#>         n = if (!is.null(names(by))) 
#>             names(by)
#>         else paste0("Group.", seq_along(by))
#>         agr[n] = "identity"
#>         st_agr(x) = agr
#>         x
#>     }
#> }
#> <environment: namespace:sf>
```


Overall: many thanks for your contribution.

**Comment by Robinlovelace** [comment]
Update: by using the more explicit `by` syntax it also returns an sf object as expected:

```r
world_agg4 = aggregate(world["pop"], list(world$continent), sum)
```

**Comment by Robinlovelace** [comment]
Please take a look at the update text. Any better?

**Comment by beingalink** [comment]
Thank you, the new text is much clearer and explicitely mentions the differences. Perfect! :)

**Comment by Robinlovelace** [comment]
Great. I was thinking of adding a note explaining what a generic function is, perhaps with reference to this: http://adv-r.had.co.nz/S3.html Good idea or too much detail at this stage in Chapter 3?

Any further comments/suggestions you have: very welcome, great to have input showing the benefits of having it available before it's launched as a physical book.

**Comment by beingalink** [comment]
I think the short explanation given in the sentence is fine. Perhaps adding a reference to "Advanced R" thru a footnote might be valueable for some readers but I wouldn't try to explain the OO system of R any further at that point.

Another thing you mentioned actually puzzled me more: You directly access the aggregate function of sf thru `sf:::aggregate()` and not `sf::aggregate`. Does that mean that the aggregate function of `sf` is not exported but just internal? Does this have some implications (author not wanting it to be used officially)?

Given your positive responses so far, I'll of course open further tickets in the future if things aren't clear to me. Thanks for your quick and gentle answers to my questions.

**Comment by Robinlovelace** [comment]
Hi @beingalink I think `aggregate.sf()` is designed to be called using generic method dispatch but I cannot find that explicitly done with `UseMethod()` in the source code. It is exported but I can only see it with `:::` despite it seemingly being exported. Edzer is the best person to ask about that - I'm not 100% sure what's going on so am very grateful for the feedback.

**Comment by edzer** [comment]
https://github.com/r-spatial/sf/blob/master/R/aggregate.R#L44-L46
https://github.com/r-spatial/sf/blob/master/NAMESPACE#L18

**Comment by beingalink** [comment]
@edzer Is the reason that there is no `export(aggregate)` as there is for all the `st_*` functions because `aggregate.sf()` is to be called using generic method dispatch as @Robinlovelace said above? And this is why you need to call `sf:::aggregate()` instead of `sf::aggregate()`?

**Comment by edzer** [comment]
There is no `sf::aggregate()` nor is there an `sf:::aggregate()`, @Robinlovelace 's comment about this was wrong. Package `stats` exports the generic `aggregate` (not `base` as Robin suggests), and package `sf` exports the S3 aggregate method for `sf` objects. (Package `raster`, interestingly, exports an S4 `aggregate` generic.)

The wish to call functions directly from package's namespaces using `::` works for functions, not for generics. You could call `sf:::aggregate.sf`, but then you're not using the (exported) package API.

**Comment by beingalink** [comment]
Thanks a lot for your answer. Now the whole thing is quite a bit more clear to me (`S3method()` vs. doing simply `export()` and how to call these functions).

**Comment by Robinlovelace** [comment]
Thanks for the clarification Edzer. How much work would it be to make `aggregate(pop ~ continent, FUN = sum, data = world, na.rm = TRUE)` return the same result as `aggregate(world["pop"], list(world$continent), sum)`?

Thanks for putting me right on the terminology: `aggregate` is a generic method exported by the[ `stats` package]https://stat.ethz.ch/R-manual/R-devel/library/stats/html/00Index.html), which is part of the *default installation* not base R, as I incorrectly stated. It seems to me that just by using the name `aggregate.sf()` makes the function be used if the first argument of a call to the generic `aggregate()` is an `sf` object, which would explain the behaviour.

A list of default packages loaded when you start R is provided here: https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Default-packages

**Comment by edzer** [comment]
You can't without masking `stats::aggregate.formula`. S4 can dispatch on the second argument, S3 can't.

**Comment by Robinlovelace** [comment]
Aha that explains it. Thanks again for clarifying what is going on. Gives me confidence that the updated description (it doesn't work with `~`) is future proof. Previously it implied that `aggregate()` could not return `sf` objects which was misleading so very grateful to @beingalink for pointing this out and putting the world to rights - or at least improving it incrementally!
