### ISSUE TITLE
Check RQGIS <-> QGIS 3 connection 

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#175]

**Comment by Nowosad** [comment]
@jannes-m What's the status of this issue?

**Comment by jannes-m** [comment]
I didn't have time to work further on RQGIS3 but my plan is to implement RQGIS until QGIS3 becomes the QGIS LTR in February next year at the latest. In any case, there will be a RQGIS3.

**Comment by Robinlovelace** [comment]
Sounds sensible. I think it's worded in a way that is future proof and not tied to QGIS versions so we can close this for now.

**Comment by Robinlovelace** [comment]
Suggestion: we could update the QGIS version number to be more future proof by mentioning time of writing and that QGIS 3 support is in the pipeline.

Current text

```
 Please install the long-term release of QGIS, i.e. 2.18, since RQGIS so far does not support QGIS 3.
```

Suggested new text:

```
At the time of writing (autumn 2018) RQGIS only supports the [Long Term Release](https://qgis.org/en/site/getinvolved/development/roadmap.html) (2.18) but support for QGIS 3 is in the pipeline.
```

**Comment by jannes-m** [comment]
:+1: , will change accordingly
