### ISSUE TITLE
Decide on the code style

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#177]
eg. `<-` vs `=`

**Comment by Robinlovelace** [comment]
Fuel to the :fire:  (already discussed but hey ; ) 

http://www.separatinghyperplanes.com/2018/02/why-you-should-use-and-never.html

**Comment by Robinlovelace** [comment]
Happy for this to be closed for now @Nowosad ? I think we've decided and can revisit at a later date if needs be.

**Comment by Nowosad** [comment]
Sure, I am fine with it.
