### ISSUE TITLE
Alternative layout for USA

### ISSUE THREAD

**Issue by rCarto** [Robinlovelace/geocompr#179]
I found the point made by @Nowosad on this [post](https://nowosad.github.io/post/making-alternative-inset-maps-of-the-usa/) very true.
I suggest here, for your interest,  an alternative solution.  
This alternative is based on the [`mapinsetr`](https://github.com/riatelab/mapinsetr) package. The package is not on CRAN now, but I may sent it there in the future.

```r
# devtools::install_github("riatelab/mapinsetr")
library(mapinsetr)
library(spData)
us_states2163 = st_transform(us_states, 2163)

# ! alaska and hawaii shapes and sizes use hawaiian and alaskan projections 
# but outputs formally use the us mainland projection !
# move hawaii on the us mainland map 
ha <- move_and_resize(x = hawaii, xy = c(-2490000, -2300000), prj = 2163)
# move alaska on the us mainland map 
al <- move_and_resize(x = alaska, xy = c(-1660000, 900000), prj = 2163)
# merge mainland, alaska and hawaii
us <- inset_rbinder(l=list(us_states2163, al, ha))

# plot the map
plot(st_geometry(us))
# add lines
segments(x0 = st_bbox(al)[1], y0 = st_bbox(al)[2] - 100000, 
         x1 = st_bbox(al)[3], y1 = st_bbox(al)[2] - 100000, 
         lwd= 1.2, lty =2)
segments(x0 = st_bbox(ha)[1]+200000, y0 = st_bbox(ha)[4] + 150000, 
         x1 = st_bbox(ha)[3], y1 = st_bbox(ha)[2] + 300000, 
         lwd= 1.2, lty =2)
```

![rplot](https://user-images.githubusercontent.com/3041254/37652208-1553aa32-2c3b-11e8-992c-8e0f9c727d67.png)

```r
# all features are on the same sf object
us$pop_density <- us$total_pop_15 / us$AREA
plot(us['pop_density'], breaks="quantile")
segments(x0 = st_bbox(al)[1], y0 = st_bbox(al)[2] - 100000, 
         x1 = st_bbox(al)[3], y1 = st_bbox(al)[2] - 100000, 
         lwd= 1.2, lty =2)
segments(x0 = st_bbox(ha)[1]+200000, y0 = st_bbox(ha)[4] + 150000, 
         x1 = st_bbox(ha)[3], y1 = st_bbox(ha)[2] + 300000, 
         lwd= 1.2, lty =2)
```
![rplot01](https://user-images.githubusercontent.com/3041254/37652217-1da76796-2c3b-11e8-9e08-10c9553f64db.png)

**Comment by Nowosad** [comment]
Hey @rCarto! It looks great. 
I plan to take a look at your package during the next weekend.

**Comment by mdsumner** [comment]
Alaska seems too big?  (I can check in detail later but it does seem a bit large). 

Another tiny point, but I'd like to see the real-world map as a comparison, it's not that disparate that insetting is so important, though I understand specific needs for it. 

Here's what wrld_simpl shows in 2163

![image](https://user-images.githubusercontent.com/4107631/37829745-6ac1e66c-2ef4-11e8-886c-8693b45f6452.png)

```R
plot(st_transform(st_as_sf(subset(wrld_simpl, NAME == "United States"))[1], 2163)$geometry)
```

**Comment by gisma** [comment]
great input from @rCarto  and the discussion of @Nowosad  is not only a US mapping issue. same with the antartic or Austria or central asia. so I appreciate  @mdsumner comment.
Mybe I got the message wrong  but  It hink the focus of mapping not so much is ist looking too big or too small but is what message has to be communicated . I think it is worthwhile to keep these classical "how to lie with maps" issues on mind when showing other how to produce a nice map.

**Comment by Nowosad** [comment]
Yes, you're right @gisma - it is mostly about that kind of issues.

Good point @mdsumner. I also think Alaska looks too big. @rCarto why it is like that?

**Comment by rCarto** [comment]
Alaska is big. But this: 
```r 
library(sf)
library(mapinsetr)
library(spData)
us_states2163 = st_transform(us_states, 2163)
al <- move_and_resize(x = alaska, xy = c(-1660000, 900000), prj = 2163)
st_area(alaska) - st_area(al)
```
> -0.002441406 m^2

tells me that its size is ok. 
Alaska uses the Alsakan projection (`st_crs(alaska)`) and we consider 1 meter in alaska = 1 meter in US mainland. 

For the need of insets, at scale and with correct projections see this example of the french overseas territories :
https://en.wikipedia.org/wiki/Overseas_France & https://en.wikipedia.org/wiki/Overseas_France#/media/File:France-Constituent-Lands.png

**Comment by mdsumner** [comment]
Thanks for that, appreciate you humouring me - it is big!  It still "looks wrong" to me, but I accept your comparison, the key to me is that 2163 *is* equal-area and that the area is conserved after moving it. 

FWIW, I compared with 


```R
library(spData)
library(sf)

plot(st_coordinates(st_transform(us_states, "+proj=laea +lon_0=-100 +lat_0=40")), pch = ".", asp = 1)
par(new = TRUE)
d <- as.data.frame(st_coordinates(alaska))
plot(range(d$X), range(d$Y), type = "n", asp = 1)
purrr::walk(split(d, paste(d$L1, d$L2, d$L3, sep = "-")), ~polygon(.x$X, .x$Y))

```
(If anyone knows how to use the `par(new = TRUE)` idiom with sf I'd follow that, but to make this work I had to go raw).
