### ISSUE TITLE
Issues with references

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#180]
Problem: these are missing (thanks @Nowosad ):

```
pandoc-citeproc: reference grolemund_r_2016 not found 
pandoc-citeproc: reference gillespie_efficient_2016 not found 
pandoc-citeproc: reference schratz_performance_nodate not found
```

Cause: Zotero is limited to 100 citations, we've gone over that now.

Proposed solution: sync zotero library locally.

Status: I'm on it!

**Comment by Robinlovelace** [comment]
Fixed with this commit: https://github.com/Robinlovelace/geocompr/commit/6445745902b2a68da5f121cf8ff7fc8591a1fd22

**Comment by Nowosad** [comment]
https://forums.zotero.org/discussion/64371/is-there-a-limit-to-the-number-of-items-that-zotero-can-put-in-a-bibliography

@Robinlovelace is the number of items really the issue?

**Comment by Robinlovelace** [comment]
Not sure but suspected it was - as there were 99 references last time I checked (reproduced just now):

``` r
geocompr:::dl_citations(f = "refs.bib", user = 418217, collection = "9K6FRP6N")
refs = RefManageR::ReadBib("refs.bib")
#> Ignoring entry 'brenning_spatial_2012'  (line380) because:
#>  A bibentry of bibtype 'InProceedings' has to specify the field: editor
length(refs)
#> [1] 99
```

**Comment by Robinlovelace** [comment]
Yet there are 104 in the geocompr library: https://www.zotero.org/groups/418217/energy-and-transport/items/collectionKey/9K6FRP6N

**Comment by Robinlovelace** [comment]
Another reprex that suggests the limit is the issue, when the hardcoded 100 limit is changed.

``` r
dl_citations = function(f, user, collection, key = NULL) {
  if (is.null(key)) {
    req = paste0("https://www.zotero.org/api/groups/", user, "/collections/", 
      collection, "/items/top?limit=200&format=bibtex&v=1")
    bib = httr::GET(req, httr::write_disk(f, overwrite = TRUE))  # old download method - no longer works
  } else {
    bib = RefManageR::ReadZotero(user = user, .params = list(key = key, 
      collection = collection))
    # Get bibliography (run once from project root)
    RefManageR::WriteBib(bib = bib, file = f)
  }
}
dl_citations(f = "refs.bib", user = 418217, collection = "9K6FRP6N")
readLines("refs.bib")
#> Warning in readLines("refs.bib"): incomplete final line found on 'refs.bib'
#> [1] "'limit' cannot be greater than 100 for format=bibtex"
```



Plan to simply delete that function unless anyone can think of a better solution.
