### ISSUE TITLE
Fail to compile at 02-spatial-data.Rmd

### ISSUE THREAD

**Issue by micha-silver** [Robinlovelace/geocompr#182]
I'm getting the following error when I try to render the book (both from within Rstudio and at the command line):

```
> version
              _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          4.4                         
year           2018                        
month          03                          
day            15                          
svn rev        74408                       
language       R                           
version.string R version 3.4.4 (2018-03-15)
nickname       Someone to Lean On    
bookdown::render_book("index.Rmd", output_format = "bookdown::gitbook", clean = FALSE)
processing file: index.Rmd
  |........                                                         |  12%
label: unnamed-chunk-1 (with options) 
List of 2
 $ include: logi FALSE
 $ cache  : logi FALSE
  |................                                                 |  25%
   inline R code fragments
  |........................                                         |  38%
label: unnamed-chunk-2 (with options) 
List of 1
 $ echo: logi FALSE
  |................................                                 |  50%
   inline R code fragments
  |.........................................                        |  62%
```

..... more normal output ...... until:

```
Quitting from lines 184-185 (02-spatial-data.Rmd)
Error in CPL_crs_from_epsg(as.integer(x)) :
  Expecting a single value: [extent=4].
Calls: local ... st_crs.numeric -> make_crs -> CPL_crs_from_epsg -> .Call
In addition: Warning message:
In if (is.na(x)) NA_crs_ else if (inherits(x, "crs")) x else if (is.numeric(x))
CPL_crs_from_epsg(as.integer(x)) else if (is.character(x)) { :
  the condition has length > 1 and only the first element will be used
Execution halted
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile 02-spatial-data.Rmd
In addition: Warning message:
In verify_rstudio_version() :
  Please install or upgrade Pandoc to at least version 1.17.2; or if you are using RStudio, you can just install RStudio 1.0+.`
```

Thanks, Micha

**Comment by Nowosad** [comment]
Thanks @micha-silver. We are aware of this problem (https://github.com/r-spatial/sf/issues/685). I'll fix this issue in the next few days.

**Comment by Nowosad** [comment]
@micha-silver It should work now. You just need to install the newest version of **spData**:
```r
devtools::install_github("nowosad/spData")
```

**Comment by micha-silver** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Worked fine
    Thank you
    
    On 03/24/2018 08:08 PM, Jakub wrote:
    
    
      @micha-silver
        It should work now. You just need to install the newest version
        of spData:
      
        devtools::install_github("nowosad/spData")
      
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Robinlovelace/geocompr","title":"Robinlovelace/geocompr","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Robinlovelace/geocompr"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Nowosad in #182: @micha-silver It should work now. You just need to install the newest version of **spData**:\r\n```r\r\ndevtools::install_github(\"nowosad/spData\")\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/Robinlovelace/geocompr/issues/182#issuecomment-375908776"}}}
    
    
    -- 
Micha Silver
Arava Drainage Authority
phone +972 776-449459
cell: +972-523-665918
