### ISSUE TITLE
Issue when compiling Chapter 9 - html dependency not found

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#187]
It gives me this error message:

```
Error: path for html_dependency not found: /home/robin/R/x86_64-pc-linux-gnu-library/3.4/leaflet/htmlwidgets/lib/Leaflet.label
Please delete _main.md after you finish debugging the error.
Execution halted
```

**Comment by Nowosad** [comment]
@Robinlovelace is it still a problem or can we close this issue?

**Comment by Robinlovelace** [comment]
Yes, it's still preventing me from building Chapter 9, with the latest version of leaflet.

**Comment by Nowosad** [comment]
Is it working on travis? If so - maybe that is a local problem of some sort..

**Comment by Robinlovelace** [comment]
Yeah it's just a local problem. Flagged it here in case it affects other people.

**Comment by Robinlovelace** [comment]
Works when I recloned the repo so must have been something temporary. It's strange because I deleted the cache with

```r
unlink("_bookdown_files/", recursive = T)
```

There must have been something else going on in that folder... Any ideas? Happy it's fixed in any case even though I'm not quite sure why!
