### ISSUE TITLE
Remove temporary line of code (units issue in rmapshaper)

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#188]
The new (temporary) line of code - https://github.com/Robinlovelace/geocompr/commit/829881e7b0a3af52e23b672e9e8e8a7891319d01.

Related to https://github.com/ateucher/rmapshaper/issues/75#issuecomment-379002318.

**Comment by Robinlovelace** [comment]
Great fix - can revert that and close this when fixed upstream.

**Comment by ateucher** [comment]
Hey @Nowosad - I have started working on this (and related issues) [here](https://github.com/ateucher/rmapshaper/tree/preserve-df), but it is definitely a work in progress. If you want to write a test or two for `units` treatment that would be awesome.

**Comment by Robinlovelace** [comment]
This is the last remaining 'proper' issue so keeping open. But not a biggy. Keep us updated of any developments and many thanks for an awesome geospatial package @ateucher .

**Comment by Robinlovelace** [comment]
https://github.com/ateucher/rmapshaper/pull/116

**Comment by Nowosad** [comment]
@Robinlovelace neat. One question though -- should it not reinstate units later?

**Comment by Robinlovelace** [comment]
Good point. Not without a warning.
