### ISSUE TITLE
Layered plots not aligning

### ISSUE THREAD

**Issue by erstearns** [Robinlovelace/geocompr#198]
Hello again! This is linked to my previous issue #197, in section 2.1.4, this code : 
`plot(world["continent"])
plot(world_centroids,add=TRUE, cex = sqrt(world$pop)/10000)`

produces misaligned layers, as it did with the Asia object. The centroids proportional to population are appearing in the lower right corner, as they did with the Asia object. See here for example: 
![image](https://user-images.githubusercontent.com/25041596/38824948-c7287204-415f-11e8-9150-ca90c844f644.png)

I am new to this thus unfortunately do not have code to suggest for fixing the issue.

**Comment by Robinlovelace** [comment]
Are you sure this is an issue with the book? I suspect it may be linked to the underlying software (**sf**).

Please try to install the latest version of sf, I suspect it's linked to https://github.com/r-spatial/sf/issues/704 . Also, just to clarify, have you found an issue with the output displayed in the book's online home at http://geocompr.robinlovelace.net/ or is it an issue you're having on your computer?

**Comment by Nowosad** [comment]
https://geocompr.robinlovelace.net/spatial-class.html#fig:contpop

**Comment by erstearns** [comment]
Thank you for the fix! Works properly now!

**Comment by erstearns** [comment]
Actually -- sorry about that, meant to post that for the Asia plot -- for this one (Section 2.1.5), the plot displayed still does not reflect the code. The code when run displays this plot: 
![image](https://user-images.githubusercontent.com/25041596/38880648-12f247d0-421b-11e8-9de8-d59287a76276.png)

I am trying a few things now and this code gets me closer:
`plot(world["continent"],reset=FALSE,main="Country contintinents and populations", graticule = st_crs(4326))
plot(world_centroids,add=TRUE, cex = sqrt(world$pop)/10000, lwd = 5)`

However the graticule setting still appears off so tried this but not proper projection to match your background grid in the display plot: 

`laea = st_crs("+proj=laea +lat_0=30 +lon_0=-95") # Lambert equal area
world_laea <- st_transform(world, laea)
plot(world_laea["continent"],reset=FALSE,main="Country contintinents and populations", graticule = TRUE)`

Sorry for the mixup!

**Comment by Robinlovelace** [comment]
Try this (may need to update the code shown in the chapter so thanks for raising this):

``` r
library(sf)
#> Linking to GEOS 3.5.1, GDAL 2.2.2, proj.4 4.9.2
library(spData)
world_proj = st_transform(world, "+proj=eck4")
old_mar = par()$mar
par(mar = c(0, 0, 0, 0))
world_centroids_largest = st_centroid(world_proj, of_largest_polygon = TRUE)
main = "\nCountry continents and populations"
plot(st_geometry(world_proj), graticule = TRUE, reset = FALSE)
plot(world_proj["continent"], add = TRUE)
cex = sqrt(world$pop)/10000
plot(st_geometry(world_centroids_largest), add = TRUE, cex = cex, lwd = 2)
```

![](https://i.imgur.com/9G9bk1p.png)

``` r
par(mar = old_mar)
```

**Comment by erstearns** [comment]
This works to produce the graphic you have pictured!  However the title is still not showing up, as it isn't in your plot either. The following code works to get the title included:

```
world_proj = st_transform(world, "+proj=eck4")
old_mar = par()$mar
par(mar = c(0, 0, 0, 0))
world_centroids_largest = st_centroid(world_proj, of_largest_polygon = TRUE)
plot(st_geometry(world_proj),main="\nCountry contintinents and populations", graticule = TRUE, reset = FALSE)
plot(world_proj["continent"], add = TRUE)
cex = sqrt(world$pop)/10000
plot(st_geometry(world_centroids_largest), add = TRUE, cex = cex, lwd = 2)
```
Result:
![image](https://user-images.githubusercontent.com/25041596/38882767-e55f4a48-421f-11e8-9e3b-d2fbf49d0a1e.png)

Thank you!

**Comment by Robinlovelace** [comment]
Updated. There are pros and cons here but added the title back. I think by default **sf** plots colors according to the first variable, explaining the coloured circles.
