### ISSUE TITLE
Additional packages in the Selected R packages for spatial data retrieval table

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#214]
https://geocompr.robinlovelace.net/read-write.html#tab:datapackages
- [x] https://cran.r-project.org/web/packages/getlandsat/index.html
- [ ] https://github.com/16EAGLE/getSpatialData

**Comment by Robinlovelace** [comment]
Awesome work @Nowosad - there are always more packages appearing so we will need to be selective. But I think that was an important one. Something I've just seen that is at least worth linking to is this - great overview of weather data access options from R (this :package: seems the best atm): https://github.com/ropensci/GSODR#other-sources-of-weather-data-in-r - worth adding? I can give it a bash if so!

**Comment by Robinlovelace** [comment]
Heads-up on this @Nowosad I've added some context saying there are loads of them and have linked to the overview provided by **GSODR**.
