### ISSUE TITLE
Popups in Figure 1.1 are missing.

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#218]
The popups in Figure 1.1 Where the authors are from have disappeared in the online book.
(It works locally..)

**Comment by Nowosad** [comment]
Update: popups are on the map. However, there is some unknown issue influencing the markers and popups.

**Comment by Robinlovelace** [comment]
Agreed. Popups are there but the labels are grey, as illustrated below. Suggest it may be worth reporting at  https://github.com/rstudio/leaflet/issues any ideas @schloerke  (and thanks for great updates in **leaflet**).

The closest issue I can see in there is this: https://github.com/rstudio/leaflet/issues/527 

![image](https://user-images.githubusercontent.com/1825120/39898422-80942880-54ae-11e8-97f5-aadea30f2937.png)

**Comment by schloerke** [comment]
@Nowosad @Robinlovelace 

Ok. Two independent bugs.  

1. The markers are not showing up
  * Please download `devtools::install_github("rstudio/leaflet#544")` and see if that fixes your website markers not showing up.  (The leaflet cdn does is not supporting https which is news to me. Changed to unpkg.com). Please let me know if this fixes your missing marker issue.  Thank you in advance!
2. mapview is loading a js library called PopupTable which is setting the popup css background to #c4c4c4. This style will have to be overwritten in a local css file of your own to override the color.
  * Popup requirement: https://github.com/r-spatial/mapview/blob/b7efb59ca0ab3f17ce5f1061355374fea850a56c/R/popup.R#L485
  * Popup css line: https://github.com/r-spatial/mapview/blob/develop/inst/htmlwidgets/lib/popup/popup.css#L141

\-Barret

**Comment by Robinlovelace** [comment]
Many thanks for the update - will look into it.

**Comment by Nowosad** [comment]
Popups are back! http://geocompr.robinlovelace.net/intro.html

**Comment by Robinlovelace** [comment]
Just tested and yes they're back and looking great. Many thanks Jakub!
