### ISSUE TITLE
Mention other approaches in spatial modelling chapters

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#220]
Mention and add links to **brms**, **keras** and/or **tensorflow** packages. As discussed with @Nowosad. Thoughts @jannes-m? See these as non-essential but beneficial for context.

**Comment by Nowosad** [comment]
@jannes-m What's your opinion on this?

**Comment by Robinlovelace** [comment]
Good question. I also think we should reference this recent paper https://peerj.com/articles/5518/ (not yet in there) and possibly link to this reproducible tutorial: https://github.com/Envirometrix/BigSpatialDataR

**Comment by Robinlovelace** [comment]
Heads-up @thengl it's still not too late to input into this chapter but time is running out: https://geocompr.robinlovelace.net/spatial-cv.html any comments/suggestions v. welcome although we cannot guarantee to have time to act on them: https://geocompr.robinlovelace.net/spatial-cv.html

**Comment by jannes-m** [comment]
**keras** and **tensorflow** are the current hype. If we find a good way to say that these tools (basically neural networks) can also be beneficial for geocomputing, then there's no harm in mentioning them. You need a lot of data in terms of observations and columns, so yes, quite handy technique to extract patterns from an ever-increasing amount of data. Ah right, we should mention machine learning and AI in this context.

**Comment by Robinlovelace** [comment]
Closing as this is covered in the conclusion.
