### ISSUE TITLE
missing citation in section 1.3

### ISSUE THREAD

**Issue by katiejolly** [Robinlovelace/geocompr#229]
Looks like there was supposed to be a full citation with "Robinson", but maybe I'm reading it wrong! Didn't see anything in the sources list at the end of the chapter.

> Python is the final language for geocomputation that deserves attention in this section. Like R, Python has gained popularity due to the rapid growth of data science (Robinson)

**Comment by Robinlovelace** [comment]
Closed in https://github.com/Robinlovelace/geocompr/commit/5a0de5b374f6bb2f91a591abd8b7724c4d983bc6 - I think this is better (I've removed the formal reference as it's just a blog post, although a very good one!).
