### ISSUE TITLE
different dim() output in 2.2 (raster data)

### ISSUE THREAD

**Issue by katiejolly** [Robinlovelace/geocompr#235]
In section 2.2, the text says:

> To access individual header information, you can use following commands: dim(new_raster) (dimensions - number of rows, number of columns, number of cells)...

But when I ran `dim(new_raster)`, I got:

`> dim(new_raster)
[1] 457 465   1`

The number of cells, though, would be  

`> ncell(new_raster)
[1] 212505`

So it looks like `dim(new_raster)` is returning number of rows, number of columns, and number of layers in this case. I also checked the documentation

> dim {raster}	R Documentation
> **Dimensions of a Raster* object**
> 
> Description
> 
> Get or set the number of rows, columns, and layers of a Raster* object. You cannot use this function to set the dimensions of a RasterStack object.

Maybe an older version of `dim()` returned the number of cells, or am I missing an argument? Thank you!
(I also checked my version of `{raster}` and it is the most recent (2.6-7))

**Comment by katiejolly** [comment]
Same behavior with dim(r_brick) in the RasterBrick section.

**Comment by jannes-m** [comment]
@katiejolly Thanks for spotting this! You are absolutely right: `dim()` returns the number of rows, columns and layers. Have changed this now, thanks again! But note when you type `new_raster` into the console this will print the number of rows, columns and number of cells.
