### ISSUE TITLE
Broken figures

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#246]
- [x] Figure 1.1 (style)
- [x] Various figures in c2 lack captions, as illustrated here: https://github.com/Robinlovelace/geocompr/commit/0df1e9d95153f0e2f155638d13f5fa1959cf9558
- [x] Figure 3.2
- [x] Figure 4.2
- [x] Figure 5.11
- [x] Figure 8.18 (style)
- [x] Figure 9.1
- [x] Figure 12.4

**Comment by Robinlovelace** [comment]
- [ ] Various figures in c2 lack captions, as illustrated here: https://github.com/Robinlovelace/geocompr/commit/0df1e9d95153f0e2f155638d13f5fa1959cf9558

**Comment by Nowosad** [comment]
@Robinlovelace Do you think that captions are necessary in the Simple feature geometry types section?

**Comment by jannes-m** [comment]
In general, I would say that every figure needs a caption. But I think I know which figures you are referring to where one could about an exception. Still, I would place a caption, this is more consistent and at the same time you don't know where the final editing will place the figure so it's better to have a caption in case the figure is not placed closed to the text it is referring to. I also think that a 2x2 grid might be probably a better solution for representing the lines, points, polygon, polygon with a hole figure. And then a caption would be definitely a requirement. One could also place the next two figures in one figure (Multi-figure + geometry collection).

**Comment by Nowosad** [comment]
Sure thing.

**Comment by Nowosad** [comment]
@jannes-m @Robinlovelace Figure 3.2 is now removed (not by me..). Is it was intentionally? If so - there are the figure references left in the text...

**Comment by jannes-m** [comment]
In fact, all raster figures are missing now from 3.3 Manipulating raster objects. This was certainly not intentional, and I think I haven't done this but I will have a look at this in the next days. Thanks for spotting, @Nowosad !!

**Comment by Nowosad** [comment]
I think I found the issue with figure 3.2 - there was a change with `tmap_arrange()`. I think I've fixed it now.

**Comment by Nowosad** [comment]
@jannes-m What is the role of the black grid in the left panel of Figure 4.7?

**Comment by Nowosad** [comment]
Update: Figure 9.1 is missing.

**Comment by jannes-m** [comment]
Well, the black grid is the raster we use to subset the raster it overlays (Figure 4.7), it also says so in the text. But if this is unclear, let me know, then I'll have to rewrite to make it clearer. 
Regarding Figure 9.1, interesting, no idea why this figure is now missing, I guess, someone has renamed the .png file (will have a look). There are a few more figures missing from c9, I plan to take care of this next week.

**Comment by Robinlovelace** [comment]
9.1 is now fixed. Others? The sliver example is awesome, I will use it and cross-reference it from earlier sections.

**Comment by Nowosad** [comment]
@jannes-m - I was just confused because I thought the left panel is connected to the middle and right ones... Maybe it is better to split them into two figures?

**Comment by Robinlovelace** [comment]
Heads-up @Nowosad I've 'fixed' Figure 12.4, by removing it. 8 down, one to go. Great work!
