### ISSUE TITLE
include dodgr example in Ch 12?

### ISSUE THREAD

**Issue by mpadge** [Robinlovelace/geocompr#253]
Following on from discussion in [this `dodgr` issue](https://github.com/ATFutures/dodgr/issues/58#issuecomment-396199208), you could maybe add an example along the lines of
```
net <- dodgr::dodgr_streetnet ("bristol uk")
graph <- dodgr::weight_streetnet (net, wt_profile = "bicycle")
n_origins <- 100
n_destinations <- 200
od_mat <- matrix (runif (n_origins * n_destinations), nrow = n_origins,
                  ncol = n_destinations)
verts <- dodgr::dodgr_vertices (graph)
origins <- sample (verts$id, size = n_origins)
destinations <- sample (verts$id, size = n_destinations)
f <- dodgr::dodgr_flows_aggregate (graph, from = origins, to = destinations,
                                   flow = od_mat)
dodgr_flowmap (f)
```
It's a bit complex I admit. Alternatively, if you had a pre-prepared OD matrix, that could be mapped to the network to avoid the `dodgr_vertices` and `sample` calls.

The following code further demonstrates how to make an interactive map, first reducing flows to manageable size by removing lowest 10% of values
```
indx <- which (f$flow > (0.1 * max (f$flow)))
f_sf <- dodgr::dodgr_to_sf (f [indx, ])
f_sf <- sf::st_sf (f_sf$dat, f_sf$geoms)
flow <- f_sf$flow / max (f_sf$flow)
cols <- rev (heat.colors (30)) [30 * flow]
mapview::mapview (f_sf, color = cols, lwd = 10 * flow)
```

**Comment by mpadge** [comment]
Cool. As always, let me know of any potential code modifications you might think of that might make the task easier, and I'll happily incorporate

**Comment by Robinlovelace** [comment]
Closing for now. @mpadge let me know if you get a chance next week but atm the priority is completing the book. Happy for this to be re-opened later down the line...
