### ISSUE TITLE
Travis build broken

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#255]
Seems to be affecting Chapter 2, which I've not touched lately (have been working on c10) so suspect it's due to a change in package. Travis log: https://travis-ci.org/Robinlovelace/geocompr/builds/393339585#L2653

And message

```
Quitting from lines 682-683 (02-spatial-data.Rmd) 
Error in extract_raster__data(nm = rl@data@names, isf = rl@data@isfactor,  : 
  could not find function "extract_raster__data"
```

**Comment by Nowosad** [comment]
Don't worry;) 99% chance it is due to the recent work with tmap. Martijn is improving categorical rasters support.

**Comment by Robinlovelace** [comment]
Indeed, as per my comment here: https://github.com/mtennekes/tmap/commit/ef5386bac05e9c83cacbc85701eb48031ad9a75a#commitcomment-29392734
