### ISSUE TITLE
Michael Sumner's rasters tips 

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#26]
https://twitter.com/mdsumner/status/860482390702960641 

- get the thing into memory for processing: readAll(x) /1
- doing multiple extractions on same vector layer, use cellFromXY, cellFromPolygons etc. to build index /2
- don't use projectRaster(raster, crs = projection(shp)), use spTransform(shp, projection(raster)) /3
- extract on a one-layer RasterLayer may be slow, use extract(brick(raster()), ...) one weird trick /4
- extract tiled file is VERY SLOW, readAll into memory, or rewrite untiled writeRaster(raster(), "file.tif") if too big for mem /5
- read the performance vignette for large files https://cran.r-project.org/web/packages/raster/vignettes/functions.pdf … /6
- (read the introduction vignette too) /7
- a brick on file in .grd format is slow for crop(brick, ex) for every layer, it's better if brick is in memory /8
- re /8 this is not true for a brick on file in NetCDF format, internally optimized for crop() on all layers /9
- crop, extract, other ops will be slow for a stack composed of multiple single-layer files, try conversion to a bulk format /10
- do try coarse grained parallel::parLapply(cluster, list-of-rasters-or-files, rasterOps) it can be effective /11
- explore velox, fasterize, and unrelated packages like spatstat, oce / 12
- sometimes raster(readGDAL(file)) is faster than raster(file) /13

The idea from https://twitter.com/clavitolo/status/865671631368105984

**Comment by Nowosad** [comment]
raster tips: set options(rasterMaxMemory = nbytes) to change limit for redirect to file (by default not set, hard coded to 100Mb)

https://twitter.com/mdsumner/status/868655402224762880

**Comment by Robinlovelace** [comment]
@mdsumner thanks for providing this list. Are they still your top tips or would you make any alterations to them based on recent developments? Are any not futureproof?

**Comment by Robinlovelace** [comment]
Great - I think we've got most of those covered now:

- General intro to raster: http://geocompr.robinlovelace.net/spatial-class.html#raster-data
- Spatial operations: http://geocompr.robinlovelace.net/spatial-operations.html#spatial-ras
- Geometric operations: http://geocompr.robinlovelace.net/transform.html#geo-ras
- Raster-vector: http://geocompr.robinlovelace.net/raster-vector.html

One question: is the distinction between spatial and geometric operations clear? And have we missed anything? Thanks @mdsumner for all these tips, hope we've done them justice!

**Comment by mdsumner** [comment]
LGTM!  The book is awesome btw, it's great to see this all laid out in detail. 

5/ is now fixed, it's in the queue on CRAN

There's no need to `as(x, "Spatial")` for extract now for sf, since Nov 2017 (support for sf is patchy but more is coming)

One new "tip" is that extract can be massively sped up by using fasterize, but it's a bit abstract - and presumably raster will apply this improvement some time soon. I also didn't realize extract had that `df` argument (which is embarassing). 

```R
library(raster)
library(sf)

#install.packages("spDataLarge", repos = "https://nowosad.github.io/drat/",
#                 type = "source")
library(spDataLarge)
srtm = raster(system.file("raster/srtm.tif", package = "spDataLarge"))
zion = read_sf(system.file("vector/zion.gpkg", package = "spDataLarge"))
zion = st_transform(zion, projection(srtm))

fast_extract <- function(x, y) {
  y[["ID"]] <- seq_len(nrow(y))
  rast_poly <- fasterize::fasterize(y, x, field = "ID")
  vals <- values(rast_poly)
  out <- raster::extract(x, seq_len(ncell(x))[!is.na(vals)], df = TRUE)
  out[["ID"]] <- vals[!is.na(vals)]
  out
}
library(rbenchmark)
benchmark(ex_values = raster::extract(x = srtm, y = zion, df = TRUE),
fex_values = fast_extract(srtm, zion), 
replications = 2)
#test replications elapsed relative user.self sys.self user.child sys.child
#1  ex_values            2   9.773   12.402     9.776        0          0         0
#2 fex_values            2   0.788    1.000     0.788        0          0         0


ex_values = raster::extract(x = srtm, y = zion, df = TRUE)
fex_values = fast_extract(srtm, zion)
identical(ex_values, fex_values)
#[1] TRUE
```

**Comment by Nowosad** [comment]
Hey @mdsumner! Thanks for you kind words and sharing your knowledge.
I like the idea for `fast_extract()`, but it is probably too abstract for the book. It is also (I assume) more limited that `raster::extract()`, e.g. extracting by points or lines are not supported.

Yep, I am waiting for more consistent sf support in **raster**. Right now, `crop` expects **sp** object, while `mask` can also work on **sf** ones...

**Comment by jhagenauer** [comment]
Thanks for \4... this seems still to improve performance significantly.

**Comment by mdsumner** [comment]
fwiw this suggests it shouldn't matter any more: https://github.com/rspatial/raster/issues/5

![image](https://user-images.githubusercontent.com/4107631/94248100-57e8b300-ff61-11ea-8027-e75e1771f95b.png)
