### ISSUE TITLE
mapdeck

### ISSUE THREAD

**Issue by SymbolixAU** [Robinlovelace/geocompr#264]
I've been writing [mapdeck](https://github.com/SymbolixAU/mapdeck) over the last couple of weeks. It uses [deck.gl](http://deck.gl/#/) for WebGL rendering, and [Mapbox](https://www.mapbox.com/) for the maps. 

The benefit of using WebGL is its ability to render many thousands (millions) of points/shapes on a map ([for example](https://twitter.com/symbolixAU/status/1023419542712664064)).

Maybe something to consider for future iterations?

**Comment by Robinlovelace** [comment]
Looks promising and something I've been keeping an eye on. Can you post a simple reproducible example to show what it can do building on this:  


``` r
# Another recent web mapping package is **mapdeck** which uses the `Deck.gl` JavaScript library to enable efficient rendering in the browser allowing large datasets (up to millions of points) to be visualized interactively. A minimal reproducible example is demonstrated below (results not shown):
library(spData)
devtools::install_github("SymbolixAU/mapdeck")
#> Using GitHub PAT from envvar GITHUB_PAT
#> Skipping install of 'mapdeck' from a github remote, the SHA1 (28d97770) has not changed since last install.
#>   Use `force = TRUE` to force installation
mapdeck::add_polygon(nz)
#> Error in names(object) <- nm: attempt to set an attribute on NULL
```

Created on 2018-08-03 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Created on 2018-08-03 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

It will be difficult to justify putting that in the printed edition if it's not on CRAN, what are planned timelines for it?

Thanks for the heads-up in any case, looks promising!

**Comment by SymbolixAU** [comment]
Sure thing

```
library(spData)
library(sf)
library(mapdeck)

## Currently supports sf objects projected into Web Mercartor
sf <- sf::st_sf(nz)
sf <- sf::st_transform(sf, "+init=epsg:4326")

## you need a MAPBOX access token
key <- read.dcf("~/Documents/.googleAPI", fields = "MAPBOX")

mapdeck(
  token = key
  , style = 'mapbox://styles/mapbox/dark-v9'
  ) %>%
  add_polygon(
    data = sf
    , layer_id = "polygon"
    , fill_colour = "Median_income"
    )
```

![screen shot 2018-08-03 at 6 57 32 pm](https://user-images.githubusercontent.com/18344164/43634345-2c10f96c-974f-11e8-9404-19c938533020.png)

In an ideal world I'd like v1.0 out by the end of August.

**Comment by Robinlovelace** [comment]
Thanks for the reprex, looks good. Let me know when there are any updates (e.g. on CRAN) and we can include it.

**Comment by SymbolixAU** [comment]
will do.

**Comment by Robinlovelace** [comment]
No that's not a problem. I'll get an API key to check it's fully reproducible. We do the same thin in the GIS chapter, where we save versions of the outputs to avoid tricky dependencies: https://github.com/Robinlovelace/geocompr/blob/master/09-gis.Rmd

**Comment by Robinlovelace** [comment]
Any update on this? Please provide something by the end of the week if possible. Looks like great work in any case, will be awesome if you can visualise z dimensions.

**Comment by SymbolixAU** [comment]
Thanks for the reminder, I'm on it - you'll have an example in a couple of days.

**Comment by SymbolixAU** [comment]
How's this as a start:



[Mapdeck](https://github.com/SymbolixAU/mapdeck) provides acecss to Uber's [Deck.gl](http://deck.gl/#/) framework, which in turn uses WebGL for rendering graphics. Since it's using WebGL it's well suited for visualising large datastes, and quickly. 

Mapdeck uses [Mapbox](https://www.mapbox.com/) as the map layer, so you need an [access](https://www.mapbox.com/help/how-access-tokens-work/) token to view the maps. 

An advantage over some other mapping libraries in R is the 2.5d perspectives offered. That is, you can pan, zoom and rotate around the maps, and view the data 'extruded' from the map.

This example is using a data set of road accidents in the UK. The height of the bars respresent higher numbers of accidents in that area. 

```{r}

library(mapdeck)

set_token(read.dcf("~/Documents/.googleAPI", fields = "MAPBOX"))

df <- read.csv(paste0(
'https://raw.githubusercontent.com/uber-common/deck.gl-data/master/',
'examples/3d-heatmap/heatmap-data.csv'
))

mapdeck( 
  style = mapdeck_style('dark')
  , pitch = 45 
  , location = c(0, 52)
  , zoom = 4
  ) %>%
add_grid(
  data = df
  , lat = "lat"
  , lon = "lng"
  , cell_size = 1000
  , elevation_scale = 50
  , layer_id = "grid_layer"
  , colour_range = viridisLite::plasma(5)
)

```

In the browser you can zoom in and out, drag the map, and hold Cmd/Ctrl and drag to rotate the map

You can add multiple layers to a map by 'piping' them together with the `%>%` operator. 

```{r}

df <- capitals
df$key <- 1L
df_arcs <- merge(
  df[df$country == "Australia", ]
  , df[df$country != "Australia", ]
  , by = "key"
  )

mapdeck(
  style = mapdeck_style('dark')
  , pitch = 45
) %>%
  add_arc(
    data = df_arcs
    , origin = c("lon.x","lat.x")
    , destination = c("lon.y", "lat.y")
    , stroke_from = "country.x"
    , stroke_to = "country.y"
  ) %>%
  add_scatterplot(
    data = capitals
    , lon = "lon"
    , lat = "lat"
    , fill_colour = "country"
    , radius = 5000
  )

```

Mapdeck also supports `sf` objects

```{r}
library(sf)
str(roads)


mapdeck(
  , style = mapdeck_style('dark')
  , location = c(145, -37.8)
  , zoom = 10
  ) %>%
  add_path(
    data = roads
    , stroke_colour = "RIGHT_LOC"
    , layer_id = "path_layer"
    , tooltip = "ROAD_NAME"
    , auto_highlight = TRUE
  )

```

**Comment by Robinlovelace** [comment]
Great work! Could you add this as a PR on line 684 onwards in this file?: 
https://github.com/Robinlovelace/geocompr/edit/master/08-mapping.Rmd

**Comment by Robinlovelace** [comment]
Just ran the example. Agree, really impressive output!

**Comment by SymbolixAU** [comment]
Thanks!

> Great work! Could you add this as a PR on line 684 onwards in this file?:

done.

**Comment by Robinlovelace** [comment]
Job done! :world_map: :rocket: :guitar:

**Comment by maxlavoie** [comment]
To be able to rotate the map by holding Cmd/Ctrl + arrow should be added to the documentation. Nice tip!

**Comment by Robinlovelace** [comment]
> To be able to rotate the map by holding Cmd/Ctrl + arrow should be added to the documentation. Nice tip!

That's one for @SymbolixAU, in the (I think likely) event that you didn't see this.
