### ISSUE TITLE
Packages 'decidio' and 'rmapshaper' not loading

### ISSUE THREAD

**Issue by erstearns** [Robinlovelace/geocompr#266]
Hello there,
I just got a new computer (woot woot!) and am trying to reproduce the book locally again, however when I run: `devtools::install_github("robinlovelace/geocompr") `, the packages 'decidio' and 'rmapshaper' fail to load. I tried loading them each individually, and 'decidio' fails because it is supposedly unavailable for R 3.5.1. while 'rmapshaper' fails because of dependency failures. Any suggestions for fixing these issues? Thank you.

**Comment by Robinlovelace** [comment]
I can see **decido** is no longer on CRAN and have removed it from the DESCRIPION (it's no longer used in the main book) - see https://github.com/Robinlovelace/geocompr/commit/c3d19842207cfe79bf278e2511cf9742b4aeaa7b 

Regarding **rmapshaper** it depends what operating system you're using. See https://github.com/ateucher/rmapshaper#installation (not much there) - I suspect it's an issue with installing **v8**: https://github.com/jeroen/V8

Let us know how you get on an thanks for the input!

**Comment by erstearns** [comment]
Thank you for the quick response! That fixed the **decido** issue.  I was running the install on Ubuntu. I will try installing the dev version.

I also have a new work machine running Windows and ran the package install on it and no longer encounter the **decido** issue, however I get a loading failure message for **spDataLarge**.  I found this page, however, and have modified the advice given there for R 3.5.1 for anyone encountering similar issues:

1. Install all of the required packages using `devtools::install_github("robinlovelace/geocompr")`
2. Install **spDataLarge** after loading **spData** - `library(spData)` and afterwards install **spDataLarge** using its address -` install.packages("spDataLarge", repos = "https://nowosad.github.io/drat/", type = "source")`

Thanks again!
