### ISSUE TITLE
4.2.4 non-overlapping joins: units error

### ISSUE THREAD

**Issue by seanangio** [Robinlovelace/geocompr#269]
Hi, really enjoying the book. I'm running into an error in the Non-overlapping joins section of Ch 4. Perhaps I've done something wrong.

Running this block:
```
cycle_hire_P = st_transform(cycle_hire, 27700)
cycle_hire_osm_P = st_transform(cycle_hire_osm, 27700)
sel = st_is_within_distance(cycle_hire_P, cycle_hire_osm_P, dist = 20)
```

Returns for me:
```
Error: In ‘udunits_from_proj[x$units]’, ‘udunits_from_proj’ and ‘x’ are not recognized by udunits. See a table of valid unit symbols and names with valid_udunits(). Add custom user-defined units with install_symbolic_unit().
```

Any advice on avoiding that error?

**Comment by seanangio** [comment]
I encounter the same error again in a place like 4.2.6 Distance relations.

```
nz_heighest = nz_height %>% top_n(n = 1, wt = elevation)
canterbury_centroid = st_centroid(canterbury)
st_distance(nz_heighest, canterbury_centroid)
```
Returns for me:
```
Error: In ‘udunits_from_proj[x$units]’, ‘udunits_from_proj’ and ‘x’ are not recognized by udunits. See a table of valid unit symbols and names with valid_udunits(). Add custom user-defined units with install_symbolic_unit().
```

**Comment by Robinlovelace** [comment]
I think this is an issue with R packages or system dependencies, not the book itself.

Try running:

```r
devtools::install_github("robinlovelace/geocompr")
```

that should update old packages and tell you if anything is going wrong. Info on installing **units** can be found here: https://github.com/r-quantities/units/

**Comment by seanangio** [comment]
It's definitely not the book's problem. I can't install `lwgeom`. 
```
ERROR: dependencies ‘lwgeom’, ‘rcartocolor’ are not available for package ‘geocompr’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/geocompr’
Installation failed: Command failed (1)
```
I suppose I'll ask there if I can't sort it out. Thanks

**Comment by seanangio** [comment]
updating R to the latest version solved this problem for anyone else facing something similar.

**Comment by Robinlovelace** [comment]
Great to hear you fixed it and thanks for documenting it for the benefit of others. Any other issues you have, or opportunities to improve the book, please let us know.
