### ISSUE TITLE
Michael Sumner's vectors tips 

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#27]
https://twitter.com/mdsumner/status/860676991040733184

- [x]  rmapshaper::ms_simplify for reducing resolution while maintaining topology (shared edges) and object data /1
~~- raster::shapefile for easy read/write /2 (but say no to shp)~~
- rgeos::gBuffer(xsdf, width = 0, byid = TRUE) and similar w sf::st_buffer will resolve many topology problems, geometry errors /3
- ggpolypath will draw polygon holes correctly but is limited with some aesthetics because identity is implicit in gg not absolute /4
~~- ggplot2-like fortify to df decomposition is rogue but helpful for some tasks, see spbabel for examples including recomposition /5~~
~~- use df[c("x", "y")] <- http://as.data .frame(rgdal::project(as.matrix(df[c("lon", "lat")]), prj)) rogue diy transforms /6~~
- [x]  - don't go rogue until you know what you're doing with from/to proj crs ... /7
- ultimate auto-graticule is probably unicorn, see graticule pkg for manual control over getting exactly what's needed /7
- your map is a unique creation, do whatever rogue or otherwise to get what you need /8
- use mapview and leaflet and plotly to interactively explore your map data /9
- use fasterize for rasterizing /10
- [x]  use sf::st_crs for EPSG look up /11
- [x]  use Geopackage for data you care about, shapefile do a lot of dumb down, though sometimes it's the only option /12
- sf uses planar assumptions for projected but ellipsoidal for longlat /13
- set crs NA for planar in longlat, transform back then forward for ellipsoidal in projected (need tell much longer story here) /14
- sf::st_segmentize in longlat? You probably wanted vertical orthodromes and horizontal loxodromes, i.e planar assumption /15
- sf poly constructors do heavy checking on ring closure, diy/rogue for fast creation when checking not needed /16
- [x]  use sf st_read/read_sf and write counterparts for wicked fast I/o, use as(x, "Spatial") st_as_sf rather than rgdal for sp i/o /17
- try geom_sf in dev version of tidyverse/ggplot2 share your real world examples! /18
- use spex pkg to get an extent polygon (rather than just a raw extent with no crs) /19

**Comment by Robinlovelace** [comment]
Many of these are no longer relevant - think it would be good to cross-out the ones that are no longer needed, e.g. `raster::shapefile()` (`st_read("shape.shp")` works now).

**Comment by Nowosad** [comment]
Strikethrough any no longer relevant. And mark those we've already mentioned.

**Comment by Robinlovelace** [comment]
Thanks!

**Comment by Robinlovelace** [comment]
Bump @Nowosad we're getting through these! Just to say I think closing this before Review II is a good plan. To that end I've shifted the deadline for that back to December 31st. I think many of these are done already - happy to take this on if you're happy to do the raster tips one in #26.
