### ISSUE TITLE
error in 3.2.3 example

### ISSUE THREAD

**Issue by nbruns** [Robinlovelace/geocompr#278]
https://geocompr.robinlovelace.net/attr.html#vector-attribute-manipulation

In section 3.2.3 name discrepancies are corrected. The example corrects issues in Democratic Republic of Congo and Côte d'Ivoire. Côte d'Ivoire does not need to be corrected, at it's the same in both name vectors.  This introduces an inconsistency.

Namely, the text promises 46 rows, and the markdown now compiles to:
nrow(world_coffee_match)
45

**Comment by Nowosad** [comment]
Thanks Nick! 
@Robinlovelace can you take a look at it? This example had changed with the new version of the `world` object, which is now based on the newest version of naturalearth data.

**Comment by Robinlovelace** [comment]
Hi Nick, as @Nowosad says this was caused by a change in **spData** that broke our example. Many thanks for identifying the issue, very grateful. The previous commit should have fixed it. Please do let us know if not and if you find any further issues please do let us know.
