### ISSUE TITLE
distance computation and sf versions

### ISSUE THREAD

**Issue by nbruns** [Robinlovelace/geocompr#280]
The below snippet from section 4.2.6 will fail if you are using:
sf_0.5-5 
and not sf .6-3

with the error:
Error: In ‘udunits_from_proj[x$units]’, ‘udunits_from_proj’ and ‘x’ are not recognized by udunits.
See a table of valid unit symbols and names with valid_udunits().
Add custom user-defined units with install_symbolic_unit().

```r
library(sf)
library(raster)
library(tidyverse)
library(spData)

canterbury = nz %>% filter(Name == "Canterbury")
canterbury_height = nz_height[canterbury, ]
z_heighest = nz_height %>% top_n(n = 1, wt = elevation)
canterbury_centroid = st_centroid(canterbury)
st_distance(nz_heighest, canterbury_centroid)
```

**Comment by nbruns** [comment]
Mac users:
Compiling from source can be complicated due to the gdal dependency, and thus its easier to install an sf binary. Installing the sf .6-3 binary, however, requires 
-R >= 3.5
-which in turn requires  
 >= OS X 10.11 (El Capitan)

**Comment by Robinlovelace** [comment]
Many thanks for the input. May be useful for other+++
