### ISSUE TITLE
Create 'guestbook,

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#289]
A place where people can leave comments e.g. via a pull request containing text explaining how the book was used. On the same page could be embedded social media posts from ppl who've used the book.

**Comment by Nowosad** [comment]
https://geocompr.github.io/publicity/

**Comment by Robinlovelace** [comment]
job done it seems. maybe worth renaming it 'guestbook' but that page does the job so closing. Thanks!
