### ISSUE TITLE
Cannot do as(sp, "spatial") on Travis

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#29]
See this - not sure why this fails: https://travis-ci.org/Robinlovelace/geocompr#L2289

**Comment by Nowosad** [comment]
Don't use `as()` is probably a temporary solution. I'm trying to investigate how to make it works.

**Comment by Robinlovelace** [comment]
Agree - a temporary solution. Not worth spending much time on as it will be fixed upstream.

 It's something @edzer may have encountered in tests on **sf**. Any input welcome Edzer!

Also I wanted to ask you if plotting should fail if there are NAs in the geometry column? I suspect that is what's going on in #28, this should be reproducible:



```r
devtools::install_github("nowosad/spData")
```

```r
library(sf)
f = system.file("shapes/wrld.shp", package = "spData")
world = st_read(f)
```

```
## Reading layer `wrld' from data source ...
```

```r
world_base_subset = world[world$pop > 1e9,] # no error
nrow(world_base_subset) # 11 not right
```

```r
# plot(world_base_subset[1]) # errors with:
# Error in CPL_gdal_dimension(st_geometry(x), NA_if_empty) : 
#   not compatible with STRSXP
```

**Comment by Nowosad** [comment]
Ok, I think that I found a solution. I've changed our rendering approach from Merge and Knit to Knit and Merge (https://bookdown.org/yihui/bookdown/new-session.html). @Robinlovelace try to `make build` and let me know.

**Comment by Nowosad** [comment]
(It also fixed an error with the `units` package)

**Comment by Robinlovelace** [comment]
Great work - sounds fixed to me. Can re-open if there are any further issues. Great work!
