### ISSUE TITLE
STARS library 

### ISSUE THREAD

**Issue by rasanderson** [Robinlovelace/geocompr#299]
Are there any plans to include mention of the new STARS raster library which provides "tidy" raster data analogous to "sf"?  One challenge might be that STARS, led by Ebner Peznar, is still being developed but it looks very promising. 

https://www.r-spatial.org/r/2017/11/23/stars1.html# 

Issues can be opened on the book's contents (see 1) its code (2) or general questions (3). 

(1) If it's a problem with the book's content please link to the place in the book where you found the problem. This is section 1.2, for example:

http://geocompr.robinlovelace.net/intro.html#why-geocomputation-with-r

or edit the file directly - you can fix typos in that chapter from here, for example:

https://github.com/Robinlovelace/geocompr/edit/master/01-introduction.Rmd

(2) If it's a problem with the code please describe what you did and what you expected.
Include a minimal reproducible example (AKA a reprex) where possible. If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, check out <https://www.tidyverse.org/help/#reprex>.

---

A brief description of the problem.

```r
# insert reproducible example here
```

(3)

If you have a general question, feel free to use this form. 
However, you may get a better response from another site (e.g at <https://stackoverflow.com/>, http://gis.stackexchange.com/ or <https://community.rstudio.com/>):
it may be quicker to check and post questions there.

**Comment by Robinlovelace** [comment]
Thanks for the input, which has led to the above commit which closed this issue. We now mention **stars** in more detail and link to its repo. Please take a look and let us know if you have any further feedback.
