### ISSUE TITLE
gpkg instead of shp

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#30]
My idea is to mostly use the .gpkg format for vector examples. We could show one example with .shp at the beginning, and shortly inform that we will use .gpkg later in the book. We could also add an extended explanation why .gpkg is better in an appendix to the book. What do you think about it @Robinlovelace ?

**Comment by Robinlovelace** [comment]
Yes I agree that .gpkg is better. Happy for the 1st example to with that format, to set the agenda. Let's close this when we add a prominent gpkg e.g. or 2.

**Comment by Robinlovelace** [comment]
Fixed I say - cheers for making the switch to the geographical file format of the future! 

Note - we should say something advantages of different file formats. I'll add a place-holder ready for this content to go in (see below) - you up for saying something on shp vs gpkg? I can say something about geojson also.
