### ISSUE TITLE
suggestion for 4.2.1. spatial subsetting

### ISSUE THREAD

**Issue by LennertSchepers** [Robinlovelace/geocompr#306]
Thank you for this great book!

I was reading section 4.2.1 about spatial subsetting (https://geocompr.robinlovelace.net/spatial-operations.html#spatial-subsetting).
In this example you first create a logical vector, and then subset by using filter():
`canterbury_height3 = nz_height %>% filter(sel_logical)`

But maybe it's also an option (and quicker to read and understand) if you combine both in one line?
`canterbury_height3 = nz_height %>% filter(st_intersects(x = ., y = canterbury, sparse = FALSE))`

I also noted that at the end of this section, the link text to the vignette is 'Spatial Joins Extended' instead of  'Spatial Subsetting Extended' (the link works fine, it's only the link text).

**Comment by Robinlovelace** [comment]
Thanks for the suggestion, which I've implemented. Should update on the website soon. Any further comments/suggestions: welcome!
