### ISSUE TITLE
Minor suggestion for Ch 10: `O` variable

### ISSUE THREAD

**Issue by mdsumner** [Robinlovelace/geocompr#310]
Minor suggestion for Ch 10: 

https://geocompr.robinlovelace.net/algorithms.html#geographic-algorithms

Use `Origin` rather than `O` in the code. O is easily mistaken for 0 and will be hard to spot if mis-typed in code like

```r
x_coords <- c(10, 0, 0, 12, 20, 10)
y_coords <- c(0, 0, 10, 20, 15, 0)
poly_mat <- cbind(x_coords, y_coords)

O <- poly_mat[1, ]
T1 <- rbind(O, poly_mat[2:3, ], 0)  ## silent killer!  

```

I'm not sure `Origin` is the best choice, but it's safer than 0: 

```r
Origin <- poly_mat[1, ]
T1 <- rbind(Origin, poly_mat[2:3, ], Origin)
```

**Comment by mdsumner** [comment]
Also, suggest include the code for Figure 10.2, i.e. 

```r
lines(T1, lwd = 2)
C1 = (T1[1, ] + T1[2, ] + T1[3, ]) / 3
points(C1[1], C1[2])
```

I'm uncomfortable about C1 being created from T1[1, ] without `drop = FALSE`, it's real gotcha to then try to `points(C1)` - but putting the drop arg everywhere is not great either. If the explicit code to do the extra plotting is included, I think that's a reasonable compromise.

**Comment by Robinlovelace** [comment]
Hi @mdsumner many thanks for the input. 100% agree `O` is confusing. Not only because it's tantalizingly similar to `0` but also because it's meaning is shrouded in mystery unless you have just read the description.

Regarding the second suggestion, are you suggesting adding `drop = FALSE` to convert the matrix into a vector (will look a the relevant chunk and get back after I've fixed the `Original` message in this issue (get it ; ).

**Comment by mdsumner** [comment]
I mean drop = F to avoid turning the matrix into a vector, which I guess is what you meant? 

The problem is that while lines(T1)  will work as expected, points(C1) will not - it's one of those things that plagued me for years while learning!

**Comment by Robinlovelace** [comment]
Yes I see what you mean - the opposite of what I said (too early in the morning to be dealing with [simplifying vs preserving subsetting](http://adv-r.had.co.nz/Subsetting.html#subsetting-operators))!

Taking a read. Makes me very grateful you raised this issue (by default `[` simplifies the matrix, coercing int into a vector, right?):

> Preserving subsetting keeps the structure of the output the same as the input, and is generally better for programming because the result will always be the same type. Omitting drop = FALSE when subsetting matrices and data frames is one of the most common sources of programming errors.

**Comment by Robinlovelace** [comment]
This shows what's going on: 

```
> Origin = poly_mat[1, ] # create a point representing the origin
> T1 = rbind(Origin, poly_mat[2:3, ], Origin) # create 'triangle matrix'
> C1 = (T1[1, ] + T1[2, ] + T1[3, ]) / 3 # find centroid
> class(C1)
[1] "numeric"
> C1 = (T1[1, ,drop = F] + T1[2, , drop = F] + T1[3, ,drop = F]) / 3 # find centroid
> class(C1)
[1] "matrix"
```

One question: should we replace `C1[1]` with `C1[, 1]` also? Hypothesis: yes.
