### ISSUE TITLE
Grayed Out Section (Foundations)

### ISSUE THREAD

**Issue by rywhale** [Robinlovelace/geocompr#316]
Not sure if this qualifies as an Issue or if it's just because the book is a work in progress. 

"Foundations" is listed in the navbar but it's not clickable:
![image](https://user-images.githubusercontent.com/33959166/46294227-48e1ec80-c563-11e8-8ad5-a38dcb3811aa.png)

(Loving the book so far btw, thanks for all the work folks)

**Comment by Robinlovelace** [comment]
Hi @rywhale I think that's just how bookdown/gitbook works. Other examples with unclickable Part headings:

http://adv-r.had.co.nz/

http://r4ds.had.co.nz/

https://bookdown.org/yihui/rmarkdown/

Thanks for the input in any case. Glad you're enjoying it. If you spot anything else please let us know!
