### ISSUE TITLE
Add opacity variability to help overcome issues with thematic maps

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#32]
As pointed out by @rsbivand this is an issue: too much focus given to large areas. Nice solution is setting opacity propoportional to pop. density, as shown here: https://twitter.com/PhilPierdo/status/865953679840612353

Another solution is to apply a mask hiding everything but buildings as implemented by @oobr.

**Comment by Robinlovelace** [comment]
By @oobrien that should be - do you have a good citation for your method Oliver? Thanks for creating it!

**Comment by oobrien** [comment]
HI @Robinlovelace Yes, we detailed the technique in: 

O’Brien, O., Cheshire, J. Interactive mapping for large, open demographic data sets using familiar geographical features. Journal of Maps. doi:10.1080/17445647.2015.1060183

**Comment by Robinlovelace** [comment]
Awesome - cheers for the link.

**Comment by Robinlovelace** [comment]
Closing and adding to the list of ideas.
