### ISSUE TITLE
typo mistake?

### ISSUE THREAD

**Issue by OrlandoSabogal** [Robinlovelace/geocompr#321]
In section 11.4, the second paragraph starts: "However, geographic data is special. As we saw in Chapter 12, the ‘first law’ of geography states that points close to each other are, generally, more similar than points further away (Miller 2004)."

I think that the "As we **saw** in Chapter 12" may be should be "As we **will see** in chapter 12". 

The link leads chapter 12 and yes, it talks about the first law of geography.

**Comment by Robinlovelace** [comment]
Thanks Orlando - we moved the chapters around but forgot to update their links to other chapters. cc also @jannes-m who led this chapter. Please let us know if you find any further issues.
