### ISSUE TITLE
Spelling issues

### ISSUE THREAD

**Issue by jannes-m** [Robinlovelace/geocompr#330]
Guys, it's great to see the book nearly finished. I was just reading c2 and stumbled across a few typos and also spelling issues. Maybe we can collect here the spelling issues and then decide on how to write these words in a consistent manner throughout the book:

- [x] dataframe or data frame
- [x] geospatial, spatial or geographic (data)

**Comment by Nowosad** [comment]
I've noticed this kind of issue a few months ago and tried to fix it as much as I could. I think we should stick with `data frame`. Correct me if I am wrong, but now we only use "dataframe" just once in the book "‘Spatial dataFrame’". 
@Robinlovelace what do you think about removing/rewriting the sentence with "‘Spatial dataFrame’"?

**Comment by jannes-m** [comment]
Yes, I remember that we have talked about that, but I wasn't sure if we decided on something. Ok, perfect, then let's stick with data frame! I will read through the book in the coming days, so I would suggest to leave this issue open until I am finished.

**Comment by Robinlovelace** [comment]
I think 

- data frame
- geographic

are usually most appropriate.

I'll do a quick search for non-standard words and plan to close this issue when done. Thanks for spotting these inconsistencies @jannes-m !

**Comment by Robinlovelace** [comment]
Note in the previous commit I've replaced many instances of `spatial data` with `geographic data`. I've left `spatial databases` intact. There may be other places we can tighten the prose, think this is a step in the right direction, more changes welcome.
