### ISSUE TITLE
Remark for Chapter 12: `bristol_od` geographic resolution

### ISSUE THREAD

**Issue by loreabad6** [Robinlovelace/geocompr#332]
Really nice book, especially chapter 12, I've been using it a lot (thanks!). But, I found something that bothers me a bit. In [section 12.4](https://geocompr.robinlovelace.net/transport.html#transport-zones) when the `bristol_od` data is explained, it states:

> `bristol_od` is provided at higher geographic resolution than `bristol_zones`, as can be seen from the number of rows in each

But this is not true, right? The geographic resolution for both data sets is actually the same (MSOA level). The number of rows differ because there are several trips that happen from one same MSOA to different ones, therefore referring to unique OD pairs but not unique `geo_code`s.

**Comment by Robinlovelace** [comment]
Yes that is correct: both use MSOAs as the basis. The point I'm trying to make is that OD data is more geographically detailed because there are more possible combinations of OD pairs than zones. I agree 'resolution' is a confusing word. Would the following work better?

```
`bristol_od` is an origin-destination (OD) dataset on travel to work between zones from the UK's 2011 Census (see section \@ref(desire-lines)).
The first column is the ID of the zone of origin and the second column is the zone of destination.
`bristol_od` has more rows than `bristol_zones`, representing travel *between* zones rather than the zones themselves:
```

the original in context is:

```
`bristol_od` is an origin-destination (OD) dataset representing travel to work between zones from the UK's 2011 Census (see section \@ref(desire-lines)).
The first column is the ID of the zone of origin and the second column is the zone of destination.
`bristol_od` is provided at higher geographic resolution than `bristol_zones`, as can be seen from the number of rows in each:
```

**Comment by loreabad6** [comment]
Yes! I really think that makes it clearer! Thank you!

**Comment by Robinlovelace** [comment]
No problem, the feedback is really appreciated : )
