### ISSUE TITLE
Copyediting

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#334]
# Chapters

- [x] Chapter 1 Introduction jn

See https://github.com/Robinlovelace/geocompr/pull/338

## I Foundations

- [x] Chapter 2 Geographic data in R rl

https://github.com/Robinlovelace/geocompr/pull/336

- [x] Chapter 3 Attribute data operations jn

https://github.com/Robinlovelace/geocompr/pull/339

- [x] Chapter 4 Spatial data operations rl

https://github.com/Robinlovelace/geocompr/pull/346

- [x] Chapter 5 Geometry operations jm
Please find all commits made to implement your suggestions in PR #337. Regarding the request to put a footnote to Table 5.1, we are sorry to say that this is not easily done when trying to support an HTML and a pdf version at the same time. Therefore, we have opted to add the explanation of the acronyms into the caption of the table.

- [x] Chapter 6 Reprojecting geographic data jn

https://github.com/Robinlovelace/geocompr/pull/342

- [x] Chapter 7 Geographic data I/O jn

https://github.com/Robinlovelace/geocompr/pull/341

## Part II Extensions

- [x] Chapter 8 Making maps with R jn

https://github.com/Robinlovelace/geocompr/pull/343

- [x] Chapter 9 Bridges to GIS software jm
Please find all commits made to implement your suggestions in PR #340.
There was a problem with the header of the pdf, e.g., it said 9.2 Introduction instead of 9.1Introduction. We hope that this was due to a footnote issue but we will check on this as soon as we have compiled the pdf anew.
Please note that in the GIScience world, it is common to say "to union polygons", i.e., GIScientists have verbalized union. But you are absolutely right that union is not a verb according to the dictionary. If the verbalization is unacceptable we can use something like join or unite (imo this sounds better than unionise but I leave the final decision on this to the native speakers, of course).

- [x] Chapter 10 Scripts, algorithms and functions rl

- [x] Chapter 11 Statistical learning jm
Please find the suggested  changes in #354.
Latex puts Table 11.1 is in the middle of a bullet list, can we somehow change that?
##  Part III Applications

- [x] Chapter 12 Transportation rl

https://github.com/Robinlovelace/geocompr/pull/351

- [x] Chapter 13 Geomarketing jm
The suggested changes can be found in #355.
Page 285: In the header it says "13.4 Tidy the input data". It should state either "13.3 Tidy the input data" or "13.4 Create census rasters". Both headers can be found on page 285, the mixture "13.4 Tidy the input data" is awkward. How can we tell Latex to do so?

- [x] Chapter 14 Ecology jm
Please find all suggested changes in #357.
Figure 14.2 is put in between a table. Can we somehow prevent Latex from doing so. Furthermore, Figure 14.2 appears "rasterized", i.e., visually unappealing. The same is true for Figure 14.5. Note that this is not the case for the online versions of the figures. Is there a way to prevent the "rasterization" in the pdf?

- [x] Chapter 15 Conclusion rl

# Other

- [x] Check if Table 7.2 fits in pdf
- [x] Check if Table 7.3 fits in pdf
- [x] Check if Table 8.1 fits in pdf
- [x] Check if excersices numbers in ch8 make sense
- [ ] Check if sections are numbered correctly, e.g., in Chapter 6 or 8

## Intro sections

- [x] delete Lists of Tables and Figures from TOC and book
- [x] use a lowercase i for "Input".
- [x] "Where next", as in "Where to go next?"
- [x] delete Who this book is for
- [x] data,
- [x] Part I: ...
- [x] 1 -> I
- [x] new to R,
- [x] learning curve,
- [x] section 1.2 -> Section 1.2 (and all other instances, e.g. with `gsub('section \\', 'Section \\', x)`
- [x] 1.2,
- [x] text of the book,
- [x] read on;
- [x] & -> and

- See https://github.com/Robinlovelace/geocompr/commit/0b3e3a6da2e29cab3f418f22423790c0285d9c4b

**Comment by Nowosad** [comment]
Jannes: 5, 9, 11, 13, 14
Robin: 2, 4, 10, 12, 15
Jakub: 1, 3, 6, 7, 8
