### ISSUE TITLE
Demonstrate spatial clipping with venn diagram-like image

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#35]
E.g. from http://r4ds.had.co.nz/transform.html

![](http://r4ds.had.co.nz/diagrams/transform-logical.png)

**Comment by mdsumner** [comment]
You probably know, but just in case - the figures in the 3rd sf vignette are very helpful: http://edzer.github.io/sfr/articles/sf3.html

**Comment by Robinlovelace** [comment]
Yes, those are useful indeed. FYI this figure was actually generated using sf and I plan to expand on that to reproduce every case - I say the venn diagrams after generating the figure btw so their likeness is a coincidence:

![](http://robinlovelace.net/geocompr/figures/venn-1.png)

Code: 

https://github.com/Robinlovelace/geocompr/blame/master/01-introduction.Rmd#L15

**Comment by Robinlovelace** [comment]
Any further suggestions, very welcome - random question but what would you think about adding content on [stars](https://github.com/r-spatial/stars)?

**Comment by mdsumner** [comment]
I'll be happy to though it will be a little while until it's clear what topics would be best. I'm currently seeing how far we can push NetCDF into the tidyverse via ncdf4, some of that might be of interest.  It's really not ready but that work is here:  https://github.com/r-gris/tidync

Also I did jot these down for discussion within the stars project and that's probably where my interest would lie, these areas where GIS traditionally doesn't fit naturally. https://github.com/mdsumner/stars.use.cases/blob/master/Use-cases.rmd

**Comment by Robinlovelace** [comment]
Really useful info. Lots learn and tell in the area of geocomputation with R - priority = get the strong foundations in modular chunks so people can see how to build on them - vector clipping is a big part of that. Getting on it now.
