### ISSUE TITLE
Not compiling on Mac

### ISSUE THREAD

**Issue by neuwirthe** [Robinlovelace/geocompr#358]
I just tried knitting with 

`bookdown::render_book("index.Rmd")`

and the knitting process broke.

```

label: sfplot (with options) 
List of 5
 $ fig.cap  : chr "Plotting with sf, with multiple variables (left) and a single variable (right)."
 $ out.width: chr "49%"
 $ fig.show : chr "hold"
 $ warning  : logi FALSE
 $ fig.scap : chr "Plotting with sf."

  |................                                                 |  24%
  ordinary text without R code

  |................                                                 |  25%
label: unnamed-chunk-15 (with options) 
List of 1
 $ warning: logi FALSE

Assertion failed: (!static_cast<bool>("should never be reached")), function itemsTree, file AbstractSTRtree.cpp, line 379.
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile 02-spatial-data.Rmd
> 
```

**Comment by neuwirthe** [comment]
It seems that downloading the package `globe` solved that problem.
Now there is another one , in file `08-mapping.Rmd`.
I had to manually install package `USAboundaries`. But I still get the following error:

```
label: unnamed-chunk-41 (with options) 
List of 2
 $ fig.show: chr "hide"
 $ message : logi FALSE

Assertion failed: (0), function query, file ../../../../src/geos-3.6.1/src/index/strtree/AbstractSTRtree.cpp, line 287.
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile 08-mapping.Rmd
Calls: <Anonymous> ... render_new_session -> tryCatch -> tryCatchList -> Rscript_render
Execution halted
```

**Comment by Robinlovelace** [comment]
Hi @neuwirthe thanks for the feedback. I guess this is an issue with the versions of sf/GEOS you have installed. I suggest taking a read of this, double checking **sf** works after: https://github.com/r-spatial/sf#macos

If **sf** works, please re-try building the book and let us know if it's still now working. If not, I think it's an issue for the **sf** issue tracker.

On a related note, do you think the install instructions are sufficient for MAC users here:  https://geocompr.robinlovelace.net/spatial-class.html#prerequisites

There is still scope to update them.

**Comment by neuwirthe** [comment]
I reinstalled sf (I had it installed before) and things worked and still work with the newly compiled version. I still get the same error.
About the instructions: I had to find out that I needed to install package `globe`. Was this my fault, or do you need to install your bootstrap installer?

**Comment by Robinlovelace** [comment]
Thanks for the feedback. Seems like an issue with chapter 8. Any ideas @nowosad?

**Comment by neuwirthe** [comment]
I also rendered the whole book on Windows. No problem, it worked.

**Comment by Robinlovelace** [comment]
This suggests it's a GEOS issue:

```
Assertion failed: (0), function query, file ../../../../src/geos-3.6.1/src/index/strtree/AbstractSTRtree.cpp, line 287.
```

**Comment by neuwirthe** [comment]
I brought gems and goal up to the latest rel4eases.
There are 3 files exhibiting with essentially the same error.

Then reference to geos disappeared

```
08-mapping
label: unnamed-chunk-41 (with options) 
List of 2
 $ fig.show: chr "hide"
 $ message : logi FALSE

Assertion failed: (0), function query, file AbstractSTRtree.cpp, line 293.
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile 08-mapping.Rmd
  
13-location 
label: unnamed-chunk-15
Assertion failed: (!static_cast<bool>("should never be reached")), function itemsTree, file AbstractSTRtree.cpp, line 379.
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile 13-location.Rmd
  
15-synthesis	
label: unnamed-chunk-2
Assertion failed: (!static_cast<bool>("should never be reached")), function itemsTree, file AbstractSTRtree.cpp, line 379.
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile 15-synthesis.Rmd  
```

**Comment by neuwirthe** [comment]
It seems that the problems with `13-location` and `15-synthesis` are just consequences of `08-mapping` not working. Both try to reference `08-mapping,md` which does not exist because rendering of this file broke. 
Trying to render `08-mapping.Rmd` by itself produces another error. When running
```
knitr::include_app("https://bookdown.org/robinlovelace/coffeeapp/")
```
I get
```
Error in enc2utf8(x) : argument is not a character vector
```

**Comment by Robinlovelace** [comment]
That is likely the source of the problem. Good detective work!

**Comment by Robinlovelace** [comment]
Have you tried commenting-out that line?

**Comment by neuwirthe** [comment]
We have a blackout at the moment ☹️

Von meinem iPad gesendet

**Comment by neuwirthe** [comment]
Problems essentially solved. I had QGIS on the same machine, and QGIS brings its own gdal. 
After cleaning out older versions of gdal and setting appropriate environment variables
(having PATH in .Renviron pointing to the latest homebrew version of gdal) I could render the book.
There was one problem remaining.

In `07-read-write-plot.Rmd` from line 437 on

```
url = "https://developers.google.com/kml/documentation/KML_Samples.kml"
st_layers(url)
kml = read_sf(url, layer = "Placemarks")
```

does not work
When run by itself, it produces the following error:

```GDAL Error 1: JSON parsing error: unexpected character (at offset 0)GDAL Error 1: JSON parsing error: unexpected character (at offset 0)GDAL Error 1: JSON parsing error: unexpected character (at offset 0)GDAL Error 1: JSON parsing error: unexpected character (at offset 0
```

downloading the file and working with the local copy, however works.
With this change, I can render the book.


These changes solved my problem

```
filename = "KML_Samples.kml"
url = "https://developers.google.com/kml/documentation/KML_Samples.kml"
download.file(url,filename)
st_layers(filename)
kml = read_sf(filename, layer = "Placemarks")
```

**Comment by Robinlovelace** [comment]
Hi @neuwirthe, many thanks for raising this issue and persisting with it until, seemingly, a solution has been found. I have re-written the offending lines and closed the issue as a result. If you find any other issues with the book, or issues with reproducibility on Mac or any other platform, don't hesitate to say!
