### ISSUE TITLE
Reference issue in the second chapter

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#36]
@Robinlovelace there is a mention of three packages - sp, rgdal, and rgeos in the second chapter, however references are missing there. It looks like they are not in the geocompr package description, therefore there are no valid bib entry of them. 
The question is - should we add them to the description or we should add theirs bib entry to the ref.bib file?

**Comment by Robinlovelace** [comment]
I think add them to the description - will automate the generation of the version we're using. Well spotted.

**Comment by Nowosad** [comment]
Great!
