### ISSUE TITLE
Docker install fails with log message: ERROR: You must set a unique PASSWORD (not 'rstudio') first!

### ISSUE THREAD

**Issue by karmaal2010** [Robinlovelace/geocompr#360]
Hi,
I ran the docker instructions for mac and it builds a container but exit(1) with error message:

ERROR: You must set a unique PASSWORD (not 'rstudio') first! e.g. run with:
docker run -e PASSWORD=<YOUR_PASS> -p 8787:8787 rocker/rstudio

Full log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] add: executing... 
Nothing additional to add
[cont-init.d] add: exited 0.
[cont-init.d] userconf: executing... 

ERROR: You must set a unique PASSWORD (not 'rstudio') first! e.g. run with:
docker run -e PASSWORD=<YOUR_PASS> -p 8787:8787 rocker/rstudio

[cont-init.d] userconf: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.

**Comment by Robinlovelace** [comment]
Thanks for reporting. I noticed this - due an update in Rocker described here: https://github.com/rocker-org/rocker/wiki/Using-the-RStudio-image#running-rstudio-server

Essentially, you now have to run it with something like: 

```
docker run -d -p 8788:8787 -v $(pwd):/home/rstudio/data -e USERID=$UID PASSWORD=pickASafePassWord --name rstudio robinlovelace/geocompr
```

Will update the README accordingly. Thanks for reporting.

**Comment by Robinlovelace** [comment]
Added those changes to the readme so closing for now. Hope this helps and let us know if you have any further issues.

**Comment by karmaal2010** [comment]
It worked for me with a second   -e  

docker run -d -p 8788:8787 -v $(pwd):/home/rstudio/data -e USERID=$UID -e PASSWORD=pickASafePassWord --name rstudio robinlovelace/geocompr

Thanks so much, the book is amazing !!!
