### ISSUE TITLE
5.2.4 Rotation

### ISSUE THREAD

**Issue by vaulot** [Robinlovelace/geocompr#367]
Hi

https://geocompr.robinlovelace.net/geometric-operations.html#geo-vec

I think the rotation functiion should not be 
```rotation = function(a){
  r = a * pi / 180 #degrees to radians
  matrix(c(cos(r), sin(r), -sin(r), cos(r)), nrow = 2, ncol = 2)
}
```

But 

```rotation = function(a){
  r = a * pi / 180 #degrees to radians
  matrix(c(cos(r), -sin(r), +sin(r), cos(r)), nrow = 2, ncol = 2)
}
```

The way it is it rotates of angle -a....  In you figure the county of NZ are rotated clockwise and not counter clockwise as stated.

By the way... Thanks for a great book....

**Comment by Nowosad** [comment]
Thank you very much. You are definitely right - the presented example is clockwise rotated. https://github.com/Robinlovelace/geocompr/commit/68ddb6e094525249668726d30331b4b2c3e88c9a

**Comment by babayoshihiko** [comment]
```{r 05-geometry-operations-16}
nz_rotate = (nz_sfc - nz_centroid_sfc) * rotation(30) + nz_centroid_sfc
```

I got an error:
Error in CPL_geos_is_empty(st_geometry(x)): Evaluation error: IllegalArgumentException: Points of LinearRing do not form a closed linestring.

Some other values (e.g. rotation(3) or rotation(180)) work.

**Comment by Nowosad** [comment]
Hi @babayoshihiko -- I cannot reproduce your problem. I assume that the issue could be related to the external libraries (GEOS?), but I am not sure...

``` r
library(spData)
library(sf)
#> Linking to GEOS 3.10.2, GDAL 3.4.3, PROJ 8.2.1; sf_use_s2() is TRUE
rotation = function(a){
  r = a * pi / 180 #degrees to radians
  matrix(c(cos(r), sin(r), -sin(r), cos(r)), nrow = 2, ncol = 2)
} 
nz_sfc = st_geometry(nz)
nz_centroid_sfc = st_centroid(nz_sfc)
nz_rotate = (nz_sfc - nz_centroid_sfc) * rotation(30) + nz_centroid_sfc
plot(nz_rotate)
```

![](https://i.imgur.com/oLIk7wi.png)

<sup>Created on 2022-07-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by babayoshihiko** [comment]
@Nowosad 
I recompiled sf against GEOS 3.10.3, but I still get the same error.

> library(spData)
> library(sf)
Linking to GEOS 3.10.3, GDAL 3.2.0, PROJ 7.2.1; sf_use_s2() is TRUE
> #> Linking to GEOS 3.10.2, GDAL 3.4.3, PROJ 8.2.1; sf_use_s2() is TRUE
> rotation = function(a){
+     r = a * pi / 180 #degrees to radians
+     matrix(c(cos(r), sin(r), -sin(r), cos(r)), nrow = 2, ncol = 2)
+ } 
> nz_sfc = st_geometry(nz)
> nz_centroid_sfc = st_centroid(nz_sfc)
> nz_rotate = (nz_sfc - nz_centroid_sfc) * rotation(30) + nz_centroid_sfc
Error in CPL_geos_is_empty(st_geometry(x)) : 
  Evaluation error: IllegalArgumentException: Points of LinearRing do not form a closed linestring.
> plot(nz_rotate)
Error in plot(nz_rotate) : object 'nz_rotate' not found
>

**Comment by Nowosad** [comment]
Hi @babayoshihiko -- sadly, I do not have any good answers here. Have you tried updating GDAL as well?

**Comment by babayoshihiko** [comment]
@Nowosad, Thank you for your advice anyway.

This happens only on my old mac, and not on my new mac. The old mac has OS Sierra 10.12.6. I compiled base R 4.2.0, geos 3.10.3, GDAL 3.5.1, and CRAN's sf from source in this order to make sure they are linked to the same GEOS library. But I do not have libgeom, and macOS is too old (with older system libs).

I will investigate the issue later when I have more time.

**Comment by Nowosad** [comment]
Hi @babayoshihiko -- thank you for letting us know. Hopefully, your message will be useful for other people with the same issue.
