### ISSUE TITLE
Mapdeck example no longer seems to work

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#368]
Reproducible example, try this:

``` r
library(mapdeck)
set_token(Sys.getenv("MAPBOX"))
df = read.csv("https://git.io/geocompr-mapdeck")
ms = mapdeck_style("dark")
mapdeck(style = ms, pitch = 45, location = c(0, 52), zoom = 4) %>%
add_grid(data = df, lat = "lat", lon = "lng", cell_size = 1000,
         elevation_scale = 50, layer_id = "grid_layer",
         colour_range = viridisLite::plasma(6))
```

![](https://i.imgur.com/X2CTA4m.png)

<sup>Created on 2019-03-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Any ideas @SymbolixAU ?

**Comment by Robinlovelace** [comment]
P.s. this is what I see: 
![image](https://user-images.githubusercontent.com/1825120/55084371-fb22e880-509c-11e9-991f-6f5b32da84f3.png)

**Comment by Robinlovelace** [comment]
Guess it's an issue with zoom, centering...

**Comment by Robinlovelace** [comment]
Update: this, with slightly different data, works:

df = data.frame(
  lng = runif(1000, 0, 1),
  lat = runif(1000, 52, 53)
  )
library(mapdeck)
ms = mapdeck_style("dark")
mapdeck(style = ms, pitch = 45, location = c(0, 52), zoom = 4) %>%
add_grid(data = df, lat = "lat", lon = "lng", cell_size = 10000,
         elevation_scale = 50, layer_id = "grid_layer",
         colour_range = viridisLite::plasma(6))

**Comment by SymbolixAU** [comment]
It's `NA`s causing it to centre incorrectly. If you remove them it works as before.

```r
df <- df[!is.na(df$lng), ]

mapdeck(style = ms, pitch = 45, location = c(0, 52), zoom = 4) %>%
  add_grid(data = df, lat = "lat", lon = "lng", cell_size = 1000,
           elevation_scale = 50, layer_id = "grid_layer",
           colour_range = viridisLite::plasma(6))
```

![Screen Shot 2019-03-28 at 7 33 10 am](https://user-images.githubusercontent.com/18344164/55110374-ff4a1700-512b-11e9-8c03-3c82b210e212.png)

I've added a issue on mapdeck to [handle NA](https://github.com/SymbolixAU/mapdeck/issues/147)
