### ISSUE TITLE
Section on best practices for visualisation

### ISSUE THREAD

**Issue by cvitolo** [Robinlovelace/geocompr#37]
Hi there, your book already looks amazing!

It would be great to add a section dedicated to best practices for visualisation, e.g. use of **color-blind friendly palettes**. A package that provides some nice palettes is [viridis](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html). There are also tools to select good color schemes for maps and other graphics (e.g. [colorbrewer2](http://colorbrewer2.org)).

The use of these palettes throughout the book would also help strenghten the message.

**Comment by Robinlovelace** [comment]
That will go into chapter 10 most likely. Any ideas there welcome: https://github.com/Robinlovelace/geocompr/blob/master/11-advanced-mapping.Rmd

**Comment by Nowosad** [comment]
https://geocompr.robinlovelace.net/adv-map.html

**Comment by Robinlovelace** [comment]
@cvitolo please take a look at this new chapter if you get a chance. Cover the most important things? Any feedback welcome.
