### ISSUE TITLE
Link to guestbook on landing page

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#372]
We're interested to know how the book has been used 'in the wild'. If you have a use case of something you've done using methods/ideas in the book, we'd love to hear from you! We've also put tweets mentioning the book up on our guestbook, which we intend to keep up-to-date: https://geocompr.github.io/guestbook/

**Comment by Robinlovelace** [comment]
And link to this on the landing page.

**Comment by markusloecher** [comment]
Dear authors, 
I really like the book, thanks a lot for creating such valuable content.
I would love it even more if you could at least mention my very popular [RgoogleMaps](https://cran.r-project.org/web/packages/RgoogleMaps/index.html) package which (i) was a pioneering contribution to rendering maps in R, and (ii) eventually led the authors of the sp package to add their great support for map plots.

Thanks,
Markus

**Comment by Robinlovelace** [comment]
Hi @markusloecher thanks for the comment! Yes it was indeed pioneering, would it fit into 'The history of R-spatial' section? https://geocompr.robinlovelace.net/intro.html#the-history-of-r-spatial 

You could edit the text here, pull requests are welcome: https://github.com/Robinlovelace/geocompr/edit/main/01-introduction.Rmd

**Comment by markusloecher** [comment]
Thanks for the super fast and helpful reply.
Yes, history or R spatial section would be good or (unless my package is really outdated by now ?) in
Section \@ref(other-mapping-packages)  ?

Thx

**Comment by Robinlovelace** [comment]
Good point, and yes it seems the package is still in the ascendancy and from a quick comparison, similar popularity levels with `tmap`. I would suggest mentioning it in the history section as one of the first (right) packages for getting map visualisations anywhere on Earth (right?) and perhaps in the mapping chapter, the R’s spatial ecosystem section is more for the foundations.



``` r
dls = cranlogs::cran_downloads(package = "RgoogleMaps", from = "2009-01-01", to = Sys.Date())
plot(dls$date, dls$count)
```

![](https://i.imgur.com/4wO9BfP.png)

<sup>Created on 2021-11-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Nowosad** [comment]
Dear @markusloecher - thanks for your suggestion. I plan to work on the updates of the history section sometime this month and could add RgoogleMaps there. I would just need some justification for that (with hundreds of spatial R packages - it is impossible to mention them all).

Could you clarify your statements? 

> was a pioneering contribution to rendering maps in R

What was pioneering about this package? For example, the **maps** package allowed to display spatial data ~20 years ago...

> eventually led the authors of the sp package to add their great support for map plots.

Based on CRAN archives, **RgoogleMaps** is several years younger than **sp**. Therefore, how exactly did it impact the **sp** package?

**Comment by markusloecher** [comment]
Dear @Nowosad,
thanks for your message. I created RgoogleMaps in 2008 out of pure need, because at the time there simply was NO package which allowed to overlay R plots on Web based maps, such as google/OSM/bing/stamen maps. 
Neither **maps** nor **sp** offered this functionality at all; instead the background was always just a white canvas. Look at the standard examples (e.g. plotting the _meuse_ data ), and there simply was no easy way to have a real map background until a few years ago !
In that sense _RgoogleMaps_ was pioneering and really the only tool at the time.
While sp is much older, the authors tackled OSM/google map backgrounds MUCH later.

A few years later, **_ggmap_** came out, which is a fantastic implementation into ggplot2; but if you look at the essential coordinate transformation, they were based upon/copied from  _RgoogleMaps_.

Best
Markus

**Comment by Robinlovelace** [comment]
Continuously maintained since 2009, 7 years before `sf` was released in 2016, impressive!

Sounds like it was the first package for overlaying map data on map tiles from online mapping services https://cran.r-project.org/src/contrib/Archive/RgoogleMaps/ and if so worthy of mention.

**Comment by markusloecher** [comment]
Thx :)
And there is a JSS paper from 2015 on it as well:
https://www.jstatsoft.org/article/view/v063i04

Best
Markus

**Comment by markusloecher** [comment]
Allow me just one more follow-up comment.
Until about 2015, the only plot of the meuse data possible was this type.

![image](https://user-images.githubusercontent.com/7353291/139872112-c64c44ea-c807-4407-bb93-e1362c0d9e6e.png)

And RgoogleMaps allowed the following

![image](https://user-images.githubusercontent.com/7353291/139872330-e557ed34-3ef8-4ffd-ab44-bb96accfa2bf.png)

And the NEWS page of the sp package states:

Changes in version 1.2-0 (2015-09-01)
..
Support for Google Earth or OpenStreetMap background maps in sp::plot and spplot. Maps returned by function GetMap in package RgoogleMaps
...
are now understood by plotting functions in sp. In particular, sp::plot now has an argument bgMap, spplot now has panel functions panel.RgoogleMaps and panel.ggmap; See demo(webmap) for examples.
