### ISSUE TITLE
13-location-jm.R 

### ISSUE THREAD

**Issue by philipus** [Robinlovelace/geocompr#375]
the code has some problems with figure P_3 - labeling does not work. For the last figure I get not Berlin but Nürnberg. locality does not exist in metro_names. The Filtering for Berlin can not work like this berlin = dplyr::filter(metros_2, names == "Berlin") because names do not exist but names.city.

**Comment by jannes-m** [comment]
Yes, you are right the code has been updated in the meantime. Thanks for spotting. Should work now again. Closed via 408a3af.
