### ISSUE TITLE
Error in rcpp_scatterplot_geojson_df

### ISSUE THREAD

**Issue by liygzting** [Robinlovelace/geocompr#377]
relate to :https://symbolixau.github.io/mapdeck/articles/layers.html
I just run this example 
mapdeck( token = mykey ) %>%
add_scatterplot(
  data = capitals
  , lat = "lat"
  , lon = "lon"
  , radius = 500000
  , fill_colour = "country"
  , layer_id = "scatter_layer"
  , palette = "plasma"
)

ERROR:
Error in rcpp_scatterplot_geojson_df(data, l, geometry_column) : 
  regex_error

when I remove ", fill_colour = "country""
it's work

**Comment by Robinlovelace** [comment]
Thanks for reporting the issue @liygzting. That code was left as a legacy from tests with the package and should not have been in there. Deleted now.
