### ISSUE TITLE
Section on projections and datum

### ISSUE THREAD

**Issue by cvitolo** [Robinlovelace/geocompr#38]
People working with geospatial data rarely work in one projection, however this is a topic that is often neglected in books. 

A brief intro and explanation of how to transform existing maps using various different projections would be great. But more importantly, it would be extremely interesting to read about what can go badly wrong with projection mismatches.

**Comment by Robinlovelace** [comment]
Agree an intro to this would be good - I've just added that in Chapter 2. The book currently has an entire chapter on CRSs (06) so should fill that need, although I'm not sure that it requires an entire chapter.

I'm now thinking that Spatial Transformations or Geographic Transformations would be a better title for that chapter, so it could include sections on [affine transformations](https://cran.r-project.org/web/packages/sf/vignettes/sf3.html#affine-transformations) as well as further detail on CRSs building on the section in chapter 02. Sound good?

**Comment by cvitolo** [comment]
Sounds great!

**Comment by Robinlovelace** [comment]
This has been done I think. @cvitolo pls take a look here: http://geocompr.robinlovelace.net/spatial-class.html#crs-intro and here: http://geocompr.robinlovelace.net/transform.html#reproj-geo-data 

Seem OK to you? Any suggestions welcome.
