### ISSUE TITLE
Broken external links

### ISSUE THREAD

**Issue by prosoitos** [Robinlovelace/geocompr#399]
The link https://proj4.org/geodesic.html, in [section 6.3](https://geocompr.robinlovelace.net/reproj-geo-data.html#which-crs-to-use) seems broken.

**Comment by prosoitos** [comment]
And another one: https://proj4.org/usage/index.html at the very end of [section 6.5](https://geocompr.robinlovelace.net/reproj-geo-data.html#modifying-map-projections).

**Comment by Nowosad** [comment]
Thanks! There was a recent change in the proj website that broke the links. https://github.com/Robinlovelace/geocompr/commit/955731d111c345c203f5e34c13634d0f266043ef

**Comment by prosoitos** [comment]
My pleasure!
