### ISSUE TITLE
Additional datasets to use

### ISSUE THREAD

**Issue by cvitolo** [Robinlovelace/geocompr#40]
Finding interesting datasets to showcase algorithms can be very difficult.

One option could be to use [ECMWF](https://www.ecmwf.int/) and [Copernicus](http://www.copernicus.eu) data. If you are not familiar with them, ECMWF stands for European Centre for Medium-range Weather Forecast, it is an inter-governamental organisation and stores the largest meteorological data archive in the world (global coverage). Copernicus is a European programme that provides satellite and in-situ observations for a number of domains (e.g. biodiversity, environmental protection, climate, public health, tourism, etc.). 

There are countless uses for these datasets!

**Comment by Robinlovelace** [comment]
These sound like ideal candidates for the more advanced chapters, especially chapter 8 on rasters. Thanks for the links.

**Comment by Robinlovelace** [comment]
A big dataset on bikes from Holland: http://www.bikeprint.nl/fietstelweek/

**Comment by Robinlovelace** [comment]
Heads-up the Copernicus data is covered here: https://geocompr.robinlovelace.net/read-write.html#geographic-data-packages

Does that section cover the kind of thing you were thinking? Not mentioned ECMWF yet, can still do so if will be of benefit to lots of readers.

**Comment by Robinlovelace** [comment]
Closing for now. If anyone thinks of any more 'must include' datasets let me know but I think most of them are covered in https://geocompr.robinlovelace.net/read-write.html
