### ISSUE TITLE
Requested clarification in sections 4.3.4/4.3.5: focal vs. zonal operations

### ISSUE THREAD

**Issue by florisvdh** [Robinlovelace/geocompr#402]
More clarity is needed on the distinction between the filters in both types of operation.

Currently, the following statements are a source of confusion:

- In the paragraph on focal operations:

> The neighborhood (also named kernel, filter or moving window) under consideration is typically of size 3-by-3 cells (that is the central cell and its eight surrounding neighbors), but can take on any other (not necessarily rectangular) shape as defined by the user.

- In the paragraph on zonal operations:

> *Zonal* operations are similar to focal operations.
> The difference is that zonal filters can take on any shape instead of a predefined rectangular window.

Perhaps (as I understand it), the primary distinction is that the focal operations use a 'moving window' while the zonal operations don't: these just apply an aggregation function per subgroup of raster cells as defined by another raster. Rather than the distinction being in the form of the filter.

**Comment by jannes-m** [comment]
The distinction is that zonal operations use filters whose parts (raster cells) don't need to be neighbors, think for instance of land use categories or the example we have used in the book, soil grain sizes (sand, silt, clay; https://geocompr.robinlovelace.net/attr.html#fig:cont-raster). By comparison, the raster cells used as a focal filter have to be connected. 
If you can think of a better explanation in the book, please let us know.

**Comment by florisvdh** [comment]
@jannes-m  Your answer already provides more clarity. The current confusion arises because it is not actually explained what 'zonal filters' are. From the two cited sentences in 4.3.5 (i.e. the first two of the zonal subsection), no clear distinction can be made compared to focal operations (where 'any other shape' is also mentioned). Then the text moves to an example.

I think a second distinction that could be pointed at more explicitly is the way in which zonal and focal filters are defined: the former are defined by a second raster's values, while the latter are defined explicitly in an abstract way (matrix of weights).

**Comment by jannes-m** [comment]
Reading the two sentences instead of just the one you have cited and looking at the indicated figure, I think the difference is already made clear:

>Zonal operations are similar to focal operations. The difference is that zonal filters can take on any shape instead of a predefined rectangular window. Our grain size raster is a good example (Figure 3.2) because the different grain sizes are spread in an irregular fashion throughout the raster.
 
But if you have a better suggestion, please let us know!

**Comment by florisvdh** [comment]
I see! Well, at least the explanation wasn't clear enough to me ;-). You're definitely right that the example does shed more light on what zonal operations are about. But, I propose to make a small PR to show which wording I think would make things more clear from the beginning, is that OK to you @jannes-m ?

**Comment by jannes-m** [comment]
sure, very much welcome!

**Comment by jannes-m** [comment]
Closed via #416
