### ISSUE TITLE
Requested clarification in section 4.3: subsection structure

### ISSUE THREAD

**Issue by florisvdh** [Robinlovelace/geocompr#403]
The current sections 4.3.3 to 4.3.6 actually belong to 4.3.2. I suggest to put them one level lower (maybe you will want to use a different numbering system or none at all for that level). Further, the second paragraph of 4.3.6 (section 'Global operations and distances') generalizes on map algebra and connects with vector processing; it therefore overarches 4.3.3 to 4.3.6. I think it should be distinguished from 4.3.6, e.g. as a fifth subsection of 4.3.2: 'Map algebra compared to vector processing'.

**Comment by jannes-m** [comment]
We were not allowed to use headings below the third level. So your suggestion to make 4.3.3-4.3.6 part of 4.3.2 make sense and if I remember correctly, we did so in the beginning. Regarding 4.3.6 I am not entirely sure what you are referring to. Global operations are part of map algebra, and one typical global operation is the computation of a distance raster or in more general terms the computation of a weighting or cost raster. Of course, there is an equivalent for this in vector processing but this the case for many spatial raster operations. Don't we point that out somewhere in the book, I thought we wrote that somewhere...

**Comment by florisvdh** [comment]
> Don't we point that out somewhere in the book, I thought we wrote that somewhere...

See second paragraph under 4.3.6, that's my second point: that paragraph does not specifically belong to 4.3.6 (it is not just about global operations), but overarches 4.3.3 to 4.3.6. That paragraph goes as:

> Many map algebra operations have a counterpart in vector processing (Liu and Mason 2009). Computing a distance raster (zonal operation) while only considering a maximum distance (logical focal operation) is the equivalent to a vector buffer operation (Section 5.2.5). Reclassifying raster data (either local or zonal function depending on the input) is equivalent to dissolving vector data (Section 4.2.3). Overlaying two rasters (local operation), where one contains NULL or NA values representing a mask, is similar to vector clipping (Section 5.2.5). [... and so on]

I am still convinced that from the sections layout, no confusion should arise about the relations between 'map algebra', 'local operations', 'focal operations' and so on.

**Comment by jannes-m** [comment]
You are right the last paragraph are concluding remarks regarding map algebra operations. Therefore, it is suboptimal that the paragraph appears in the global operations section. Therefore, you propose a new very short section named "Map algebra compared to vector processing". Maybe not a bad idea, opinions @Robinlovelace & @Nowosad?

**Comment by Nowosad** [comment]
It would be one option. Another one would be to move (and slightly rewrite) this paragraph to the end of 4.3.2.

**Comment by jannes-m** [comment]
Ok, thanks for the suggestions. I think the best solution for the moment is to add an extra section header. This makes clear that we are no longer talking about global operations. Putting this stuff to the beginning of the map algebra section would be also possible, however, then we would have to explain in advance what are the different operations are.
