### ISSUE TITLE
Requested clarification in section 5.2.7: geometry casting

### ISSUE THREAD

**Issue by florisvdh** [Robinlovelace/geocompr#404]
In the first paragraph it is stated:

> Importantly, `st_cast` behaves differently on single simple feature geometry (`sfg`) objects, simple feature geometry column (`sfc`) and simple features objects.

There is an explanation (in a note and thereafter) on a difference in behaviour between sfg and sfc/sf objects regarding transformation from multi- to non-multi-objects.

However, confusion arises with table 5.1. There should be more consistency between the accompanying paragraph and the table caption:

> Table 5.1 shows possible geometry type transformations on **simple feature objects**. Each input _simple feature object with only one element_ (first column) is transformed directly into another geometry type.

> Table 5.1: Geometry casting on **simple feature geometries** (see Section 2.1) with input type by row and output type by column.

**Comment by Nowosad** [comment]
Great find. Thank you @florisvdh ! https://github.com/Robinlovelace/geocompr/commit/261f1c180997fa7bac94cc89ed18ce48eaab3563

**Comment by florisvdh** [comment]
Perfect, thanks.
