### ISSUE TITLE
Requested clarification in section 5.3.3: methods of raster::disaggregate

### ISSUE THREAD

**Issue by florisvdh** [Robinlovelace/geocompr#407]
> The `disaggregate()` function provides two methods.
> The first (nearest neighbor, `method = ""`) simply gives all output cells the value of the nearest input cell, and hence duplicates values which leads to a blocky output image.

I suggest to better explain the 'nearest neighbor' method, as it is not unequivocal here.

Actually, from `help(raster::disaggregate)` I do not see mention of 'nearest neighbor', so I doubt if it is actually correct (to me it seems misleading). Rather than searching for a 'nearest neighbor', in the case of `method = ""` "the values in the new RasterLayer are the same as in the larger original cells" (quoted from `help(raster::disaggregate)`).

Still looking further, I guess something has went wrong here. "ngb" is the alternative method in `resample()` (where "bilinear" is the default), not in `raster::disaggregate`. That makes sense, as `resample()` is used for two non-matching raster objects.

**Comment by jannes-m** [comment]
I guess you are right, my bad, will rewrite... thanks for spotting!

**Comment by jannes-m** [comment]
closed through 218bf727e1767d51bddd3045e2bc1a3d2bcd4fdc

**Comment by florisvdh** [comment]
Perfect, thank you @jannes-m
