### ISSUE TITLE
Requested clarification in section 7.4: query string

### ISSUE THREAD

**Issue by florisvdh** [Robinlovelace/geocompr#409]
> Like other web APIs, OWS APIs use a 'base URL' and a 'query string' proceding a `?` to request data.

The precise meaning of "a ‘query string’ proceding a ?" should be worded more clearly.

**Comment by Robinlovelace** [comment]
Working on it...

**Comment by Robinlovelace** [comment]
See updated text below. I also found a couple of other issues in the text of section 7.4, which I think I've fixed. Seem OK to you @florisvdh? Agree the meaning of 'query string' was not clear. Thanks for reporting.

![image](https://user-images.githubusercontent.com/1825120/59466402-29ef6600-8e25-11e9-92ba-02bb65948a91.png)

**Comment by florisvdh** [comment]
Text and example definitely improved, thank you.

You will know better than me, but is 'proceding a ?' proper English? I just can't find 'proceding' in a dictionary :-) I think you mean that the query arguments are preceded by a '?'.

**Comment by Robinlovelace** [comment]
You're right again @florisvdh, well spotted. I've changed it to the plain English word 'following'.

**Comment by florisvdh** [comment]
Nice!
