### ISSUE TITLE
Print quality, book style, etc.

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#41]
@gavinsimpson:

"Tip from a reader; if you are writing a book intended for print & use #knitr, turn off the background on code blocks; it looks shit. #rstats"
"Also, think carefully about using syntax highlighting & the scheme you use; #knitr default doesn't print well 
in BW #rstats"

Sources: 
1. https://twitter.com/ucfagls/status/867447242549886976
2. https://twitter.com/ucfagls/status/867450581589254144
3. https://twitter.com/ucfagls/status/867455372843405312

**Comment by Robinlovelace** [comment]
Figure for Chapter 11. Heads-up @Nowosad and @jannes-m pls dump print quality images here to avoid cluttering the geocompr repo.

![urban-animated-print](https://user-images.githubusercontent.com/1825120/30220855-065855ec-94b9-11e7-9cc8-53cd74f69341.png)

**Comment by Robinlovelace** [comment]
Another figure, probably not for inclusion:
![sp-dep-package-growth](https://user-images.githubusercontent.com/1825120/31147295-49dd935a-a881-11e7-86a8-0e9d5c13fb84.png)

**Comment by Robinlovelace** [comment]
Figure for chapter 8: 
![image](https://user-images.githubusercontent.com/1825120/34098369-f78e2dc4-e3d3-11e7-919e-bccad6d1625a.png)

**Comment by Robinlovelace** [comment]
Another image for the transport chapter: 
![image](https://user-images.githubusercontent.com/1825120/34133431-8514e494-e44c-11e7-93e2-819ff81ea5ca.png)

**Comment by Robinlovelace** [comment]
![09-us_pop](https://user-images.githubusercontent.com/1825120/38543030-5794b6f0-3c9b-11e8-9da9-10ec1f3ea726.gif)

**Comment by Robinlovelace** [comment]
Figure `fig:saga-twi` from GIS chapter: 
![image](https://user-images.githubusercontent.com/1825120/39205055-8e68a3ce-47f1-11e8-8874-0142d7f591e2.png)

**Comment by Robinlovelace** [comment]
Figure showing book in docker:

![image](https://user-images.githubusercontent.com/1825120/39538109-9b50e7ac-4e33-11e8-93b3-e00e95a79294.png)

**Comment by Robinlovelace** [comment]
Another docker-related screenshot:

![image](https://user-images.githubusercontent.com/1825120/39538462-d4db2928-4e34-11e8-8612-add5188ed642.png)

**Comment by Robinlovelace** [comment]
An image showing synced views with `tm_facet()` for c9:

![image](https://user-images.githubusercontent.com/1825120/39561040-ee7ac544-4e9a-11e8-9b73-3b531e9b1f1d.png)

**Comment by Robinlovelace** [comment]
Screenshot of the shiny app (when not hosted):

![image](https://user-images.githubusercontent.com/1825120/39690606-8f9400c8-51d2-11e8-84d7-f4a66a477d2a.png)

**Comment by Robinlovelace** [comment]
RStudio code check:

![image](https://user-images.githubusercontent.com/1825120/39698841-6e600584-51ee-11e8-9dd0-2c17b2836f79.png)

**Comment by Robinlovelace** [comment]
Last figure of c7 - seems to be failing due to **tmap** issues atm: 

![image](https://user-images.githubusercontent.com/1825120/39901156-a8ec9ef6-54be-11e8-94fb-0b5f6b48775e.png)

**Comment by Robinlovelace** [comment]
Breweries etc from mapview: 

![image](https://user-images.githubusercontent.com/1825120/39979271-5f515256-573d-11e8-9ede-e472ca007d73.png)

**Comment by Robinlovelace** [comment]
Chapter 1 interactive figure:

![image](https://user-images.githubusercontent.com/1825120/40053015-a5014298-5837-11e8-8876-d24ac638c48e.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/40724710-9b4307c6-6419-11e8-9667-1894d631421f.png)

coffeeApp screenshot (not needed - just in case, looks better than the lifeApp example)

**Comment by Robinlovelace** [comment]
Closing for now I think all the issues are sorted except the code block background. Will open a separate issue on that.

**Comment by Robinlovelace** [comment]
![bikeshop-berlin](https://user-images.githubusercontent.com/1825120/45922317-d7e66900-bec0-11e8-9bfe-a73ba60a2a7f.png)
