### ISSUE TITLE
Requested clarification in section 7.5: tif vs. tiff

### ISSUE THREAD

**Issue by florisvdh** [Robinlovelace/geocompr#410]
Compare the GeoTIFF line in table 7.2 (under '7.5 File formats'):

> GDAL provides access to more than 200 vector and raster data formats.
Table \\@ref(tab:formats) presents some basic information about selected and often used spatial file formats.
>
> "GeoTIFF", ".tiff", "Popular raster format similar to `.tif` format but stores raster header.", "Raster", "Open",

with (under '7.7.2 Raster data'):

> The file extension determines the output file when saving a `Raster*` object to disk.
For example, the `.tif` extension will create a GeoTIFF file:

This makes me wonder whether a distinction between `.tif` and `.tiff` actually makes sense (I presume it does not).
Anyhow, the explanation in the table does make a distinction between both extensions, and this contradicts with the implementation under 7.7.2.

If I'm correct, it would be better to just list both extensions in the table and link them to GeoTIFF.
A possible explanation could then be: _"Popular raster format, following the regular TIFF file specification but with a raster header."_
I'm not sure if my explanation is officially correct ;-). I've taken a quick look at the Wikipedia pages on [TIFF](https://en.wikipedia.org/wiki/TIFF) and [GeoTIFF](https://en.wikipedia.org/wiki/GeoTIFF).

**Comment by prosoitos** [comment]
I was wondering about any potential difference between `.tif` and `.tiff` too. A bit of googling convinced me that they are simply 2 equivalent ways of writing the same extension (like `.jpg` and `.jpeg`). But maybe it is not the case?

**Comment by Nowosad** [comment]
Yes, I think those extensions are equivalents. @jannes-m ?

**Comment by jannes-m** [comment]
as far as I know but I haven't checked

**Comment by Nowosad** [comment]
What do you think about replacing

`"GeoTIFF", ".tiff", "Popular raster format similar to .tif format but stores raster header.", "Raster", "Open"`

with 

`"GeoTIFF", ".tif/.tiff", "Popular raster format. A TIFF file containing additional spatial metadata.", "Raster", "Open"`

?
@jannes-m @florisvdh @prosoitos

**Comment by florisvdh** [comment]
@Nowosad Seems OK to me.

**Comment by Robinlovelace** [comment]
+1 Go for it @Nowosad

**Comment by Nowosad** [comment]
Awesome.
https://github.com/Robinlovelace/geocompr/commit/854ac1b24d9ccbb58d4bdd02c9cacee9c1ea506f

**Comment by prosoitos** [comment]
Much less confusing. I like the change too.
