### ISSUE TITLE
Requested clarification in section 7.7.2: raster file format

### ISSUE THREAD

**Issue by florisvdh** [Robinlovelace/geocompr#411]
> The `raster` file format (native to the `raster` package) is used when a file extension is invalid or missing. 
Some raster file formats come with additional options.
You can use them with the `options` [parameter](http://www.gdal.org/formats_list.html).

The second sentence causes some confusion with the first, i.e. '`raster` file format' vs. 'raster file format' -- especially because they appear next to each other, within the same paragraph (a little lack of attention causes the reader to think it is still about the `raster` file format).

One solution may be to split it into separate paragraphs.

**Comment by Nowosad** [comment]
Thanks!
