### ISSUE TITLE
Not sure if nz and nz_hight datasets have Name == "Canterbury" (Chapter 4)

### ISSUE THREAD

**Issue by PauGallesClara** [Robinlovelace/geocompr#417]
In chapter 4, The following code (4.2.1) doesnt't work.
       canterbury = nz %>% filter(Name == "Canterbury")
       canterbury_height = nz_height[canterbury, ]

In appereance, datsets nz and nz_heigt don't have province name (such as "Canterbury"). They just have (long, lat, group, order, region,  subregion). Am I right? Is there anything that must be done before executing the code (for exeample joining other data..)?
Thank you in advance

**Comment by Robinlovelace** [comment]
The region names are in the `Name` column, as shown below. Do you get something different? Closing for now.

``` r
names(spData::nz)
#> [1] "Name"          "Island"        "Land_area"     "Population"   
#> [5] "Median_income" "Sex_ratio"     "geom"
```

<sup>Created on 2019-06-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by PauGallesClara** [comment]
HI ! If I put your code I get what you say.
But if I execute just nz I get just (long, lat, group,  order, region,  subregion) but "Name" it doesn't appear
And if i ask class(nz) I get that is just a data.frame
Due to that when I execute the next code I get the this error message:
> canterbury = nz %>% filter(Name == "Canterbury")
Error: object 'Name' not found

Something is happening, and  I'm affraid that prolem is only mine. Can you help me?

**Comment by Nowosad** [comment]
@PauGallesClara have you tried to install the newest version of the spData package?

```r
install.packages("spData")
```

**Comment by PauGallesClara** [comment]
Thank you for your answer. I'v installed again the spData
And when I call the library(spData) I get that error message:
> library(spData)

Attaching package: ‘spData’

The following object is masked _by_ ‘.GlobalEnv’:

    nz

Maybe, somehow I have conflicts with nz?

**Comment by Nowosad** [comment]
Try it one more time in a new, clean R session.

**Comment by PauGallesClara** [comment]
I'v tried again and again, and I still have the same problem...

Just for finishing that, one more question. Wich class must have nz ? sf, sp or data.frame?
When I execute:
> names(spData::nz)
[1] "Name"          "Island"        "Land_area"     "Population"    "Median_income" "Sex_ratio"     "geom" 
 
but just nz
> nz
        long       lat group order        region subregion

Maybe there, there is the probrem on how the spData is beign installed in my pc. Because I should have the same answer in both cases, no?
Thank you for your time and patience

**Comment by Nowosad** [comment]
@PauGallesClara , please try to restart R, and then:

```r
remove(list = ls())
library(sf)
library(spData)
nz
```

What is the output here?

**Comment by PauGallesClara** [comment]
It works!!!
Now 
> class(nz)
[1] "sf"         "data.frame"

Thank you very much!!!!

**Comment by Nowosad** [comment]
:+1:
