### ISSUE TITLE
Add binder?

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#429]
Experimenting with binder here: https://github.com/geocompr/RGSWorkshop

Let's see what comes of it - give it a try if you get a chance and let me know if it works!

**Comment by Robinlovelace** [comment]
Heads-up: it works!

![image](https://user-images.githubusercontent.com/1825120/63516007-05c69a00-c4e4-11e9-803e-b0086284e916.png)

**Comment by jannes-m** [comment]
@pat-s will use it at the summer school next week

**Comment by Robinlovelace** [comment]
Worth adding a binder link to this repo? I suspect so.

**Comment by Robinlovelace** [comment]
I think that PR request will close that issue :tada: 

Can you test it here and review the PR @jannes-m and @Nowosad ?

https://github.com/Robinlovelace/geocompr/tree/binder

**Comment by Robinlovelace** [comment]
It works! 

![image](https://user-images.githubusercontent.com/1825120/63574735-61defc00-c580-11e9-973b-fce6953c7850.png)
