### ISSUE TITLE
Royal Geographical Society (RGS) reproducible map competition

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#437]
Just as with the EGU reproducible map competition #371 and the GISRUK reproducible map competition #376 we have a best map competition for the RGS Geocomputation Workshop. Deadline for submissions: 16:30 UK time. There are two categories and at least one winner will be based at the course. Entrants are welcome from anywhere across the world. 

Categories:

- most creative map making people think in new ways about geographic phenomena
- most policy relevant map - that could help save the world (or at least encourage evidence-based policy-making)

**Comment by LivJH** [comment]
[RGSMap.zip](https://github.com/Robinlovelace/geocompr/files/3599941/RGSMap.zip)

Zip file of R script and accompanying code 

Olivia Horsefield

**Comment by Robinlovelace** [comment]
Many thanks for the submission @LivJH !

**Comment by Robinlovelace** [comment]
Confirmed, the map is indeed reproducible, as verified by the output of 
```r
reprex::reprex({
  # code shown below goes here...
})
```

``` r
download.file("https://github.com/Robinlovelace/geocompr/files/3599941/RGSMap.zip", "RGSMap.zip")
unzip("RGSMap.zip")
# file.edit("RGS_mapcompetition.R")

policedata <- read.csv("2019-07-merseyside.csv", header = TRUE) # assigned the data to policedata object

outcome <- read.csv("2019-07-outcomes.csv", header = TRUE)

# merge data sets

policedata2 <- merge(policedata, outcome, by = "Crime.ID")





# mapping -----------------------------------------------------------------

library(tmap) # for creating aesthetic maps
library(tmaptools)
library(sf) #  convert a table to a spatial object
#> Linking to GEOS 3.5.1, GDAL 2.1.2, PROJ 4.9.3



# create a tibble datafame containing all of the data we would like
CrimeType <- tibble::tibble(
  crime_type = policedata2$Crime.type,
  lon = policedata2$Longitude.x,
  lat = policedata2$Latitude.x
)

# make the tibble spatial using sf() package
coords <- c("lon", "lat") # create an object with the coords in
CrimeType_sf <- st_as_sf(CrimeType, coords = coords) # turn the tibble data frame into a spatial object to make mapping easier



# or we can plot crime type using tmap
tmap_mode("view") # make the map interactive
#> tmap mode set to interactive viewing
tm_shape(CrimeType_sf) +
  tm_dots(col = "crime_type")
#> Warning: Currect projection of shape CrimeType_sf unknown. Long-lat (WGS84)
#> is assumed.
```

![](https://i.imgur.com/7dpEaAt.png)

<sup>Created on 2019-09-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by j-herring** [comment]
Hi Robin,

Here is my entry, hopefully it's reproducible

[Reproducible_Map_Contest.zip](https://github.com/Robinlovelace/geocompr/files/3610009/Reproducible_Map_Contest.zip)

**Comment by Robinlovelace** [comment]
It is reproducible :tada: 

``` r
download.file("https://github.com/Robinlovelace/geocompr/files/3610009/Reproducible_Map_Contest.zip", "map.zip")
unzip("map.zip")
# file.edit("Broadband_Map.R")

# Reproducable Map Contest

# James Herring, 13th September 2019
# Mapping of England and Wales Ofcom data on Broadband Connectivity, at MSOA level

# The map produced by this code shoes the percentage of premises in each MSOA in England and Wales without access to Superfast broadband speeds (i.e. 30Mbps and higher)
# This could help with Government broadband policy, to show which areas of the country to target for interventions


### Code Setup ####

# Load libraries
library(leaflet)
library(sf)
#> Linking to GEOS 3.5.1, GDAL 2.1.2, PROJ 4.9.3
library(tidyverse)


# Define coordinate systems
ukgrid = 27700
latlong = 4326


### Load Ofcom data ####

# Data downloaded from: https://www.ofcom.org.uk/__data/assets/file/0020/150662/fixed-output-area-data.zip
# For more information see: https://www.ofcom.org.uk/research-and-data/multi-sector-research/infrastructure-research/connected-nations-update-spring-2019

# Note, this data is at Output Area level, and will be aggregated to MSOA level below.

Ofcom_OA <- read_csv("201901_fixed_oa11_coverage_r02.csv")
#> Parsed with column specification:
#> cols(
#>   .default = col_double(),
#>   oa11 = col_character()
#> )
#> See spec(...) for full column specifications.


### Load ONS Lookup table between Output Areas and MSOAs ####

# Data downloaded from https://geoportal.statistics.gov.uk (Lookups -> Census Lookups -> Output Area Lookups)

OA_Lookup <- read_csv("Output_Area_to_Lower_Layer_Super_Output_Area_to_Middle_Layer_Super_Output_Area_to_Local_Authority_District_December_2011_Lookup_in_England_and_Wales.csv")
#> Parsed with column specification:
#> cols(
#>   OA11CD = col_character(),
#>   LSOA11CD = col_character(),
#>   LSOA11NM = col_character(),
#>   MSOA11CD = col_character(),
#>   MSOA11NM = col_character(),
#>   LAD11CD = col_character(),
#>   LAD11NM = col_character(),
#>   LAD11NMW = col_logical(),
#>   ObjectId = col_double()
#> )
#> Warning: 10036 parsing failures.
#>    row      col           expected actual                                                                                                                                                       file
#> 166001 LAD11NMW 1/0/T/F/TRUE/FALSE  Conwy 'Output_Area_to_Lower_Layer_Super_Output_Area_to_Middle_Layer_Super_Output_Area_to_Local_Authority_District_December_2011_Lookup_in_England_and_Wales.csv'
#> 166002 LAD11NMW 1/0/T/F/TRUE/FALSE  Conwy 'Output_Area_to_Lower_Layer_Super_Output_Area_to_Middle_Layer_Super_Output_Area_to_Local_Authority_District_December_2011_Lookup_in_England_and_Wales.csv'
#> 166003 LAD11NMW 1/0/T/F/TRUE/FALSE  Conwy 'Output_Area_to_Lower_Layer_Super_Output_Area_to_Middle_Layer_Super_Output_Area_to_Local_Authority_District_December_2011_Lookup_in_England_and_Wales.csv'
#> 166004 LAD11NMW 1/0/T/F/TRUE/FALSE  Conwy 'Output_Area_to_Lower_Layer_Super_Output_Area_to_Middle_Layer_Super_Output_Area_to_Local_Authority_District_December_2011_Lookup_in_England_and_Wales.csv'
#> 166005 LAD11NMW 1/0/T/F/TRUE/FALSE  Conwy 'Output_Area_to_Lower_Layer_Super_Output_Area_to_Middle_Layer_Super_Output_Area_to_Local_Authority_District_December_2011_Lookup_in_England_and_Wales.csv'
#> ...... ........ .................. ...... ..........................................................................................................................................................
#> See problems(...) for more details.


### Tidy Ofcom Data and aggregate to MSOA level ####

# Make syntatically valid names
names(Ofcom_OA) <- make.names(names(Ofcom_OA), unique = TRUE)

# Merge MSOA to Ofcom data from OA_Lookup, add Columns for Country, and flag NAs
Ofcom_OA2 <- merge(Ofcom_OA, OA_Lookup, by.x = "oa11", by.y = "OA11CD", all.x = TRUE) %>%
  mutate(Country = substr(oa11, 1, 1), NA_Flag = ifelse(!is.na(MSOA11NM), 1, 0)) 

# Look at NAs
group_by(Ofcom_OA2, Country, NA_Flag) %>%
  summarise()
#> # A tibble: 4 x 2
#> # Groups:   Country [4]
#>   Country NA_Flag
#>   <chr>     <dbl>
#> 1 E             1
#> 2 N             0
#> 3 S             0
#> 4 W             1
# No MSOA data for Northern Ireland and Scotland - ignore for this purposes, only look at England and Wales

# Select columns of interest; aggregate by MSOA; remove NAs (i.e. Scotland and Northern Ireland); and get MSOA level proportions
# Note, I aggregated several fields in order to play around with plotting different variables
Ofcom_OA3 <- select(Ofcom_OA2, oa11, All.Premises,
                    Number.of.premises.with.UFBB.availability, 
                    Number.of.premises.with.SFBB.availability, 
                    Number.of.premises.with.Full.Fibre.availability,
                    Number.of.premises.unable.to.receive.30Mbit.s,
                    MSOA11CD) %>%
  group_by(MSOA11CD) %>%
  summarise(All_Prems = sum(All.Premises),
            UFBB_Prems = sum(Number.of.premises.with.UFBB.availability),
            SFBB_Prems = sum(Number.of.premises.with.SFBB.availability),
            FF_Prems = sum(Number.of.premises.with.Full.Fibre.availability),
            Sub30_Prems = sum(Number.of.premises.unable.to.receive.30Mbit.s)) %>%
  filter(!is.na(MSOA11CD)) %>%
  mutate(UFBB_Percentage = 100*(UFBB_Prems/All_Prems),
         SFBB_Percentage = 100*(SFBB_Prems/All_Prems),
         FF_Percentage = 100*(FF_Prems/All_Prems),
         Sub30_Percentage = 100*(Sub30_Prems/All_Prems))

# Now plot this on an MSOA map of England and Wales


### Load MSOA Shapefiles, transform coordinates, and merge Ofcom data ####

MSOAs <- read_sf(dsn = "Middle_Layer_Super_Output_Areas_December_2011_Boundaries_BSC", 
                 layer = "Middle_Layer_Super_Output_Areas_December_2011_Boundaries_BSC")

# Transform projection system from Eastings/Northings to Lat/Long (in order to plot using leaflet)
st_set_crs(MSOAs, ukgrid)
#> Warning: st_crs<- : replacing crs does not reproject data; use st_transform
#> for that
#> Simple feature collection with 7201 features and 6 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: 82678 ymin: 5343 xmax: 655604.7 ymax: 657534.1
#> epsg (SRID):    27700
#> proj4string:    +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84=446.448,-125.157,542.06,0.15,0.247,0.842,-20.489 +units=m +no_defs
#> # A tibble: 7,201 x 7
#>    objectid msoa11cd msoa11nm msoa11nmw st_areasha st_lengths
#>       <dbl> <chr>    <chr>    <chr>          <dbl>      <dbl>
#>  1        1 E020000… City of… City of …   2983633.      8018.
#>  2        2 E020000… Barking… Barking …   2091907.      7086.
#>  3        3 E020000… Barking… Barking …   2122216.      7405.
#>  4        4 E020000… Barking… Barking …   2569470.      7149.
#>  5        5 E020000… Barking… Barking …   1111109.      5491.
#>  6        6 E020000… Barking… Barking …   1727225.      5707.
#>  7        7 E020000… Barking… Barking …   1506212.      6457.
#>  8        8 E020000… Barking… Barking …    994429.      4941.
#>  9        9 E020000… Barking… Barking …   1128519.      6473.
#> 10       10 E020000… Barking… Barking …   1565999.      6647.
#> # … with 7,191 more rows, and 1 more variable: geometry <MULTIPOLYGON [m]>

MSOAs <- st_transform(MSOAs, latlong)

# Merge on Ofcom data
MSOAs <- merge(MSOAs, Ofcom_OA3, by.x = "msoa11cd", by.y = "MSOA11CD", all.x = TRUE)


### Plot on leaflet map ####

# Define colour palette for MSOA shapes
pal_Sub30 <- colorNumeric(palette = c("#ffffcc", "#fd8d3c", "#bd0026"), domain = MSOAs$Sub30_Percentage)

# Define HTML hover over labels
labels <- sprintf(
  "<strong>%s</strong><br/>%g%% of premises have sub-Superfast speeds (< 30Mbps) <br/>%g premises out of %g total premises",
  MSOAs$msoa11nm, round(MSOAs$Sub30_Percentage,2), MSOAs$Sub30_Prems, MSOAs$All_Prems
) %>% lapply(htmltools::HTML)

# Leaflet code
Ofcom_map <- leaflet() %>%
  addTiles() %>%
  addPolygons(data = MSOAs,
              opacity = 1,
              weight = 0.01, # If stroke width is given weight of 0, mouseover highlight persists
              fillOpacity = 1,
              fillColor = ~pal_Sub30(MSOAs$Sub30_Percentage),
              highlight = highlightOptions(
                weight = 5,
                color = "#666",
                fillOpacity = 0.9,
                bringToFront = TRUE),
              label = labels,
              group = "Sub30") %>%
  addLegend(pal = pal_Sub30, values = MSOAs$Sub30_Percentage, title = "% of premises with <30Mbps", position = "topright",
            labFormat = labelFormat(suffix = "%"))

# Launch map
Ofcom_map
```

![](https://i.imgur.com/67KN575.png)

<sup>Created on 2019-09-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by SimonCoulombe** [comment]
This map shows where traffic originates (on the south shore) and where it arrives (on the north shore).  It aims to demonstrate that a proposed 4 billion $ tunnel on the eastern part of the city (touching the western tip of the island) is futile: 

library(tidyverse)
library(sf)
library(mapview)
library(readxl)
library(janitor)
library(tmap)

download.file(
  url = "https://www.transports.gouv.qc.ca/fr/ministere/Planification-transports/enquetes-origine-destination/quebec/2017/Documents/EnqOD_QUE2017_Matrices_SM.XLSX",
  destfile = here::here("EnqOD_QUE2017_Matrices_SM.XLSX")
)
download.file(
  url = "http://www12.statcan.gc.ca/census-recensement/2011/geo/bound-limit/files-fichiers/2016/lsdr000b16a_f.zip",
  destfile = here::here( "lsdr000b16a_f.zip")
)

download.file(
  url = "http://www12.statcan.gc.ca/census-recensement/2011/geo/bound-limit/files-fichiers/2016/lsr_000b16a_f.zip",
  destfile = here::here("lsr_000b16a_f.zip")
)

utils::unzip(
  here::here("lsdr000b16a_f.zip"),
  exdir= here::here()
)

utils::unzip(
  here::here("lsr_000b16a_f.zip"),
  exdir= here::here()
)


correspondance_sm_sr  <-
  tibble::tribble(
    ~SM,       ~SRIDU,
    10, "4210015.00",
    10, "4210016.00",
    10, "4210017.00",
    10, "4210018.00",
    10, "4210019.00",
    10, "4210014.00",
    21, "4210003.00",
    21, "4210005.00",
    21, "4210006.00",
    22, "4210001.01",
    22, "4210001.02",
    30, "4210022.00",
    30, "4210023.00",
    30, "4210024.00",
    30, "4210021.00",
    30, "4210025.00",
    30, "4210004.00",
    40, "4210020.00",
    40, "4210002.00",
    40, "4210007.00",
    40, "4210008.00",
    40, "4210009.00",
    40, "4210010.00",
    40, "4210011.00",
    40, "4210012.00",
    40, "4210013.00",
    50, "4210029.00",
    50, "4210030.00",
    50, "4210031.00",
    50, "4210035.00",
    50, "4210036.00",
    60, "4210034.00",
    60, "4210033.01",
    60, "4210033.02",
    70, "4210026.00",
    70, "4210027.00",
    70, "4210028.00",
    70, "4210037.00",
    70, "4210038.01",
    70, "4210038.02",
    81, "4210101.00",
    81, "4210102.00",
    81, "4210103.00",
    81, "4210100.00",
    91, "4210116.00",
    100, "4210115.00",
    100, "4210117.02",
    100, "4210117.01",
    110, "4210110.00",
    110, "4210111.00",
    120, "4210112.01",
    120, "4210112.02",
    120, "4210113.01",
    120, "4210113.02",
    130, "4210118.00",
    130, "4210114.00",
    140, "4210120.01",
    140, "4210120.02",
    140, "4210120.03",
    150, "4210220.01",
    150, "4210220.02",
    160, "4210280.02",
    160, "4210280.01",
    160, "4210280.03",
    170, "4210290.04",
    170, "4210290.03",
    170, "4210290.01",
    180, "4210272.00",
    180, "4210271.01",
    180, "4210271.02",
    190, "4210273.01",
    190, "4210273.02",
    190, "4210273.04",
    190, "4210273.03",
    200, "4210270.01",
    200, "4210270.03",
    200, "4210270.04",
    210, "4210300.00",
    210, "4210311.01",
    210, "4210311.02",
    221, "4210310.00",
    221, "4210320.02",
    221, "4210320.01",
    221, "4210320.04",
    230, "4210320.03",
    230, "4210340.03",
    230, "4210320.07",
    230, "4210320.08",
    240, "4210340.01",
    240, "4210340.02",
    250, "4210330.00",
    260, "4210320.05",
    260, "4210360.02",
    270, "4210360.01",
    290, "4210119.02",
    290, "4210119.04",
    290, "4210119.03",
    300, "4210140.01",
    300, "4210140.02",
    300, "4210140.03",
    310, "4210032.00",
    310, "4210260.01",
    310, "4210260.02",
    310, "4210260.03",
    320, "4210040.01",
    320, "4210040.04",
    320, "4210040.03",
    330, "4210039.01",
    330, "4210039.02",
    340, "4210041.02",
    340, "4210041.05",
    340, "4210041.07",
    350, "4210240.02",
    350, "4210240.01",
    360, "4210160.01",
    360, "4210041.04",
    360, "4210041.06",
    360, "4210041.08",
    360, "4210041.09",
    370, "4210041.03",
    370, "4210160.03",
    370, "4210160.04",
    370, "4210160.05",
    380, "4210230.01",
    380, "4210230.02",
    390, "4210210.01",
    390, "4210210.02",
    400, "4210170.03",
    400, "4210170.04",
    400, "4210170.05",
    410, "4210170.07",
    410, "4210170.06",
    430, "4210801.00",
    430, "4210802.00",
    430, "4210800.01",
    430, "4210800.02",
    440, "4210810.00",
    440, "4210811.00",
    440, "4210812.00",
    460, "4210820.03",
    460, "4210820.04",
    460, "4210820.01",
    470, "4210825.00",
    480, "4210830.01",
    480, "4210830.02",
    490, "4210835.07",
    490, "4210835.06",
    490, "4210835.03",
    490, "4210835.04",
    490, "4210835.05",
    500, "4210840.02",
    500, "4210840.01",
    520, "4210850.05",
    520, "4210850.04",
    520, "4210850.03",
    520, "4210846.02",
    520, "4210850.02",
    520, "4210846.03",
    530, "4210846.04",
    540, "4210845.06",
    540, "4210845.03",
    540, "4210845.04"
  )
correspondance_sm_sdr <- 
  tibble::tribble(
    ~SDRIDU, ~SM,
    "2433090", 670,
    "2434017", 660,
    "2419110", 680,
    "2419068", 560,
    "2419117", 680,
    "2419097", 571,
    "2419105", 571,
    "2421020", 650,
    "2420020", 450,
    "2421005", 650,
    "2421045", 280,
    "2422020", 590,
    "2422045", 620,
    "2421025", 640,
    "2421030", 640,
    "2420025", 450,
    "2420005", 450,
    "2421035", 630,
    "2421040", 630,
    "2420015", 450,
    "2420030", 450,
    "2422025", 590,
    "2422030", 600,
    "2421010", 650,
    "2421015", 650,
    "2422005", 581,
    "2422010", 581,
    "2422015", 581,
    "2422035", 600,
    "2422040", 610,
    "2426070", 550,
    "2423057", 300,
    "2423072", 420,
    "2433095", 670,
    "2434007", 660,
    "2434025", 660,
    "2434120", 581,
    "2420010", 450
  )
sm_names <- 
  
  tibble::tribble(
    ~SM,                                                                                            ~nom, ~rivenord, ~est,
    10,                                                                               "Haute-Ville Est",         1,    1,
    21,                                                                  "Haute-Ville Ouest (Montcalm)",         1,    1,
    22,                                                           "Haute-Ville Ouest (Saint-Sacrement)",         1,    1,
    30,                                                                               "Basse-Ville Est",         1,    1,
    40,                                                                             "Basse-Ville Ouest",         1,    1,
    50,                                                                                "Vieux-Limoilou",         1,    1,
    60,                                                                                        "Lairet",         1,    1,
    70,                                                                                     "Maizerets",         1,    1,
    81,                                                                                       "Sillery",         1,    0,
    91,                                                                            "Cité Universitaire",         1,    0,
    100,                                                                        "Sainte-Foy Centre-Nord",         1,    0,
    110,                                                                         "Sainte-Foy Centre-Sud",         1,    0,
    120,                                                                          "Pointe-de-Sainte-Foy",         1,    0,
    130,                                                                              "Quatre-Bourgeois",         1,    0,
    140,                                                                                     "Cap-Rouge",         1,    0,
    150,                                                                    "Notre-Dame-des-Laurentides",         1,    1,
    160,                                                                                   "Orsainville",         1,    1,
    170,                                                                              "Charlesbourg-Est",         1,    1,
    180,                                                                    "Charlesbourg (Trait-Carré)",         1,    1,
    190,                                                                            "Henri-Bourassa Est",         1,    1,
    200,                                                                              "Charlesbourg Sud",         1,    1,
    210,                                                                                       "Giffard",         1,    1,
    221,                                                           "Monseigneur-Gauthier,Vieux-Beauport",         1,    1,
    230,                                                                              "Seigneuriale Sud",         1,    1,
    240,                                                                                     "Courville",         1,    1,
    250,                                                                                   "Montmorency",         1,    1,
    260,                                                               "Sainte-Thérèse-de-Lisieux Ouest",         1,    1,
    270,                                                                 "Sainte-Thérèse-de-Lisieux Est",         1,    1,
    280,                                                                                    "Boischatel",         1,    1,
    290,                                                                "Quartier Laurentien, Champigny",         1,    0,
    300,                                                                            "L'Ancienne-Lorette",         1,    0,
    310,                                                                                        "Vanier",         1,    1,
    320,                                                                                      "Duberger",         1,    0,
    330,                                                                                    "Les Saules",         1,    0,
    340,                                                                                "Neufchâtel Est",         1,    0,
    350,                                                                                   "Lebourgneuf",         1,    1,
    360,                                                                              "Neufchâtel Ouest",         1,    0,
    370,                                                        "Loretteville, Neufchâtel Nord, Wendaké",         1,    0,
    380,                                                                                   "Saint-Émile",         1,    1,
    390,                                                                             "Lac-Saint-Charles",         1,    0,
    400,                                                                           "Val-Bélair (Bélair)",         1,    0,
    410,                                                                 "Val-Bélair (Val-Saint-Michel)",         1,    0,
    420,                                                                   "Saint-Augustin-de-Desmaures",         1,    0,
    430,                                                                                        "Lauzon",         0,    1,
    440,                                                                                  "Lévis Centre",         0,    1,
    450,                                                                               "L'Île-d'Orléans",         1,    1,
    460,                                                                             "Saint-Romuald Est",         0,    1,
    470,                                                  "Pintendre, Saint-Joseph-de-la-Pointe-de-Lévy",         0,    1,
    480,                                                                           "Saint-Romuald Ouest",         0,    0,
    490,                                                                        "Saint-Jean-Chrysostome",         0,    0,
    500,                                                                                        "Charny",         0,    0,
    510,                                                                 "Sainte-Hélène-de-Breakeyville",         0,    0,
    520,                                                                                 "Saint-Nicolas",         0,    0,
    530,                                                                              "Saint-Rédempteur",         0,    0,
    540,                                                                       "Saint-Étienne-de-Lauzon",         0,    0,
    550,                                                                       "Saint-Lambert-de-Lauzon",         0,    0,
    560,                                                                                   "Saint-Henri",         0,    1,
    571,                                                        "Beaumont, Saint-Charles-de-Bellechasse",         0,    1,
    581, "Lac-Saint-Joseph, Fossambault-sur-le-Lac, Sainte-Catherine-de-la-Jacques-Cartier, Lac Sergent",         1,    0,
    590,                                                          "Saint-Gabriel-de-Valcartier, Shannon",         1,    0,
    600,                                                             "Stoneham-et-Tewksbury, Lac-Delage",         1,    1,
    610,                                                                                  "Lac-Beauport",         1,    1,
    620,                                                                      "Sainte-Brigitte-de-Laval",         1,    1,
    630,                                                                "L'Ange-Gardien, Château-Richer",         1,    1,
    640,                                                               "Sainte-Anne-de-Beaupré, Beaupré",         1,    1,
    650,                                  "Saint-Joachim, Saint-Ferréol-les-Neiges, Saint-Tite-des-Caps",         1,    1,
    660,                                                               "Donnacona, Neuville, Pont-Rouge",         1,    0,
    670,                                                     "Saint-Antoine-de-Tilly, Saint-Apollinaire",         0,    0,
    680,                                                    "Saint-Michel-de-Bellechasse, Saint-Vallier",         0,    1,
    999,                                                                               "Hors territoire",         1,    1
  )


shp_sdr <- read_sf(here::here("lsdr000b16a_f.shp"))  %>%
  inner_join(correspondance_sm_sdr) 
shp_sr <- read_sf(here::here("lsr_000b16a_f.shp")) %>%
  inner_join(correspondance_sm_sr) 


shp_sm <- rbind(shp_sdr %>% select(SM), 
                shp_sr %>% select(SM)) %>%
  group_by(SM) %>%
  summarise() %>%  # group_by et summarise pour créer 1 seul polygones à partir des n SR de chaque secteur municipal
  left_join(sm_names) 





trajets_auto_am <- read_excel(here::here( "EnqOD_QUE2017_Matrices_SM.XLSX"),
                              sheet= "SAXAU17T", skip =12, na= "." )  %>% 
  clean_names %>%
  filter(secteurs_municipaux != "TOTAL") %>%
  rename(origine = x2) %>% 
  select(-total, - secteurs_municipaux) %>%
  gather(key= destination, value= trajets, starts_with("x")) %>%
  mutate(destination = as.numeric(str_sub(destination, 2)),
         trajets = ifelse(is.na(trajets),0, as.numeric(trajets))) %>%
  mutate(origine = ifelse(origine== 510, 490, origine), # début breakyville dans st jean chrysostome
         destination= ifelse(destination == 510, 490, destination))  %>%
  group_by(origine,destination ) %>% 
  summarise(trajets = sum(trajets)) %>%# fin breakyville dans st jean chrysostome
  ungroup() %>%
  left_join(sm_names %>% select(origine= SM, origine_nom = nom, origine_est = est, rivenord_origine = rivenord)) %>%
  left_join(sm_names %>% select(destination= SM, destination_nom = nom, destination_est = est, rivenord_destination = rivenord))%>%
  filter(destination != 999 & origine != 999)


origine_am <- 
  trajets_auto_am %>% 
  group_by(origine) %>%
  summarise(origine_am = sum(trajets)) %>%
  rename(SM = origine)
destination_am <- 
  trajets_auto_am %>% 
  group_by(destination) %>%
  summarise(destination_am = sum(trajets)) %>%
  rename(SM = destination)
origine_am_traverse_fleuve <- 
  trajets_auto_am %>% 
  filter(rivenord_origine !=  rivenord_destination) %>%
  group_by(origine) %>%
  summarise(origine_am_traverse_fleuve = sum(trajets)) %>%
  rename(SM = origine)
destination_am_traverse_fleuve <- 
  trajets_auto_am %>% 
  filter(rivenord_origine !=  rivenord_destination) %>%
  group_by(destination) %>%
  summarise(destination_am_traverse_fleuve = sum(trajets)) %>%
  rename(SM = destination)
final_data <- shp_sm %>% 
  left_join(origine_am)%>%
  left_join(destination_am) %>%
  left_join(origine_am_traverse_fleuve) %>%
  left_join(destination_am_traverse_fleuve) %>%
  mutate(pct_destination_traverse_fleuve = destination_am_traverse_fleuve / destination_am)


final_data %>% 
  mutate(
    rivesud_to_rivenord = ifelse(rivenord==1, destination_am_traverse_fleuve, -origine_am_traverse_fleuve)
  ) %>%
  mapview(zcol= "rivesud_to_rivenord")

**Comment by Robinlovelace** [comment]
Update: the winners have been announced here https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1909&L=QUANT-GEOG&O=D&P=6787

Congratulations to @j-herring and @LivJH 🎉
