### ISSUE TITLE
to generate an object to be plotted as an animated map

### ISSUE THREAD

**Issue by nreguera** [Robinlovelace/geocompr#441]
Hi,

I am trying to reproduce the sample shown in the figure 8.17 of [this link](https://geocompr.robinlovelace.net/adv-map.html#animated-maps)  to generate an animated map, but I am having difficulties to create the object from which the map would be plotted. 

As far as I have learnt, the map is generated from a dataframe that contains a geographical variable on it. In my case, I have a dataframe with the [data](https://raw.githubusercontent.com/nreguera/geocompr/master/data.csv) that I want to plot (province, district, period, and radiance) and the spatial [object](https://raw.githubusercontent.com/nreguera/geocompr/master/map.csv) (in the link you can only see the dataframe of the spatial object, that I downloaded from [gadm](https://gadm.org/)), but I am struggling to merge both objects (dataframe+spatial object) to use them in the same way as in the example.

This is the code I am using to merge but it doesn´t work at all:

`mymap <- sp::merge(df, map,
            by.y = c("province","district"),
            by.x = c("map@data$NAME_1","map@data$NAME_2"))`

Any guidance would be appreciate.

Thanks.

Natxo.

**Comment by Robinlovelace** [comment]
Hi @nreguera, can you share a reproducible example? The following code works for me:

``` r
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.4.0, PROJ 5.2.0
library(tidyverse)
library(spData)
library(tmap)
#> Warning in fun(libname, pkgname): rgeos: versions of GEOS runtime 3.7.1-CAPI-1.11.1
#> and GEOS at installation 3.7.0-CAPI-1.11.0differ
m_save = world %>% filter(continent != "Antarctica") %>% 
  tm_shape() + 
  tm_polygons() +
  tm_shape(urban_agglomerations) +
  tm_dots(size = "population_millions", title.size = "Population (m)", alpha = 0.5, col = "red") +
  tm_facets(along = "year", free.coords = FALSE)
tmap::tmap_animation(tm = m_save, filename = "/tmp/urban-animated.gif", width = 1200, height = 800)
#> Animation saved to /tmp/urban-animated.gif
magick::image_read("/tmp/urban-animated.gif")
```

![](https://i.imgur.com/hdUOlnm.gif)

<sup>Created on 2019-09-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Please try to run the preceding lines of code and let us know how you get on. Suerte!

**Comment by nreguera** [comment]
Hola!

Your example works for me, but I am trying to reproduce it with another data (btw is the area animation, figure 8.17, not the dots animation).

Attached a reproducible sample: [Animate.zip](https://github.com/Robinlovelace/geocompr/files/3569333/Animate.zip).

Thanks.

**Comment by Robinlovelace** [comment]
``` r
download.file("https://github.com/Robinlovelace/geocompr/files/3569333/Animate.zip", "Animate.zip")
unzip("Animate.zip")
# file.edit("Problem-Animation.Rmd")
library(sf)
#> Linking to GEOS 3.5.1, GDAL 2.1.2, PROJ 4.9.3
library(tidyverse)
library(spData)
library(tmap)

country_map = readRDS("gadm36_KHM_0_sp.rds")
districts_map = readRDS("gadm36_KHM_2_sp.rds")

class(country_map)
#> [1] "SpatialPolygonsDataFrame"
#> attr(,"package")
#> [1] "sp"
class(districts_map)
#> [1] "SpatialPolygonsDataFrame"
#> attr(,"package")
#> [1] "sp"

cm = st_as_sf(country_map)
dm = st_as_sf(districts_map) %>%
  rmapshaper::ms_simplify() %>% 
  rename(district = NAME_2)
#> Registered S3 method overwritten by 'crul':
#>   method                 from
#>   as.character.form_file httr
#> Registered S3 method overwritten by 'geojsonlint':
#>   method         from 
#>   print.location dplyr

data = read.csv(file="data.csv", header=TRUE, sep=",")
data$X = NULL

plot(dm)
#> Warning: plotting the first 9 out of 13 attributes; use max.plot = 13 to
#> plot all
```

![](https://i.imgur.com/Rcs7oul.png)

``` r

nrow(data)
#> [1] 14240
head(data)
#>       province     district       date radiance
#> 1 BatdÃ¢mbÃ¢ng    Aek Phnum 2012-04-01   633.54
#> 2   Rôtânôkiri Andoung Meas 2012-04-01   677.49
#> 3       Kândal   Angk Snuol 2012-04-01   913.92
#> 4        Takêv Angkor Borei 2012-04-01    19.83
#> 5       Kâmpôt  Angkor Chey 2012-04-01    42.11
#> 6     Siemréab  Angkor Chum 2012-04-01   280.09
head(dm)
#> Simple feature collection with 6 features and 13 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: 102.3363 ymin: 13.35823 xmax: 103.4459 ymax: 14.02342
#> epsg (SRID):    4326
#> proj4string:    +proj=longlat +datum=WGS84 +no_defs
#>   GID_0   NAME_0   GID_1           NAME_1 NL_NAME_1     GID_2
#> 1   KHM Cambodia KHM.1_1 Bântéay Méanchey      <NA> KHM.1.1_1
#> 2   KHM Cambodia KHM.1_1 Bântéay Méanchey      <NA> KHM.1.2_1
#> 3   KHM Cambodia KHM.1_1 Bântéay Méanchey      <NA> KHM.1.3_1
#> 4   KHM Cambodia KHM.1_1 Bântéay Méanchey      <NA> KHM.1.4_1
#> 5   KHM Cambodia KHM.1_1 Bântéay Méanchey      <NA> KHM.1.5_1
#> 6   KHM Cambodia KHM.1_1 Bântéay Méanchey      <NA> KHM.1.6_1
#>           district VARNAME_2 NL_NAME_2 TYPE_2 ENGTYPE_2 CC_2   HASC_2
#> 1            Malai      <NA>      <NA>   Srok  District <NA> KH.OM.ML
#> 2    Mongkol Borei      <NA>      <NA>   Srok  District <NA> KH.OM.MB
#> 3         Ou Chrov      <NA>      <NA>   Srok  District <NA> KH.OM.OC
#> 4       Phnum Srok      <NA>      <NA>   Srok  District <NA> KH.OM.PS
#> 5 Preah Netr Preah      <NA>      <NA>   Srok  District <NA> KH.OM.PN
#> 6   Serei Saophoan      <NA>      <NA>   Srok  District <NA> KH.OM.SS
#>                         geometry
#> 1 MULTIPOLYGON (((102.819 13....
#> 2 MULTIPOLYGON (((102.8192 13...
#> 3 MULTIPOLYGON (((102.819 13....
#> 4 MULTIPOLYGON (((103.4416 13...
#> 5 MULTIPOLYGON (((103.4181 13...
#> 6 MULTIPOLYGON (((102.8857 13...

# clean data
d = data %>% 
  mutate(year = lubridate::year(date)) %>% 
  group_by(year, district) %>% 
  summarise(radiance = mean(radiance, na.rm = T)) %>% 
  spread(key = year, value = radiance, sep = "_") 

nrow(d)
#> [1] 176
summary(dm$district %in% d$district)
#>    Mode    TRUE 
#> logical     178

# how to attach the radiance to the map?
dm_joined = inner_join(dm, d)
#> Joining, by = "district"
#> Warning: Column `district` joining character vector and factor, coercing
#> into character vector
dm_joined %>% 
  select(matches("year")) %>% 
  plot()
```

![](https://i.imgur.com/ziH61EZ.png)

``` r

# plot with tmap
dm_joined %>% 
  tm_shape() + 
  tm_polygons(col = names(dm_joined)[grepl(pattern = "year", x = names(dm_joined))], title = "Radiance") +
  tm_layout(legend.outside = TRUE)
```

![](https://i.imgur.com/ZCfBn98.png)

<sup>Created on 2019-09-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
Update: adding a few changes to the above allows you to animate it with `tmap_animation()`:

```
m = dm_joined %>% 
  tm_shape() + 
  tm_polygons(col = year_names) +
  tm_facets(nrow = 1, ncol = 1, free.scales = FALSE) +
  tm_layout(legend.position = c("right", "bottom"))

m

tmap_animation(m, filename = "out.gif")
```

Resulting in the output below.
![out](https://user-images.githubusercontent.com/1825120/64237559-7a420580-cef4-11e9-816f-8ab7f3b5395b.gif)

Let me know how you get on, thanks for the interesting question, hope this helps.

**Comment by nreguera** [comment]
Wow @Robinlovelace  that looks very interesting. It´s very close to I was looking for, but I have some questions:

- Why you convert the map object into sf?
- I can´t reproduce your code because in this line:

`mutate(year = lubridate::year(date))`

Gives me this error:

> Error in UseMethod("mutate_") : no applicable method for 'mutate_' applied to an object of class "function"

- This code is in fact in the middle of a cleaning and transformation stage, and the dataset I sent you is in some point of this process. So what I am looking for is to represent the info not ony by year but my month and year. The "date" field contains the day but only because I was using this format for another visualization. Is there a way to do this?

Thanks!

**Comment by Robinlovelace** [comment]
> Why you convert the map object into sf?

Because sf datasets have many advantages. See here: https://geocompr.robinlovelace.net/spatial-class.html#why-simple-features

**Comment by Robinlovelace** [comment]
> I can´t reproduce your code because in this line:

Try updating your versions of R and your packages with `update.packages()`. Then it should work. 

>  The "date" field contains the day but only because I was using this format for another visualization. Is there a way to do this?

You would modify this line in the above code to group by month:

```
  group_by(year, district) %>% 
```

> Thanks!

No worries, glad to be of assistance. Also note, this issue tracker is not really for asking general questions but is about the book. In future, please post such questions to forums such as:


- http://r-sig-geo.2731867.n2.nabble.com/
- https://gis.stackexchange.com/
- https://community.rstudio.com/

**Comment by nreguera** [comment]
Thank you so much and sorry for using this thread for out of topic questions. Indeed I am reading your book and trying to apply it to my thesis. I read the part of simple features, but I guess I need to re-read it again.

Congrats for the book.

Natxo.

**Comment by Robinlovelace** [comment]
No problem @nreguera, and further comments/questions you have on the book, feel free to open an issue. In fact this issue has been useful so thanks for asking!
