### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#450]
This is worth doing for multiple reasons. Any suggestions @Nowosad / @jannes-m on what a good template would be?

**Comment by Nowosad** [comment]
How about https://github.com/hadley/adv-r/blob/master/CODE_OF_CONDUCT.md ?

**Comment by Nowosad** [comment]
https://github.com/Robinlovelace/geocompr/commit/91522f015fe5729ca5a10d31c4ba780a2b41d434

**Comment by Robinlovelace** [comment]
Thanks @Nowosad, fast work!
