### ISSUE TITLE
Link to netlify not showing

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#453]
I added this to `index.Rmd`:

https://github.com/Robinlovelace/geocompr/blob/3aba4faf178ee0fca60ac7c5dcc28838b1ea51e3/index.Rmd#L252-L255

However, it's still not showing here https://geocompr.robinlovelace.net/ and I'm not sure why. Any ideas @Nowosad or anyone?

Linked to #450

**Comment by Nowosad** [comment]
You added it to a wrong place. It should be good now - https://github.com/Robinlovelace/geocompr/commit/6e54e399c7ff0f62757d625aac55bfbf6f4493a6.

**Comment by Nowosad** [comment]
@Robinlovelace Please check after the book is built and close the issue.

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/68870259-80bddc00-06f2-11ea-94da-a85cd1016883.png)

Looks great to me. Many thanks Jakub!
