### ISSUE TITLE
Load times

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#457]
Load times on some pages are slooow. 

![image](https://user-images.githubusercontent.com/1825120/70613013-de651b80-1bff-11ea-85ca-995d3767054e.png)

**Comment by Nowosad** [comment]
I've tried to do something with it a few months ago but my html/css/js skills are too weak. 
The main issues with adv-map are: .gif files size (especially the us borders animation) and JavaScript execution time (>4s).

**Comment by Robinlovelace** [comment]
I think that just by compressing the images we can go a long way. I can run gifs through https://ezgif.com/optimize and there are similar tools for png size reduction. Suggested approach unless we find out any automated approaches.

**Comment by Nowosad** [comment]
I think I've tried that already. But feel free to try it on your own, maybe I've missed something...


(You can test the website performance using Chrome/Chromium Audits - https://www.vojtechruzicka.com/chrome-audit-lighthouse/)

**Comment by Robinlovelace** [comment]
Closing for now, not a big deal.
