### ISSUE TITLE
sfheaders

### ISSUE THREAD

**Issue by SymbolixAU** [Robinlovelace/geocompr#466]
Do you think a section on [sfheaders](https://github.com/dcooley/sfheaders) is appropriate for the book? 

The two main concepts of the package are

1. Easily create `sf` objects from data.frames
2. call all the underlying C++ code from another package

An example of point 1 

```r
df <- data.frame(
  id = c(rep(1,5), rep(2,5))
  , x = rnorm(10)
  , y = rnorm(10)
)

sfheaders::sf_polygon(
  obj = df
  , polygon_id = "id"
)

# Simple feature collection with 2 features and 1 field
# geometry type:  POLYGON
# dimension:      XY
# bbox:           xmin: -2.291738 ymin: -2.20817 xmax: 2.479548 ymax: 0.8571166
# z_range:        zmin: NA zmax: NA
# m_range:        mmin: NA mmax: NA
# epsg (SRID):    NA
# proj4string:    NA
# id                       geometry
# 1  1 POLYGON ((1.030851 -2.20817...
# 2  2 POLYGON ((-0.6725756 -1.556...
```
And examples of point 2 are on [the website](https://dcooley.github.io/sfheaders/articles/Cpp.html)

cc @dcooley

**Comment by Robinlovelace** [comment]
Good thinking @SymbolixAU, the idea being the creation of `sf` objects without all the `sf` dependencies, right? I think it could fit well as a new section 2.2.9: https://geocompr.robinlovelace.net/spatial-class.html#sf

PRs welcome!

**Comment by dcooley** [comment]
yes, in fact that's the 3rd main concept of the package.

I should get some time after RStudioconf to add something.

**Comment by Robinlovelace** [comment]
Heads-up @dcooley we're commencing work on the 2nd edition so now could be a good time to write something for this, especially as `sfheaders` is now more tested and mature.

**Comment by dcooley** [comment]
Sounds good. In which section / chapter would you like me to write something?

**Comment by Robinlovelace** [comment]
I think right here in Chapter 2, in a new `### sfheaders` section before the `## Raster` section, would be ideal. Heads-up @Nowosad in case Jakub has a second opinion and/or a general :+1: on this. Thanks!

**Comment by Nowosad** [comment]
Hi @dcooley - I agree with @Robinlovelace about the position in the text. We are in the process of making several changes, so I also think it would be best if you could write this subsection in a separate .Rmd file that we could later merge to the book text.

**Comment by dcooley** [comment]
Will do.

Do you have a deadline you're working to? Or you want me to work to?

**Comment by Robinlovelace** [comment]
March 2022 is what our internal deadline for the Second Edition: https://github.com/Robinlovelace/geocompr/milestone/6

It would be great if you could get something before then, we'll be ramping up our activities on the book this autumn and we'll be completing a few 'pre-2nd edition' steps by end of September so that could make a good target if you want to get this in soon. If there's benefit of waiting that's also an option but by end of the year I'd say so we can see how it fits.

**Comment by dcooley** [comment]
I've started writing words in [my fork](https://github.com/dcooley/geocompr/blob/issue446/sfheaders.Rmd). How do you prefer pull requests? Are you happy if I make one now as a 'work-in-progress' so you can see the changes as they happen, or would you prefer a PR once it's almost complete?

**Comment by Robinlovelace** [comment]
Work in progress PR welcome. `sfheaders.Rmd` looking good! We can have a think about where it would best fit but, in the meantime, many thanks for putting this together.

**Comment by Robinlovelace** [comment]
Heads-up @dcooley we're on a mission to submit Part 1 to reviewers in the next 2 weeks. Let us know if you want to put in a PR or you're happy for us to take from that and add it? Also let us know how you want this to be cited, as the R package standard citation? Thanks.

**Comment by dcooley** [comment]
I have some spare time this weekend so I'll update the PR, then it should be ready for you to take and do what you want with it on Monday 31st if that's cool?

**Comment by Robinlovelace** [comment]
That would be amazing. Many thanks David!

**Comment by Robinlovelace** [comment]
Now done. Results looking good to me! https://geocompr.robinlovelace.net/spatial-class.html#the-sfheaders-package
