### ISSUE TITLE
Chapter 6 compilation fail

### ISSUE THREAD

**Issue by Darrellc199** [Robinlovelace/geocompr#470]
Working on a clean install of RStudio 1.2.5033, with clean install of R 3.6.2 and RTools 3.5, on Windows 10.

Utilizing instructions provided on the https://geocompr.robinlovelace.net/ build of the website, the bookdown compiling seems to function until chapter 6, at which point, the following Error occurs:

>Quitting from lines 421-426 (06-reproj.Rmd) 
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 177, 191
Calls: local ... <Anonymous> -> st_sf -> cbind -> cbind -> data.frame
In addition: Warning message:
>The shape world_laea1 is invalid. See sf::st_is_valid 
>
>Execution halted
>Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile 06-reproj.Rmd
>
> Quitting from lines 421-426 (06-reproj.Rmd) 
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 177, 191
Calls: local ... <Anonymous> -> st_sf -> cbind -> cbind -> data.frame
In addition: Warning message:
The shape world_laea1 is invalid. See sf::st_is_valid 
>
>Execution halted
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile 06-reproj.Rmd

**Comment by Nowosad** [comment]
To fix this issue you need to use the development version of the tmap package:

```r
library(devtools)
install_github("mtennekes/tmaptools")
install_github("mtennekes/tmap")
```

Learn more at https://github.com/mtennekes/tmap/issues/387.

Please reopen the issue if the error still exists.
