### ISSUE TITLE
Travis failing again...

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#472]
Seems to be in relation to `st_crs()`: https://travis-ci.org/Robinlovelace/geocompr/builds/648646404#L5429

**Comment by Nowosad** [comment]
I will take a look at it sometime this week.

**Comment by Nowosad** [comment]
https://travis-ci.org/Robinlovelace/geocompr/builds/650824046

**Comment by Robinlovelace** [comment]
Good fix, thanks @Nowosad, and @mtennekes.
