### ISSUE TITLE
Make master branch protected?

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#474]
Ensuring all changes are reviewed and reducing the number of rebuilds on Travis, Docker and Binder. https://help.github.com/en/enterprise/2.16/admin/developer-workflow/configuring-protected-branches-and-required-status-checks

We could also start developing on the `develop` branch, as per this: https://nvie.com/posts/a-successful-git-branching-model/

Thoughts @Nowosad and @jannes-m, sound like a good plan?

**Comment by jannes-m** [comment]
I like the master/develop branch separation.

**Comment by Nowosad** [comment]
:+1:

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/74921441-afb8ad80-53c5-11ea-99e7-8b22d88af1ff.png)


Done, at least 1 person needs to approve PRs to master now I think.
