### ISSUE TITLE
link2GI now not available as a CRAN package

### ISSUE THREAD

**Issue by ThomasG77** [Robinlovelace/geocompr#475]
Due to "check problems were not corrected in time" e.g https://cran.r-project.org/web/packages/link2GI/index.html, I was unable to install `link2GI` library on Ubuntu 18.04

The way to solve it partially has been to run

```
install.packages(c("R.utils", "sf", "https://cran.r-project.org/src/contrib/Archive/link2GI/link2GI_0.4.1.tar.gz"))
```

To compile successfully, before that, I have also needed to install `libudunits2.so` due to below feedback while installing `sf`

>   Configuration failed because libudunits2.so was not found. Try installing:
>     * deb: libudunits2-dev (Debian, Ubuntu, ...)
>     * rpm: udunits2-devel (Fedora, EPEL, ...)
>     * brew: udunits (OSX)
>   If udunits2 is already installed in a non-standard location, use:
>     --configure-args='--with-udunits2-lib=/usr/local/lib'
>   if the library was not found, and/or:
>     --configure-args='--with-udunits2-include=/usr/include/udunits2'
>   if the header was not found, replacing paths with appropriate values.
>   You can alternatively set UDUNITS2_INCLUDE and UDUNITS2_LIBS manually.

When I mentioned partially, it's due to the fact that when I clone the repo and run `make` to build a local version for offline use, because of the `library(link2GI)` calls in Rmarkdown files used by `bookdown`, it fails and I'm not "R fluent enough" at the moment to know how to solve it.

I don't know where the issue for `link2GI` should be mentioned or if it's necessary as some community members has already planned to fix soon `link2GI` to make it again a package supported on CRAN.

PS: [Affected code mentions to `link2GI`](https://github.com/Robinlovelace/geocompr/search?utf8=%E2%9C%93&q=link2GI&type=)

**Comment by Nowosad** [comment]
Hi @ThomasG77 - thanks for the opening this issue.
I have noticed this problem two days ago, but I think that @gisma is working on fixing it (https://github.com/r-spatial/link2GI). 

@gisma do you need any help with that?

**Comment by Robinlovelace** [comment]
Thanks for raising this, great to hear a fix is in the pipeline. Lots of changes at the moment, hopefully things settle down in the coming months.

**Comment by Robinlovelace** [comment]
`link2gi` seems to be back :tada: https://cran.r-project.org/package=link2GI

Does that fix the issue for you @ThomasG77 ?

**Comment by ThomasG77** [comment]
Yes. Thanks for the quick feedback

**Comment by gisma** [comment]
Even if the issue is closed, apologies for not being available (I lost the laptop :-( and needed to set up a replacement for a while). And thanks for the quick clarification of the situation.

**Comment by Nowosad** [comment]
Sorry to hear about your lost laptop.. 
And thanks for the CRAN fix given the circumstances.
