### ISSUE TITLE
Basemap greyed-out in Chapter 8

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#485]
See https://geocompr.robinlovelace.net/adv-map.html#interactive-maps

I see this: 

![image](https://user-images.githubusercontent.com/1825120/78402651-dc7df880-75f2-11ea-800c-1b5160e6c64a.png)

**Comment by Nowosad** [comment]
@Robinlovelace I think that some provider tiles does not work well with leaflet. Have you tried to change `addProviderTiles(providers$OpenStreetMap.BlackAndWhite)`?

**Comment by Robinlovelace** [comment]
Didn't try that one, but the positron one is good.

**Comment by Nowosad** [comment]
Yep, positron looks good. Thanks @Robinlovelace
