### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#488]
https://travis-ci.org/github/Robinlovelace/geocompr/builds/671023475#L7987

Documenting as hard to debug:

```
output file: references.knit.md

List of 10

 $ name      : chr "leaflet-providers"

 $ version   : chr "1.9.0"

 $ src       :List of 1

  ..$ file: chr "/tmp/RtmpH6K7CU"

 $ meta      : NULL

 $ script    : chr "leaflet-providers_1.9.0.js"

 $ stylesheet: NULL

 $ head      : NULL

 $ attachment: NULL

 $ package   : NULL

 $ all_files : logi FALSE

 - attr(*, "class")= chr "html_dependency"

Error: path for html_dependency not found: /tmp/RtmpH6K7CU

Execution halted

makefile:2: recipe for target 'html' failed

make: *** [html] Error 1

The command "make html" exited with 2.
```

Saving html output from leaflet map will solve the problem, I hope.

**Comment by Robinlovelace** [comment]
Attempted fix: https://github.com/Robinlovelace/geocompr/commit/4c599d385c86b0d9df61ebfa7392af9063caf670

**Comment by Nowosad** [comment]
For some (unknown) reason, the development version of **tmaptools** is not used in ghactions....

**Comment by Robinlovelace** [comment]
Could just add 

```
remotes::install_github("mtenekkes/tmaptools")
```

into the actions .yaml file

**Comment by Nowosad** [comment]
You have a typo in the code above. It should be:
```
remotes::install_github("mtennekes/tmaptools")
```
Can you try it? I am not sure where to put it.

**Comment by Robinlovelace** [comment]
Sure, will try now.

**Comment by Robinlovelace** [comment]
:crossed_fingers: @Nowosad are you free to talk briefly?

**Comment by Nowosad** [comment]
We are back online - https://geocompr.robinlovelace.net/
