### ISSUE TITLE
Move to GH Actions

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#493]
I added GitHub Actions to our book. The code was based on our travis file, [GitHub Actions of sf](https://github.com/r-spatial/sf/blob/master/.github/workflows/R-CMD-check-with-db.yaml), and the [ropensci-org/blog-guidance](https://github.com/ropensci-org/blog-guidance/tree/master/.github/workflows) repo. You can learn more about it in the *5. How to deploy a preview of the book for pull requests* part of https://ropensci.org/blog/2020/04/07/bookdown-learnings/.

- https://github.com/Robinlovelace/geocompr/pull/491

This could be our first step for https://github.com/Robinlovelace/geocompr/issues/476. I think the installation part works already - maybe we now need to update some settings related to Netlify, but I am not sure...

**Comment by Nowosad** [comment]
https://github.com/Robinlovelace/geocompr/runs/578699757?check_suite_focus=true Awesome!

**Comment by Robinlovelace** [comment]
The question now: what to do with Travis? I suggest we stop building on Travis and purge the travis set-up stuff. There may be benefits of keeping it but I guess the -s of maintenance time will outweigh the +s of having a backup CI system, GH Actions seems a solid foundation for #476 .

**Comment by Nowosad** [comment]
Completely agree.
