### ISSUE TITLE
The search button on the website doesn't work

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#500]
Reproducible example: go to https://geocompr.robinlovelace.net/ and click on the search button:

![image](https://user-images.githubusercontent.com/1825120/79243117-1cec3a80-7e6d-11ea-8d0e-f5bc1fb88579.png)

You should be able to search for things but it doesn't seem to work, tested on Firefox and Chome. Any ideas @Nowosad or anyone?

A strange one, sure it used to work...

**Comment by ColinFay** [comment]
Seems to be Github action related. 

Got the same issue at https://engineering-shiny.org/ and https://ggplot2-book.org/

**Comment by Robinlovelace** [comment]
Thanks for the links @ColinFay

**Comment by Robinlovelace** [comment]
Fixed, as shown here:

![Peek 2020-09-19 22-31](https://user-images.githubusercontent.com/1825120/93689580-d65bd580-fac7-11ea-86a5-33644c7d5707.gif)
