### ISSUE TITLE
Figure 2.5 looks slightly different

### ISSUE THREAD

**Issue by EagleGeo** [Robinlovelace/geocompr#503]
![Figure2 5](https://user-images.githubusercontent.com/42878579/79287077-9c3f3580-7e90-11ea-826c-64e52115273f.PNG)

**Comment by Nowosad** [comment]
Thanks @EagleGeo.

@Robinlovelace I can reproduce this issue with (especially see the US)...

``` r
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0
library(spData)
plot(world["continent"], reset = FALSE)
cex = sqrt(world$pop) / 10000
world_cents = st_centroid(world, of_largest = TRUE)
#> Warning in st_centroid.sf(world, of_largest = TRUE): st_centroid assumes
#> attributes are constant over geometries of x
#> Warning in st_centroid.sfc(st_geometry(x), of_largest_polygon =
#> of_largest_polygon): st_centroid does not give correct centroids for longitude/
#> latitude data
plot(st_geometry(world_cents), add = TRUE, cex = cex)
```

![](https://i.imgur.com/796eSdO.png)

<sup>Created on 2020-04-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The actual code behind the figure works well:

``` r
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0
library(spData)
world_proj = st_transform(world, "+proj=eck4")
world_cents = st_centroid(world_proj, of_largest_polygon = TRUE)
#> Warning in st_centroid.sf(world_proj, of_largest_polygon = TRUE): st_centroid
#> assumes attributes are constant over geometries of x
par(mar = c(0, 0, 0, 0))
# plot(st_geometry(world), graticule = TRUE, reset = FALSE)
plot(world_proj["continent"], reset = FALSE, main = "", key.pos = NULL)
g = st_graticule()
g = st_transform(g, crs = "+proj=eck4")
plot(g$geometry, add = TRUE, col = "lightgrey")
cex = sqrt(world$pop) / 10000
plot(st_geometry(world_cents), add = TRUE, cex = cex, lwd = 2, graticule = TRUE)
```

![](https://i.imgur.com/WxwirS9.png)

<sup>Created on 2020-04-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
On a local version of the book I see this:

![image](https://user-images.githubusercontent.com/1825120/79635332-355b9e00-8168-11ea-958d-2f09656f1b83.png)

But when you run the code it shows this:

![image](https://user-images.githubusercontent.com/1825120/79635361-545a3000-8168-11ea-90f5-7fcdafe58976.png)

That is deliberate. Did you follow the link to the script mentioned in the previous text @EagleGeo ?:

> A basic version of the map can be created with the following commands (see exercises at the end of this chapter and the script [`02-contplot.R`](https://github.com/Robinlovelace/geocompr/blob/master/code/02-contpop.R) to create Figure \@ref(fig:contpop)):

I don't think this is an issue, it's designed to make the reader think: "Why is my version of the plot different?", ask questions and explore the source code, which I think it has done.

@EagleGeo would it be clearer if the text above was modified? E.g. to:

> An unprojected version of this figure can be created with the following commands (see exercises at the end of this chapter and the script [`02-contplot.R`](https://github.com/Robinlovelace/geocompr/blob/master/code/02-contpop.R) to reproduce Figure \@ref(fig:contpop)):
