### ISSUE TITLE
Figure 2.6 India map was very small

### ISSUE THREAD

**Issue by EagleGeo** [Robinlovelace/geocompr#504]
![Figure2 6](https://user-images.githubusercontent.com/42878579/79287345-7ebe9b80-7e91-11ea-8320-88c4ceb41f56.PNG)

**Comment by Nowosad** [comment]
@EagleGeo I cannot reproduce this (see below). Have you tried to reset your device with `dev.off()` before?

``` r
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0
library(spData)
world_asia = world[world$continent == "Asia", ]
india = world[world$name_long == "India", ]
plot(st_geometry(india), expandBB = c(0, 0.2, 0.1, 1), col = "gray", lwd = 3)
plot(world_asia[0], add = TRUE)
```

![](https://i.imgur.com/R9RBVd9.png)

<sup>Created on 2020-04-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Nowosad** [comment]
@EagleGeo please reopen the issue if `dev.off()` is not a fix.
