### ISSUE TITLE
error when installing the "geocompkg" 

### ISSUE THREAD

**Issue by EagleGeo** [Robinlovelace/geocompr#505]
![geocompkg](https://user-images.githubusercontent.com/42878579/79350507-8a4baa00-7f05-11ea-8972-7a1e9c8969b6.PNG)

**Comment by Nowosad** [comment]
Try:
```r
install.packages("Rcpp")
```

**Comment by EagleGeo** [comment]
Thanks! It worked for the most part and I chose to update all the packages (option 1). I received an error at the end of the updating.
![geocompkg1](https://user-images.githubusercontent.com/42878579/79352460-e3b4d880-7f07-11ea-90ab-5099a51c627e.PNG)

**Comment by Nowosad** [comment]
Try:
```r
rm(list = ls())
```
next, restart R, and try to install it again.

**Comment by EagleGeo** [comment]
So I did. Then it says that the "glue" package was missing, so I installed the package. Now I received message when updating the packages.
![geocompkg2](https://user-images.githubusercontent.com/42878579/79353655-5a060a80-7f09-11ea-9b5a-0489b4cde6d9.PNG)

**Comment by Robinlovelace** [comment]
Maybe uninstall and reinstall R? I've seen these recursive package issues on Windows before and they can take ages to resolve. Note: R 4.0.0 will be released in less than 2 weeks so that could be the perfect opportunity for a fresh install.

**Comment by EagleGeo** [comment]
Thanks, I just installed 3.6.3 this morning. Was using 3.6 before. Will try it again.

**Comment by EagleGeo** [comment]
I uninstalled all the old R and reinstalled 3.6.3. What I found was that it would fail on the same error, "cannot remove prior installation of package " x".  The difference is the x, for example, it is "fs" this time and "backports" last time.
![geocompkg](https://user-images.githubusercontent.com/42878579/79360920-9722ca80-7f12-11ea-86e1-9e66ad7d336c.PNG)
I guess that I will wait for R 4.00.
Thanks!

**Comment by Robinlovelace** [comment]
You can completely remove old packages from your system. See here for guidance: https://stackoverflow.com/questions/48773148/addressing-the-cannot-remove-prior-installation-of-package-error-when-updating

**Comment by Nowosad** [comment]
You can also try to remove all of the packages (http://www.theanalyticslab.nl/how-to-remove-all-user-installed-packages-in-r/) and install them again...

**Comment by EagleGeo** [comment]
Robinlovelace:

As suggested, I used  setdiff(dir(.libPaths()), .packages(all = TRUE)) to find that I need to install the "fs" package, when installing, I get this error.
![geocompkg](https://user-images.githubusercontent.com/42878579/79379630-2e951700-7f2d-11ea-8a58-a581ffd45aff.PNG)

**Comment by Robinlovelace** [comment]
You could try this advice: https://community.rstudio.com/t/whenever-i-dowload-any-package-it-says-failed-and-says-unable-to-create-file/21685/11?u=robinlovelace

**Comment by EagleGeo** [comment]
Somehow the missing package errors were all gone. But I am having a problem with the spDataLarge package.
![geocompkg](https://user-images.githubusercontent.com/42878579/79381416-efb49080-7f2f-11ea-92de-363dcca77d3f.PNG)

**Comment by Robinlovelace** [comment]
Great to hear @EagleGeo. 

> But I am having a problem with the spDataLarge package.

Have you read the beginning of this chapter carefully?

https://geocompr.robinlovelace.net/spatial-class.html

You should find the solution there.

**Comment by EagleGeo** [comment]
Thanks all for your kind help and patience. Now I am good to go.
