### ISSUE TITLE
Figure 5.22 doesn't show of line and polygon rasterization

### ISSUE THREAD

**Issue by dhersz** [Robinlovelace/geocompr#506]
Currently it only shows the California shape over what I suppose is a grid of centroids twice.

![image](https://user-images.githubusercontent.com/1557047/79480772-ef2a0180-7fe4-11ea-903a-3d834c8458ee.png)

**Comment by Robinlovelace** [comment]
Well spotted. Verified at https://geocompr.robinlovelace.net/geometric-operations.html#fig:vector-rasterization2

**Comment by Nowosad** [comment]
Thanks! I have opened a new issue at https://github.com/mtennekes/tmap/issues/417

**Comment by Nowosad** [comment]
And it should be fine now. Thanks @dhersz for letting us know about the issue.
