### ISSUE TITLE
Footnotes are not working

### ISSUE THREAD

**Issue by dhersz** [Robinlovelace/geocompr#507]
The issue is not related to a specific chapter, it has been happening since introduction (I haven't read all the book yet, but as far as Chapter 5 no footnotes have worked).

Link to a footnote in introduction, for example, (https://geocompr.robinlovelace.net/intro.html#fn2, second paragraph section 1.1) redirects you to the beginning of the chapter.

The same is true for https://geocompr.robinlovelace.net/geometric-operations.html#fn22, for example, which redirects you to the beginning of chapter 5.

Nothing happens by clicking them if you're already at the page that they'd redirect you.

**Comment by Darrellc1991** [comment]
I can confirm that this issue persists in my local html copy built as per the build instructions on the Welcome page - both pre- and post-TRAVIS builds.

**Comment by Robinlovelace** [comment]
Thanks for reporting, definitely an issue. Will take a look.

**Comment by Robinlovelace** [comment]
I think it's a bug in bookdown: https://github.com/rstudio/bookdown/issues/840

**Comment by Nowosad** [comment]
@Robinlovelace I have a suspicion that this bug is related to the broken search button, and most importantly, its source in our book. Just now, I have built the first chapter of our book locally - I have a working search button and footnotes. I am going to work on this issue now.

**Comment by Nowosad** [comment]
@Robinlovelace please check a local build using two versions of `_bookdown.yml:
1. 
```
rmd_files: 
    - "index.Rmd"
    - "01-introduction.Rmd"
    - "02-spatial-data.Rmd"
    #- "references.Rmd"
```
2. 
```
rmd_files: 
    - "index.Rmd"
    - "01-introduction.Rmd"
    - "02-spatial-data.Rmd"
    - "references.Rmd"
```

In my case, the second version moves most of the footnotes to the references section (?!).

**Comment by Robinlovelace** [comment]
@Nowosad this is an important issue, thanks for looking into it, I will do the test build now.

**Comment by Robinlovelace** [comment]
Update, I confirm that in the second version the footnotes are in the references chapter:

![image](https://user-images.githubusercontent.com/1825120/79635670-19f19280-816a-11ea-8734-c83b534bd43b.png)

**Comment by Nowosad** [comment]
Ok, it seems related to https://github.com/rstudio/bookdown/issues/840. If you remove all of new lines in the footnotes - they start to work as expected...

**Comment by Robinlovelace** [comment]
> Ok, it seems related to rstudio/bookdown#840. If you remove all of new lines in the footnotes - they start to work as expected...

Yes, only multi-line footnotes. Should we switch to single line footnotes, which should also make them shorter and easier to maintain, or wait for an upstream fix? Thinking the former.

**Comment by Robinlovelace** [comment]
> Ok, it seems related to rstudio/bookdown#840. If you remove all of new lines in the footnotes - they start to work as expected...

Yes, only multi-line footnotes. Should we switch to single line footnotes, which should also make them shorter and easier to maintain, or wait for an upstream fix? Thinking the former.

**Comment by Nowosad** [comment]
@Robinlovelace - we can try to do both. Can you improve the footnotes (e.g., change to single lines, remove references in them, make them more concise)? I will report this issue on the bookdown github page.

**Comment by Nowosad** [comment]
https://github.com/rstudio/bookdown/issues/840#issuecomment-615846696

**Comment by cderv** [comment]
Hi, 

I have made a PR to fix the bookdown issue. This should fix also this issue - multiline footnotes works again. See https://github.com/rstudio/bookdown/pull/876

**Comment by Nowosad** [comment]
Footnotes are back - https://geocompr.robinlovelace.net/spatial-class.html#fn5. Thank you a lot @cderv !
