### ISSUE TITLE
Wrong raster listed on Chapter 6 exercise 3

### ISSUE THREAD

**Issue by dhersz** [Robinlovelace/geocompr#509]
> 3. Transform the continuous raster (cat_raster) into WGS 84 using the nearest neighbor interpolation method. What has changed? How does it influence the results?

> 4. Transform the categorical raster (cat_raster) into WGS 84 using the bilinear interpolation method. What has changed? How does it influence the results?

The [Chapter 6 exercise](https://geocompr.robinlovelace.net/reproj-geo-data.html#exercises-4) 3 cites `cat_raster` as a continuous raster and asks to transform it using the nearest neighbor interpolation method. However, `cat_raster` is a categorical raster, and is also cited in the following question. I think you meant the `con_raster`, which is continuous and also used as an example in [Section 6.6](https://geocompr.robinlovelace.net/reproj-geo-data.html#reprojecting-raster-geometries).

The [exercise solution](https://geocompr.github.io/geocompkg/articles/solutions06.html) also quotes the question differently:
> Transform the continuous raster (cat_raster) into NAD83 / UTM zone 12N using the nearest neighbor interpolation method. What has changed? How does it influence the results?

**Comment by Robinlovelace** [comment]
Thanks for raising this @dhersz. Are you up for taking a look @Nowosad ?

**Comment by Nowosad** [comment]
Once more - many thanks @dhersz! It should be fixes with https://github.com/Robinlovelace/geocompr/pull/515/files.
