### ISSUE TITLE
Discuss spatial indexes

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#51]
This would be well-suited to chapter 04 I think: http://r-spatial.org/r/2017/06/22/spatial-index.html

**Comment by Nowosad** [comment]
The spatial index is going to be always built in sf. I think one/two sentence about it in the forth chapter will be enough.

**Comment by Robinlovelace** [comment]
Agreed, potentially with reference to the article linked-to above. You up for adding a sentence + link on that @Nowosad ?

**Comment by Nowosad** [comment]
@Robinlovelace take a look at https://github.com/Robinlovelace/geocompr/commit/2c0ead2a92387125afe3fb6848dd84c40804892c. 
I've added a text block - It could be improved though.

**Comment by Robinlovelace** [comment]
That looks good enough to me, suggest closing for now, or when the PR is merged.
