### ISSUE TITLE
Revert 'hotfix' to Figure 5.25 following upstream (tmap) solution

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#511]
Currently it shows:

![image](https://user-images.githubusercontent.com/1825120/79603311-026fc680-80e4-11ea-8ace-4358f90658d7.png)

Addressed by #510

**Comment by jannes-m** [comment]
already fixed the bug, will issue a PR today. Apparently, the latest version of `tmap` can no longer handle categorical rasters.

**Comment by Robinlovelace** [comment]
Thanks for the quick response @jannes-m, I suspect this could usefully be addressed in the `tmap` package.

**Comment by Robinlovelace** [comment]
But will happily accept a 'hotfix' that fixes it for now. I think PR #510 represents such a fix and suggest we merge it for now if it does indeed fix the specific issue.

**Comment by Nowosad** [comment]
@jannes-m there are several changes in the **tmap** version 3. Now it uses **stars** in the background for the raster data, and it has some consequences/limitations. This is one of them.

**Comment by Robinlovelace** [comment]
> there are several changes in the tmap version 3. Now it uses stars in the background for the raster data, and it has some consequences/limitations. This is one of them.

Fully agree. Suggest merging this PR and opening a separate issue in `tmap`. Also wanting to encourage PRs from new contributors, especially when they identify and fix issues in one!

**Comment by Nowosad** [comment]
@Robinlovelace I will investigate this issue today. However, I think it is related to a discussion I already had with Martijn - our previous way of making this figure is no longer valid. There are new ways to do it.

**Comment by Nowosad** [comment]
I was wrong. It seems to be a bug in **tmap**. I reported it just now - https://github.com/mtennekes/tmap/issues/417.

**Comment by jannes-m** [comment]
ok, just let me write down my solution here, which deratifies the *grain* raster and which avoids turning a raster object into an **SpatialGridDataFrame** (if this was the hotfix, haven't looked at it admittedly):

``` r
library(tmap)
library(spData)
library(raster)
#> Loading required package: sp
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:raster':
#> 
#>     intersect, select, union
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
tmap_options(main.title.size = 1)

cols = c("clay" = "brown", "sand" = "rosybrown", "silt" = "sandybrown")

tm_shape(deratify(grain, "ID")) + 
  tm_raster(legend.show = FALSE, palette = cols) +
  tm_layout(main.title = "Raster", frame = FALSE)
```

![](https://i.imgur.com/YettkTF.png)

<sup>Created on 2020-04-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
Hi @jannes-m, great diagnosis. I only saw your comment here, which has a better solution IMO, after merging #510. Happy for this more elegant solution to go in, although it will make virtually no difference to the user and the long term solution is to revert to the original code when **tmap** accepts the raster object directly. Will update the name of the issue accordingly and submit a PR that should fix it when `tmap` is ready.

**Comment by jannes-m** [comment]
And one other comment which has to do with the distro I use (Arch). Updating my spatial R ecosystem took me almost 3 hours, most of the time is spent on compilation from source. What took me a while to figure out was that I had to install `v8-r` which is a dependency of package **V8**  which in turn is used by **tmap**, **mapdeck**, etc. Before actually installing `v8-r` I had to increase the partition space of folder `/tmp` as it downloads >4GB of installation stuff otherwise the Error *No space on device* occurred. Here is what I did in accordance with this [gist](https://gist.github.com/ertseyhan/618ab7998bdb66fd6c58). Might be useful for other Arch users running into the same problem.

```{sh}
# temporarily increase the size of the /tmp folder
sudo mount -o remount,size=10G,noatime /tmp 
# install v8-r using trizen
trizen -S v8-r
```

**Comment by Robinlovelace** [comment]
> Updating my spatial R ecosystem took me almost 3 hours

Very useful info that could be of use for others.

This is a good argument for using distros that have precompiled binaries such as Ubuntu with the set-up outlined here (which we now use in our Dockerfiles) and, I believe Fedora (an article on this may be in the pipeline): https://github.com/rocker-org/rocker/blob/master/r-ubuntu/bionic/Dockerfile#L27-L28

**Comment by Nowosad** [comment]
Fixed.
