### ISSUE TITLE
Issue with cat_raster object?

### ISSUE THREAD

**Issue by dhersz** [Robinlovelace/geocompr#512]
Right now the [chapter 6 exercise](https://geocompr.github.io/geocompkg/articles/solutions06.html) 4 solution shows the following plot for `cat_raster_wgs84`:

![image](https://user-images.githubusercontent.com/1557047/79603657-266ee000-80c3-11ea-9e9b-c5cb00ee7801.png)

I have also arrived at the same result, but if I run `plot(cat_raster_wgs84)` again (following the same command previously sent) I get the following plot:

![image](https://user-images.githubusercontent.com/1557047/79603772-55855180-80c3-11ea-8766-0274f379c4bd.png)

I could replicate this with the following code:

```
wgs84 <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
cat_raster_wgs84 <- cat_raster %>% 
  projectRaster(crs = wgs84, method = "bilinear")

plot(cat_raster)
plot(cat_raster_wgs84)
plot(cat_raster_wgs84)
```

The exercise solution leads to the assumption that the raster is messed up because of the wrong method used when reprojecting (at least that's how I interpreted it), but this is not the case, because the same results happens even when using the nearest neighbour method:

```
wgs84 <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
cat_raster_wgs84 <- cat_raster %>% 
  projectRaster(crs = wgs84, method = "ngb")

plot(cat_raster)
plot(cat_raster_wgs84)
plot(cat_raster_wgs84)
````

The first `plot(cat_raster_wgs84)` here, in this case, also generates a strange plot.

In fact, even when plotting another completely different raster, that has not been modified or reprojected, also leads to the strange gradient plot:

```
plot(cat_raster)
plot(con_raster)
```

![image](https://user-images.githubusercontent.com/1557047/79604430-739f8180-80c4-11ea-9456-1f3e53815b64.png)

If I plot `cat_raster` after `con_raster` the plots are alright.

So I don't really know what's going on, but `cat_raster` seems to be the cause of the problems.

**Comment by Nowosad** [comment]
Thanks @dhersz for letting us know. This is a very strange bug. I have opened a new issue about this at https://github.com/rspatial/raster/issues/111.

**Comment by Nowosad** [comment]
It should be fine now - see https://github.com/rspatial/raster/issues/111.
