### ISSUE TITLE
Missing GET 'path' argument in Section 7.4

### ISSUE THREAD

**Issue by dhersz** [Robinlovelace/geocompr#513]
When showing how to download from WFS services with a `GetFeature` request the following code is presented:

```
qf = list(request = "GetFeature", typeName = "area:FAO_AREAS")
file = tempfile(fileext = ".gml")
httr::GET(url = base_url, query = qf, httr::write_disk(file))
fao_areas = sf::read_sf(file)
#> Error: Cannot open "C:\Users\Usuario\AppData\Local\Temp\Rtmpae1Xug\file32c417b24647.gml"; The source could be corrupt or not supported. See `st_drivers()` for a list of supported formats.
```

This throws an error, because the full url is missing the `path` argument that was previously used (`path = endpoint`).

Changing the `GET` line code fixed the problem.

```httr::GET(url = base_url, path = endpoint, query = qf, httr::write_disk(file))```

**Comment by Robinlovelace** [comment]
Thanks for raising this and other comments, will take a look at this on tomorrow.

**Comment by Nowosad** [comment]
Thanks a lot @dhersz - I fixed it in soon-to-be ready pull request - https://github.com/Robinlovelace/geocompr/pull/515.

**Comment by Robinlovelace** [comment]
Great fix @Nowosad, I suggest we close issues when fixed on the website next time though.
