### ISSUE TITLE
load sdData from github not cran

### ISSUE THREAD

**Issue by respite99** [Robinlovelace/geocompr#52]
Current (25 June):
2 Geographic data in R
Prerequisites
This chapter requires the packages sf, and spData to be installed and loaded:
library(sf)
library(spData)

Should be:
devtools::install_github("nowosad/spData")

**Comment by Nowosad** [comment]
Hi @respite99 ,
thanks for this issue.

You need to have the packages sf, and spData to be installed and loaded. There are several ways to install these packages and we recommend to install them using:
```R
# it install all the packages needed for the book
devtools::install_github("Robinlovelace/geocompr") 
```
And next, you need to load them:
```R
library(sf)
library(spData)
```

Let me know if it works;)

**Comment by Robinlovelace** [comment]
Closing for now - I think the above commit resolves any ambiguity in Chapter 2 and please do let us know if you have any other feedback on the book.
