### ISSUE TITLE
Issue with tmap plot in Chapter 2

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#521]
I see:

```
label: raster-intro-plot2 (with options) 
List of 3
 $ echo   : logi FALSE
 $ fig.cap: chr "Examples of continuous and categorical rasters."
 $ warning: logi FALSE

Quitting from lines 762-763 (02-spatial-data.Rmd) 
Error in if (prod(xy_dim) > max.raster) { : 
  missing value where TRUE/FALSE needed
Calls: local ... print_tmap_arrange -> print_tmap -> mapply -> <Anonymous>
```

https://github.com/Robinlovelace/geocompr/runs/601364384#step:10:869

**Comment by Nowosad** [comment]
That a new bug, already reported at https://github.com/mtennekes/tmap/issues/421.

**Comment by Nowosad** [comment]
It is fixed now - https://github.com/mtennekes/tmap/commit/5781411bd61b20c58184eb1971d3e35153e8958c.

**Comment by Robinlovelace** [comment]
Updated with remote: https://github.com/geocompr/geocompkg/commit/feaeceb42903adcdac2aaac14a9ec9753ad72aac

**Comment by Robinlovelace** [comment]
Update on this @Nowosad it seems there may be a slightly different issue now: https://github.com/Robinlovelace/geocompr/runs/604523588#step:10:868

**Comment by Nowosad** [comment]
It works locally for me... Maybe it is good to add `remotes::install_github("mtennekes/tmaptools")`?

**Comment by Robinlovelace** [comment]
Updated here: https://github.com/geocompr/geocompkg/commit/2eb37f8de2413467da8c6faf0fa35a5d5dad8830
