### ISSUE TITLE
Show how to make animated map with Covid-19 data

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#522]
How can one make an animated map of open data on officially reported deaths from Covid-19 like this?
![covid-19-animated-map](https://user-images.githubusercontent.com/1825120/79768034-1e60ab80-8322-11ea-9c99-9997b588ee57.gif)

**Comment by Nowosad** [comment]
Done - https://geocompr.github.io/post/2020/mapping-covid-19/
