### ISSUE TITLE
Different palette used in Figure 8.5

### ISSUE THREAD

**Issue by dhersz** [Robinlovelace/geocompr#530]
In [Figure 8.5](https://geocompr.robinlovelace.net/adv-map.html#static-maps) (I don't know how to link to a section based on an image, sorry) the rightmost map was generated with the `RdBu` palette, not the `BuGn`.

![image](https://user-images.githubusercontent.com/1557047/80526955-02848780-896a-11ea-8b31-7409726bf662.png)

The [code](https://raw.githubusercontent.com/Robinlovelace/geocompr/master/code/08-tmpal.R) used to generate it shows it.

P.S.: I keep making issues about minor stuff, if this is bothering you or you think it's not that relevant just let me know.

**Comment by Robinlovelace** [comment]
Hi @dhersz thanks for raising this, it's not bothering us, it's really useful. Keep them coming!

**Comment by Nowosad** [comment]
@dhersz https://youtu.be/bLgoqnqJ4DY?t=2461 - my answer is in the next ~20 seconds in this video.

**Comment by dhersz** [comment]
Cool, I'm glad to know!
