### ISSUE TITLE
Easy way to make inset maps proportionate located to main map bounding box?

### ISSUE THREAD

**Issue by dhersz** [Robinlovelace/geocompr#532]
I tried replicating [Figure 8.14](https://geocompr.robinlovelace.net/adv-map.html#fig:insetmap1), but realized that, since the `x` and `y` arguments passed to `viewport` are relative to the "graphical area" (sorry, I don't know the actual name of it, but the area dedicated to plotting maps on the bottom right corner) of RStudio (which apparently is a viewport itself), I'm not able to reproduce the figure you generated.

Illustrating my point, this is what you generated:

![](https://geocompr.robinlovelace.net/08-mapping_files/figure-html/insetmap1-1.png)

This is what I arrived at when running the code:

![image](https://user-images.githubusercontent.com/1557047/80541964-8cd8e580-8982-11ea-913a-b8603b34af38.png)

In fact, the maps arrengement also changes if I zoom the plot (just changing the width of the graphical area of RStudio does the trick):

![image](https://user-images.githubusercontent.com/1557047/80542034-ada13b00-8982-11ea-8f48-6a862a24b7f3.png)

I'd like to have the inset map always located at the same place, proporcionally to the main map, but that's not what is happening.

Apparently this is due to the graphical area of RStudio being a viewport. The inset map is set based on this viewport, and not the main map bounding box. This annoys me a bit because it makes the code/map making less reproducible, since each user may end up with a different inset map location due to local configuration. 

I glanced through the `viewport` documentation and saw that the location and size of a viewport are based on its parent (which can be another viewport). So I tried messing up a bit and creating a viewport tree with the `grid` package, where the main viewport would have the main map proportions and the inset map viewport would be arranged based on its parent (the main viewport). However, I have no previous experience with the `grid` package and with viewports, so I wasn't able to generate what I was trying to.

Perhaps any of you may have tried to do something similar before?

I know this is not an issue itself, but I think it's related to the book content and to what I believe is one of the goals of the book - making geocomputation easily reproducible. Cheers!

**Comment by Nowosad** [comment]
@dhersz Thanks for this comment. I am aware of this issue, but do not know the proper solution. After writing this section, I also tried several different approaches to create inset maps, see (1) https://geocompr.github.io/geocompkg/articles/us-map.html, (2) https://nowosad.github.io/post/making-alternative-inset-maps-of-the-usa/, (3) https://github.com/Nowosad/us-map-alternative-layout, and (4) https://github.com/Nowosad/spain-map-layout. There is a lot of code in the mention examples. Let me know if you prefer one of the approaches more than the other.

**Comment by dhersz** [comment]
@Nowosad thanks for the reply. Using the `layout` viewport seems very good, but I found it hard to apply when trying to generate an inset map like the one used in Figure 8.14 (which I mentioned in the original post).

I tried a different approach, which almost led me to what I wanted.
I was able to create and arrange the viewports which I think I'd need, but I couldn't actually plot the maps within them. Let me show what I have:

```R
# function for extracting width and height as normalised values -----------

norm_dim <- function(obj) {
    bbox <- st_bbox(obj)
    
    width <- bbox[["xmax"]] - bbox[["xmin"]]
    height <- bbox[["ymax"]] - bbox[["ymin"]]
    
    w <- width/max(width, height)
    h <- height/max(width, height)
    
    c("w" = w, "h" = h)
}


# creating the main map and inset map viewports ---------------------------

main_w <- norm_dim(nz_region)[["w"]]
main_h <- norm_dim(nz_region)[["h"]]

# using "snpc" unit to ensure width to height ratio stays constant
# independently of ROOT viewport dimensions
main_vp <- viewport(x = 0.5, y = 0.5,
                    width = unit(main_w, "snpc"), height = unit(main_h, "snpc"),
                    name = "main")

ins_w <- norm_dim(nz)[["w"]]
ins_h <- norm_dim(nz)[["h"]]

# using "cm" ratio to ensure inset map offsets the main map border by 0.5 cm
ins_vp <- viewport(x = unit(1, "npc") - unit(0.5, "cm"), y = unit(0.5, "cm"),
                   width = unit(ins_w, "snpc") * 0.3, height = unit(ins_h, "snpc") * 0.3,
                   just = c("right", "bottom"), name = "ins")

# printing viewports tree -------------------------------------------------
grid.newpage()
grid.rect()
grid.text(current.viewport()$name, x = 0, y = 1, just = c("left", "top"))
pushViewport(main_vp)
grid.rect()
grid.text(current.viewport()$name, x = 0, y = 1,just = c("left", "top"))
pushViewport(ins_vp)
grid.rect()
grid.text(current.viewport()$name, x = 0, y = 1,just = c("left", "top"))
```
![image](https://user-images.githubusercontent.com/1557047/80644788-9c1e6880-8a40-11ea-88e8-70cbb1184883.png)

So I thought that just plotting the maps when inside the desired viewport would do the trick, but apparently not:

```R
# printing ----------------------------------------------------------------
grid.newpage()
grid.rect()
grid.text(current.viewport()$name, x = 0, y = 1, just = c("left", "top"))

pushViewport(main_vp)
print(nz_height_map, vp = current.viewport())

pushViewport(ins_vp)
print(nz_map, vp = current.viewport())
```
![image](https://user-images.githubusercontent.com/1557047/80645537-a7be5f00-8a41-11ea-9010-5675bf7690f8.png)

It seems that I'm stuck at what should be the easiest part: plotting the maps. Do you have an idea how to follow up from what I've done?

**Comment by dhersz** [comment]
@Nowosad thanks for the reply. Using the `layout` viewport argument seems to work for the US and Spain case, but I think it wouldn't work so well when generating Figure 8.14 because you'd have to position the inset map as you positioned the Hawaii map, which is still relative to the main viewport.

I tried another approach and it seems to work. However, the plotting behaviour doesn't seem stable: running this code twice generates a blank plot in the second time... I don't know. Here's the code:

```R
# function for extracting width and height as normalised values -----------

norm_dim <- function(obj) {
    bbox <- st_bbox(obj)
    
    width <- bbox[["xmax"]] - bbox[["xmin"]]
    height <- bbox[["ymax"]] - bbox[["ymin"]]
    
    w <- width/max(width, height)
    h <- height/max(width, height)
    
    c("w" = w, "h" = h)
}


# creating the main map and inset map viewports ---------------------------

main_w <- norm_dim(nz_region)[["w"]]
main_h <- norm_dim(nz_region)[["h"]]

# using "snpc" unit to ensure width to height ratio stays constant
# independently of ROOT viewport dimensions
main_vp <- viewport(x = 0.5, y = 0.5,
                    width = unit(main_w, "snpc"), height = unit(main_h, "snpc"),
                    name = "main")

ins_w <- norm_dim(nz)[["w"]]
ins_h <- norm_dim(nz)[["h"]]

# using "cm" ratio to ensure inset map offsets the main map border by 0.5 cm
ins_vp <- viewport(x = unit(1, "npc") - unit(0.5, "cm"), y = unit(0.5, "cm"),
                   width = unit(ins_w, "snpc") * 0.3, height = unit(ins_h, "snpc") * 0.3,
                   just = c("right", "bottom"), name = "ins")

# printing maps -----------------------------------------------------------

grid.newpage()

print(nz_height_map, vp = main_vp)

pushViewport(main_vp)
print(nz_map, vp = ins_vp)
```
![](https://i.imgur.com/eZmNLA8.png)
<sup>Created on 2020-04-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Nowosad** [comment]
Great work @dhersz! I run the code several times, and get the map each time without any issues... It is hard to tell what is the source of your issue (operating system (and its graphic device)?, R version?, R packages versions?). I do not know...


``` r
library(spData)
library(spDataLarge)
library(grid)
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0
library(tmap)

nz_region = st_bbox(c(xmin = 1340000, xmax = 1450000,
                      ymin = 5130000, ymax = 5210000),
                    crs = st_crs(nz_height)) %>% 
    st_as_sfc()

nz_height_map = tm_shape(nz_elev, bbox = nz_region) +
    tm_raster(style = "cont", palette = "YlGn", legend.show = TRUE) +
    tm_shape(nz_height) + tm_symbols(shape = 2, col = "red", size = 1) +
    tm_scale_bar(position = c("left", "bottom"))

nz_map = tm_shape(nz) + tm_polygons() +
    tm_shape(nz_height) + tm_symbols(shape = 2, col = "red", size = 0.1) + 
    tm_shape(nz_region) + tm_borders(lwd = 3) 


norm_dim <- function(obj) {
    bbox <- st_bbox(obj)
    
    width <- bbox[["xmax"]] - bbox[["xmin"]]
    height <- bbox[["ymax"]] - bbox[["ymin"]]
    
    w <- width/max(width, height)
    h <- height/max(width, height)
    
    c("w" = w, "h" = h)
}


# creating the main map and inset map viewports ---------------------------

main_w <- norm_dim(nz_region)[["w"]]
main_h <- norm_dim(nz_region)[["h"]]

# using "snpc" unit to ensure width to height ratio stays constant
# independently of ROOT viewport dimensions
main_vp <- viewport(x = 0.5, y = 0.5,
                    width = unit(main_w, "snpc"), height = unit(main_h, "snpc"),
                    name = "main")

ins_w <- norm_dim(nz)[["w"]]
ins_h <- norm_dim(nz)[["h"]]

# using "cm" ratio to ensure inset map offsets the main map border by 0.5 cm
ins_vp <- viewport(x = unit(1, "npc") - unit(0.5, "cm"), y = unit(0.5, "cm"),
                   width = unit(ins_w, "snpc") * 0.5, height = unit(ins_h, "snpc") * 0.5,
                   just = c("right", "bottom"), name = "ins")

# printing maps -----------------------------------------------------------

grid.newpage()

print(nz_height_map, vp = main_vp)
#> stars object downsampled to 877 by 1140 cells. See tm_shape manual (argument raster.downsample)

pushViewport(main_vp)
print(nz_map, vp = ins_vp)
```

![](https://i.imgur.com/QsrsY8u.png)

<sup>Created on 2020-05-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dhersz** [comment]
Glad to know it works. Not sure the source of the issue either, it seems to be related to RStudio. If I refresh the plot or zoom it the expected result shows up.

Another small detail in this code is that if you want to ensure that the inset map offsets the main one by 0.5 cm (or whatever you have set) you'd need to add `tm_layout(outer.margins = 0)` to both `nz_height_map` and `nz_map`. Probably not a good practice to set an absolute offset distance instead of a relative one, but anyway...

**Comment by Nowosad** [comment]
Superseded by https://github.com/Robinlovelace/geocompr/issues/882
