### ISSUE TITLE
coffeeApp on Figure 8.25 doesn't start

### ISSUE THREAD

**Issue by dhersz** [Robinlovelace/geocompr#535]
coffeeApp on [Figure 8.25](https://geocompr.robinlovelace.net/adv-map.html#fig:lifeApp) doesn't start.

![image](https://user-images.githubusercontent.com/1557047/80816994-ef123000-8ba6-11ea-9420-1cff2d51cae9.png)

I ran the [code ](https://github.com/Robinlovelace/geocompr/blob/master/coffeeApp/app.R)in my computer and it worked.

**Comment by Robinlovelace** [comment]
What environment are you running the crashing code on? I don't think this is an issue if the code runs OK locally so closing for now, but if you spot an issue with the book let us know.

In summary, I think this is an issue with your set-up not the contents of the book but happy to re-visit if there are issues with the code.

**Comment by Nowosad** [comment]
@Robinlovelace visit Chapter 8 - https://geocompr.robinlovelace.net/adv-map.html#fig:lifeApp. The issue related to the book online version.

**Comment by Robinlovelace** [comment]
Aha yes that's quite an issue, was looking at the wrong figure.

**Comment by Robinlovelace** [comment]
Looking at this now :beers:

**Comment by Robinlovelace** [comment]
Please check the latest version after the next build (hopefully the build is fixed). One issue, the app should have 2 columns of UI but I see this. Do others see this?:

![image](https://user-images.githubusercontent.com/1825120/80872692-72b54500-8cab-11ea-8880-2b5159cd31c8.png)

**Comment by dhersz** [comment]
I see two columns both when running locally and when visiting https://shiny.robinlovelace.net/coffeeApp/.

![image](https://user-images.githubusercontent.com/1557047/80972592-af408800-8df4-11ea-90c4-b3977f375b6f.png)
