### ISSUE TITLE
cannot replicate figure 2.3 from Geocomputation with R

### ISSUE THREAD

**Issue by willet713** [Robinlovelace/geocompr#536]
Hi,  I just installed the most recent version of R, 4.0.0 for Windows, yesterday (May 1), and installed and loaded the packages "sf" and "spData". I am trying to learn R's capabilities for geocomputing so I am reading Chapter 2 of Geocomputation with R. Although I can reproduce the output from the command

names(world)

I get an error message when trying 

plot(world)

and the output from 

summary(world["lifeExp"])

does not contain the "geom" column. 

See output below. Any idea about what is wrong or missing?

> names(world)
 [1] "iso_a2"    "name_long" "continent" "region_un" "subregion" "type"     
 [7] "area_km2"  "pop"       "lifeExp"   "gdpPercap" "geom"     
> mode(world$geom)
[1] "list"
> plot(world)
Error in data.matrix(x) : 
  'list' object cannot be coerced to type 'double'
> summary(world["lifeExp"])
    lifeExp     
 Min.   :50.62  
 1st Qu.:64.96  
 Median :72.87  
 Mean   :70.85  
 3rd Qu.:76.78  
 Max.   :83.59  
 NA's   :10     
>
(Sorry I could not format this in monospace font.)

**Comment by Robinlovelace** [comment]
Hi @willet713 have you loaded the `sf` package with the `library()` function before trying to plot the `world` object? I think that will fix it, as shown below.

``` r
library(spData)
plot(world)
#> Warning in data.matrix(x): NAs introduced by coercion

#> Warning in data.matrix(x): NAs introduced by coercion

#> Warning in data.matrix(x): NAs introduced by coercion

#> Warning in data.matrix(x): NAs introduced by coercion

#> Warning in data.matrix(x): NAs introduced by coercion

#> Warning in data.matrix(x): NAs introduced by coercion
#> Error in data.matrix(x): 'list' object cannot be coerced to type 'double'
library(sf)
#> Linking to GEOS 3.7.2, GDAL 2.4.2, PROJ 5.2.0
plot(world)
#> Warning: plotting the first 9 out of 10 attributes; use max.plot = 10 to plot
#> all
```

![](https://i.imgur.com/srcFPLT.png)

<sup>Created on 2020-05-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
