### ISSUE TITLE
Section on where to ask questions

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#537]
A section on where to ask questions. Basically the contents of this in prose and with a section, I can imagine linking to it many times for people who ask me minor questions that they could better ask in other places: https://nowosad.github.io/whyr_webinar004/#45

**Comment by Robinlovelace** [comment]
Just add text for this, was supposed to be in a PR but never mind... Feedback welcome, was wondering if it should be in Chapter 1 but seems to fit well at the end. We can always add cross references to it from earlier chapters.

**Comment by Nowosad** [comment]
👍🏻 looks great. This section is very similar to the advice I often give to other people. 

I think it fits well in the last chapter. Maybe we can add a link to it at the book's landing page (https://geocompr.robinlovelace.net/)?
