### ISSUE TITLE
plot time in gpx data using sf

### ISSUE THREAD

**Issue by marcelocarvalhoalves** [Robinlovelace/geocompr#538]
Dear Robin,
I am trying to read gpx data using sf as you did in this example:
https://geocompr.github.io/geocompkg/articles/gps-tracks.html

The map with time data is not loading into map with color points, but only track_fid, track_seg_id, track_seg_point_id and ele . Do you know if this is a problem with time data configuration or some package to load?

The code I am trying is:
> library(sf)
Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
Warning message:
package ‘sf’ was built under R version 3.5.3 
> p = read_sf("E:/Aulas/Topografia/Aula13/activity_4871799754.gpx", layer = "track_points")
> p
Simple feature collection with 486 features and 27 fields
geometry type:  POINT
dimension:      XY
bbox:           xmin: -44.97712 ymin: -21.21822 xmax: -44.96131 ymax: -21.21166
epsg (SRID):    4326
proj4string:    +proj=longlat +datum=WGS84 +no_defs
 A tibble: 486 x 28
  track_fid track_seg_id track_seg_point~   ele time                magvar geoidheight
       <int>        <int>            <int> <dbl> <dttm>               <dbl>       <dbl>
 1         0            0                0  891  2020-05-02 16:57:44     NA          NA
 2         0            0                1  891. 2020-05-02 16:57:45     NA          NA
 3         0            0                2  891. 2020-05-02 16:57:47     NA          NA
 4         0            0                3  892. 2020-05-02 16:57:50     NA          NA
 5         0            0                4  892. 2020-05-02 16:57:53     NA          NA
 6         0            0                5  893. 2020-05-02 16:57:58     NA          NA
 7         0            0                6  893. 2020-05-02 16:57:59     NA          NA
 8         0            0                7  893. 2020-05-02 16:58:00     NA          NA
 9         0            0                8  893  2020-05-02 16:58:01     NA          NA
10         0            0                9  893  2020-05-02 16:58:02     NA          NA
 ... with 476 more rows, and 21 more variables: name <chr>, cmt <chr>, desc <chr>,
   src <chr>, link1_href <chr>, link1_text <chr>, link1_type <chr>, link2_href <chr>,
   link2_text <chr>, link2_type <chr>, sym <chr>, type <chr>, fix <chr>, sat <int>,
   hdop <dbl>, vdop <dbl>, pdop <dbl>, ageofdgpsdata <dbl>, dgpsid <int>,
   ns3_TrackPointExtension <chr>, geometry <POINT [°]>
> plot(p)
Warning messages:
1: plotting the first 10 out of 27 attributes; use max.plot = 27 to plot all 
2: In min(x) : no non-missing arguments to min; returning Inf
3: In max(x) : no non-missing arguments to max; returning -Inf
4: In min(x) : no non-missing arguments to min; returning Inf
5: In max(x) : no non-missing arguments to max; returning -Inf

Thank you
best regards
Marcelo

**Comment by marcelocarvalhoalves** [comment]
The problem was solved by updating the sf.

**Comment by Robinlovelace** [comment]
Hi @marcelocarvalhoalves, thanks for reporting this and closing the issue. Next time you open an issue on GitHub, here or elsewhere, it helps to provide a reproducible example. Uploading a small part of your data can help others explore the problem and help with debugging quickly.
