### ISSUE TITLE
Error in sf-tidyverse combination

### ISSUE THREAD

**Issue by Jonkman1** [Robinlovelace/geocompr#540]
Dear all

I tried to rerun Robins script on Covid19 of 23 april 2020. It gave some errors. When I tried older scripts (which ran well before) gave the same erros messages (see my reproducable file). What is going on here, can someone help. Thanks, big best, -Harrie
[](url)

[Lovelace.Rmd.zip](https://github.com/Robinlovelace/geocompr/files/4652771/Lovelace.Rmd.zip)
lace.Rmd.zip]

**Comment by Robinlovelace** [comment]
Hi @Jonkman1 can you be more specific? Would help if you can show what system setup you have, e.g. by typing `sessionInfo()`. I get a result like this:

``` r
sessionInfo()
#> R version 3.6.3 (2020-02-29)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 18.04.4 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
#> 
#> locale:
#>  [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
#>  [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
#>  [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_3.6.3       magrittr_1.5         tools_3.6.3         
#>  [4] htmltools_0.4.0.9003 yaml_2.2.1           stringi_1.4.6       
#>  [7] rmarkdown_2.1.2      highr_0.8            knitr_1.28          
#> [10] stringr_1.4.0        xfun_0.13            digest_0.6.25       
#> [13] rlang_0.4.6.9000     evaluate_0.14
```

<sup>Created on 2020-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Please also show the specific lines of code that were failing and what you expected. In short, please provide a reproducible example of the type outlined here: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example/5963610#5963610

**Comment by Jonkman1** [comment]
Thanks, Robin. I updated everything (system and packages) and it worked. Thanks, big best, -Harrie
