### ISSUE TITLE
 sp 1.4.-2 warning proj4string(x) using raster::extract in 5.4.2

### ISSUE THREAD

**Issue by ALanguillaume** [Robinlovelace/geocompr#541]
When updating to sp 1.4-2 expect a new warning upon calling raster::extract() in section 5.4.2

Working on the Rstudio server provided by binder:

``` r
install.packages("sp")
```
``` r
library(sf)
library(raster)
srtm = raster(system.file("raster/srtm.tif", package = "spDataLarge"))
data("zion_points", package = "spDataLarge")
zion_points$elevation = raster::extract(srtm, zion_points)
```
The last line will yield:

``` r
Warning message:
In proj4string(x) : CRS object has comment, which is lost in output
```
Reinstalling sp version 1.4-1 mutes the warning.

``` r
devtools::install_version("sp", version = "1.4-1")
```
and thanks guys for all the great work !

**Comment by Robinlovelace** [comment]
Thank you for reporting. We'll take a look. I imagine it's just a case of resetting the CRS component of the `zion` object, right @Nowosad ?

**Comment by ALanguillaume** [comment]
If of any help here is the warning traceback, after converting warnings to errors `options(warn = 2)` :

``` r
17: doWithOneRestart(return(expr), restart)
16: withOneRestart(expr, restarts[[1L]])
15: withRestarts({
        .Internal(.signalCondition(simpleWarning(msg, call), msg, 
            call))
        .Internal(.dfltWarn(msg, call))
    }, muffleWarning = function() NULL)
14: .signalSimpleWarning("CRS object has comment, which is lost in output", 
        base::quote(proj4string(x)))
13: warning("CRS object has comment, which is lost in output")
12: proj4string(x)
11: proj4string(x)
10: projection(y)
9: methods::extends(class(x), "BasicRaster")
8: projection(y)
7: tolower(projection(y))
6: compareCRS(px, projection(y), unknown = TRUE)
5: .local(x, y, ...)
4: extract(x, y, ...)
3: extract(x, y, ...)
2: raster::extract(srtm, zion_points)
1: raster::extract(srtm, zion_points)
```
Calling directly ` proj4string(srtm)` does not throw any warning:
```
[1] "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
```

**Comment by Nowosad** [comment]
Hi @ALanguillaume - I cannot reproduce this issue on two computers: Fedora with sp 1.4-2 and (1) R 3.6, GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0 and (2) R 4.0, GEOS 3.8.1, GDAL 3.0.4, PROJ 6.3.2. 

What is your R version? raster version? Operating system? PROJ and GDAL versions?

**Comment by ALanguillaume** [comment]
Hi @Nowosad 
My local machine: Windows 10, R 4.0, GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1, raster 3.1-5, sp 1.4-2, sf 0.9-3, rgdal 1.5-10.
I did not mention that before because the same happen on the geocompr mybinder, which now is Ubuntu 20.04 , R 4.0,  GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1, raster 3.1-5, sp 1.4-2, sf 0.9-4, rgdal 1.5-10.

Note that on both systems reinstalling sp 1.4-1, will suppress the warning.

**Comment by Nowosad** [comment]
Can you try to use the development version of raster (I have raster 3.3-3)? I think there was a recent change in raster related to CRSs.

**Comment by ALanguillaume** [comment]
Okay, the new dev version of raster did silence the warning. Thanks guys. Closing here.
