### ISSUE TITLE
Reduce dependencies needed to build book

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#546]
With 50+ dependencies, some of which are used only in one chapter in code chunks that do not run, I think there is an incentive to move some of the `Imports` listed here to `Suggests`, to reduce build times: https://github.com/geocompr/geocompkg/blob/master/DESCRIPTION

**Comment by Robinlovelace** [comment]
One question for @Nowosad, any idea why GH actions is still spending ages installing mapdeck and other unnused packages, even after I demoted them to Suggests here https://github.com/geocompr/geocompkg/pull/16/files ?

On https://github.com/Robinlovelace/geocompr/pull/549 there is this:


```
Remotes: 
    # geocompr/geocompkg, # old
    geocompr/geocompkg@reduce-deps, # new

```

But mapdeck and friends are still being installed, pushing build times to over an hour!:

https://github.com/Robinlovelace/geocompr/runs/768446869#step:10:2712

**Comment by Robinlovelace** [comment]
Update: I think the above commit is the answer and hopefully the solution.

**Comment by Robinlovelace** [comment]
Still seems to insist on installing mapdeck: https://github.com/Robinlovelace/geocompr/runs/768582519#step:10:256

**Comment by Robinlovelace** [comment]
OK just realised: `tmap` itself indirectly depends on mapdeck, plus it's a useful package. Removing pROC and mlr and a few others will be worthwhile though. `tmap` depends on `leafem` which in turn depends on `mapdeck` it seems: https://cran.r-project.org/web/packages/leafem/index.html

**Comment by Robinlovelace** [comment]
Closing for now as it's done. However, the book still has loads of dependencies including mapdeck, surprisingly indirectly required by tmap, and there is an unmerged pr in the geocompkg repo. Can you take a look @Nowosad ? I have been a bit brutal in removing dependencies and setting `eval=FALSE` in C9 C11 and C14. Apologies @jannes-m . I hope to get more (if not all) chunks evaluating in those chapters in future versions but that's for another day and another issue.

**Comment by Nowosad** [comment]
@Robinlovelace there are two PR in the geocompkg repo. Which is the good one?

**Comment by Robinlovelace** [comment]
Good point, only one good PR now. The `purge-deps` branch was just a test.

**Comment by Robinlovelace** [comment]
And as a related point think about dependencies led to this: https://github.com/r-spatial/leafem/pull/21

**Comment by Nowosad** [comment]
Neat

**Comment by Nowosad** [comment]
@Robinlovelace please look at https://github.com/Robinlovelace/geocompr/runs/788038868?check_suite_focus=true - "Failed with error:  'there is no package called 'data.table''"

**Comment by Robinlovelace** [comment]
This is the error I see:

```
The OSRM server returned an error:
##[error]Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//IETF/
                     (right here) ------^
```

**Comment by Robinlovelace** [comment]
https://github.com/Robinlovelace/geocompr/runs/788038868?check_suite_focus=true#step:10:7706

**Comment by Robinlovelace** [comment]
Correction, I see what you mean now: https://github.com/Robinlovelace/geocompr/runs/788038868?check_suite_focus=true#step:10:7694

**Comment by Robinlovelace** [comment]
I realise now: just adding `quietly = TRUE` fixes it. That is strange!

https://github.com/ropensci/stplanr/issues/408

**Comment by Robinlovelace** [comment]
Will submit to CRAN asap.

**Comment by Robinlovelace** [comment]
Heads-up @Nowosad: **stplanr** 0.6.1 is now on CRAN and the dependency on **data.table** should have been removed.

**Comment by Robinlovelace** [comment]
Fixed, finally!
