### ISSUE TITLE
Create exercises section for chapter 3

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#55]
E.g. using a new dataset.

**Comment by Nowosad** [comment]
New dataset idea:
- Contiguous United States spatial data (with a few attributes)
- Contiguous United States non-spatial data (to show how joins work)

**Comment by Robinlovelace** [comment]
Sounds good.

**Comment by Nowosad** [comment]
https://github.com/Robinlovelace/geocompr/commit/fa0f9c52e5a046c1aee084317e549ade24b9aa53

**Comment by Nowosad** [comment]
@Robinlovelace - I've added the exercises - http://robinlovelace.net/geocompr/attr.html#exercises-3. Feel free to add/change anything.

**Comment by Robinlovelace** [comment]
These are excellent. I like the progression - they start easy but become harder. I'll make a few more changes and then close this issue.

**Comment by Nowosad** [comment]
@Robinlovelace Feel free to reopen
