### ISSUE TITLE
Error message on dev version of tmap

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#556]
When building the book locally with the development version of **tmap** installed I get this error message:

```
Quitting from lines 762-763 (02-spatial-data.Rmd) 
Error: Invalid color specification. The available raster variables are: "srtm.tif".
```

I'm not sure that this is an issue with **tmap** or even if it will cause the CI build to fail, but seems like a raster visualisation issue to me. Are you up for taking a look @Nowosad ?

**Comment by Nowosad** [comment]
I am checking it right now.

**Comment by Nowosad** [comment]
I think we were using a temporary code there. I will fix that in a few minutes and will create a new PR.

**Comment by Nowosad** [comment]
https://github.com/Robinlovelace/geocompr/pull/557

**Comment by Robinlovelace** [comment]
:+1:
