### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#564]
Not had a chance to investigate but should get a chance next week. Any ideas @Nowosad ?

**Comment by Nowosad** [comment]
I will take a look at it sometime during the weekend,

**Comment by Robinlovelace** [comment]
Looks like a CRS issue in a tmap plot https://github.com/Robinlovelace/geocompr/runs/906426034?check_suite_focus=true#step:10:861

```
label: raster-intro-plot2 (with options) 
List of 3
 $ echo   : logi FALSE
 $ fig.cap: chr "Examples of continuous and categorical rasters."
 $ warning: logi FALSE

proj_create: several objects matching this name: Nouvelle Triangulation Francaise Paris grades to 4326, Nouvelle Triangulation Francaise Paris grades to 4326
Quitting from lines 762-763 (02-spatial-data.Rmd) 
Error in CPL_lwgeom_transform(x, crs) : 
  st_lwgeom_transform: one of the proj strings is invalid
```

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/88452351-e3f13800-ce55-11ea-9d6f-540e15809513.png)

**Comment by Robinlovelace** [comment]
One for the `tmap` issue tracker?

**Comment by Nowosad** [comment]
Maybe... firstly, it would be good to reproduce this error...

**Comment by Nowosad** [comment]
I cannot...
@mtennekes do you have any idea why this kind of error could occur?

**Comment by Robinlovelace** [comment]
Additional issue: it still relied on `RQGIS`. Fixed by replacing all instances as follows:

```zsh
sd 'package = "RQGIS"' 'package = "spDataLarge"' $(fd .)
```

**Comment by Robinlovelace** [comment]
https://github.com/Robinlovelace/geocompr/pull/565/commits/b2b8e5db61e310296581530cba7be3df4a45c189

**Comment by Robinlovelace** [comment]
Finally sorted :tada: This is still and issue though:

https://github.com/Robinlovelace/geocompr/issues/564#issuecomment-663823526

**Comment by Robinlovelace** [comment]
?

**Comment by Nowosad** [comment]
We still need to fix https://github.com/Robinlovelace/geocompr/issues/564#issuecomment-663823526. - I am keeping it open until we have it fixed.

**Comment by Robinlovelace** [comment]
That's a separate issue. I suggest either renaming this issue or, IMO better, open a separate issue related to the `tmap` issue. This may not be the best place to raise that issue though if we can create a minimal reproducible example, it seems like a `tmap` or maybe even `sf`/`PROJ` issue to me...

**Comment by Nowosad** [comment]
https://github.com/Robinlovelace/geocompr/issues/566
