### ISSUE TITLE
Issues with Binder

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#570]
https://github.com/rocker-org/binder/issues/42#issuecomment-695664168

**Comment by Robinlovelace** [comment]
It's down this morning: 

![image](https://user-images.githubusercontent.com/1825120/94119082-4eb6f380-fe46-11ea-8e25-44de084e9145.png)

Is this also down for you @Nowosad ?

**Comment by Robinlovelace** [comment]
This link seems to spin-up but does not deploy: https://mybinder.org/v2/gh/robinlovelace/geocompr/master?urlpath=rstudio

**Comment by Nowosad** [comment]
Yep, I have the same error.

**Comment by Robinlovelace** [comment]
Heads-up @Nowosad and @jannes-m could you try this out: https://rstudio.cloud/project/1642300

I think most of the book can be tested there in browser but not sure if others can access it. If so I reckon it's worth adding a badge. Still trying to fix binder issues...

**Comment by Nowosad** [comment]
I was able to access it (after login):

![2020-10-31_06-48](https://user-images.githubusercontent.com/3457131/97772215-2efda400-1b45-11eb-9f76-f24d29b280a5.png)

**Comment by jannes-m** [comment]
Yes, I can access it, too. Sent from my Huawei phone-------- Original message --------From: Robin <notifications@github.com>Date: Sat, 31 Oct 2020, 01:05To: Robinlovelace/geocompr <geocompr@noreply.github.com>Cc: Jannes Muenchow <malnamalja@gmx.de>, Mention <mention@noreply.github.com>Subject: Re: [Robinlovelace/geocompr] Issues with Binder (#570)
Heads-up @Nowosad and @jannes-m could you try this out: https://rstudio.cloud/project/1642300
I think most of the book can be tested there in browser but not sure if others can access it. If so I reckon it's worth adding a badge. Still trying to fix binder issues...

**Comment by Robinlovelace** [comment]
Many thanks guys, the updated texts is as follows:
[![Launch Rstudio Binder](http://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/robinlovelace/geocompr/master?urlpath=rstudio)

You can also have a play with the repo in RStudio Cloud by clicking on this link (requires log-in):

[![Launch Rstudio Cloud](images/cloud.png)](https://rstudio.cloud/project/1642300)


Any further tests/comments/changes very welcome.

**Comment by Robinlovelace** [comment]
Interesting observation - the rendering is different when you build the book in binder, not sure why:

![image](https://user-images.githubusercontent.com/1825120/97809803-1dacb880-1c67-11eb-8bb4-73036df080f5.png)

Heads-up all, especially @Nowosad, I had to make these changes for it to build in binder, any objections to merging this? https://github.com/Robinlovelace/geocompr/pull/586

**Comment by Nowosad** [comment]
Hi @Robinlovelace, I am not a very active user of Binder, therefore, if you are happy with the changes - so am I. 

Regarding the rendering style - I have no idea. Can you explain me how to reproduce this issue?

**Comment by Robinlovelace** [comment]
Hi @Nowosad to reproduce the issue, click here and build the book: https://mybinder.org/v2/gh/robinlovelace/geocompr/master?urlpath=rstudio

**Comment by Nowosad** [comment]
Thanks - I followed your guidelines and get a proper results (see below). To create an html version, I just run `make html` in the RStudio terminal. 

![2020-11-02_12-13](https://user-images.githubusercontent.com/3457131/97862007-ef7db600-1d04-11eb-8c9e-71e10d235d1c.png)

**Comment by Robinlovelace** [comment]
Interesting... May have just been a one-off glitch. Good to know we can reproduce the entire book in-browser with Binder in any case, thanks for testing.

**Comment by Robinlovelace** [comment]
Since the latest commit it's working, but without plots. See 
![image](https://user-images.githubusercontent.com/1825120/134740523-05690800-4acc-4144-921a-6f639ee5da5b.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/134745706-97ef6921-be3c-4dbb-bc99-9d0a4771d0d6.png)


Latest commit from r-conda.

**Comment by Robinlovelace** [comment]
Latest Binder build with a few extra install.packages() calls allowed the entire book to built in Binder :tada: 

![image](https://user-images.githubusercontent.com/1825120/134786902-a2eb058d-138b-42aa-b4aa-3c42dbfff46e.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/134802314-6dd368c7-f5eb-4cd7-b8ff-428dfa93954c.png)
