### ISSUE TITLE
github actions tibble rendering

### ISSUE THREAD

**Issue by mps9506** [Robinlovelace/geocompr#571]
Hi,

I noticed in the rendered book, that tibbles and sf data frames are rendered with some encodings that don't render properly in the code chunks. For example, see section 2.2.1:
```r
world_mini = world[1:2, 1:3]
world_mini
#> Simple feature collection with 2 features and 3 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -180 ymin: -18.3 xmax: 180 ymax: -0.95
#> geographic CRS: WGS 84
#> [90m# A tibble: 2 x 4[39m
#>   iso_a2 name_long continent                                                geom
#>   [3m[90m<chr>[39m[23m  [3m[90m<chr>[39m[23m     [3m[90m<chr>[39m[23m                                      [3m[90m<MULTIPOLYGON [°]>[39m[23m
#> [90m1[39m FJ     Fiji      Oceania   (((180 -16.1, 180 -16.6, 179 -16.8, 179 -17, 179 -…
#> [90m2[39m TZ     Tanzania  Africa    (((33.9 -0.95, 34.1 -1.06, 37.7 -3.1, 37.8 -3.68, …
```

I believe adding `crayon.enabled = NULL` to https://github.com/Robinlovelace/geocompr/blob/f6a05cc9cd077d14958ef3364633263c2aac7a7b/code/before_script.R#L19 fixes this for me, but i don't know if that is the best solution.

I'm not an expert on this encoding stuff. This might also be a system/browser issue. I'm using Windows and Firefox to view the built book.

**Comment by Robinlovelace** [comment]
Thanks for the report. Confirmed one Ubuntu Firefox looking here: https://geocompr.robinlovelace.net/spatial-class.html#intro-sf

I think your solution sounds reasonable, wonder if there is a need for an upstream solution, e.g. for that setting to the default for rmarkdown documents. May be worth asking the developers of the `crayon` package. Great diagnosis btw, I didn't know that was happening, let alone how to fix it!

**Comment by mps9506** [comment]
This is a pretty deep rabbit hole with a few issues already listed on `crayon`, so I hesitate to open another issue there.  `render_book()` locally or using Windows with Github Actions does produce a properly rendered tibble. So, while `options(crayon.enabled = NULL)` would be a quick fix, I'm wondering if something in the workflow yaml or upstream actions might have an impact. 
If you want to leave this open, I am developing a toy repo to try and isolate the cause.

**Comment by Robinlovelace** [comment]
Great, thanks for the follow-up. Two main options are to close quickly but keep this open in the hope of a 'proper' fix or to leave open and do nothing for now, to revisit as/when a 'proper' solution becomes clear. `yaml` fixes could go into the `r-lib/actions` repo is another potential upstream solution.

Given that this is not a major issue I have linked this to the 2nd edition milestone with the aim of fixing it in one way or another by the end of the year. Sound like are reasonable plan? Any other follow-up comments/suggestions from anyone are welcome in the meantime.

**Comment by Robinlovelace** [comment]
Update, I've created a PR representing the quick-fix solution, not tested yet but can merge if that seems like the best option: https://github.com/Robinlovelace/geocompr/pull/572

**Comment by mps9506** [comment]
🤦‍♂️ Turns out that `r-lib/actions/setup-r` has an argument (not sure if that is the right terminology for yaml?) to control this option and it is `TRUE` by default:
https://github.com/r-lib/actions/blob/8d3872345ff5ace500bdbf7c5835618f3fa6dcc9/setup-r/action.yml#L14-L16 

So updating the following
https://github.com/Robinlovelace/geocompr/blob/0c003c385326f06d2243d1c6eca8f8ceeeb8e12f/.github/workflows/master.yaml#L26-L31
 as:
```yml
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'
          crayon.enabled: 'FALSE' 
```
will set the option in the actions build only and won't impact builds on local or other platforms. I wanted to make sure this worked, so I setup a play repo:
https://github.com/mps9506/rendertest
with a rendered book: https://mps9506.github.io/rendertest/
and pdf for good measure: https://github.com/mps9506/rendertest/blob/gh-pages/_main.pdf

**Comment by Robinlovelace** [comment]
Excellent solution by the looks of it, look forward to testing!

**Comment by Robinlovelace** [comment]
Great news, seems to be fixed :tada: 

![image](https://user-images.githubusercontent.com/1825120/94192047-4db5ae80-fea6-11ea-86ab-34f60146c58a.png)


Should this go into a PR in `r-lib/actions` and the bookdown action, if it's not already? Many thanks for spotting this and finding out a future-proof solution @mps9506.
