### ISSUE TITLE
UTM Datum

### ISSUE THREAD

**Issue by BeBrian** [Robinlovelace/geocompr#574]
Dear Robin,
in chapter 6.3. you state that "All UTM projections have the same datum (WGS84) [...]". If I understand this right I think this is not correct. UTM projections may have different datums, e.g. in Europe a datum often used is ETRS89 for UTM projection (e.g. ETRS89 / UTM zone 32N)
Thanks for your great book and regards

**Comment by Robinlovelace** [comment]
Thanks for raising this issue @BeBrian. I am not an expert in this field and think you may be right. Do you have a source to support that? If we can add a link to a good research on UTM datums that will further strengthen the section.

**Comment by BeBrian** [comment]
Hey @Robinlovelace, basically any Cartographic or GIS - Textbook. I will look one up which might be available online. But for a quick validation, just type utm in the search mask of https://spatialreference.org and be overburdened by the amount of CRSs that uses UTM as the projection.

**Comment by Robinlovelace** [comment]
Thanks for the follow-up. One of the first CRSs that I found following your suggestion was this:

```
PROJCS["WGS_1984_UTM_Zone_17N",
    GEOGCS["GCS_WGS_1984",
        DATUM["WGS_1984",
            SPHEROID["WGS_1984",6378137,298.257223563]],
        PRIMEM["Greenwich",0],
        UNIT["Degree",0.017453292519943295]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["False_Easting",500000],
    PARAMETER["False_Northing",0],
    PARAMETER["Central_Meridian",-81],
    PARAMETER["Scale_Factor",0.9996],
    PARAMETER["Latitude_Of_Origin",0],
    UNIT["Meter",1]]
```

https://spatialreference.org/ref/sr-org/13/prettywkt/

That seems to have a WGS datum, right? Assuming the second column in this table is the datum you're right, a wide range of datums are used, although I'm not 100% sure what this list represents (and I see there are many pages, loads of CRSs as you say):

![image](https://user-images.githubusercontent.com/1825120/94678602-ad80df00-0316-11eb-9c9f-86d81950cef8.png)

How would you re-word that sentence, or would it be best just to remove that incorrect statement?

Very grateful to you for identifying this issue, hope to get it resolved soon.

**Comment by Darrellc1991** [comment]
Hey all - Not quite an expert on this aspect, but based on what I'm
skimming of the exchange, it might be as simple noting that it saves it as
WGS84 "by default".

**Comment by Robinlovelace** [comment]
Thanks for the follow-up. Given that I'm not sure what 'default' means in this context I've decided to play it safe by removing reference to UTM datums altogether. The sentence now reads:

> UTM EPSG codes run sequentially from 32601 to 32660 for northern hemisphere locations and from 32701 to 32760 for southern hemisphere locations.

Any further comments/suggestions very welcome and heads-up @Nowosad and @jannes-m if you have any comments on this please chime in.

**Comment by Nowosad** [comment]
I am fine with the change. Thanks!
