### ISSUE TITLE
Typo in preface

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#575]
In the preface it says 

> Academics and post-graduate students working on projects in fields including Geology, Regional Science, Biology and Ecology, Agricultural Sciences (precision farming), Archaeology, Epidemiology, Transport Modeling, and broadly defined Data Science which require the power and flexibility of R for their research 

The issue is that the noun "Academics" does not match the pronoun "which", it should be "who". Furthermore, the sentence is rather long and clunky and could be improved in otherways, e.g.: 

> Academics and post-graduate students working with geographic data --- in fields such as Geology, Regional Science, Biology and Ecology, Agricultural Sciences, Archaeology, Epidemiology, Transport Modeling, and broadly defined Data Science --- who require the power and flexibility of R for their research 

See here for the issue in the book: https://geocompr.robinlovelace.net/preface.html

See here to edit the file and fix it (leaving this open as it's a good 'first pull request): https://github.com/Robinlovelace/geocompr/edit/master/index.Rmd

**Comment by VishalAmbavade** [comment]
@Robinlovelace, I would like to work on this issue. Can you please provide more information about the same?

**Comment by Robinlovelace** [comment]
Great. Please edit this file: https://github.com/Robinlovelace/geocompr/edit/master/index.Rmd

Good luck with it.

**Comment by VishalAmbavade** [comment]
@Robinlovelace I have made few changes to the file. Please check it and let me know if any further details are required.

**Comment by Robinlovelace** [comment]
Looking at it now...
