### ISSUE TITLE
Vulnerability to external file

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#576]
This isn't a reliable endpoint: https://biogeo.ucdavis.edu/data/climate/worldclim/1_4/grid/cur/prec_10m_bil.zip.

I think it's making builds fail.

**Comment by Nowosad** [comment]
I think it is a fairly new issue - https://github.com/rspatial/raster/issues/169 and I hope it is going to be fixed soon.

**Comment by Robinlovelace** [comment]
I've uploaded a version of it here: https://github.com/Robinlovelace/geocompr/releases/download/1.2/prec_10m_bil.zip
