### ISSUE TITLE
How to make a facetted map regions within an country, with the rest of the country 'greyed out'?

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#579]
I have just found a reproducible solution to this problem that I thought worth posting here in case it's of use for others, in relation to the visualization chapter:

``` r
library(tidyverse)
library(tmap)
library(rnaturalearth)
uk = rnaturalearth::ne_countries(scale = 50, country = "United Kingdom", returnclass = "sf")
plot(uk)
#> Warning: plotting the first 10 out of 63 attributes; use max.plot = 63 to plot
#> all
```

![](https://i.imgur.com/clLPpwX.png)

``` r
pct_zones = pct::get_pct(geography = "msoa", layer = "z", national = TRUE)
#> Warning in CPL_crs_from_input(x): GDAL Message 1: +init=epsg:XXXX syntax is
#> deprecated. It might return a CRS with a non-EPSG compliant axis order.
sf::st_crs(pct_zones) = 4326
plot(pct_zones[c("bicycle", "foot", "car_driver")])
```

![](https://i.imgur.com/VVDs8oP.png)

``` r
pct_zones_en = pct_zones %>% 
  filter(str_detect(string = geo_code, pattern = "E"))
pct_zones_boundary = sf::st_union(pct_zones_en) %>% 
  sf::st_buffer(dist = 0.001)
#> Warning in st_buffer.sfc(., dist = 0.001): st_buffer does not correctly buffer
#> longitude/latitude data
#> dist is assumed to be in decimal degrees (arc_degrees).
plot(pct_zones_boundary)
```

![](https://i.imgur.com/wJx5pWL.png)

``` r
tm_shape(uk, bbox = sf::st_bbox(pct_zones)) +
  tm_polygons() +
  tm_shape(pct_zones_en) +
  tm_fill(c("bicycle", "foot", "car_driver")) +
  tm_shape(pct_zones_boundary) +
  tm_borders()
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
#> Some legend labels were too wide. These labels have been resized to 0.55, 0.55. Increase legend.width (argument of tm_layout) to make the legend wider and therefore the labels larger.
#> Some legend labels were too wide. These labels have been resized to 0.55, 0.55, 0.55, 0.55. Increase legend.width (argument of tm_layout) to make the legend wider and therefore the labels larger.
#> Some legend labels were too wide. These labels have been resized to 0.55, 0.55, 0.55, 0.55, 0.55, 0.55. Increase legend.width (argument of tm_layout) to make the legend wider and therefore the labels larger.
```

![](https://i.imgur.com/IwdefLj.png)

<sup>Created on 2020-10-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
In case you get errors such as

```
  invalid crs: +proj=longlat +init=epsg:4326 +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0
```

I suggest setting the CRS for every object, e.g.:

```
sf::st_crs(uk) = 4326
```

**Comment by eugenividal** [comment]
I am sorry, but It did not work for me @Robinlovelace. See below: 

> sf::st_crs(uk) = 4326
> 
> pct_zones = pct::get_pct(geography = "msoa", layer = "z", national = TRUE)
Error in st_crs.character(x@projargs) : 
  invalid crs: +proj=longlat +init=epsg:4326 +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0

**Comment by Robinlovelace** [comment]
Sorry to hear @eugenividal, thanks for the update. Have you tried installing the most recent versions of sf and tmap? If that does not fix it it may be GDAL version issue - see here for info on how to update GDAL on 18.04: https://rtask.thinkr.fr/installation-of-r-3-5-on-ubuntu-18-04-lts-and-tips-for-spatial-packages/

And here for a good tutorial for Ubuntu 20.04: https://rtask.thinkr.fr/installation-of-r-4-0-on-ubuntu-20-04-lts-and-tips-for-spatial-packages/

Hope that helps, keep us posted!

**Comment by eugenividal** [comment]
Muchas gracias @Robinlovelace ! It's working now 🚀

**Comment by Robinlovelace** [comment]
:rocket: :rocket: Fantastic!
