### ISSUE TITLE
Packages depends by time

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#58]
https://twitter.com/jakub_nowosad/status/880418742748012544

**Comment by Robinlovelace** [comment]
Any update on this? Otherwise we can track it by storing the data (that's actually what we're doing in the git history of the .csv file).

**Comment by Nowosad** [comment]
No update yet. I just (10 minutes ago) came back from a conference. I would try to work on it in the next few weeks.

**Comment by Nowosad** [comment]
It looks like a very time consuming project. I think that there are more important things to do now...

**Comment by Robinlovelace** [comment]
Agreed, cheers for closing.
