### ISSUE TITLE
Improve example app in the visualisation chapter

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#584]
The shiny app in Chapter 8 isn't particularly informative: https://geocompr.robinlovelace.net/adv-map.html#mapping-applications

![image](https://user-images.githubusercontent.com/1825120/97105131-b0ba8100-16b0-11eb-9bcb-c652f8ea3805.png)

Any ideas of an app that would be more interesting? I think something transport related, perhaps related to the London cycle hire scheme linked to earlier in the chapter could be useful.

**Comment by Nowosad** [comment]
Hi @Robinlovelace - my thinking is the same. It would be good to have an app that uses some other data from the book. Based on the cycle hire data, we could for example, make an app that asks for coordinates and returns top 5 closest stations. It could also have some additional filters (e.g., I have a large group of friends, so I need at least 6 bikes)...

**Comment by Robinlovelace** [comment]
+1 to that idea.

**Comment by KiranmayiV** [comment]
I had a go at this, the app is here [https://github.com/KiranmayiV/CycleStations-London/blob/main/CycleHire_London.R](https://github.com/KiranmayiV/CycleStations-London/blob/main/CycleHire_London.R). It looks like this:
<img width="1280" alt="Screen Shot 2021-01-01 at 12 07 53 pm" src="https://user-images.githubusercontent.com/6985788/103431790-0881e500-4c2a-11eb-9d3f-7ea51db47137.png">

If it seems ok would be happy to contribute or make changes as required.

**Comment by Robinlovelace** [comment]
Hi @KiranmayiV, thanks for sharing and the offer of support. Seems OK and yes please do make a PR, let me know if you have any questions on that and look forward to seeing it updated in the book!
