### ISSUE TITLE
Show how to change the projection center of a WGS84 map in the book, reprojecting data chapter

### ISSUE THREAD

**Issue by PanfengZhang** [Robinlovelace/geocompr#591]

**Comment by Robinlovelace** [comment]
Do have a reproducible example to demonstrate what you mean and what you're hoping to achieve @PanfengZhang ?

**Comment by PanfengZhang** [comment]
> Do have a reproducible example to demonstrate what you mean and what you're hoping to achieve @PanfengZhang ?

Thank you very much.
I want to convert the projection center from the longitude/latitude of (0, 0) to (148, 0), the example shown as below.

rm(list = ls())
library(spData)
library(ggplot2)
library(sf)

crs1 = "+proj=longlat +datum=WGS84"
# world comes from spData package
world <- st_union(world) # returns a single world map without countries' border
ggplot() +
  geom_sf(data = world) +
  coord_sf(expand = FALSE, crs = crs1) +
  theme_bw()

crs2 = "+proj=longlat +lon_0=148 +lat_0=0 +datum=WGS84"
ggplot() +
  geom_sf(data = world) +
  coord_sf(expand = FALSE, crs = crs2) +
  theme_bw()

But the projection center is still (0, 0) of longitude/latitude, as shown in the following figure.
![Rplot](https://user-images.githubusercontent.com/20354811/102842162-4c623680-4441-11eb-9d95-4ccbf3e6afb1.png)

I hope to achieve the similar effect as shown below
![change_projection_center_NCL](https://user-images.githubusercontent.com/20354811/102842321-a95dec80-4441-11eb-831c-5b80ef60279e.png)

This figure was generated by the NCL language (http://www.ncl.ucar.edu/). The NCL scripts was shown as below.

wkstype = "png"
wks     = gsn_open_wks (wkstype, "change_projection_center_NCL")  
mres                       = True              ; plot mods desired
;change the projection and projection center
mres@mpProjection           = "CylindricalEquidistant"; "Robinson"; "Mollweide"; 
mres@mpCenterLatF           = 0
mres@mpCenterLonF           = 148
plot = gsn_csm_map(wks, mres)

**Comment by Robinlovelace** [comment]
This is a good question and I think it's worth adding an example to Chapter 6 demonstrating how to do it. I think the `lon_0=-74` bit in the command below moves the centrepoint of the map. 


```r
world_laea2 = st_transform(world,
                           crs = "+proj=laea +x_0=0 +y_0=0 +lon_0=-74 +lat_0=40")
```

This should also work for other types of projection. I suggest re-reading this chapter and trying different `crs` settings: https://geocompr.robinlovelace.net/reproj-geo-data.html

@Nowosad wrote much of that section and may have other suggestions.

**Comment by PanfengZhang** [comment]
> This is a good question and I think it's worth adding an example to Chapter 6 demonstrating how to do it. I think the `lon_0=-74` bit in the command below moves the centrepoint of the map.
> 
> ```r
> world_laea2 = st_transform(world,
>                            crs = "+proj=laea +x_0=0 +y_0=0 +lon_0=-74 +lat_0=40")
> ```
> 
> This should also work for other types of projection. I suggest re-reading this chapter and trying different `crs` settings: https://geocompr.robinlovelace.net/reproj-geo-data.html
> 
> @Nowosad wrote much of that section and may have other suggestions.

**Comment by PanfengZhang** [comment]
> This is a good question and I think it's worth adding an example to Chapter 6 demonstrating how to do it. I think the `lon_0=-74` bit in the command below moves the centrepoint of the map.
> 
> ```r
> world_laea2 = st_transform(world,
>                            crs = "+proj=laea +x_0=0 +y_0=0 +lon_0=-74 +lat_0=40")
> ```
> 
> This should also work for other types of projection. I suggest re-reading this chapter and trying different `crs` settings: https://geocompr.robinlovelace.net/reproj-geo-data.html
> 
> @Nowosad wrote much of that section and may have other suggestions.

Thank you. I tried this transform and the result was shown as follows.
[Rplot.pdf](https://github.com/Robinlovelace/geocompr/files/5729725/Rplot.pdf)


I tried other methods based on the  cartographic projection (https://proj.org/usage/projections.html), the result was shown as belows.
crs2 = "+proj=longlat +datum=WGS84 +pm=148E"
ggplot() +
  geom_sf(data = world) +
  coord_sf(expand = FALSE, crs = crs2) +
  theme_bw()
![Rplot02](https://user-images.githubusercontent.com/20354811/102887118-4b58f580-4491-11eb-9a36-4f7d6f5bdaeb.jpg)

and, if the coordinate reference system is:
crs2 = "+proj=longlat +datum=WGS84 +pm=120E", 
then the result figure is
![Rplot03](https://user-images.githubusercontent.com/20354811/102887277-9b37bc80-4491-11eb-8081-85eb84a03f09.jpg)

Although the projection center is converted correctly, it produces confusing results.

**Comment by jannes-m** [comment]
Have a look at the section Example of a failed projection [here](https://mgimond.github.io/Spatial/coordinate-systems-in-r.html) and/or use another projection as already suggested by @Robinlovelace.

**Comment by Robinlovelace** [comment]
Here's a crude solution that removes everything near the map edge in the new projection:

``` r
rm(list = ls())
library(spData)
library(ggplot2)
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0

w1 = spData::world
lon_center = -74
lon_edge = lon_center + 180
matrix_center = matrix(c(lon_edge, lon_edge, 90, -90), ncol = 2)
line_center = sf::st_linestring(matrix_center)
line_center_sfc = st_sfc(line_center, crs = st_crs(w1))
polygon_cent = st_buffer(line_center_sfc, dist = 1)
#> Warning in st_buffer.sfc(line_center_sfc, dist = 1): st_buffer does not
#> correctly buffer longitude/latitude data
#> dist is assumed to be in decimal degrees (arc_degrees).
plot(w1$geom)
plot(polygon_cent, add = TRUE)
```

![](https://i.imgur.com/Vxva5Ow.png)

``` r
w2 = sf::st_difference(w1, polygon_cent)
#> although coordinates are longitude/latitude, st_difference assumes that they are planar
#> Warning: attribute variables are assumed to be spatially constant throughout all
#> geometries
plot(w2$geom)
```

![](https://i.imgur.com/M8XyM6u.png)

``` r
crs = "+proj=moll +lon_0=-74"
w3 = st_transform(w2, crs = crs)

ggplot() +
  geom_sf(data = w3) +
  coord_sf(expand = FALSE) +
  theme_bw()
```

![](https://i.imgur.com/91imaoD.png)

``` r
w3 = w3[!grepl(pattern = "Antarctica", x = w3$name_long), ]

ggplot() +
  geom_sf(data = w3) +
  coord_sf(expand = FALSE) +
  theme_bw()
```

![](https://i.imgur.com/RAzLlb4.png)

<sup>Created on 2020-12-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by PanfengZhang** [comment]
> Have a look at the section Example of a failed projection [here](https://mgimond.github.io/Spatial/coordinate-systems-in-r.html) and/or use another projection as already suggested by @Robinlovelace.

Thank you very much!

**Comment by PanfengZhang** [comment]
> Here's a crude solution that removes everything near the map edge in the new projection:
> 
> ```r
> rm(list = ls())
> library(spData)
> library(ggplot2)
> library(sf)
> #> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
> 
> w1 = spData::world
> lon_center = -74
> lon_edge = lon_center + 180
> matrix_center = matrix(c(lon_edge, lon_edge, 90, -90), ncol = 2)
> line_center = sf::st_linestring(matrix_center)
> line_center_sfc = st_sfc(line_center, crs = st_crs(w1))
> polygon_cent = st_buffer(line_center_sfc, dist = 1)
> #> Warning in st_buffer.sfc(line_center_sfc, dist = 1): st_buffer does not
> #> correctly buffer longitude/latitude data
> #> dist is assumed to be in decimal degrees (arc_degrees).
> plot(w1$geom)
> plot(polygon_cent, add = TRUE)
> ```
> 
> ![](https://camo.githubusercontent.com/33f3ac43e027cad396351ab45f78b8ee54721f3a652391e10390b38381f64c98/68747470733a2f2f692e696d6775722e636f6d2f56787661354f772e706e67)
> 
> ```r
> w2 = sf::st_difference(w1, polygon_cent)
> #> although coordinates are longitude/latitude, st_difference assumes that they are planar
> #> Warning: attribute variables are assumed to be spatially constant throughout all
> #> geometries
> plot(w2$geom)
> ```
> 
> ![](https://camo.githubusercontent.com/15a955f819c1b454865a5f5df2bf23c7b5351421691dd473b85da222c723a620/68747470733a2f2f692e696d6775722e636f6d2f4d3858794d36752e706e67)
> 
> ```r
> crs = "+proj=moll +lon_0=-74"
> w3 = st_transform(w2, crs = crs)
> 
> ggplot() +
>   geom_sf(data = w3) +
>   coord_sf(expand = FALSE) +
>   theme_bw()
> ```
> 
> ![](https://camo.githubusercontent.com/1b9966d19133bc032791b135ed05b7d961cf615cc2e1a9f72b91a7cbe95a7d50/68747470733a2f2f692e696d6775722e636f6d2f3931696d616f442e706e67)
> 
> ```r
> w3 = w3[!grepl(pattern = "Antarctica", x = w3$name_long), ]
> 
> ggplot() +
>   geom_sf(data = w3) +
>   coord_sf(expand = FALSE) +
>   theme_bw()
> ```
> 
> ![](https://camo.githubusercontent.com/3a9682d325ed593712304304579b6750241f5daebea688684f35b992b8b31edb/68747470733a2f2f692e696d6775722e636f6d2f52417a4c6c62342e706e67)
> 
> Created on 2020-12-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)

Thank you very much!
