### ISSUE TITLE
Ambiguous/misleading exercise in Chapter 3

### ISSUE THREAD

**Issue by zmbc** [Robinlovelace/geocompr#594]
[The Chapter 3 exercises](https://geocompr.robinlovelace.net/attr.html#exercises-1) include the following:

> 13. Calculate the change in median income between 2010 and 2015 for each state. Bonus: What was the minimum, average and maximum median income in 2015 for each region? What is the region with the largest increase of the median income?

[The solution](https://geocompr.github.io/geocompkg/articles/solutions03.html) says:

```
us_income_change = us_states %>%
  left_join(us_states_df, by = c("NAME" = "state")) %>%
  mutate(income_change = median_income_15 - median_income_10)

us_income_change_reg = us_income_change %>%
  group_by(REGION) %>%
  summarize(min_income_change = min(income_change),
            mean_income_change = mean(income_change),
            max_income_change = max(income_change))
```

This code, at the region level, calculates the unweighted mean (average) of the changes in median income within each constituent state. This is **not** the same thing as the change in median income across the whole region. In fact, I can't imagine it being a very useful metric at all, because a very small state like Wyoming's median income change affects the result the same as a very large state like California's.

I don't think it's possible to calculate the answer to how I intuitively interpreted the question--the change in median income across the whole region--from the available data.

**Comment by Robinlovelace** [comment]
Thanks for flagging this @zmbc. The point is to get people working with summary statistics, aggregating over categories, of a coarse regional geographic resolution in this example. I take your point about it not being the median income in each state. Is it rather the change in *mean median incomes per state*? And would using the population weighted 'mean median' improve the example? Or would you suggest using a different example altogether?

Open to ideas, this feedback is greatly appreciated.

**Comment by zmbc** [comment]
Yes, what is calculated by the code is the *average/mean change in state median incomes*. I doubt this is something that would need to be calculated for any actual use-case, but updating the question to use that language would unambiguously specify what to do (I cheated and looked at the answer because I was confused :smiley:).

I love the idea of calculating a region-level statistic because that feels like a very realistic thing to do. Unfortunately, this isn't possible with metrics that are reported as medians.

What do you think about going a totally different direction with the question to use poverty level statistics, since those are reported in absolute numbers?

The question could become:

> 13. Calculate the change in percentage of citizens living below the poverty level between 2010 and 2015 for each state. (Hint: See `?us_states_df` documentation on the poverty level columns.) Bonus: What was the minimum, average and maximum change in state poverty percentage for each region? What is the region with the largest decrease of overall poverty percentage?

The new answer to the question, in its entirety:

```diff
us_pov_pct_change = us_states %>%
  left_join(us_states_df, by = c("NAME" = "state")) %>%
  mutate(pov_pct_10 = (poverty_level_10 / total_pop_10) * 100, pov_pct_15 = (poverty_level_15 / total_pop_15) * 100) %>%
  mutate(pov_pct_change = pov_pct_15 - pov_pct_10)

us_pov_pct_change_reg = us_pov_pct_change %>%
  group_by(REGION) %>%
  summarize(min_state_pov_pct_change = min(pov_pct_change),
            mean_state_pov_pct_change = mean(pov_pct_change),
            max_state_pov_pct_change = max(pov_pct_change),
            region_pov_pct_10 = sum(poverty_level_10) / sum(total_pop_10),
            region_pov_pct_15 = sum(poverty_level_15) / sum(total_pop_15)) %>%
  mutate(region_pov_pct_change = region_pov_pct_15 - region_pov_pct_10)
#> `summarise()` ungrouping output (override with `.groups` argument)

us_pov_pct_change_reg %>%
  filter(region_pov_pct_change == min(region_pov_pct_change)) %>%
  pull(REGION) %>%
  as.character()
#> [1] "Norteast"
```

Let me know what you think -- it definitely adds some complexity. Might make sense to remove the first part of the bonus question.

**Comment by Nowosad** [comment]
Hi @zmbc , thanks for opening this issue and suggesting an improved exercise! 
Maybe the bonus question can be used as a separate exercise - what do you think about that?

**Comment by Robinlovelace** [comment]
I think this is a great suggestion, many thanks @zmbc. One thought: to make the first part easier could we make it about change in numbers? I think calculating percentage change is hard for R beginners and we want to make it as accessible as possible. The percentage could then be a bonus and then, as @Nowosad says, the bonus could become another question.

If  you're up for putting in a Pull Request implementing the change let us know @zmbc otherwise Jakub or I can give it a go.

**Comment by Robinlovelace** [comment]
Hi @zmbc your changes are now deployed and you're now a contributor to this open source project :tada: 

Do you have a Twitter handle? Can tag you in a follow-up Tweet saying thank you.

![image](https://user-images.githubusercontent.com/1825120/104812424-f4c5a980-57f9-11eb-8529-e7273ce6c902.png)

https://geocompr.robinlovelace.net/attr.html#exercises-1

**Comment by zmbc** [comment]
@Robinlovelace Nope, I don't have Twitter.

Thanks for your feedback and review of the changes! This is one of the friendliest open source projects I've ever contributed to :smiley:
