### ISSUE TITLE
How to split linestrings into segments with equal length

### ISSUE THREAD

**Issue by garethcao** [Robinlovelace/geocompr#596]
Deal All,

I am trying to split a linestring into multiple parts with equal length, while fail to find suitable command for it. To be more specific, I have a shpfile of a river and the whole river is one polyline in the current data. I want split it into 10 segments with equal length.

I know how to achieve it in ArcGIS while fail to replicate the same function in R. I have experimented with st_segmentize, but it seems that it could not fulfill the task described above. Do you have any suggestions for it? Of course, I fully understand that there may be no function that could solve this problem directly and I have to do it in an indirect way. Any hints for such a method would also be much helpful.

Thanks a lot!

**Comment by Nowosad** [comment]
Hi @garethcao, could you prepare some reproduciable example containing some data?

**Comment by garethcao** [comment]
> Hi @garethcao, could you prepare some reproduciable example containing some data?

[Boundary.zip](https://github.com/Robinlovelace/geocompr/files/5840935/Boundary.zip)

Please kindly check the attached files for a river. I was just trying to split it into 10 segments with equal length. Thanks so much for your reply!

**Comment by Robinlovelace** [comment]
Hi @garethcao this is actually a great use case of the new **qgisprocessing** package that I've discussed with @jannes-m in relation to the GIS Bridges chapter. https://geocompr.robinlovelace.net/gis.html

See reproducible code here for how it works (requires QGIS to be installed): https://github.com/paleolimbot/qgisprocess/issues/26

Does that help? I've seen pure R solutions but none of them are particularly fast. Suspect there are other solutions in R/GEOS/C++/other that I've not seen and very interested to hear of other solutions.

**Comment by garethcao** [comment]
Thanks so much for your kind reply. I am sorry that I have not had enough time to read the latter chapters of the book and thus miss the function you mentioned. Your suggestion was especially useful and I have already solved the problem based on it.
