### ISSUE TITLE
How to extract raster from .gdb instead of empty polygons?

### ISSUE THREAD

**Issue by garethcao** [Robinlovelace/geocompr#599]
Dear All,

I have met with a problem when importing raster data of light intensity. Concretely, the following file contains raster data of Chinese nightlight intensity. I write the following command to import it:

`file_temp = st_read(dsn = 'path/tif.gdb', layer = 'noflare_20131')`
`light = raster(file_temp)`
`plot(light)`

[https://www.dropbox.com/s/o8rn7cnb4a5rc6j/tif.gdb.zip?dl=0](url)

However, it seems that I have only extracted an empty polygon into R without values of light intensity. In contrast, when importing the data into ArcGIS, it could be displayed successfully.

I guess that I should add some options to the command st_read() or raster() while have not figured out a specific solution. Thanks for your reading and look forward to any comment!

**Comment by Nowosad** [comment]
Hi @garethcao! 

I would suggest you asking this question at https://gis.stackexchange.com/ - then your question could be seen (and hopefully solved) by a larger number of people.

**Comment by jannes-m** [comment]
Since it is a raster file, you should not use sf (st_read), which only handles vector data. Have a look if the stars or raster package support reading from a. gdb

**Comment by jannes-m** [comment]
Since it is a raster file, you should not use sf (st_read), which only handles vector data. Have a look if the stars or raster package support reading from a. gdb

**Comment by jannes-m** [comment]
Have also a look at:

https://gis.stackexchange.com/questions/267186/importing-raster-with-r-from-file-geodatabase

Or simply export your raster as geotif from within ArcGIS.

**Comment by Nowosad** [comment]
For a reference - https://gis.stackexchange.com/questions/385255/how-to-extract-raster-from-gdb-instead-of-empty-polygons
