### ISSUE TITLE
Error when loading tmap

### ISSUE THREAD

**Issue by yanbinghan** [Robinlovelace/geocompr#601]
Hi,

Here is the error message I got: 

> library(tmap) 
Error: package or namespace load failed for ‘tmap’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘stars’

Could you please let me know how to deal with it? Thank you so much. 

Best, Yanbing

**Comment by Nowosad** [comment]
Hi, try to install the stars package:

```r
install.package("stars")
```

**Comment by yanbinghan** [comment]
> Hi, try to install the stars package:
> 
> ```r
> install.package("stars")
> ```
