### ISSUE TITLE
Mistake in the units section of Foundations (.. the results of the res() command after projection)

### ISSUE THREAD

**Issue by gbortz27** [Robinlovelace/geocompr#602]
Units are of equal importance in the case of raster data. However, so far sf is the only spatial package that supports units, meaning that people working on raster data should approach changes in the units of analysis (for example, converting pixel widths from imperial to decimal units) with care. The new_raster object (see above) uses a WGS84 projection with decimal degrees as units. Consequently, its resolution is also given in decimal degrees but you have to know it, since the res() function simply returns a numeric vector.

res(new_raster)
#> [1] 0.000833 0.000833
If we used the UTM projection, the units would change.

repr = projectRaster(new_raster, crs = "+init=epsg:26912")
res(repr)
#> [1] 0.000833 0.000833  **** This is not correct should be [1] 73.8 92.5 i think
Again, the res() command gives back a numeric vector without any unit, forcing us to know that the unit of the UTM projection is meters.

**Comment by Robinlovelace** [comment]
Thanks @gbortz27, what would your suggestion be for the text? I defer to the judgement of @Nowosad and @jannes-m who have more experience with raster datasets, although I can see there is an inconsistency. Please also add a link to the specific section in the book (and perhaps even lines of code in the source code) you are referring to.

**Comment by Nowosad** [comment]
Thank you @gbortz27 - I wil try to find some time later this week to investigate this issue.

**Comment by Nowosad** [comment]
It should be fine now. Thank you for letting us know @gbortz27.  

@Robinlovelace - sorry for pushing to master - bad habits...

**Comment by Robinlovelace** [comment]
> @Robinlovelace - sorry for pushing to master - bad habits...

No worries. Good fix!
