### ISSUE TITLE
Mention the crssuggest package

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#609]
It would be great to mention this in the relevant chapter: https://github.com/walkerke/crsuggest

Specifically it would fit perfectly here: https://geocompr.robinlovelace.net/reproj-geo-data.html#which-crs-to-use

Heads-up @walkerke, awesome package, let me know if you've any comments/suggestions on describing the package and thanks for developing it!

**Comment by walkerke** [comment]
Thanks @Robinlovelace!  I'd be happy to write a little about crsuggest and submit a PR, if you'd like!

**Comment by Robinlovelace** [comment]
Thanks Kyle, that would be amazing :pray:  This is the relevant file: https://github.com/Robinlovelace/geocompr/edit/master/06-reproj.Rmd

**Comment by Nowosad** [comment]
Hi @walkerke -- I added a short paragraph about the crssuggest package to the book -- https://github.com/Robinlovelace/geocompr/commit/594ddaa67ee2098715ca22e14a91fe7207ee0a8e. Could you take a look and improve it if necessary? 

Related: https://github.com/walkerke/crsuggest/issues/7
