### ISSUE TITLE
Create a vignette with solutions to the exercises. 

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#61]

**Comment by Robinlovelace** [comment]
And place it in spData.

**Comment by Nowosad** [comment]
Do you think it is a better place than geocompr?

**Comment by Robinlovelace** [comment]
Yes as it can be installed from CRAN, has fewer deps and will be installed from chapter 2 onwards, even if geocompr is not.

**Comment by Robinlovelace** [comment]
In Efficient R Programming we put them in another package also: https://github.com/csgillespie/efficient/tree/master/vignettes

Another question: should these be separate vignettes of just 1 big one? Suspect many will be easier to find answers but 1 big one could have advantages also.

**Comment by Nowosad** [comment]
I would start with the only one. If it would become very large - then we could think about separating it.

**Comment by Robinlovelace** [comment]
Agreed. I suggest we develop it in geocompr and then move it to spData when ready.

**Comment by Nowosad** [comment]
Nice idea. I'm going to create it in the next few days.

**Comment by Robinlovelace** [comment]
Great - I've added some commented-out solutions already that could help populate it. This will improve the book loads by making it more interactive - not quite at the level of **learnr** but we can take inspiration from the thinking behind it: https://blog.rstudio.com/2017/07/11/introducing-learnr/
