### ISSUE TITLE
Suggestions for updates to spatial modeling section

### ISSUE THREAD

**Issue by pat-s** [Robinlovelace/geocompr#610]
In the last years, some developments happened in the field of spatial ML.

I see in #567 you are already aware that {mlr} has been deprecated.

Besides this, spatial CV has evolved into spatiotemporal CV.
With respect to the mlr framework, the new kid on the block is [{mlr3spatiotempcv}](https://github.com/mlr-org/mlr3spatiotempcv).
We are in the process of writing a JSS paper currently.

Next, there is also the [{spatialsample}](https://github.com/tidymodels/spatialsample) for people who prefer the tidyverse framework.

I am wondering if @jannes-m has motivation and time to update this section, given that he was the initial author.

Speaking of myself, I am busy with writing the [{mlr3spatiotempcv}](https://github.com/mlr-org/mlr3spatiotempcv) paper and getting my PhD done. I could certainly do a review of a potential rewrite but do not have capacities as an author right now.

Thanks for your work on this!

**Comment by Robinlovelace** [comment]
It's exciting to see progress on these new frameworks that, from a glance, seem to offer multiple benefits to users. Definitely keen to include this stuff, especially `mlr3spatiotempcv` (which I understand is basically a direct replacement of the code currently in Section 11.5: https://geocompr.robinlovelace.net/spatial-cv.html#intro-cv

Look forward to hearing back from you and Jannes on this, thanks for raising this as a standalone issue as you say linked to #567

**Comment by jannes-m** [comment]
Thanks for pointing this out again, @pat-s! It is certainly on the to-do list, and I just have to find some time to update the corresponding chapters. I will have to plan how I can put at least a few hours a week in updating the chapters to guarantee at least a steady albeit slow progress. In any case, it is great to have you @pat as a reviewer, thanks a lot in advance!
