### ISSUE TITLE
Support s2, fix build

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#612]
Build is failing and it's due to updates to sf, v1:

https://github.com/Robinlovelace/geocompr/runs/2836316541#step:10:1503

**Comment by Nowosad** [comment]
Ok, I know why the problem occurred - it uses older version (pre-s2) of the `world` object. I will update **spData** on CRAN as soon as possible. It should fix the issue.

**Comment by Robinlovelace** [comment]
Good detective work, thanks for the upstream fix.

**Comment by Nowosad** [comment]
Fixed - https://geocompr.robinlovelace.net/ and https://cran.r-project.org/web/packages/spData/index.html.

**Comment by Robinlovelace** [comment]
Great work Jakub! I've just pushed to this repo. If we rebuild tomorrow hopefully the docker based builds will pass also: https://github.com/geocompr/docker/commits/master
