### ISSUE TITLE
Issue building on upstream versions of OSGeo/sf?

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#615]
I'm seeing this error:

```
 Quitting from lines 325-328 (03-attribute-operations.Rmd) 
Error in s2_geography_from_wkb(x, oriented = oriented, check = check) : 
  Evaluation error: Found 1 feature with invalid spherical geometry.
[6] Loop 0 is not valid: Edge 0 crosses edge 78.
Calls: local ... as_s2_geography.WKB -> new_s2_xptr -> s2_geography_from_wkb
Execution halted
```

Not sure if that's an issue with `sf`, `s2` or something else, any ideas @Nowosad ? Here's the error in context: https://github.com/Robinlovelace/geocompr/runs/2898659118#step:4:3078

**Comment by Nowosad** [comment]
Is there a chance that this build uses the old CRAN version of spData (0.3.8)?

**Comment by Robinlovelace** [comment]
> Is there a chance that this build uses the old CRAN version of spData (0.3.8)?

Yes, that is a possibility. I've triggered another build on the docker files that were last updated 6 days ago, if we try again tomorrow that may resolve it https://github.com/geocompr/docker/commits/master

**Comment by Robinlovelace** [comment]
Fixed :tada: 

![image](https://user-images.githubusercontent.com/1825120/123539501-fb096b80-d731-11eb-82bd-cfc62e5f7233.png)

Builds: https://github.com/Robinlovelace/geocompr/runs/2922827611

**Comment by Nowosad** [comment]
Neat
