### ISSUE TITLE
Pipe operator

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#616]
One of the things we need to decide on for the next edition is: which pipe operator we will use:

- tidyverse one - `%>%` 
- post R4.1 one - `|>` - https://youtu.be/X_eDHNVceCU?t=4082

**Comment by Robinlovelace** [comment]
Good question. I would tentatively advocate going for the base R pipe, partly to emphasise that the contents assume users have recently developed versions of R and associated packages installed, something that is especially data in the rapidly moving field of r-spatial.

**Comment by Nowosad** [comment]
Same feeling here.

**Comment by Nowosad** [comment]
https://github.com/Robinlovelace/geocompr/pull/794 -- I replaced most of the pipes with the base one (except for a few rare occasions where it was not directly possible on R 4.1 (which I am using atm)).

**Comment by Robinlovelace** [comment]
I think we should write the pipes for R >= 4.2.0 so we can benefit from the `_` syntax.

**Comment by Nowosad** [comment]
Yep -- my plan is to start adding `_` when I have R 4.2 on my local computer (probably in a few weeks).

**Comment by Robinlovelace** [comment]
Good time to forge ahead with this now I reckon, I need a 'forcing function' to update my RStudio default short-cut settings, looking forward to using the new pipe!

**Comment by Nowosad** [comment]
(BTW -- I added `_` to the text a few weeks ago)

**Comment by Nowosad** [comment]
https://github.com/Robinlovelace/geocompr/pull/794
