### ISSUE TITLE
Switch 4.2.1 and 4.2.2 section order

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#621]
Currently we have this:

![image](https://user-images.githubusercontent.com/1825120/130120156-9ea86438-eedf-4ba9-97ba-654ead43122e.png)

Plan is to change the order. Correct @Nowosad ?

**Comment by Nowosad** [comment]
Yes, that is one of minor ideas for edition 2.

**Comment by Robinlovelace** [comment]
Agreed. Assigning you for now but also happy to work on this one Jakub.

**Comment by Nowosad** [comment]
Close?

**Comment by Nowosad** [comment]
Ok -- I just (wrongly) thought you decided on not doing it.

**Comment by Robinlovelace** [comment]
I've thought about it some more. Subsetting is an easy and intuitive place to start section 4.2: https://geocompr.robinlovelace.net/spatial-operations.html#spatial-vec and although not logical from some perspectives I think it's fine and good for beginners to see an operation before seeing the topological relations / binary predicates that drive them. So closing for now, we can always revisit this.
