### ISSUE TITLE
Failing actions

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#624]
I'm perplexed by this one:

```
The downloaded source packages are in
	‘/tmp/RtmpM835fW/downloaded_packages’
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/geocompr/geocompkg/contents/DESCRIPTION?ref=HEAD'
Calls: saveRDS ... github_DESCRIPTION -> download -> base_download -> base_download_headers
Execution halted
Error: Process completed with exit code 1.
```

https://github.com/Robinlovelace/geocompr/runs/3403350869#step:6:32

**Comment by Nowosad** [comment]
I am quite sure that I have seen issue like that a few weeks ago (and was able to fix it).... I will think about it

**Comment by Robinlovelace** [comment]
OK, I will try a few other things...

**Comment by Nowosad** [comment]
https://github.com/Robinlovelace/geocompr/commit/f6ce89184dcba2aed5e724f42af01d466a2f9518 - we will see...

**Comment by Nowosad** [comment]
(it seems to, at least, fixed the first issue)

**Comment by Robinlovelace** [comment]
Makes sense. In other news, the worflow .yaml files are a bit of a mess. Are they are target in the tying mission? In definite need of tidying...

**Comment by Robinlovelace** [comment]
Closing for now as the immediate cause of the failing actions is resolved.
