### ISSUE TITLE
Links to edit source have gone

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#634]
In the final chapter at https://geocompr.robinlovelace.net/conclusion.html for example, I see this:

![image](https://user-images.githubusercontent.com/1825120/132241778-1f443ac4-06c8-4944-ad51-b228a2c3cb9b.png)

Looking for the view/edit source buttons e.g. as shown here https://adv-r.hadley.nz/vectors-chap.html

![image](https://user-images.githubusercontent.com/1825120/132241860-aa598a52-b678-428f-898a-12e7c2447316.png)

**Comment by Nowosad** [comment]
Working on it now.

**Comment by Nowosad** [comment]
Fixed

**Comment by Robinlovelace** [comment]
:pray: looking great!

![image](https://user-images.githubusercontent.com/1825120/132254382-3fafb2c0-00b8-4a87-9590-5ebc7fc32080.png)
