### ISSUE TITLE
Typo in main Readme (under "Reproducing this book")

### ISSUE THREAD

**Issue by olyerickson** [Robinlovelace/geocompr#635]
Very minor typo: this sentence in the **Reproducing this book** section is missing a word :

```
To ease reproducibility, we created the geocompkg package. Installing it from GitHub will install 
all the R packages needed build the book (you will a computer with necessary system dependencies 
and the remotes package installed):
```

I suggest, "...you will need a computer..."

**Comment by Robinlovelace** [comment]
Good point. FYI on fixing it this is how I would proceed

1. Search for the file in GitHub with "will a computer", leading here (reproducible search output is a great feature): https://github.com/Robinlovelace/geocompr/search?q=%22will+a+computer%22
2. Click on the first link, leading here: https://github.com/Robinlovelace/geocompr/blob/12de961cfca364cb2d24ba0559368c51b84d7c62/README.Rmd
3. Replace 12de961cfca364cb2d24ba0559368c51b84d7c62 with main in the url, leading here: https://github.com/Robinlovelace/geocompr/blob/main/README.Rmd
4. Click the edit button taking you here: https://github.com/Robinlovelace/geocompr/edit/main/README.Rmd
5. Fix the typo in the online editor
6. Commit the change
7. Put in a PR

Bit convoluted but it works. You up for giving a go @olyerickson ? Many thanks for spotting this in any case, my bad :facepalm:

**Comment by olyerickson** [comment]
_Done_; it was 42% easier because I was already at the README in the github ;)

**Comment by Robinlovelace** [comment]
Did you click on 'Open Pull Request'? That's the bit that gets everyone and I cannot see anything here: https://github.com/Robinlovelace/geocompr/pulls

**Comment by olyerickson** [comment]
Sorry, brain fart. Done.

**Comment by Robinlovelace** [comment]
Many thanks for the fix!
