### ISSUE TITLE
Build is failing with `[rast] filename is empty` error

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#638]
Error message locally:

```
Error: [rast] filename is empty. Provide a valid filename
```

Will try again after installing dev `terra` with

```r
remotes::install_github("rspatial/terra")
```

**Comment by Robinlovelace** [comment]
Interestingly there's a different error message on actions:

```
Quitting from lines 1052-1055 (05-geometry-operations.Rmd) 
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'crs' for signature '"sf"'

Calls: local ... withVisible -> eval -> eval -> rast -> rast -> crs -> <Anonymous>
In addition: There were 11 warnings (use warnings() to see them)
Execution halted
Error in Rscript_render(f, render_args, render_meta, add1, add2) : 
  Failed to compile 05-geometry-operations.Rmd
Calls: <Anonymous> -> render_new_session -> Rscript_render
Execution halted
Error: Process completed with exit code 1.
```

https://github.com/Robinlovelace/geocompr/runs/3645149374#step:10:3461

**Comment by Nowosad** [comment]
To be able to build the book, you need to have the most recent terra dev version - I have opened several GH issues for terra, and many of them are already fixed.

I do not know why we have the GHA error - I will investigate it tomorrow.

**Comment by Robinlovelace** [comment]
Awesome, great work on the upstream comms and it's good that we build from the dev version.

**Comment by Nowosad** [comment]
Fixed.
