### ISSUE TITLE
Update Figure 1.2 shown n. downloads of geographic packages

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#639]
I think we should:

- [x] Remove ggmap
- [x] Add terra
- [x] Add stars
- [x] Make the figure wider than it is tall
- [ ] Anything else?

We could use a log scale for the Y axis. Thoughts? I'm up for giving this a go. Currently the figure is as follows:

![image](https://user-images.githubusercontent.com/1825120/133975854-a6fb1afd-8a0f-4f48-9bbc-3119b66aab93.png)

**Comment by Robinlovelace** [comment]
Update: stars at tmap currently have v. few downloads, maybe stars but not tmap should be included...

![image](https://user-images.githubusercontent.com/1825120/133976763-47c27b37-07c0-4ac7-b92d-56c8ea47d3d4.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/133976992-94ac2ee6-236f-41bd-86cb-b53b1cc0937d.png)

Log version, I think this is a bit better...

**Comment by Robinlovelace** [comment]
Also thinking about resolution. Results with 

```r
ggsave("figures/spatial-package-growth.png", ggfig, width = 6, height = 4, dpi = 150)
```

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/133977382-e46c5f5a-68ac-4d63-92c8-d2106e9ea967.png)

**Comment by Nowosad** [comment]
I started working on a new version of these figure some time ago. I have experimented by creating a few facets, e.g., spatial classes, spatial viz, spatial modeling, etc. I like the log version, but still plan to modify this figure.

**Comment by Robinlovelace** [comment]
> I started working on a new version of these figure some time ago. I have experimented by creating a few facets, e.g., spatial classes, spatial viz, spatial modeling, etc. I like the log version, but still plan to modify this figure.

Confident that the changes in https://github.com/Robinlovelace/geocompr/commit/2f2cfa564ee7196fe37a3db8bb7bedf114df117a are an improvement. Happy for further changes. Main conceptual change: only class system packages are in there now. I don't think adding facets is a good plan, confusing enough with 5 class system packages, we can save vis pkgs to the relevant chapter is my thinking.

**Comment by Nowosad** [comment]
@Robinlovelace feel free to merge the PR.
