### ISSUE TITLE
cant find objects "evel" or "grain" in chapter 4

### ISSUE THREAD

**Issue by JannisLi** [Robinlovelace/geocompr#641]
Hi, sorry i am not sure if this is the right place to ask these questions because its probably an issue of my settings not the code. Anyhow I have a problem loading these objects (with the both terra or raster syntax):

> elev = rast(system.file("raster/elev.tif", package = "spData"))
Error: [rast] filename is empty. Provide a valid filename

> grain = rast(system.file("raster/grain.tif", package = "spData"))
Error: [rast] filename is empty. Provide a valid filename

> raster_filepath = system.file("raster/elev.tif", package = "spData")
> elev = raster(raster_filepath)
Error in .local(.Object, ...) : 
Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
  Cannot create a RasterLayer object from this file.

> elev = brick(raster_filepath)
Error in .rasterObjectFromFile(x, objecttype = "RasterBrick", ...) : 
  provide a valid filename

Any suggestions?
Thanks

**Comment by Nowosad** [comment]
Hi @JannisLi ,

long story short - we are currently working on the second edition of Geocomputation with R. Several new changes are based on the development versions of some packages. For example, you need the development versions of **terra**, **tmap**, **spData**, and **spDataLarge** to be able to reproduce the current code in the book.

```r
remotes::install_github("rspatial/terra")
remotes::install_github("mtennekes/tmap")
remotes::install_github("nowosad/spData")
remotes::install_github("nowosad/spDataLarge")
```

I will close all of your issues for now. Feel free to let us know if there is still anything wrong.

Best,
Jakub

**Comment by JannisLi** [comment]
Hi Jakub,

thanks for your answer. If it helps I am happy to send any problems I come across.
And thanks a lot for this fantastic book! It helps a lot reading it!

Best
Jannis
