### ISSUE TITLE
4.3.1 Spatial subsetting 

### ISSUE THREAD

**Issue by JannisLi** [Robinlovelace/geocompr#642]
Hi, anohter problem i came across is that the code below does not produce the same output as it should:

> elev = rast(nrows = 6, ncols = 6, resolution = 0.5, 
           xmin = -1.5, xmax = 1.5, ymin = -1.5, ymax = 1.5,   vals = 1:36)

> clip = rast(xmin = 0.9, xmax = 1.8, ymin = -0.45, ymax = 0.45,  resolution = 0.3, vals = rep(1, 9))

> elev[clip]
   lyr.1
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
26    26
27    27
28    28
29    29
30    30
31    31
32    32
33    33
34    34
35    35
36    36

> terra::extract(elev, ext(clip))
  lyr.1
1    18
2    24 

I have no idea why.

**Comment by Nowosad** [comment]
See https://github.com/Robinlovelace/geocompr/issues/641
