### ISSUE TITLE
Chapter 3 grain_order 

### ISSUE THREAD

**Issue by JannisLi** [Robinlovelace/geocompr#643]
For producing the "grain" object the *grain_order* seems to be missing:

concering this chunk:
grain_char = sample(grain_order, 36, replace = TRUE)
grain_fact = factor(grain_char, levels = c("clay", "silt", "sand"))
grain = rast(nrows = 6, ncols = 6, resolution = 0.5, 
             xmin = -1.5, xmax = 1.5, ymin = -1.5, ymax = 1.5,
             vals = grain_fact)

grain_char = sample(grain_order, 36, replace = TRUE) # does not work
Error in sample(grain_order, 36, replace = TRUE) : 
  object 'grain_order' not found

**Comment by Nowosad** [comment]
See https://github.com/Robinlovelace/geocompr/issues/641
