### ISSUE TITLE
Update reproducing the book section and link to it from 'On this page' section

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#644]
To link to the issue tracker, feedback form, and reproducing the book section.

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/134256623-610a0e84-e1d8-41a6-aab7-6c5a97c5cec9.png)

Updated slightly since then. Looking good to me. Heads-up @Nowosad .

**Comment by Nowosad** [comment]
Awesome!
