### ISSUE TITLE
Are packages being cached correctly to speed up build times?

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#651]
Heads-up @Nowosad I just noticed that package versions are being updated. This surprised me as I thought up-to-date packages would be cached.

Example from the build logs:

```
Run pak::local_install_dev_deps(upgrade = TRUE)
  pak::local_install_dev_deps(upgrade = TRUE)
  remotes::install_github("geocompr/geocompkg", dependencies = TRUE)
  remotes::install_github("rspatial/terra") #temporary, remove later
  shell: /usr/local/bin/Rscript {0}
  env:
    GITHUB_PAT: ***
    R_LIBS_USER: /home/runner/work/_temp/Library
    TZ: UTC
    _R_CHECK_SYSTEM_CLOCK_: FALSE
    NOT_CRAN: true
ℹ Loading metadata database
✔ Loading metadata database ... done

 
→ Will update 22 packages.
→ Will download 19 CRAN packages (18.54 MB).
→ Will download 4 packages with unknown size.
+ cpp11       0.3.1    → 0.4.0    [bld][dl] (317.56 kB)
+ digest      0.6.27   → 0.6.28   [bld][cmp][dl] (165.07 kB)
+ e1071       1.7-8    → 1.7-9    [bld][cmp][dl] (566.72 kB)
+ geocompkg   0.0.104  → 2.0.1    [bld][cmp][dl] (GitHub: 7542111)
+ geometa     0.6-3    → 0.6-4    [bld][dl] (532.93 kB)
+ htmlwidgets 1.5.3    → 1.5.4    [bld][dl] (956.85 kB)
+ httpuv      1.6.2    → 1.6.3    [bld][cmp][dl] (1.81 MB)
```

Source: https://github.com/Robinlovelace/geocompr/runs/3709957567#step:9:18

**Comment by Nowosad** [comment]
Close?

**Comment by Robinlovelace** [comment]
Can do but want to get a better understanding of build times out of interest first. I see

22 minutes: https://github.com/Robinlovelace/geocompr/runs/3712311410

22 minutes: https://github.com/Robinlovelace/geocompr/runs/3712241870

23 minutes: https://github.com/Robinlovelace/geocompr/runs/3709980138

I'm still not sure why we're seeing these messages:

```
+ cpp11       0.3.1    → 0.4.0    [bld][dl] (317.56 kB)
+ digest      0.6.27   → 0.6.28   [bld][cmp][dl] (165.07 kB)
+ e1071       1.7-8    → 1.7-9    [bld][cmp][dl] (566.72 kB)
+ fontawesome            0.2.2    [bld][dl] (1.12 MB)
+ geocompkg   0.0.104  → 2.0.1    [bld][cmp][dl] (GitHub: 954e47b)
+ geometa     0.6-3    → 0.6-4    [bld][dl] (532.93 kB)
+ gert        1.3.2    → 1.4.1    [bld][cmp][dl] (67.29 kB)
```

Those seem like quite big jumps, no? https://github.com/Robinlovelace/geocompr/runs/3712311410#step:9:20

**Comment by Nowosad** [comment]
I am quite sure this is because of https://github.com/Robinlovelace/geocompr/blob/ebbb18d82d6ae04464a611961f1ace50052eed24/.github/workflows/main.yaml#L80 - I force rebuilding of terra each time as I have opened several issues there recently, and many new changes are related to the book's text.

**Comment by Robinlovelace** [comment]
OK but I'm not sure why the versions of packages are so old, gert        1.3.2 for example...

**Comment by Nowosad** [comment]
Good point

**Comment by Robinlovelace** [comment]
Which seems to be from before 15th September. The last rebuild was after then, not that old. Sorry if this is a silly question, I may be missing something... And the main point is that 20 minute build (~6 min without compiling pkgs) is fast.

https://cran.r-project.org/src/contrib/Archive/gert/

**Comment by Nowosad** [comment]
I still think that we should move to have one repo to create an image (and update in on a daily or weekly schedule) and use this image in other GitHub actions. I have tried once or twice to understand how to do that, but failed.

**Comment by Robinlovelace** [comment]
Agreed. The image will be useful for many other things also. We can track progress on it here: https://github.com/geocompr/docker/issues/9

**Comment by Robinlovelace** [comment]
We're not sure but no longer relevant after 

>  [geocompr/docker#9](https://github.com/geocompr/docker/issues/9)

**Comment by Robinlovelace** [comment]
I think I know what was happening and the solution is simple: add `, force = TRUE` to the `install_github()` command. Same as https://github.com/geocompr/docker/issues/15
