### ISSUE TITLE
Animation GIF containing two maps.

### ISSUE THREAD

**Issue by thejibin** [Robinlovelace/geocompr#665]
I wanted to create a animation GIF with two maps (for example say COVID cases on left and Vaccination rates on right; I am trying to create something similar to one available in Chicago Tribune: https://tinyurl.com/434n4rsz). Somehow I managed to create two maps with a available data in R for a similar case. But the two maps are showing different years for a particular frame (when left shows 1950, right map shows 1955). Would you please help me to make the year and data same for a particular frame? Is there any better method available to create a similar map?

An reproducible code for the issue is below:-
#####################################

```r
library(tmap)
library(spData) #for data
library(magick)

## Copying the data to a variable
data<-spData::urban_agglomerations

## Create two variables to plot
data$var1<-data$population_millions
data$var2<-data$population_millions^2

## Create tmap object
anim <- tm_shape(world) + tm_polygons() + 
  tm_shape(urban_agglomerations) +  
  tm_dots(c("population_millions", "pop"),size=2) + 
  tm_facets(by = "year", ncol=2, nrow=1, free.coords = F, sync=TRUE) 

tmap_animation(anim, "./anim_file.gif",
                 width = 900,
                 height = 450,
                 delay=100)
magick::image_read("./anim_file.gif")
```
#####################################

**Comment by mtennekes** [comment]
The current version of tmap is indeed limited here.

A workaround to create this kind of animation in tmap3 is via `tm_arrange`, one for each year. Unfortunately, `tmap_animation` doesn't work for `tm_arrange` objects (but should be relatively easy to implement). So you'll have to create the animation directly with the `gifski`. See also this similar issue: https://github.com/r-tmap/tmap/issues/583 . This approach also handles the outside legend-issue (your 2nd question).

In tmap4, all these limitations will be solved, but it will take at least a few months before it is stable and documented.

**Comment by Robinlovelace** [comment]
This has been a great discussion, many thanks @thejibin. This has be interesting to me and I think there may be a possibility to mention this in the book but it's a not a priority atm. As Martijn says similar issue has been discussed in tmap, further comms or offers of support specific to tmap may be best placed there https://github.com/r-tmap/tmap/issues/583 PRs to open source projects always welcome!
