### ISSUE TITLE
`read_sf()` vs `st_read()`

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#666]
Currently the book uses mostly `st_read()` (https://geocompr.robinlovelace.net/read-write.html#vector-data-1). However, in my own work, I only use `read_sf()`. It is more consistent with both regular R code (e.g., `read.csv()`) but also with **stars** (`read_stars()`). 
Therefore, my suggestion is to rewrite some book parts to `read_sf()`. What do you think?

Edit: also `write_sf()` vs `st_write()`

**Comment by defuneste** [comment]
In my experience I prefer `st_read()` when I don't know anything about the data I need to import (ie mostly doing analysis) and I use the `quiet` version when I already know everything (crs, features, etc) and I don't want to get "flooded" with it (ie batch import, programing, etc).

**Comment by Robinlovelace** [comment]
Taking a look at this now.

**Comment by Robinlovelace** [comment]
Thinking about it: `st_read()` is probably the most reliable and future proof which should take precedence over convenience. However, I think including mention of the ability to use both more frequently is a good thing and am making progress on that (see commits above and below).

**Comment by Nowosad** [comment]
My thinking is that both `st_read()` and `read_sf()` are reliable and future proof (as **stars** uses `read_stars()`), and also they are very similar, with rather minor pros and cons. 

Case for `read_sf()`: 

- (a) its naming is more consistent with other similar R functions: `readxl::read_excel()`, `readr::read_csv()`, `read.csv()`, `stars::read_stars()`.
- (b) its output is more consistent with other similar R functions. Usually R functions (including `terra::rast()`) do not show the file dimensions, etc. while reading. You can check this information yourself later.

Case for `st_read()`:
- (a) we introduced it in geocompr1.
- (b) it does not require **tibble**.

Moreover, they had different `stringsAsFactors` defaults, but this difference is now gone. 

I am still on the `read_sf()` team, but this issue is not of any huge priority.

**Comment by Robinlovelace** [comment]
That's a good summary of +s and -s. In chapter 3 we talk about the advantages of **tidyverse** workflows. The advantages of `read_sf()` are real. Best thing I could think of: mention both prominently and allow the user to choose, which is what we already do regarding base R vs **tidyverse** subsetting syntax. Also a big + to newcomers is that reading sf objects is now mentioned early on in C2. Too many of our examples build `sf` objects from the beginning compared with the reality that most people just want to read-in and start analysing data. Also added more cross refs. See what you think of the updates @Nowosad and further tweaks welcome but I think the question is broadly answered (mention both). However, I would be happy to see more `st_read()` calls replaced with `read_sf()`, particularly as that will save space.
