### ISSUE TITLE
Section 2.6 Exercise 5 - reading in nlcd

### ISSUE THREAD

**Issue by dcsuh** [Robinlovelace/geocompr#667]
https://geocompr.robinlovelace.net/spatial-class.html#ex2

I can't read in nlcd.tif but I did find nlcd2011.tif from spDataLarge. I believe I installed the latest version of spDataLarge but it is possible that I have an older version with a file that was named differently.

nlcd <- system.file("raster/nlcd.tif", package = "spDataLarge") #returns nothing
nlcd <- system.file("raster/nlcd2011.tif", package = "spDataLarge") #returns correct filepath

**Comment by Nowosad** [comment]
Thanks @dcsuh! We are now updating the text in chapters 1-7 for the second edition, and our next step will be to update the exercises in these chapters. Let us know if you find any other issues!
