### ISSUE TITLE
Chapter 12.2 & 12.3 Figures and Tables not showing + input data archived?

### ISSUE THREAD

**Issue by geo-girl** [Robinlovelace/geocompr#670]
Hi, this is the first time I post something like this so please bear with me.

I was hoping to use 12.2. and 12.3 as an example in a teaching session - https://geocompr.robinlovelace.net/transport.html
But the tables and figures no longer show and the R-markdown seems to have issues as the code that generated the input data has been archived: "https://github.com/Robinlovelace/geocompr/raw/main/code/12-transport-data-gen.R"

Can you please let me know if I can replicate this differently?

Thanks

**Comment by Robinlovelace** [comment]
Many thanks for reporting this issue @geo-girl I will take a look asap.

**Comment by Robinlovelace** [comment]
Heads-up @geo-girl I've checked the updated version of c12 and it seems OK. Please take a look and let us know of any further issues. Your feedback is very much appreciated. https://geocompr.robinlovelace.net/transport.html
