### ISSUE TITLE
Missing section label in c13

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#674]
Building the book currently results in the following message:

```
bookdown::serve_book()
# ...
Warning messages:
1: The label(s) aggregation-and-disaggregation not found 
```

Resulting from this:

https://github.com/Robinlovelace/geocompr/blob/9310e14f33dcc24c69cdf237d8c03f7ddde1fd95/13-location.Rmd#L218-L226

I cannot find a reference to that section. It seems that `aggregate()` is now only used with reference to `sf` objections in C3 and C4. Is this due to the switch from `raster` to `terra` Jakub and if so which section should we direct people to?

**Comment by Nowosad** [comment]
Should be fixed now.

**Comment by Robinlovelace** [comment]
Great fix. Confirmed: 

![image](https://user-images.githubusercontent.com/1825120/140614244-0db01ce0-1e9e-47e5-b309-1096eec1c57b.png)


https://geocompr.robinlovelace.net/location.html#define-metropolitan-areas
