### ISSUE TITLE
raster/dem.tif does not exist in spDataLarge

### ISSUE THREAD

**Issue by dcsuh** [Robinlovelace/geocompr#676]
Section 5.3.3 and 5.4.4 reference raster/dem.tif from spDataLarge but this file does not exist in spDataLarge (I last installed the package on 10/29/21)

**Comment by Nowosad** [comment]
For now, please try to update it with:

```r
remotes::install_github("nowosad/spDataLarge")
```

I will fix the drat repo in the near future...

**Comment by dcsuh** [comment]
Thanks. I was also able to access the file with 
data(dem, package="spDataLarge")

**Comment by Nowosad** [comment]
Ok -- I fixed the main issue. Now the proper spDataLarge installation should work fine.
