### ISSUE TITLE
Improve description of topological relations

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#677]
Currently in the book the section on topological relations starts as follows: 

![image](https://user-images.githubusercontent.com/1825120/141611377-0b1d75d1-b7c2-4e20-badb-0f823e59f903.png)

Link: https://geocompr.robinlovelace.net/spatial-operations.html#topological-relations

We can do better than that!

I'm looking at early papers on the subject and came across these illustrations:

![image](https://user-images.githubusercontent.com/1825120/141611899-6fd12992-6f58-42b7-8fc3-008fe531b416.png)

![image](https://user-images.githubusercontent.com/1825120/141611917-38b8df36-5169-41a5-8c76-3ecd290214b9.png)

Source: https://en.wikipedia.org/wiki/DE-9IM#cite_note-sdh1990-4

**Comment by Robinlovelace** [comment]
See below a start on the figure. Any feedback welcome. Reproducible code creating that image in subsequent commit.

![image](https://user-images.githubusercontent.com/1825120/141658905-a3839ea6-b043-41b5-aa71-ec0b37175f28.png)

**Comment by Robinlovelace** [comment]
More progress on this, reproducible example:

```r
source("https://github.com/Robinlovelace/geocompr/raw/c4-v2-updates-rl/code/de_9im.R")
p1 = st_sfc(st_polygon(list(rbind(c(0, 0), c(1, 0), c(1, 1), c(0, 0)))))
p2 = st_sfc(st_polygon(list(rbind(c(0, 0), c(0, 1), c(1, 1), c(0, 0)))))
p3 = st_sfc(st_polygon(list(rbind(c(0.7, 0.3), c(0.7, 0.95), c(0.9, 0.95), c(0.7, 0.3)))))
p4 = st_sfc(st_polygon(list(rbind(c(0.6, 0.1), c(0.7, 0.5), c(0.9, 0.5), c(0.6, 0.1)))))
p5 = st_sfc(st_polygon(list(rbind(c(0, 0.2), c(0, 1), c(0.9, 1), c(0, 0.2)))))
de_9im(p1, p2)
de_9im(p1, p3)
de_9im(p1, p4)
de_9im(p4, p1)
de_9im(p1, p5)
```

<details>

``` r
source("https://github.com/Robinlovelace/geocompr/raw/c4-v2-updates-rl/code/de_9im.R")
library(sf)
#> Linking to GEOS 3.9.1, GDAL 3.3.2, PROJ 7.2.1
p1 = st_sfc(st_polygon(list(rbind(c(0, 0), c(1, 0), c(1, 1), c(0, 0)))))
p2 = st_sfc(st_polygon(list(rbind(c(0, 0), c(0, 1), c(1, 1), c(0, 0)))))
p3 = st_sfc(st_polygon(list(rbind(c(0.7, 0.3), c(0.7, 0.95), c(0.9, 0.95), c(0.7, 0.3)))))
p4 = st_sfc(st_polygon(list(rbind(c(0.6, 0.1), c(0.7, 0.5), c(0.9, 0.5), c(0.6, 0.1)))))
p5 = st_sfc(st_polygon(list(rbind(c(0, 0.2), c(0, 1), c(0.9, 1), c(0, 0.2)))))
de_9im(p1, p2)
#> Object x has the following spatial relations to y: st_intersects
#> st_touches
```

![](https://i.imgur.com/4SL6Kkb.png)

``` r
de_9im(p1, p3)
#> Object x has the following spatial relations to y: st_intersects
#> st_overlaps
```

![](https://i.imgur.com/w6GOhfS.png)

``` r
de_9im(p1, p4)
#> Object x has the following spatial relations to y: st_intersects
#> st_contains
#> st_contains_properly
#> st_covers
```

![](https://i.imgur.com/Ywkq90G.png)

``` r
de_9im(p4, p1)
#> Object x has the following spatial relations to y: st_intersects
#> st_within
#> st_covered_by
```

![](https://i.imgur.com/mAQBeFy.png)

``` r
de_9im(p1, p5)
#> Object x has the following spatial relations to y: st_disjoint
```

![](https://i.imgur.com/PiqzUX1.png)

<sup>Created on 2021-11-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Robinlovelace** [comment]
After the commit above we have the following 4.2, an improvement on the previous one but we can make it better. Thinking it would benefit from more geometries, maybe links on the bottom row?

![image](https://user-images.githubusercontent.com/1825120/141862100-3edaea36-754d-46a0-9130-d13f4349f7cd.png)

**Comment by Robinlovelace** [comment]
Latest text output:

![image](https://user-images.githubusercontent.com/1825120/141863981-31a11068-a5f3-4e19-9471-b03dbb36f9a8.png)

**Comment by Robinlovelace** [comment]
This is now MVP, we can tweak after but for this figure this is an improvement. Now I just need to complete my review of c4!

![image](https://user-images.githubusercontent.com/1825120/141866730-084be690-7b19-48cb-9747-81fb89319b8e.png)

**Comment by Nowosad** [comment]
Great work @Robinlovelace! It is rather impossible to show all of the possible topological relations, but this plot could help a lot for many people. 
Two suggestions:
1. Consider using a different font (bold, maybe?) for DE-9IM to highlight that this is different from the functions above it.
2. Try using different colors. Currently, red + blue creates a darker blue color. I have a feeling (not tested) that there is a better combination of colors that could highlight spatial relations. Also, have you tested how these colors work for people with color deficiencies?

**Comment by Robinlovelace** [comment]
Heads-up on this, on the case and planning to complete the PR implementing this later today.

**Comment by Nowosad** [comment]
Hi @Robinlovelace I have made some slight changes to this figure:
- I split the DE-9IM string from the rest of the text
- I used tmap instead of ggplot (which also resulted in a nicer arrangement of the figures
- I tried a different set of colors


PR: https://github.com/Robinlovelace/geocompr/pull/690/files

New:
![image](https://user-images.githubusercontent.com/3457131/145959593-1bc32858-ed7e-4b7e-8725-84caa3228d1f.png)

Current:
![image](https://user-images.githubusercontent.com/3457131/145959845-c82f1551-1f1d-4ac8-9cdc-6e9173b96da7.png)

**Comment by Robinlovelace** [comment]
Progress but aim was to avoid overlaps.

![image](https://user-images.githubusercontent.com/1825120/145966946-b43906be-4b5b-415d-bd88-b95921d69bb3.png)

**Comment by Nowosad** [comment]
Thanks for the suggestion @Robinlovelace -- good point. My new modification:

![image](https://user-images.githubusercontent.com/3457131/145975778-c4d86a05-b240-4924-b01c-a5dc59afeaac.png)

**Comment by Robinlovelace** [comment]
Will merge the PR and see how it looks rendered.

**Comment by Nowosad** [comment]
![image](https://user-images.githubusercontent.com/3457131/145983369-bacd7027-15e2-424b-8a8b-4cf960c0fe21.png)

**Comment by Robinlovelace** [comment]
:tada: 

https://geocompr.robinlovelace.net/spatial-operations.html#topological-relations
