### ISSUE TITLE
USAboundaries error

### ISSUE THREAD

**Issue by donojazz** [Robinlovelace/geocompr#679]
I am trying to run example from book on 8.3 Animated Maps.  Using your code from https://github.com/Robinlovelace/geocompr/blob/main/code/08-usboundaries.R

I get error at this section of code:  usb1 = USAboundaries::us_boundaries(map_date = dates_unique[1])   The error is over USAboundaries library.  States:  Error: 'us_boundaries' is not an exported object from 'namespace:USAboundaries'

I tried searching on Stack and got this as solution:  This was recommended "devtools::install_github("ropensci/USAboundariesData")"  No change after git install.

I do not see this function "us_boundaries "  in library.  

Thanks in advance

**Comment by donojazz** [comment]
BTW, I get similar error when running USAboundaries sample  at  https://www.rdocumentation.org/packages/USAboundaries/versions/0.3.1/topics/us_boundaries

Did they remove function from library??  I see it on pg 5 of updated document, but cannot get it to run.
https://cran.r-project.org/web/packages/USAboundaries/USAboundaries.pdf

**Comment by donojazz** [comment]
Just discovered this  https://github.com/ropensci/USAboundaries/commit/5c2aed38f64dc686011dc69327b6cab1d14b4844

Looks like it was depricated on Oct 8.  However all updated documentation still lists it as incorporated.

**Comment by donojazz** [comment]
I created a new run by "removing replacing  us_boundaries() with us_states() and adding  library(gifski) .  I notified   ropensci/USAboundaries@5c2aed3  that they need to update their documentation on deprication.

Now I can submit my #30daychallenge.  Thanks

**Comment by Nowosad** [comment]
Thanks @donojazz for the whole investigation!
