### ISSUE TITLE
Plot missing or wrong caption

### ISSUE THREAD

**Issue by Eyayaw** [Robinlovelace/geocompr#680]
The figure on [Raster extraction](https://geocompr.robinlovelace.net/geometric-operations.html#raster-extraction) `FIGURE 5.19: Locations of points used for raster extraction (left) and their 1km buffers (right).` seems to miss one panel or the caption is incorrect.

**Comment by Nowosad** [comment]
Thanks! That was a leftover from some old idea... https://github.com/Robinlovelace/geocompr/commit/48e621863e1ae007a759358a916aea4a7cea6c01
