### ISSUE TITLE
minor typo/leftover note to self

### ISSUE THREAD

**Issue by jrosen48** [Robinlovelace/geocompr#681]
Hi, is this (in **bold**) a minor typo/leftover note to self?

> We will use a real-world digital elevation model (DEM) because the artificial raster elev produces parallel lines **(task: verify this and explain why this happens)**

from [5.4.4](https://geocompr.robinlovelace.net/geometric-operations.html?q=contour#spatial-vectorization)

**Comment by Nowosad** [comment]
It meant to be a task for the reader. Now, I made that more obvious in https://github.com/Robinlovelace/geocompr/commit/679acc1dc05698efd1bfe1301bd465cf36bc025b.
