### ISSUE TITLE
Add raster attribute operations section to Chapter 3

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#69]

**Comment by Robinlovelace** [comment]
I think this would fit-in nicely after [section 3.6](http://robinlovelace.net/geocompr/attr.html#removing-spatial-information) and that @jannes-m is well-equipped to tackle this, probably with reference to a simple raster dataset (not sure which one though)...

**Comment by Nowosad** [comment]
https://github.com/Robinlovelace/geocompr/pull/80
