### ISSUE TITLE
Minor issues with build - missing tags/references

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#692]
On the latest version building on Actions in the geocompr/docker repo I noticed the following in the logs:

```
#6 350.0 [WARNING] Citeproc: citation bivand_progress_2021 not found
#6 388.5 Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
#6 389.4 
#6 389.4 Output created: _book/index.html
#6 389.4 [1] "/home/rstudio/geocompr/_book/index.html"
#6 389.4 Warning messages:
#6 389.4 1: The label(s) raster-data-1 not found 
#6 389.4 2: The label(s) fig:relate not found 
#6 389.4 3: The label(s) fig:crs-buf, fig:wintriproj not found 
#6 389.4 4: The label(s) fig:crs-buf not found 
```

Source: https://github.com/geocompr/docker/runs/4562518653?check_suite_focus=true#step:8:9361

**Comment by Nowosad** [comment]
Hey Robin,

Some of this images are missing due to my cleaning of chapter 6. I removed
most of the outdated information from there, e.g. the London buffer plot.

**Comment by Nowosad** [comment]
Oh, and about the raster data tag - there were at least two sections in
chapter 7 with this tag. I updated them into raster-data-read and
raster-data-write.

**Comment by Nowosad** [comment]
I fixed the following problems:

```
#6 389.4 1: The label(s) raster-data-1 not found 
#6 389.4 2: The label(s) fig:relate not found 
```

**Comment by defuneste** [comment]
Looking at the `geocompr.bib` it appears that you have `bivand_progress_2020` (https://github.com/Robinlovelace/geocompr/blob/main/geocompr.bib#L159). 

This is this article (https://link.springer.com/article/10.1007/s10109-020-00336-0) ?  if yes it make more sense to: 

-  change the @ in .bib  (2020 -> 2021)
-  see if you have cited it at other places with bivand_progress_2020
- 
I will try to do a quick PR

**Comment by Robinlovelace** [comment]
:+1: Sounds like a quick fix + low hanging fruit. Note: we use Zotero to manage the bib. Will change there and report back here.
