### ISSUE TITLE
Empty space after plot in Chapter 5

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#704]
The following code

https://github.com/Robinlovelace/geocompr/blob/0cda70031688e3d3a0ac932009f6ff0461217be8/05-geometry-operations.Rmd#L351-L362

Generates the following:

![image](https://user-images.githubusercontent.com/1825120/146673417-f6d217d8-29b6-479c-bb7b-fe667f1c189e.png)

Simple problem that should have a simple solution: how to get it so that there is less (no?) empty space above and below the plot? I think I've solved this before but cannot recall the solution!

**Comment by Nowosad** [comment]
https://bookdown.org/yihui/rmarkdown-cookbook/crop-plot.html?

**Comment by defuneste** [comment]
Using `mar` arguments  before ploting ? I never remember how it affect next plot call.

I just used default except for top and bottom. 

```r
bb = st_bbox(st_union(x, y))
box = st_as_sfc(bb)
set.seed(2017)
p = st_sample(x = box, size = 10)
p_xy1 = p[x_and_y]
par(mar= c(0, 4, 0, 2) + 0.1) ## here
plot(box, border = "grey", lty = 2)
plot(x, add = TRUE, border = "grey")
plot(y, add = TRUE, border = "grey")
plot(p, add = TRUE)
plot(p_xy1, cex = 3, col = "red", add = TRUE)
text(x = c(-0.5, 1.5), y = 1, labels = c("x", "y"), cex = 2)
```

**Comment by Robinlovelace** [comment]
Aha yes, that would do it. A bigger question is do we switch to {tmap} for this plot. Thoughts welcome.

**Comment by defuneste** [comment]
I like base plot for this kind of "dummy"/test/quick viz plotting (I probably like base plot way too much) but using {tmap} will maybe be a bit more consistent with the rest of the book. I do not think it matter too much.

**Comment by Nowosad** [comment]
``` r
library(sf)
#> Linking to GEOS 3.9.2, GDAL 3.3.2, PROJ 8.2.1; sf_use_s2() is TRUE
library(tmap)

b = st_sfc(st_point(c(0, 1)), st_point(c(1, 1))) # create 2 points
b = st_buffer(b, dist = 1) # convert points to circles
x = b[1]
y = b[2]
x_and_y = st_intersection(x, y)
bb = st_bbox(st_union(x, y))
box = st_as_sfc(bb)
set.seed(2017)
p = st_sample(x = box, size = 10)

bb = st_bbox(st_union(x, y))
box = st_as_sfc(bb)
set.seed(2017)
p = st_sample(x = box, size = 10)
p_xy1 = p[x_and_y]
par(mar= c(0, 4, 0, 2) + 0.1) ## here
plot(box, border = "grey", lty = 2)
plot(x, add = TRUE, border = "grey")
plot(y, add = TRUE, border = "grey")
plot(p, add = TRUE)
plot(p_xy1, cex = 3, col = "red", add = TRUE)
text(x = c(-0.5, 1.5), y = 1, labels = c("x", "y"), cex = 2)
```

![](https://i.imgur.com/FCXCgys.png)

``` r
x_sf = st_sf(text = "x", x)
y_sf = st_sf(text = "y", y)

tm_shape(box) +
  tm_borders(lty = 2, col = "grey70") +
  tm_shape(x_sf) +
  tm_borders() +
  tm_text(text = "text", xmod = -5,
          size = 3) +
  tm_shape(y_sf) +
  tm_borders() +
  tm_text(text = "text", xmod = 5,
          size = 3) +
  tm_shape(p_xy1) +
  tm_symbols(size = 3, col = "red", 
             border.col = "red", shape = 1) +
  tm_shape(p) +
  tm_symbols(size = 0.25) +
  tm_layout(frame = FALSE)
#> Warning: Currect projection of shape box unknown. Long-lat (WGS84) is assumed.
#> Warning: Currect projection of shape x_sf unknown. Long-lat (WGS84) is assumed.
#> Warning: Currect projection of shape y_sf unknown. Long-lat (WGS84) is assumed.
#> Warning: Currect projection of shape p_xy1 unknown. Long-lat (WGS84) is assumed.
#> Warning: Currect projection of shape p unknown. Long-lat (WGS84) is assumed.
```

![](https://i.imgur.com/MXKJbqh.png)

<sup>Created on 2022-02-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Robinlovelace** [comment]
tmap one looking a bit better for me, and matches our emerging 'in house' style, suggest we go with that, great reprex Jakub! One more question: should we make the square outer border, with dashed line, a bit bigger so it's not touching the circles (and do we need a border at all)?

**Comment by Nowosad** [comment]
@Robinlovelace we have two main options:

1. Use {tmap}, but without showing the plotting code
2. Crop the R base plots (see https://geocompr.robinlovelace.net/geometric-operations.html#clipping based on my two recent commits - https://github.com/Robinlovelace/geocompr/commit/1d15002329be36a16bc6b9272eba97d93f46c19e and https://github.com/Robinlovelace/geocompr/commit/5a99f71383b4844596582df0faa465920c2f0e14; see also https://bookdown.org/yihui/rmarkdown-cookbook/crop-plot.html)

**Comment by Robinlovelace** [comment]
Which do you think is better? I guess it depends on how useful the plotting code is (not very is my first thought).
