### ISSUE TITLE
Setting CRS

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#716]
Hey @Robinlovelace -- after your recent additions, we have two sections describing assigning CRSs. Firstly it is mentioned at the end of https://geocompr.robinlovelace.net/spatial-class.html#crs-in-r and then in https://geocompr.robinlovelace.net/reproj-geo-data.html#assigning-coordinate-systems. So I think we should do something -- how about taking some setting CRSs examples from the second chapter and moving them into the seventh one?

**Comment by Robinlovelace** [comment]
Good point and well spotted @Nowosad. Some of the content in C2 was overly detailed and deserves to be in the CRS chapter. See https://github.com/Robinlovelace/geocompr/pull/718, a fairly substantial change so putting in as a PR.
