### ISSUE TITLE
Warning messages

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#724]
Chapter 7 and other chapters now show warning messages due to functions in both `terra` and `raster`. 

![image](https://user-images.githubusercontent.com/1825120/150630361-24400d99-a103-450d-a724-1b05491ca762.png)

We suppress this with `warning=FALSE` in the chunk headers but wondering if this will fix itself in future versions that no longer import `raster`? Tried to reproduce the message:

``` r
library(terra); library(spData)
#> terra 1.5.8
```

<sup>Created on 2022-01-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

``` r
library(sf)
#> Linking to GEOS 3.10.1, GDAL 3.4.0, PROJ 8.2.0; sf_use_s2() is TRUE
library(terra)
#> terra 1.5.8
```

<sup>Created on 2022-01-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Seems to arrive after `spData` is loaded but not sure why I cannot reproduce it, installing the latest version of `spData` doesn't seem to help.

``` r
library(sf)
#> Linking to GEOS 3.10.1, GDAL 3.4.0, PROJ 8.2.0; sf_use_s2() is TRUE
library(terra)
#> terra 1.5.8
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:terra':
#> 
#>     intersect, src, union
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(spData)
```

<sup>Created on 2022-01-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Heads-up @Nowosad.

**Comment by Nowosad** [comment]
These top warnings are just a side effect of some recent raster/terra improvements. See https://github.com/rspatial/terra/issues/485

**Comment by Robinlovelace** [comment]
Great to see fix upstream. I guess it will be another self-fixing bug, let's see if it's fixed in the most recent builds that should arrive today...

**Comment by Robinlovelace** [comment]
Still present in C2 as of builds from today: https://geocompr.robinlovelace.net/attr.html

**Comment by Nowosad** [comment]
It will self-fix -- we just need to wait (maybe) until both raster and terra updates are on CRAN.
