### ISSUE TITLE
Update exercises based on vector geographic data

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#727]

**Comment by Robinlovelace** [comment]
https://github.com/Robinlovelace/geocompr/commit/3b45e2faf4afc9d2139c048c3234431232d870c8

**Comment by Robinlovelace** [comment]
Heads-up @Nowosad I think this issue is basically fixed. Please take a look at the exercises and let me know.

**Comment by Nowosad** [comment]
They should be fine now, after some cleaning. Check how they look at https://geocompr.github.io/solutions/index.html.

**Comment by Robinlovelace** [comment]
Looking great. Your Rmd magic works! One comment, I wonder if 

```
E1 ...
```

Should be:

```
- E1 ...
```

So you get proper bullet points.

**Comment by Nowosad** [comment]
I prefer "E1". Bullet points could add additional formatting issues here.

**Comment by Robinlovelace** [comment]
Another thought: auto convert `E1` to `## E1` on creation of the solutions doc so people can link to the specific solution.

Definitely adds complexity, not a priority, but putting ideas out there...
