### ISSUE TITLE
Blogpost with the list of the geocompr updates

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#728]

**Comment by Robinlovelace** [comment]
Start for 10 from README

https://github.com/Robinlovelace/geocompr/blob/3006011a56974910c224f8d9ce9848711b8c5b3c/README.Rmd#L42-L49

**Comment by Nowosad** [comment]
WIP at https://github.com/geocompr/geocompr.github.io/blob/source/content/post/2022/geocompr2-bp2.Rmd

**Comment by Nowosad** [comment]
Hi @Robinlovelace the blog post at https://github.com/geocompr/geocompr.github.io/blob/source/content/post/2022/geocompr2-bp2.Rmd is now ready for your review and updates.

**Comment by Robinlovelace** [comment]
Great will take a look asap, by end of the day most likely.

**Comment by Nowosad** [comment]
https://geocompr.github.io/post/2022/geocompr2-bp2/
