### ISSUE TITLE
Replace mention of WKT2 with simply WKT

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#729]
See #725

**Comment by Robinlovelace** [comment]
On the case...

**Comment by Robinlovelace** [comment]
Heads-up @Nowosad I was also going to remove most mentions of SRIDs from C7 but then I tested this and found that it is a thing, in `sf` at least:

```
> st_crs(new_vector)$srid
[1] "EPSG:4326"
```

**Comment by Robinlovelace** [comment]
The plot thickens: in this implementation the `srid` is returned as `4326`: https://paleolimbot.github.io/geovctrs/reference/geo_srid.html

**Comment by Nowosad** [comment]
> Heads-up @Nowosad I was also going to remove most mentions of SRIDs from C7 but then I tested this and found that it is a thing, in `sf` at least:
> 
> ```
> > st_crs(new_vector)$srid
> [1] "EPSG:4326"
> ```

I am to blame for this;) - https://github.com/r-spatial/sf/issues/1804

**Comment by Robinlovelace** [comment]
2 way link, can re-open this issue or open a new one on the definition/use of SRID if appropriate: https://github.com/r-spatial/sf/commit/30cccf56895017dafd10ec9771f553fadfc4ae86#r64434503
