### ISSUE TITLE
Submit Part 1 for peer review

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#735]
After conversation with @Nowosad I'm confident this can be done soon. How soon? I've set the updated deadline for the milestone to be end of 2nd week of Feb, can always update it. Can discuss any questions around this submission here, opening as a bit of a meta issue associated with https://github.com/Robinlovelace/geocompr/milestone/8

**Comment by Robinlovelace** [comment]
:tada:

**Comment by Nowosad** [comment]
🥇
