### ISSUE TITLE
Code overflow in data IO code

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#737]
As shown in screenshot below.

![image](https://user-images.githubusercontent.com/1825120/151398714-a86f41ca-e30d-4413-aacc-b29635fa97d6.png)

Source: https://geocompr.robinlovelace.net/read-write.html#iovec

**Comment by akshat-max** [comment]
hey I am new to open source and wanna work on this issue can anyone help me with some good resources.

**Comment by Nowosad** [comment]
Thanks @akshat-max -- for now I decided to change all code examples font sizes to be more consistent with the printed version of the book - https://github.com/Robinlovelace/geocompr/commit/947ba88b962113eb15a3be93c9eaacfc2da52006.
