### ISSUE TITLE
function hyperlinks

### ISSUE THREAD

**Issue by jimr1603** [Robinlovelace/geocompr#740]
https://geocompr.robinlovelace.net/spatial-class.html#an-introduction-to-terra
Whatever automatically made `stack()` into a hyperlink to the manual didn't trigger for `raster()` and `brick()`. 

Short term fix - manually hyperlink.
Longer-term fix - work out why it didn't trigger. 

I'll attempt 1 or the other as a PR

**Comment by Robinlovelace** [comment]
Closed by commits above.
