### ISSUE TITLE
Improve Figure 2.11

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#744]

**Comment by Nowosad** [comment]
https://github.com/Robinlovelace/geocompr/pull/746

**Comment by Nowosad** [comment]
![image](https://user-images.githubusercontent.com/3457131/152683602-05800c8c-d729-4672-a2af-89c924732c49.png)

**Comment by Robinlovelace** [comment]
Looks good but shouldn't the border color be the same in both cases? A thin green line in the left hand figure would do it for me. Overall like it, much clearer.

**Comment by Robinlovelace** [comment]
And maybe the titles could be even more descriptive, e.g.

"Buffer with dist = 1, s2 switched on (default)"

vs

"Buffer with dist = 1, s2 switched off"

**Comment by Nowosad** [comment]
How about now:
![image](https://user-images.githubusercontent.com/3457131/152752477-aa420e12-6d87-45dd-ab33-d86f2db3c136.png)
?

**Comment by Robinlovelace** [comment]
Looks good!

![image](https://user-images.githubusercontent.com/1825120/152882447-9e5c99d3-3fb0-400f-aafd-22a8d6444392.png)

https://geocompr.robinlovelace.net/spatial-class.html#s2
