### ISSUE TITLE
Installing geocompr fails

### ISSUE THREAD

**Issue by stuartE9** [Robinlovelace/geocompr#75]
Installation of each package fails with the message:'Don't know how to decompress files with extension *-*  ' .  Where *-* appears to be the version number of the particular package e.g.  3-23 or 94-5 etc.

I'm using RStudio 1.0.136 (R v3.2.0) on Mac OS X 10.10.5

Thanks for your help - looking forward to reading (contributing?)

Stu

**Comment by Nowosad** [comment]
Hi @stuartE9, thank you for the information. Can you add the whole R output, for example using the reprex package (https://github.com/tidyverse/reprex)?

**Comment by Robinlovelace** [comment]
The package with the trickiest-to-install external dependencies is **sf** so I suggest trying that separately with:

```r
install.packages("sf")
```

Does that work? If not I suggest reading the **sf** README here: https://github.com/r-spatial/sf

**Comment by stuartE9** [comment]
Seems the problem was an out of date version of R.  sf is not available for 3.2 - requires >=3.3. Updated to 3.3, installed sf individually as suggested and everything else went as advertised.  Thanks for the help.  
@Nowosad  - no need to bother you with the output from my earlier efforts - but thanks for pointing me to reprex - wasn't familiar with that one.....

**Comment by Nowosad** [comment]
Great!

**Comment by Robinlovelace** [comment]
Cheers @stuartE9 the feedback is really useful. Anymore issues / suggestions you think of while reading / testing this book project, please feel free to open another issue or Pull Request.
