### ISSUE TITLE
Word 'is' missing in 'this approach more verbose' (chap. 4)

### ISSUE THREAD

**Issue by fBedecarrats** [Robinlovelace/geocompr#760]
Hello,
The verb ("is"?) seems to be missing in the clause "this approach more verbose" in chapter 4.
Thanks for this great book!

**Comment by Robinlovelace** [comment]
Thanks for raising this issue @fBedecarrats, I agree that "is more verbose" would be better (correct). If you have time and inclination, you can try editing the relevant file and putting in a pull request (PR) from this link: https://github.com/Robinlovelace/geocompr/edit/main/04-spatial-operations.Rmd

**Comment by fBedecarrats** [comment]
Correction included in the PR above. Thanks!
