### ISSUE TITLE
3D map with rayshader in chap 09

### ISSUE THREAD

**Issue by defuneste** [Robinlovelace/geocompr#761]
Do you think it is a good idea to add a part in chap 09 Making maps with R about 3D mapping ? 

I am thinking about [rayshader](https://www.rayshader.com/) but maybe other options should be or could be considered. 

If the answer is yes then that brings to more questions: 

- What kind of data are we using and how can a reader access it?  The minimum needed is a DEM but some satellite imagery can also be used.  

- How deep should we go in displaying  uses of this package ? It can range to just mentioning it, to providing one or more reproducible examples.

**Comment by geographyclub** [comment]
The rayshader library uses this line to download data in their usage section:

[download.file](https://rdrr.io/r/utils/download.file.html)("https://tylermw.com/data/dem_01.tif.zip", loadzip)

Does this answer question 1?

**Comment by defuneste** [comment]
> Does this answer question 1?

Yes! Thanks @geographyclub  for pointing that out !  This give us more option. We will probably have to ask Tyler if we use it. 

Reading issue #560 it appears you wanted to contribute but didn't know how to use git. Well, I do not think you need to understand git at first we can just discuss in the issue section (is it fine @Robinlovelace  ?). You can use {reprex} (https://reprex.tidyverse.org/) or just use the github [markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github). Geocompr also have a [discord](https://discord.gg/Te3gWeDwmf) if you prefer and we can start a thread here also. 

One stuff that make Geocompr good is that it go deeper than a "tutorial" and provide both concept and code. I think we have to also go for that with {rayshader}. Sadly my level is not even that of a tutorial (but it can only improve :P).    

On the topic of cesium I am also interested and I think it could be nice too. Should we open an other issue?

**Comment by Robinlovelace** [comment]
> Should we open an other issue?

Not yet is my thinking. Issues are most effective when they are actionable and, to my knowledge, there is no mature R interface to Cesium. This issue is actionable now and {rayshader} is mature.

**Comment by Nowosad** [comment]
Superseded by https://github.com/Robinlovelace/geocompr/issues/882
