### ISSUE TITLE
Chapter 12 failing

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#772]
The .Rds file in this code chunk is not there: 

https://github.com/Robinlovelace/geocompr/blob/fbae3cf39ae9dbd235bd34a3c64ef7fc662dbd93/12-spatial-cv.Rmd#L456-L459

Heads-up @jannes-m

**Comment by Robinlovelace** [comment]
Also I see this in the Docker build:

```
#6 426.9 Quitting from lines 457-460 (12-spatial-cv.Rmd) 
```

Must be the same thing, but I thought that was fixed in the latest commit :confused:

**Comment by Robinlovelace** [comment]
https://github.com/geocompr/docker/runs/6066668837?check_suite_focus=true#step:8:8291

**Comment by Robinlovelace** [comment]
Update: should be fixed soon, just due to the timings of Docker builds. Still, would be good to be able to fix the code so it runs.

**Comment by jannes-m** [comment]
yes, I know, I haven't uploaded it since I was only testing if I get rid of the benchmark rds problem when knitting by only saving the scores as a data.table. You were just so quick to merge. Another thing I need to do is replace the old svm results by new mlr3 svm results.

**Comment by jannes-m** [comment]
working on it, see #777
