### ISSUE TITLE
Re-lable figures

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#775]
After running `bookdown::serve_book()` I get the following warnings, @Nowosad is up for taking a look:

```
Warning messages:
1: The label(s) rsaga, rgrass not found 
2: The label(s) rgrass not found 
3: The label(s) rsaga not found 
4: The label(s) fig:boxplot-cv not found 
5: The label(s) spatial-cv-with-mlr not found 
6: The label(s) rgrass not found 
7: In fun(libname, pkgname) :
```

**Comment by jannes-m** [comment]
will take care of spatial-cv-with-mlr and fig:boxplot-cv, thanks for noting

**Comment by jannes-m** [comment]
ok, I have taken care of the spatial-cv-with-mlr and fig:boxplot-cv labeling issues

**Comment by Nowosad** [comment]
Great. `rsaga` and `rgrass` will be fixes in the next few months.
