### ISSUE TITLE
File from Zenodo failing to download

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#778]
As mentioned in #776 this is failing: https://zenodo.org/record/5774954/files/clm_snow.prob_esacci.dec_p.90_500m_s0..0cm_2000..2012_v2.0.tif

Can you upload the data to the book's releases @jannes-m ? Or we could put the file elsewhere...

**Comment by Nowosad** [comment]
This is a file from chapter 8. I think this is a temporary zenodo issue.

**Comment by Nowosad** [comment]
I will look at a fix tomorrow (if the issue persists)
