### ISSUE TITLE
Update links to solutions

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#779]
To new site: https://geocompr.github.io/solutions/

Context: https://geocompr.github.io/post/2022/geocompr-solutions/

I'm on the case!

**Comment by Robinlovelace** [comment]
Looking at this now...

**Comment by Robinlovelace** [comment]
Seems there are not many links to solutions. Planning to update some other URLs and link to the solutions book from the landing page and the README.

**Comment by Robinlovelace** [comment]
Heads-up @Nowosad and @jannes-m this issue is now done but I wonder, is it worth linking to the solutions at the end of each chapter? I guess so.

**Comment by Nowosad** [comment]
Yes, but probably only for the html version?

**Comment by Robinlovelace** [comment]
Agreed :+1:
