### ISSUE TITLE
Reviews - edition 2, round 1, reviewer 1

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#785]
- [x] [RL] p.9 - FIGURE 1.2 - It may be useful to cite the source of the figures on pkg downloads (it must be cranlogs, so
only downloads through Rstudio?).

We now mention the origin of the downloads data.

- [x] [RL,JN] p.12 - "As of 2018 map making in R is a hot topic with dedicated packages such as tmap, leaflet and mapview all supporting the class system provided by sf, the focus of the next chapter (see Chapter 9 for more on visualization)." It may be useful to link directly to the relevant chapter (I don’t think it is the next one).

We have updated this section.

- [x] [RL] p.13 - questions E3 & E4 - These 2 questions does not seem related to the content of the chapter.

E3 has been updated to make it more relevant. E4 has been removed.

- [x] [RL] p.17 - All the packages needed to reproduce the contents of the book can be installed with the following command: remotes::install_github(“geocompr/geocompkg”) . Perhaps add something about the purpose of remotes package.

We have updated the text to explain what the **remotes** package does. We have also mentioned the `dependencies = TRUE` argument which will download additional dependencies needed to reproduce subsequent chapters.

- [x] p.20 - "A neat feature of sf is that you can change switch the default geometry engine used on unprojected data: ‘switching off’ S2 can be done with the command..." Typo: use either “switch” or “change”. 
- [x] Hyperlinks are made for S2 and s2 but not for GDAL, GEOS and PROJ.

This has been fixed: https://github.com/Robinlovelace/geocompr/commit/dedbc5c31b93a76ea5996121e340ff5f335830de

- [x] [RL,JN] p.21 - "All 18 types can be represented with the sf package, although (as of summer 2018) plotting only works for the ‘core 7’. (note 3)" What is the situation in 2022 ?
- [x] [RL] p.27-  "Plots are added as layers to existing images by setting add = TRUE . 4 To demonstrate this, and to provide a taster of content covered in Chapters 3 and 4 on..." I think “taster” is a very British specific word.
- [x] [RL,JN] p.29 - plot(world_asia[0], add = TRUE) The use of obj[0] is a bit arcane. Is it documented somewhere? What is the benefice of using this instead of the more explicit and more often used st_geometry()?
- [x] [RL] p.37 - v_sfg_sf = st_point(v, c(1, 2)) - c(1,2) is not useful here.
- [x] [JN] p.44 - Dedicated functions report each component: dim(my_rast) returns the number... Use dim() instead of dim(obj) (as it is later done for ncell(), res()...)
- [x] [?] p.46 - Note 10 may worth a proper example.

The note is now:

```
The `[[` and `$` operators can also be used to select layers, for example with commands `multi_rast$landsat_1` and `multi_rast[["landsat_1"]]`.
```

- [x] [RL] p.59 - "The alternative to %>% is nested function calls, which is harder to read: ..." The alternative is, actually more often, rather to have multiple lines with multiple assignations instead of nested functions. Also, drawback of using the pipe: it is harder to obtain and inspect intermediate results.

We now include an alternative-to-pipe example:

```
world9_filtered = filter(world, continent == "Asia")
world9_selected = dplyr::select(world9_filtered, continent)
world9 = slice(world9_selected, 1:5)
```

Furthermore we provide more context-specific guidance: https://github.com/Robinlovelace/geocompr/commit/63908348ded498fa8acac3721233f3f0eef0bf58
- [x] [RL] p.61 - world_agg4 = world %>% group_by(continent) %>% summarize(pop = sum(pop, na.rm = TRUE), `area (sqkm)` = sum(area_km2), n = n()) I would personally not encourage using space in data.frame col names (area (sqkm))
- [x] [RL] p.65 - Note on data.table - This note could be also/rather added to the first appearance of data.table p.55.
- [x] [RL] Perhaps add tidyr requirement in p.53 as it is needed at some point in the chapter.

Good point. We now also mention that tidyr is part of the tidyverse early in the chapter and that readers may want to install these packages. See https://github.com/Robinlovelace/geocompr/commit/f45a07c72301d44e13e670ba0a35f39ff0f86267 for the full set of changes in relation to this much-appreciated comment.

- [x] [JN] p.68 "For example, c(elev, grain)[1] returns a data frame with one row and two columns..." It could be useful to add as a reminder that c(rast1,rast2) creates a multilayered raster
- [x] [JN] p.69 two_layers = c(grain, elev) two_layers[1] = cbind(c(0), c(4)) two_layers[] The second line is not working on my computer (terra_1.5-21, GEOS 3.9.0, GDAL 3.2.2, PROJ 7.1.0) -- https://github.com/rspatial/terra/issues/625
- [x] [JN] p.72 E16 I’m not sure about modal(). Shouldn’t it be used with multilayered rasters ?
- [x] [RL] p. 74 "The type of spatial relationship between objects must be considered when undertaking spatial operations, as described in Section 4.2.2, on topological relations between vector features. . " Typo, the sentence ends with 2 “.”.

Fixed in https://github.com/Robinlovelace/geocompr/commit/ad199d9b079a45a0d6f497513b84ec716c15cc11

- [x] [JN] Map algebra covers a range of operations that modify raster cell values, with or without reference to surrounding cell values, is vital for many applications. Split this in 2 sentences?
- [x] [RL] p.81 4.2.3 DE-9IM strings You could state earlier in that part why it can be useful to know about this (e.g. create your own spatial predicate). It could help to keep the reader interest up in this not so easy part.

This is now done in https://github.com/Robinlovelace/geocompr/commit/be0eba1126fa3a2c143fc4b3969614e8e8d0436c and the previous commit.

- [x] [RL] p.89 "The resulting nz_agg objects have the same geometry as the aggregating object nz but with a new column summarising the values of x in each region using the function mean() (which cold, of course, be replaced by median() , sd() and other functions that return a single value)." typo: cold > could
- [x] [RL] p.90 agg_aw = st_interpolate_aw(iv, aggregating_zones, ext = TRUE) It could be better to use the full name of the argument ext => extensive.
- [x] [JN] p.93 "This can be done using the [ operator, with drop = FALSE , as outlined in Section 3.3, which also shows how raster objects can be subsetted by various objects. ..." drop = FALSE is not explicitly explained (not in 3.3 nor in this chapter).
- [x] [JN] "The location of cells in raster datasets can be calculated it using its matrix position and the resolution and origin of the dataset (stored in the header)." Typo: extra “it”.
- [x] [JN] p.97 "we can easily retrieve space- or airborne" Typo “-” ?
- [x] [JN] p.100 "of Figure 3.2)" Typos, extra “)”, twice.
- [x] [JN] "The output is shown in Figure 3.2)." The output is shown below, and not in a figure, I think.
- [x] [JN, JM] p.102-103 "E5, E7 and E8" These are notably harder than others exercises
- [x] [JN] p.107 us_states2163 = st_transform(us_states, 2163) Perhaps use “EPSG:2163”” instead of “epsg = 2163”.
- [x] [JN] p.108 us_states2163$AREA = as.numeric(us_states2163$AREA) I don’t think this operation is needed here.
- [x] [RL,JN] p.116 "It is implemented in the st_cast function from the sf package. Importantly, st_cast behaves differently on single simple feature geometry ( sfg ) objects, simple feature geometry column ( sfc ) and simple features objects." Typo, unify the use of parenthesis for function names (function_name()), st_cast => st_cast().
- [x] [JN,JM] p.120 "Of course, this is only possible if the task at hand allows a coarser resolution. Sometimes a coarser resolution is sufficient for the task at hand." This part is unclear.
- [x] [JN] p.121 "Fol- lowing code adds one row and two columns to each side of the raster while setting all new values to an elevation of 1000 meters (Figure 5.13). while setting all new values to an elevation of 1000 meters" The code that follows does not set all new values to 1000 meters.
- [x] [JN] p.122 "The newly added rows and column receive the default value of the value parameter, i.e., NA ." I don’t see where the value arg can be set.
- [x] [RL] p.128 E5 It is unclear what p, x and y are. It could be better to use “real” data in this exercice.

The exercise has been updated to make it clear what we're referring to here. See https://github.com/Robinlovelace/geocompr/commit/7d6f8376c2d6e015cd806762ffdb3ecde4bcdf68 for details.

- [x] [JN, @kadyb] p.130 "srtm_cropped = crop(srtm, vect(zion))" vect() has not been introduced. It could be good to add a small text about vector representation in terra ad perhaps earlier in the book.

We now describe `vect()`. See https://github.com/Robinlovelace/geocompr/commit/250daff61a93b66599bc3f91be51ece383572f82. Also see #780 for discussion of a new section on **terra**'s vector class system (we're not sure we will write about it but like the idea).

- [x] [JN] p.139 "As illustrated in Figure 6.8, isolines can be labelled." It could be nice to add a link to an example of such operation. -- JN: we plan to add such example to chapter 9
- [x] [JN] p.140 grain = rast(system.file("raster/grain.tif", package = "spData")) grain_poly = as.polygons(grain) %>% st_as_sf() It could be good to make the use of dissolve arg explicit as it is used with both TRUE & FALSE in fig 6.9
- [x] [JN] p.144 "The short answer is that the third way to identify CRSs is correct: EPSG:4326 is understood by sf (and by extension stars) and terra packages R covered in this book, plus many other software projects for working with geographic data including QGIS and PROJ." Typo: remove “R”.
- [x] [RL] p.149 "The output is the WKT representation of CRS. The same function, crs(), is can be also used to set a CRS for raster objects." Typo: remove “is”.
- [x] [RL] p.152 Notable components of this CRS description include the EPSG code ( EPSG: 27700 ), the projection (transverse Mercator, +proj=tmerc ), the origin ( +lat_0=49 3 +lon_0=-2 ) and units ( +units=m ) It may be better to not use proj4string notation here.

Good point. Fixed and improved in https://github.com/Robinlovelace/geocompr/commit/f2b7b41a95762cd905928b9cc01c36a1b43053be

- [x] [RL] "The less is that results obtained from lon/lat data via s2 will be different from results obtained from using projected data, although these differences reduce as the value of max_cells increases: the ‘right’ value for this argument may depend on many factors and the default value 1000 is a reasonable default, balancing speed of computation against resolution of results, in many cases." This part is not very clear. It may be useful to split it in different sentences.

Agreed, the updated prose is much clearer thanks to this comment: https://github.com/Robinlovelace/geocompr/commit/f1d079762f20de9309c12745b1764c91aac8c7b9

- [x] [JN] p.155 "Currently, we also have tools helping us to select a proper CRS, which includes the crssuggest package ." Typo, extra space at the end.
- [x] [JN] "Important note: while these tools is helpful in many situations, you need to be aware of the properties of the recommended CRS before you apply it. " Typo, “these tools is” => “these tools are”
- [x] [RL] p.157 "This is demonstrated below with reference to cycle_hire_osm , an sf object from spData that represents ‘docking stations’ where you can hire bicycles in Lon- don." It is not clear what is demonstrated below (“This?“).
- [x] [RL] p.158 #> [1] "crs" #> [1] "input" "wkt" The code producing this output is not visible. 
- [x] [RL] crs_lnd$Name #> [1] "WGS 84" ... It is not shown how crs_lnd is created.
- [ ] [RL,JN] p.164 " st_transform_proj() from the lwgeom package allows for coordinate  transformations to a wide range of CRSs, including the Winkel tripel projection:" It could be useful to describe when using lwgeom::st_transform_proj() instead of st_transform() is needed.
- [x] [JN] p.182 "The above example just shows one simple (but useful) case, but there is more to explore. The /vsicurl/ prefix also works not only for raster but also for vector file formats allowing to read vectors directly from online storage. Importantly, it is not the only prefix provided by GDAL – many more exist, such as /vsizip/ to read spatial files from ZIP archives without decompressing them beforehand or /vsis3/ for on-the-fly reading files available in AWS S3 buckets. You can learn more about it at https://gdal.org/user/virtual_file_systems.html" It is not clear if this method can be used with sf for vector files. If yes how?
- [x] [JN] p.183 "Instead of overwriting the file, we could add a new layer to the file with append =TRUE , which is supported my several spatial formats, including GeoPackage." append = TRUE add features to an existing layer, it does not add a new layer. Typo, “is supported my several” => “is supported by several”
- [x] [RL] E2. Name at least two differences between read_sf() and the more well-known function st_read(). read_sf() is used extensively and became well-known to the reader, not st_read().

**Comment by Robinlovelace** [comment]
Impressive list of useful suggestions and good progress on tackling them. Next lot of reviewer comments incoming, sorry I took a long time to get on the case, busy days at work!

**Comment by Robinlovelace** [comment]
Heads-up guys I'm working on this now, need to get the review responses submitted!

**Comment by Nowosad** [comment]
Hi @Robinlovelace -- I plan to work on some of the issues during the weekend.

**Comment by Robinlovelace** [comment]
Great stuff Jakub, let's get the responses sent asap and then move on to the (hopefully easier but still tricky) Part II.

**Comment by Robinlovelace** [comment]
Heads-up @Nowosad and @jannes-m all the issues that I think were well suited to me (and one of Jakub's I did) are now fixed. I'm going to relax! Please take a look at this, I think we will be able to close this mega issue soon :crossed_fingers:

**Comment by Nowosad** [comment]
" [RL,JN] p.164 " st_transform_proj() from the lwgeom package allows for coordinate transformations to a wide range of CRSs, including the Winkel tripel projection:" It could be useful to describe when using lwgeom::st_transform_proj() instead of st_transform() is needed." -- I  looked for any document/website showing the differences between GDAL->PROJ (`st_transform()`) and directly PROJ (`st_transform_proj()`), however I was unable to find anything...

**Comment by Robinlovelace** [comment]
Maybe we should add some test code with `echo=FALSE, eval=FALSE` to check if they're the same. I sense you know this area better than me Jakub.

**Comment by Robinlovelace** [comment]
> Maybe we should add some test code with `echo=FALSE, eval=FALSE` to check if they're the same. I sense you know this area better than me Jakub.

Heads-up @Nowosad I'm looking at this now.
