### ISSUE TITLE
 Reviews - edition 2, round 1, reviewer 2

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#787]
- [x] [RL] -- p. 17, prerequisites—it might be worth noting what version of R is “an up-to-date version of R” at
the time of publication.
- [x] [RL] -- p. 21, footnote—you wrote “as of summer 2018”—can this note be updated for the 2nd edition
and 2022?
- [x] [RL] -- p .61, Table 3.2—It seems to be ordered by the number of countries, not by population density.
- [x] [RL] --p. 89, main paragraph—“which cold, of course, be replaced” should be “which could, of course, be
replaced”
- [x] [RL] --p. 130—The first paragraph refers to “Section 7” which ought to be “Chapter 7”.
- [x] [RL] --p. 147----In the middle paragraph, “is a an sf data frame” should have either “a sf data frame” or
“an sf data frame”, depending on how your style guide approaches this.
- [x] [RL] --p. 152—last paragraph, middle—“The less is that” should be “The lesson is that”
- [x] [JN] --p. 168—The USGS is the United States Geological Survey, not Service.
- [x] [JN] --p. 183 —in the middle of section 8.7.1, “is supported my several spatial formats” should be “is
supported by several spatial formats”.
- [x] [RL] --p. 222—towards the end of the page, “a range of unusual maps including choropleth”. I’m not sure
I’d call choropleth maps unusual, as they are pretty common!
Information Classification: General
- [x] [RL] --p. 242—Towards the end of the page, should “Hello real word” be “Hello real world”?
- [x] [RL] --p. 287—At the end, you refer to “an ambitious plan to double the share of cycling by 2020” which
is at best awkward phrasing for a book being published after 2020.
- [ ] [RL] --p. 344—Section 16.4.1 is simply “TODO"

**Comment by Robinlovelace** [comment]
Great work on your issues Jakub! :fire:

**Comment by Nowosad** [comment]
👍🏻
