### ISSUE TITLE
Update code when rmapshaper is updated on CRAN

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#789]
With this message, which I can reproduce locally:

```
Quitting from lines 98-101 (05-geometry-operations.Rmd) 
Error: No method asJSON S3 class: units
Execution halted

Error in Rscript_render(f, render_args, render_meta, add1, add2) : 
  Failed to compile 05-geometry-operations.Rmd
Calls: <Anonymous> -> render_new_session -> Rscript_render
Execution halted
Error: Process completed with exit code 1.
```

**Comment by Nowosad** [comment]
I assume that we either need the dev version of https://github.com/ateucher/rmapshaper or made a change to the code...

**Comment by Robinlovelace** [comment]
Or wait until `rmapshaper` is on CRAN. Do you have an ETA for that @ateucher?

**Comment by ateucher** [comment]
I was going to wait until I had done a few more bigger things, but I'm happy to fast-track a patch update. I'll see if I can get to it this weekend.

**Comment by Robinlovelace** [comment]
Thanks Andy, I think it's worth it, but only if you get sufficient free time!

**Comment by ateucher** [comment]
rmapshaper 0.4.6 (with your units fix) is on its way to CRAN 😃
