### ISSUE TITLE
clarrification on ch05 text describing table 5.1

### ISSUE THREAD

**Issue by defuneste** [Robinlovelace/geocompr#798]
Hi @Robinlovelace and @Nowosad 

I have trouble understanding few sentences describing table 5.1 in chp 05 . 

This one is difficult: https://github.com/Robinlovelace/geocompr/blob/main/05-geometry-operations.Rmd#L524

> Each input simple feature object with only one element (first column) is transformed directly into another geometry type.  

And this one is maybe incomplete : 

>  You can see that, for example, when you cast a multipoint consisting of five pairs of coordinates into a point.

here : https://github.com/Robinlovelace/geocompr/blob/main/05-geometry-operations.Rmd#L524

++

**Comment by Robinlovelace** [comment]
As discussed on Discord, a good next step could be to chat it over. I would be up for that at some point next week. 

Link to the content online: https://geocompr.robinlovelace.net/geometric-operations.html#tab:sfs-st-cast

And permalink to the source code:

https://github.com/Robinlovelace/geocompr/blob/fe65a3a0255b06bbb4860fa91009496f5d124fbb/05-geometry-operations.Rmd#L519-L549

**Comment by Nowosad** [comment]
Hi guys -- please look at https://github.com/Robinlovelace/geocompr/pull/799 and let me know what you think.

**Comment by Robinlovelace** [comment]
Looking better. Suggested changes building on your changes here Jakub: https://github.com/Robinlovelace/geocompr/pull/800/files

A couple of points: in the table it is not clear what each input and output is, are they `sfc` objects of different lengths (number of rows when in `sf` data frames)?

And the word 'element' is not clear. I think '`sfg` object' could be clearer.

**Comment by Nowosad** [comment]
The inputs are based on the objects from https://github.com/geocompr/geocompr.github.io/blob/source/content/post/wip/casting-geometries-extended.Rmd.
So -- the first column represents input objects (with various geometry types), and all of the rest columns is "what will happen if you type transform the input object to some other geometry".

**Comment by Robinlovelace** [comment]
According to comments by @defuneste here https://github.com/Robinlovelace/geocompr/pull/799#issuecomment-1126802887 this seems fixed. Thanks for reporting and for the quick fix!
