### ISSUE TITLE
Error line 667: missing classif.auc ((12-spatial-cv.Rmd) 

### ISSUE THREAD

**Issue by Altmic** [Robinlovelace/geocompr#802]

**Comment by Robinlovelace** [comment]
Hi @Altmic thanks for opening the issue. Can you provide a few more details: what have you tried? All the code seems to be reproducible and I cannot immediately see what could be causing the issue from these lines:

https://github.com/Robinlovelace/geocompr/blob/f7ed39b58eb3a661708497318219647f9f323996/12-spatial-cv.Rmd#L662-L667

**Comment by Altmic** [comment]
Thank  you very much. I’m a very beginner, but interested in Rmarkdown and Rbookdown (I’m a retired MD and working a little in descriptive statistics to organize the data of my old institute).
The former error message has disappeared, but unfortunately I get a new one.

----------
Quitting from lines 494-499 (13-transport.Rmd) 
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'weightfield' for signature '"NULL"'
Calls: local ... eval_with_user_handlers -> eval -> eval -> weightfield -> <Anonymous>

Execution halted
Error in Rscript_render(f, render_args, render_meta, add1, add2) : 
  Failed to compile 13-transport.Rmd

——————
Thank you very much

Michael

**Comment by Robinlovelace** [comment]
> The former error message has disappeared, but unfortunately I get a new one.

What's the new one? Any feedback is welcome.

**Comment by babayoshihiko** [comment]
> It appears that the GLM\index{GLM} (aggregated AUROC\index{AUROC} was `r score[resampling_id == "repeated_spcv_coords" & learner_id == "classif.log_reg", round(mean(classif.auc), 2)]`) is slightly better than the SVM\index{SVM} in this specific case.

`r score[score$resampling_id == "repeated_spcv_coords" & score$learner_id == "classif.log_reg", round(mean(score$classif.auc), 2)]`

may fix the problem.

**Comment by jannes-m** [comment]
It is not necessary to write `score$column_name` since we are using **data.table** syntax here

**Comment by Robinlovelace** [comment]
Thanks Jannes and all, I cannot see any clear issue here so would suggest we close, unless there's a clear reproducible example and suggestion of a fix.

**Comment by babayoshihiko** [comment]
I had the same problem. Prefixing `score$` caused another error:


```
Quitting from lines 667-698 (12-spatial-cv-ja.Rmd) 
Error in `[.data.frame`(score, resampling_id == "repeated_spcv_coords" &  : 
  object 'resampling_id' not found
Calls: local ... hook_eval -> withVisible -> eval -> eval -> [ -> [.data.frame
Execution halted
Error in Rscript_render(f, render_args, render_meta, add1, add2) : 
  Failed to compile 12-spatial-cv-ja.Rmd
Calls: <Anonymous> -> render_new_session -> Rscript_render
Execution halted
make: *** [html] Error 1
Error in render_book_script(output_format, envir, quiet) : 
  Error 2 attempting to render book
Calls: <Anonymous> -> <Anonymous> -> in_dir -> render_book_script
Execution halted

Exited with status 1.
```

So I prefixed `score$` to resampling_id and so on. Mow build is successful.

My environment: macOS 12, R 4.2.0 with the latest packages. I forked and cloned the repo last week.

I guess RStudio (or bookdown) may be treating inline codes differently to code blocks. But I am not sure.

**Comment by jannes-m** [comment]
OK, strange, will remember this when working again on this chapter. Thanks for letting us know.
Note to myself: incorporate **mlr3spatiotempcv** API changes, see https://github.com/mlr-org/mlr3spatiotempcv/pull/199
