### ISSUE TITLE
Update the transport chapter's coverage of routes

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#814]
There are some issues with the Routes section of Chapter 13: https://geocompr.robinlovelace.net/transport.html#routes

- [x] It uses a now obsolete class, causing the build to fail #809 
- [x] The wording could be improved and brought more up-to-date, including mention of `r5r`, heads up @rafapereirabr and any other comments on the section welcome
- [x] The example is way too small compared with the rest of the chapter

I'm on the case.

**Comment by rafapereirabr** [comment]
Hi @Robinlovelace . Thanks for the heads up. The section looks really good and covers a lot of ground. Two quick comments:
1. I understant the section does not intend to present a comprehensive list of routing packages in R, correct? In any case, here are a few other packges that immediatly cross my mind [cyclestreets](https://cran.r-project.org/web/packages/cyclestreets/index.html), [mapboxapi](https://cloud.r-project.org/web/packages/mapboxapi/index.html), [hereR](https://cran.r-project.org/web/packages/hereR/index.html), and [gtfsrouter](https://cran.r-project.org/web/packages/gtfsrouter/index.html).
2. I think it's important to acknowledge that some routing packages (such as OTP and r5r) allow for multimodal routing. On a side note, the next version of r5r will allow users to account for both travel time and monetary costs in public transport trips.

finally, congrats on the amazing work you're building with this book ! I recommended it all the time to students and colleagues

**Comment by Robinlovelace** [comment]
Thanks for the feedback @rafapereirabr, it's not intended to be comprehensive but should provide guidance that is as future-proof as possible. In fact this issue has not yet been fixed so reopening! Thanks for the suggestions, agreed, and really glad to hear this book is of use/interest to you colleagues!
