### ISSUE TITLE
Error messages when building book

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#817]
I'm seeing this error message on `bookdown::serve_book()` after all the chapters have been build successfully. Not sure why, I don't think it should be happening as I have all packages installed with `remotes::install_github("geocompr/geocompkg", force = T, repos = T)` so opening as an issue:

```
Tweaking _book/index.html
Error in loadNamespace(name) : there is no package called ‘rstac’
```

It happened for:

- [x] **rstac**
- [x] **Rsagacmd**
- [x] **tidygeocoder**
- [x] **gdalcubes**
- [x] **whitebox**
- [x] **openeo**

After installing them, one-by-one and trying to build the book after each fresh install, I finally got it working. Do we need to update the dependencies in **geocompkg**?

**Comment by Robinlovelace** [comment]
I think the thing that unites all of these is that they are used in the book but with `eval=FALSE`. Not 100% sure. Thoughts @Nowosad ?

**Comment by Robinlovelace** [comment]
This is now the reason the build is failing I think. I'm going to add those packages to geocompkg.

**Comment by Nowosad** [comment]
**bs4_book** fails when any package mentioned in code chunks (even unevaluated ones) are missing. I tried to find a solution on how to disable it a few months ago, but I was unable to find anything...

**Comment by Robinlovelace** [comment]
Hmmm I guess we could mention them in chunks without {r}, surely that would not trigger the dependency? In any case this is the interim attempt at a fix: https://github.com/geocompr/geocompkg/commit/9533c57f0b98f1f47c191d5c18ee03c81a48e965

**Comment by Robinlovelace** [comment]
Plan to remove dependency on ows4R as it depends on rgdal and seems to be causing issues.

**Comment by Robinlovelace** [comment]
Not sure why it's complaining because the package is in geocompkg suggests: https://github.com/Robinlovelace/geocompr/runs/7161855940?check_suite_focus=true

**Comment by Robinlovelace** [comment]
These are in geocompkg Suggests so closing for now. We can re revisit later.
