### ISSUE TITLE
Another error message in C15

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#823]
I've just hit another issue in Chapter 15:

```
Quitting from lines 539-548 (15-eco.Rmd) 
Error in eval(parse_only(code), envir = envir) : 
  object 'autotuner_rf' not found
```

Source: https://github.com/Robinlovelace/geocompr/runs/7160508645?check_suite_focus=true#step:4:9413

**Comment by Robinlovelace** [comment]
I can also reproduce this locally: 

![image](https://user-images.githubusercontent.com/1825120/176991361-d1231538-190f-4c6e-8a64-be86eec2744b.png)

**Comment by jannes-m** [comment]
yep, sorry, I should have let run the `bookdown::preview_chapter()` function. Obviously, some code chunks have been set to remain unevaluated, most likely as a workaround to make the build process work again. 954f262e should fix it.

**Comment by Robinlovelace** [comment]
Great stuff, thanks Jannes. Note: I commented out a load of in-line code also, search for `"r #"` and you will find!

**Comment by jannes-m** [comment]
Ah OK, will take care of this tomorrow

**Comment by Nowosad** [comment]
@jannes-m the issue seems to still be with us -- https://github.com/Robinlovelace/geocompr/runs/7247832360?check_suite_focus=true#step:4:9383

**Comment by jannes-m** [comment]
Should be OK now, thanks for noting!
