### ISSUE TITLE
Update Chapter 5: reference `smoothr` and fix intro

### ISSUE THREAD

**Issue by Lvulis** [Robinlovelace/geocompr#830]
One fix and one suggestion came up while going through Chapter 5:
- The introduction refers to vector-raster interaction as Section 6, it should be Chapter 6. I wrote a draft changed sentence as it sounds odd to refer it as "final Section 6". Changed sentence (can PR this with next item below): `The interaction between raster and vector objects is covered in Chapter \@ref(raster-vector). `
-  The `smoothr` [package](https://strimas.com/smoothr/) offers nice ways to smoothen linestring and polygon geometries. It is not  simplifying, as it doesn't necessarily lead to less vertices, but it can help smooth out pixelated boundaries of geometries that are generated by spatial vectorization and leads to something "like" simplifying. The package implements different smoothing operators like splines and Gaussian kernel regression on the coordinates {(_x_, _y_)} independently by treating _x_ as _x(s)_ and _y_ as _y(s)_ where _s_ is the distance along the ring or line. It doesn't preserve topology but does make things look better for certain visualizations. I have used it for example to smooth pixelated shorelines before computing some shape metrics. It could be referenced in Chapter 5.2.1 and then back-referenced in Chapter 6 for spatial vectorization. 
Some initial text for `smoothr` if it were to be included before the comparison figure in 5.2.1 is below. It would necessitate some rewriting of the final part to compare both smoothing + simplification in one section. 
`An alternative to simplification is smoothing the boundaries of polygons and linestrings.
This doesn't necessarily lead to less vertices, but it can reduce the pixelated boundaries of geometries that arise from spatially vectorizing a raster (a topic covered in Chapter \@ref(raster-vector))`.

**Comment by Nowosad** [comment]
@Lvulis both suggestions are great -- feel free to make a PR.

**Comment by Nowosad** [comment]
@Robinlovelace -- now we use the **smoothr** package -- should we add it to **geocompkg**?

**Comment by Robinlovelace** [comment]
> @Robinlovelace -- now we use the **smoothr** package -- should we add it to **geocompkg**?

Yes good plan. It's worth adding **sfnetworks** also before #826 is merged.

**Comment by Lvulis** [comment]
May want to add **exactextractr** as its used for the exercises in Ch. 6 now, but it isn't needed to render text itself.

**Comment by Robinlovelace** [comment]
> May want to add **exactextractr** as its used for the exercises in Ch. 6 now, but it isn't needed to render text itself.

**exactextractr** should be in the Suggests field I think.

**Comment by Lvulis** [comment]
Sounds good.

**Comment by Robinlovelace** [comment]
> @Robinlovelace -- now we use the **smoothr** package -- should we add it to **geocompkg**?

@Nowosad now in there! See commit in the link above.
