### ISSUE TITLE
Chapter 8 fixes

### ISSUE THREAD

**Issue by Lvulis** [Robinlovelace/geocompr#833]
Went through chapter 8 and had 2 small issues running the code in the very beginning of the chapter. Submitting a related PR to address this.

- For the first public codeblock demonstrating how to use R to download data, the end of the URL for the `nps_boundary.shp` file has changed from 666527 to 673366 (now [https://irma.nps.gov/DataStore/DownloadFile/673366](https://irma.nps.gov/DataStore/DownloadFile/673366). Old URL redirects to an html page.
- On Windows I had to use the argument `mode = "wb"` in `download.file()` to get the zip file to not be corrupted. Not doing this neither Windows Explorer nor R were able to open the .zip file, while downloading it from a browser seemed to work just fine. See accepted answer here which provided the solution https://stackoverflow.com/questions/23899525/using-r-to-download-zipped-data-file-extract-and-import-csv?noredirect=1&lq=1

**Comment by Nowosad** [comment]
Hi @Lvulis -- thanks for fixing the link. I updated it a few months ago, and it changed again... Do you, maybe, have a recommendation for a better (more stable) example link?

**Comment by Lvulis** [comment]
Also tried to explicitly look for things and didn't have much luck. Another possibility that just clicked for me is a [paper's repository](https://doi.pangaea.de/10.1594/PANGAEA.868349?format=html#download) of shapefiles of permafrost zonation and associated ecogeomorphic information in various Arctic regions. The permafrost landscapes zip is the one that's probably most interesting/applicable and not a huge file (80 MB). There's 4 sets of shapefiles inside, one for Russia, one for Canada, one for USA (alaska only), and one only for the study sites (labelled PeRL). The PeRL one has around 1000 features while the others have 8k or more, so might be best. Also Pangaea is a stable repository as far as I know, it is where some of the German groups share their data.

Here's the code snippet and maybe you can take a look if the dataset is suitable. 
```R
download.file(url = "https://hs.pangaea.de/Maps/PeRL/PeRL_permafrost_landscapes.zip",
              destfile = "PeRL_permafrost_landscapes.zip", 
              mode = "wb")
unzip(zipfile = "PeRL_permafrost_landscapes.zip")
perl_permafrost = read_sf("PeRL_permafrost_landscapes/perl_perma_land.shp")
```

**Comment by Nowosad** [comment]
Thank you @Lvulis -- https://github.com/Robinlovelace/geocompr/commit/024650206f6a5c5a5026cc2c62703112371514e7
