### ISSUE TITLE
More ways to get involved

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#857]
I'm thinking that there are at least 2 other ways that people can support the project:

- [x] Help out with community translations
- [x] Get involved asking and answering questions on Discord and just sharing info

![image](https://user-images.githubusercontent.com/1825120/187088551-a96c8fbb-1bf0-499f-81e5-b0d848f3a700.png)

**Comment by Robinlovelace** [comment]
From the landing page: https://geocompr.robinlovelace.net/

**Comment by defuneste** [comment]
Would be good to help with translations! You can probably add also contribute to issue (I guess it is also on point 6).

**Comment by Robinlovelace** [comment]
Working on this now on my Saturday morning Geocompr session...
