### ISSUE TITLE
Remove cache=TRUE

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#858]
Issue: it causes frequent build errors related to `terra` objects involving pointers.

Options:

- Remove this line:

https://github.com/Robinlovelace/geocompr/blob/860bc0ecdbbc143cdb8855db02ce646cf542ae9b/code/before_script.R#L7

- Make the problematic chapters only with `cache=FALSE`

My first thought is the former to keep it simple but happy to hear other thoughts.

**Comment by Nowosad** [comment]
I assume this is your local issue? (I've never seem this problem on GHA). If so -- yep; we can disable the cache.

**Comment by jannes-m** [comment]
My guess is that the problem arises if you build the book multiple times like you do in an interactive session but never with GHA.
