### ISSUE TITLE
'Final' improvements to transport chapter

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#861]
Split-out from #835 

- [x] Improve exercises and add solutions
- [x] Would it be worth introducing GTFS data? The chapter is focused on active travel, but many of the routing engines you mention provide multimodal routing using GTFS data. Some introductory packages you could mention for gtfs exploration

    [https://r-transit.github.io/tidytransit/index.html](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fr-transit.github.io%2Ftidytransit%2Findex.html&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7Cc9705e669f8f4f000a1008da8b639778%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C637975557099069171%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Lf%2Fe2rTLQt8Kr83eJ26KFzlwOWdOqJznS3Hx%2F1baKrc%3D&reserved=0) : gtfs feed exploration
    [https://ipeagit.github.io/gtfstools/](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fipeagit.github.io%2Fgtfstools%2F&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7Cc9705e669f8f4f000a1008da8b639778%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C637975557099069171%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YdldyHGImMnlJ0YDHLV9QPFPp6eoFOlO4QLLi6VoVmU%3D&reserved=0) : provides basic functionality for filtering gtfs feeds. It could be useful for research into network resilience (to flooding for example)
- [x] You could also mention gbfs feeds ([https://github.com/simonpcouch/gbfs](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsimonpcouch%2Fgbfs&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7Cc9705e669f8f4f000a1008da8b639778%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C637975557099069171%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FmzuSNV9jmfGsazBJ0JwHpxYozGpmf9HxBms4FTwaps%3D&reserved=0)) and say that micromobility (docked/dockless systems) haven't yet been fully integrated into routing engines
I think a section on Accessibility would be useful. It's not that difficult to create isochrones in r5r / opentripplanner (or even this bespoke [accessibility](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fipeagit.github.io%2Faccessibility%2F&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7Cc9705e669f8f4f000a1008da8b639778%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C637975557099069171%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=t73plJfOuPwmbcgHwDneKvUofHNQL6xRL0fREWRK45o%3D&reserved=0) package, and it could be a nice introduction to using GTFS feeds

- [x] I think a section on Accessibility would be useful. It's not that difficult to create isochrones in r5r / opentripplanner (or even this bespoke [accessibility](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fipeagit.github.io%2Faccessibility%2F&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7Cc9705e669f8f4f000a1008da8b639778%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C637975557099069171%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=t73plJfOuPwmbcgHwDneKvUofHNQL6xRL0fREWRK45o%3D&reserved=0) package, and it could be a nice introduction to using GTFS feeds

Route and segment level outputs section

- [x] The distinction between segment and leg may be confusing for a beginner. I assumed that segment level meant one segment for each mode in a multimodal trip, but then I realized that’s not what you meant. Maybe the difference can be shown in a visual?

Other random notes

- [x] link to Bristol’s transport strategy is broken

- [x] Valhalla seems to have an R interface (I haven’t used it) [http://15.223.104.107/presentations/valhallr_d4g_2021-04-28.html#1](https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2F15.223.104.107%2Fpresentations%2Fvalhallr_d4g_2021-04-28.html%231&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7Cc9705e669f8f4f000a1008da8b639778%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C637975557099069171%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vSPLFHlMTpVzaSo%2F8S1V7XutrhUwbVIddUMu8OpNrt8%3D&reserved=0)

- [x] maybe a teaser to emmisions modeling? [https://ipeagit.github.io/gtfs2emis/](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fipeagit.github.io%2Fgtfs2emis%2F&data=05%7C01%7CR.Lovelace%40leeds.ac.uk%7Cc9705e669f8f4f000a1008da8b639778%7Cbdeaeda8c81d45ce863e5232a535b7cb%7C1%7C0%7C637975557099069171%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LGOxXr4SHqA0SdQYrwB6yLdmjLRxxTb0yvsFo%2BapbWM%3D&reserved=0)

**Comment by Robinlovelace** [comment]
Looking at this now...

**Comment by Robinlovelace** [comment]
Going to trying to improve this figure:

![image](https://user-images.githubusercontent.com/1825120/189528714-870fd51b-c82e-4624-a418-4828e4b9c8a3.png)

Source: https://geocompr.robinlovelace.net/transport.html#fig:wayssln

**Comment by Robinlovelace** [comment]
And after, this is lots better. Confident @Nowosad will be happy with this tweak : )

![image](https://user-images.githubusercontent.com/1825120/189529985-a4bebdeb-d5e0-449b-957d-5a357e763893.png)

**Comment by Nowosad** [comment]
Looks much better!

**Comment by Robinlovelace** [comment]
Looking at {tidytransit}, seems solid and continuously maintained package, definitely worth citing: 
![image](https://user-images.githubusercontent.com/1825120/194746983-05defac2-25f4-4d17-8290-c2a0a0fdb606.png)

**Comment by Robinlovelace** [comment]
Finally this is done! Many thanks @hussein-Mahfouz for all the comments.

Any feedback on any of the above welcome (especially the new exercises) @Nowosad and @jannes-m but from my perspective this chapter is now down and ready for review :tada:
