### ISSUE TITLE
Updates related to diagram in Chapter 7

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#867]
Related to this bit of code:

https://github.com/Robinlovelace/geocompr/blob/60d832e58ff304f1ac21393762390ad25d4115da/07-reproj.Rmd#L259

- [x] ~Add DiagrammeR Suggests in **geocompkg**~
- [x] Ensure text fits in boxes (maybe convert to png)
- [ ] Mention that `sf_use_s2()` setting will mean GEOS is used on lon/lat data
- [ ] Emphasise that the results are different when S2 is used? I think having 2 outputs side-by-side could help highlight that, currently the single result could lead people to believe that the result will be the same regardless of which geometry engine is used but in fact results can vary dramatically and this is an important point

Re. package dependency it caused `bookdown::serve_book()` to fail on my laptop. Although strangely GitHub Actions are working fine.

**Comment by Nowosad** [comment]
> strangely GitHub Actions are working fine

I was also surprised by that. I assume this package is installed alongside some other...
I think the best fix would be just comment out the code and provide an image. I can do that when I am back in Poznan next week.

**Comment by Robinlovelace** [comment]
I vote add it to Suggests, it's a nice package, we can use it for other images, and could be useful for other schematic diagrams. I like the resulting figure, although the text does not completely fit:

![image](https://user-images.githubusercontent.com/1825120/188260593-d5122e27-e899-4787-b225-76f7b1b862e3.png)

Source: https://geocompr.robinlovelace.net/reproj-geo-data.html#geom-proj

It's an improvement for sure in any case.

**Comment by Nowosad** [comment]
![image](https://user-images.githubusercontent.com/3457131/188260869-db9d8665-b68f-4138-be26-19394579b87a.png)
It renders fine on my firefox.

**Comment by Robinlovelace** [comment]
I guess it depends on screen size. That's from my laptop. Same issue at different zoom levels.

**Comment by Robinlovelace** [comment]
![Peek 2022-09-03 08-34](https://user-images.githubusercontent.com/1825120/188260941-ecfd9159-07f7-43a6-8f8d-fa70446d7c00.gif)

**Comment by Robinlovelace** [comment]
I've got a few more comments, will update the issue...

**Comment by Robinlovelace** [comment]
The figure fits fine in the Viewer window in RStudio:

![image](https://user-images.githubusercontent.com/1825120/188261322-b1cc5ee2-2351-4bcb-a713-ad446f8d8114.png)

**Comment by Nowosad** [comment]
Hi Robin,
commenting of your four points:
1. Not needed.
2. I just created a png file with the figure -- https://github.com/Robinlovelace/geocompr/commit/40f4017e55edb28aff700b59a84a82800f60389b
3. ...
4. Is not that Figure 7.2?

**Comment by Robinlovelace** [comment]
> Hi Robin, commenting of your four points:
> 
>     1. Not needed.
> 
>     2. I just created a png file with the figure -- [40f4017](https://github.com/Robinlovelace/geocompr/commit/40f4017e55edb28aff700b59a84a82800f60389b)
> 
>     3. ...
> 
>     4. Is not that Figure 7.2?

7.2 does indeed show that the outputs are different. I suggest showing them in this high level diagram also.

**Comment by Robinlovelace** [comment]
This is what I'm thinking.

![image](https://user-images.githubusercontent.com/1825120/188560995-ce7d2d59-459e-4a52-9ccd-125e5e4a1f00.png)

**Comment by Nowosad** [comment]
Have you tried to use `sf_use_s2(TRUE)` and `sf_use_s2(FALSE)` instead of S2 enabled/disabled? Is it better or worse?

**Comment by Robinlovelace** [comment]
High res version:

![image](https://user-images.githubusercontent.com/1825120/188572856-7946ae32-98de-444c-9f48-b1d7afcf9345.png)

**Comment by Robinlovelace** [comment]
BTW I found the cause of the overlapping text: Firefox vs Chrome differences. In Firefox the text overlaps.

**Comment by Nowosad** [comment]
It worked fine on my Firefox, so probably the actual cause is more complex....
