### ISSUE TITLE
Actions failing due to lack of mlr3proba

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#870]
As shown here: https://github.com/Robinlovelace/geocompr/runs/8283086224?check_suite_focus=true#step:4:8123

**Comment by Robinlovelace** [comment]
Any ideas people?

**Comment by Robinlovelace** [comment]
Heads-up @pat-s, do you know how best to solve this? I just checked and it seems **mlr3proba** has been removed from CRAN, a possible cause. Definitely in Jannes's court :+1: to assigning him Jakub.

**Comment by Robinlovelace** [comment]
I've updated the package in https://github.com/geocompr/geocompkg/commit/02dda6a03ade0689870d55defd297a951fef4ca6 and have set the actions going again :crossed_fingers: 

We should probably revisit this when the **mlr3** packages are stable, **mlr3extralearners** not being on CRAN is another minor issue, but save that for another day and another issue is my thinking.

**Comment by pat-s** [comment]
mlr3proba got banned from CRAN. We eventually might bring it back in spring next year.

You can install it from GH or R universe. Sorry for the troubles!

**Comment by Robinlovelace** [comment]
Thanks for the quick response Pat, although it's not what I was hoping to hear, long term CRAN issues :scream: I really appreciate your response. Any advice about our use of **mlr** packages very welcome.

**Comment by jannes-m** [comment]
If I remember correctly, the **mlr3extralearners** package has always been intended as a github package only. In any case, thanks for the quick fix, @Robinlovelace!
