### ISSUE TITLE
Add devcontainer

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#873]
As described here, can support development inside our Docker container: https://code.visualstudio.com/docs/remote/containers

**Comment by Robinlovelace** [comment]
After adding a devcontainer and opening the folder with Code, you get the option to open the project inside the devcontainer:

![image](https://user-images.githubusercontent.com/1825120/193396198-444ab202-5481-40ff-8dd9-bfecd45286a8.png)

**Comment by Robinlovelace** [comment]
It is currently downloading the right Docker container I think.

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/193396240-c241b5dd-03f1-4a46-939f-9dad4c2deebd.png)

**Comment by Robinlovelace** [comment]
Update: I've reproduced the entire book in the devcontainer. It works!

![image](https://user-images.githubusercontent.com/1825120/193398022-bbcfbfda-5d57-4c57-8db3-ed1fdb4a07be.png)

**Comment by Nowosad** [comment]
👍🏻
