### ISSUE TITLE
Problem with example code § 2.3.3

### ISSUE THREAD

**Issue by aloes2512** [Robinlovelace/geocompr#876]
# plot of example does not fit margins too large
Tried to plot(my_rast) from your example in § 2.3.3 of the book but this continuously results in error message: "figure margins too large" changing the par("mar") settings to c(1,1,1,1) does not resolve the problem
```
raster_filepath = system.file("raster/srtm.tif", package = "spDataLarge")
my_rast = rast(raster_filepath)
plot(my_rast)
```
error in plot.new() figure margins too large
 setting par(mar= c(1,1,1,1) does not resolve the problem

**Comment by Robinlovelace** [comment]
Could you try adjusting the plotting size available? See here, I suspect the second answer will help: https://stackoverflow.com/questions/23050928/error-in-plot-new-figure-margins-too-large-scatter-plot

**Comment by Nowosad** [comment]
@aloes2512 did you try to reset your graphic device with `dev.off()` before plotting?

**Comment by aloes2512** [comment]
Thank You for the fasr response. In the mean time Ifound the cause: trying to optimize the plot par(mfrow) was changed by some comand. I did not find out which one.  But setting par(mfrow=c(1,1)) solved the problem.
Thank You again.
Alf Loeffler

Von meinem iPad gesendet
