### ISSUE TITLE
Submit Part 3 for review

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#880]
This is Milestone 10 https://github.com/Robinlovelace/geocompr/milestone/10 in issue form. Marking it as an issue for discussion. I think we can submit this within the next few days, it's not perfect and there are a few issues but the sooner we get 13 to 15 reviewed the better for book timelines. I have updated the deadlines for different milestones to reflect where we're at.

Heads-up @Nowosad and @jannes-m we're almost there on this one!

**Comment by Nowosad** [comment]
Hi @Robinlovelace -- I do not know what the status of the Geomarketing chapter is. However, this week I finished improving the GIS bridges chapter, so we should have chapters: 10, 12, 13, and 15 ready for review.

We could then use chapters 9, 11, 15, and 16 for the next reviewing round.

**Comment by jannes-m** [comment]
I think I have already rewritten most of the geomarketing chapter code but before working again on this I would like to finish the spatial cv and eco chapters first.

**Comment by jannes-m** [comment]
And I should also take a look at the rewritten gis bridges chapter.

**Comment by Robinlovelace** [comment]
Superseded by #884
