### ISSUE TITLE
Add example of downloading OSM data

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/geocompr#89]
With a code example using **osmdata** by @mpadge

**Comment by Robinlovelace** [comment]
Fixed here: https://github.com/Robinlovelace/geocompr/commit/381896fb1ba84a5c24bd2d445159b95ee42df154

**Comment by jannes-m** [comment]
I have used the osmdata package in chapter gis-bridges and also in the location analysis chapter. I just let you know to make sure we do not duplicate the osmdata explanation but rather cross-reference to the chapter where osmdata is first used.

**Comment by Robinlovelace** [comment]
Great stuff - re-opening this issue as a reminder to make those cross-references, e.g.

```
See sections \@ref(ref1) and @\ref(ref2) for examples of how **osmdata** applied research.
```

@jannes-m if you have those section references to hand feel free to add that text to c5. Also happy to keep this issue open as there may be more instances of **osmdata** in the book. @mpadge your pkg proving useful in this book!

**Comment by jannes-m** [comment]
Ok, I referenced the sections in c5 (branch geomarketing fe5f900, will be soon integrated into master). The label gis will be missing (c13 r-gis bridges) until we uncomment c13 in '_bookdown.yml'.

**Comment by Robinlovelace** [comment]
Great stuff, many thanks.
