### ISSUE TITLE
Chapter 2 review

### ISSUE THREAD

**Issue by babayoshihiko** [Robinlovelace/geocompr#892]
(1) If it's about content -- link to the offending link/section

Hi, I read through the second chapter and found some issues.

**lines 277**
> Unlike the function `st_read()`, which returns attributes stored in a base R `data.frame` (and which provides more verbose messages, not shown in the code chunk below), `read_sf()` returns data as a **tidyverse** `tibble`.

The code chunk in lines 280-285 are evaluated, including st_read(). So, it **IS** shown.

**line 287**
> … (not withstanding the **spatstat** package ecosystem which provides numerous functions for spatial statistics)

What is the point of mentioning spatstat?

**line 330**:
Why not evaluate this code? It is helpful.

**line 448**:
> However, **sf** also allows multiple geometries to exist within a single feature (hence the term 'geometry collection') using "multi" version of each geometry type:

This statement should go after  line 463.

**Comment by Robinlovelace** [comment]
Thanks for these comments @babayoshihiko, I think there are some good points in there and I'm sure we'll make changes in response to this valuable feedback.

**Comment by Robinlovelace** [comment]
Heads-up @babayoshihiko I think I've fixed all the issues raise. Please check the commits above. Any further comments/suggestions/PRs welcome.
