### ISSUE TITLE
Shiny app is not working

### ISSUE THREAD

**Issue by Nowosad** [Robinlovelace/geocompr#893]
https://shiny.robinlovelace.net/CycleHireApp/ -- @Robinlovelace, see FIGURE 9.25 at https://geocompr.robinlovelace.net/adv-map.html#mapping-applications

**Comment by Robinlovelace** [comment]
Agreed, my bad, will get it working.

**Comment by Robinlovelace** [comment]
Finally it's alive again. Many thanks to @layik for support with the underlying sysadmin, more involved than expected!

![image](https://user-images.githubusercontent.com/1825120/205465566-175410aa-e242-4784-891e-732e9828c8bd.png)

**Comment by Nowosad** [comment]
Great, thanks @Robinlovelace and @layik
