### ISSUE TITLE
Ch:11 Content mistake

### ISSUE THREAD

**Issue by WarthogARJ** [Robinlovelace/geocompr#894]
Two errors:
(1) Line 12: Package is spelled wrong: "ml3measures" should be "mlr3measures"

(2) Render error:
When I run:
"_**bookdown::render_book("index.Rmd")**_"
Get error:
**Quitting from lines 622-653 (12-spatial-cv.Rmd) 
Error in mean(classif.auroc) : object 'classif.auroc' not found
Calls: local ... withVisible -> eval -> eval -> [ -> [.data.frame -> mean

Execution halted
Error in Rscript_render(f, render_args, render_meta, add1, add2) : 
  Failed to compile 12-spatial-cv.Rmd**

**Comment by jannes-m** [comment]
Thanks for spotting, will fix.

**Comment by jannes-m** [comment]
Are you sure you are using the latest version of our book? **mlr3measures** is no longer listed in the code chunk attaching all necessary packages. This in unnecessary, since it is a direct dependency of **mlr3**, hence, the following code should work without any errors:

``` r
library("mlr3")
msr("classif.auc")
#> <MeasureBinarySimple:classif.auc>: Area Under the ROC Curve
#> * Packages: mlr3, mlr3measures
#> * Range: [0, 1]
#> * Minimize: FALSE
#> * Average: macro
#> * Parameters: list()
#> * Properties: -
#> * Predict type: prob
```

<sup>Created on 2022-12-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by Robinlovelace** [comment]
Can you provide a link to the online version of the book with this faulty info @WarthogARJ ?

**Comment by WarthogARJ** [comment]
Hi,
Sure: and BTW, thanks VERY much for all your time & efforts in doing this.
I'm a newbie, and learning.

First Issue is in Line 14 in fact:
[[]](https://github.com/Robinlovelace/geocompr/blob/main/12-spatial-cv.Rmd)(url)
Is a spelling mistake of mlrmeasures (sic).

<img width="1911" alt="Screenshot 2022-12-13 at 20 06 27" src="https://user-images.githubusercontent.com/22987659/207433789-150e2a65-8df0-40fc-be94-b5037e20097b.png">

Perhaps it's just an old comment, but R-Studio picked it up when I was running the book thru a render.
Which was maybe silly to do, but I was trying to see if I could follow the directions to render it as an exercise.

The 2nd issue is still there, and perhaps it's a non-issue because perhaps it's not really smart to try to render the book as is?
Alan

**Comment by jannes-m** [comment]
Ah, you were referring to the footnote, I fixed the typo, thanks for spotting! Regarding the 2nd issue, have you run `remotes::install_github("geocompr/geocompkg", dependencies = TRUE)` before trying to render the book?

**Comment by Robinlovelace** [comment]
Good stuff and thanks for reporting Alan. I think the issue was fixed in this commit: https://github.com/Robinlovelace/geocompr/commit/f5234c4589174ffda2ad7bbcad3718d3ed71eac0

I suggest closing this issue if so, Jannes's suggestion above should fix the book build issue.

**Comment by WarthogARJ** [comment]
Completely fixed
