### ISSUE TITLE
Wrong values in the outer margin of Figure 4.13

### ISSUE THREAD

**Issue by jannes-m** [Robinlovelace/geocompr#896]
https://github.com/Robinlovelace/geocompr/blob/a6fb3918d4ee26f82761f36633e65b5403dd37fa/04-spatial-operations.Rmd#L1073

The outer margin of Figure 4.13 should be NA, see also Figure in the first edition (https://bookdown.org/robinlovelace/geocompr/spatial-operations.html#focal-operations).

**Comment by Robinlovelace** [comment]
This is what I see:

![image](https://user-images.githubusercontent.com/1825120/208229597-540c5b93-5a5c-4b70-9256-7f5a3b94c5db.png)

What should be different? Sorry I don't follow...

**Comment by Nowosad** [comment]
@Robinlovelace the new version of this figure looks like this ![](https://geocompr.robinlovelace.net/figures/04_focal_example.png).

**Comment by Nowosad** [comment]
@jannes-m thanks Jannes. I think I know the source of the issue. When I created this plot, the terra package had a different default for `na.rm` (`na.rm = TRUE`). Now, it behaves more similar to raster. I will update the figure soon.

**Comment by Nowosad** [comment]
https://geocompr.robinlovelace.net/spatial-operations.html#fig:focal-example

**Comment by jannes-m** [comment]
Excellent stuff, Jakub, thanks a lot!
