### ISSUE TITLE
Should we also mention sf::gdal_utils()? 

### ISSUE THREAD

**Issue by jannes-m** [Robinlovelace/geocompr#897]
https://github.com/Robinlovelace/geocompr/blob/8b92ec3f81c2fafbb64d31716fc1b0f13c4d9a02/05-geometry-operations.Rmd#L874

All of the four listed gdal functions mentioned here, could be also accessed with `sf::gdal_utils() `. Is this worth mentioning?

**Comment by Robinlovelace** [comment]
Probably...

**Comment by jannes-m** [comment]
Closed via 80353b307

**Comment by Robinlovelace** [comment]
:+1: thanks Jannes!
