### ISSUE TITLE
Code Clarification on raster setup

### ISSUE THREAD

**Issue by darrellcarvalho** [Robinlovelace/geocompr#900]
The setup in 3.3 for raster creation has a redundancy; it is harmless, but I wonder if there should be clarification?

the two code chunks at the beginning of the section use the `nrows` , `ncols` arguments as well as the `resolution =` argument in the `rast()` call, but per `terra::rast()` documentation, when `resolution` is set, `nrows` and `ncols` are ignored.

https://geocompr.robinlovelace.net/attr.html#manipulating-raster-objects

**Comment by Robinlovelace** [comment]
Thanks for raising this, it's worth clarifying at least and probably removing the redundancy in arguments. I'm not that experienced with `terra` though, guess this is one for @Nowosad. Thoughts on this Jakub?

**Comment by jannes-m** [comment]
You are right, @darrellcarvalho , one should set either  `nrows` and `ncols` or `resolution` since setting one of those would automatically yield the other.  

``` r
library(terra)
#> terra 1.6.41
all.equal(
  rast(resolution = 0.5, xmin = -1.5, ymin = -1.5, xmax = 1.5, ymax = 1.5,
       vals = 1:36),
  rast(nrows = 6, ncols = 6, xmin = -1.5, ymin = -1.5, xmax = 1.5, ymax = 1.5,
       vals = 1:36)
)
#> [1] TRUE
```

<sup>Created on 2022-12-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jannes-m** [comment]
Well, I would stick with `nrows` and `ncols` since this is easier to grasp for somebody with a data science background getting to know the raster data model.

**Comment by jannes-m** [comment]
https://github.com/Robinlovelace/geocompr/pull/901

**Comment by Robinlovelace** [comment]
I think this is now fixed. Can you take a look at the latest version of the book and close if fixed for you @darrellcarvalho?

**Comment by darrellcarvalho** [comment]
Looks good!
