### ISSUE TITLE
code for predicting floristic gradient producing error

### ISSUE THREAD

**Issue by rs806** [Robinlovelace/geocompr#909]
https://geocompr.robinlovelace.net/eco.html

error produced when running this code:
pred <- terra::predict(ep, model = autotuner_rf, fun = predict)

error:
Error in .__Learner__predict_newdata(self = self, private = private, super = super,  : 
  Assertion on 'newdata$colnames' failed: Names must include the elements {'carea','carea.1','cslope','cslope.1','dem','dem.1','ndvi','ndvi.1'}, but is missing elements {'carea.1','cslope.1','dem.1','ndvi.1'}.

**Comment by Robinlovelace** [comment]
Thanks for the report. It does not run on our automated checks:

https://github.com/Robinlovelace/geocompr/blob/dcaad229a2fd70ac424a8adfdb42faabe18f7606/15-eco.Rmd#L549-L551

So we need people to manually check to see issues. Jannes is probably best placed to try to reproduce the issue and fix it if confirmed.

**Comment by Nowosad** [comment]
Hi @rs806 -- I cannot reproduce your problem. Can you:

1. Try to clean your R environment, restart your R session and run the code once more (maybe there are some old or modified objects in your environment).
2. If the problem still occurs: please report your `sessionInfo()`

**Comment by rs806** [comment]
Thanks Nowosad and Robin. It works now after restarting R and only using code (and packages) specified in Chapter 15.  I had previously run code from Chapter 12 and it is possible there was a conflict caused by one those packages. I'll try to isolate the problem but for now it is working. Thanks again. Ray

**Comment by Nowosad** [comment]
Thanks!
