### ISSUE TITLE
Definition of "Multiple Features"

### ISSUE THREAD

**Issue by barryrowlingson** [Robinlovelace/geocompr#91]
Section 2.1.4 says: "So far, our geometry types have just included one feature. To represent multiple features in one object, we can use the “multi”-version of each geometry type:"

*But* I think (and a careful reading of the standard would confirm this) these things are still "single features". They're just single features with multiple (ie compound) geometries. You only get multiple features when you create an `sfc` object.

**Comment by Robinlovelace** [comment]
Not sure who wrote that but I entirely agree: features != geometries. The term geometry collection is key here I think, hence use of the term in my (hopefully improved) attempt to convey the essence of simple feature geometry types. Does this fix the issue for you?

```
So far we have created geometries with only one geometric entity per feature.
However, **sf** also allows multiple geometries to exist within a single feature (hence the term 'geometry collection') using "multi" version of each geometry type:
```

**Comment by Robinlovelace** [comment]
Closing for now as I think we've fixed it.
